### ISSUE TITLE
'RandomActivation' is not defined

### ISSUE THREAD

**Issue by rpmeira** [projectmesa/mesa#1002]
**Describe the bug**
I'm trying to follow the Introductory Tutorial in (https://mesa.readthedocs.io/en/master/tutorials/intro_tutorial.html) and I'm getting this error : NameError: name 'RandomActivation' is not defined

**Expected behavior**
The tutorial says it should print:
Hi, I am agent 2.
Hi, I am agent 9.
Hi, I am agent 5.
Hi, I am agent 3.
Hi, I am agent 7.
Hi, I am agent 0.
Hi, I am agent 4.
Hi, I am agent 6.
Hi, I am agent 8.
Hi, I am agent 1.

**To Reproduce**
![Sem título](https://user-images.githubusercontent.com/64609486/110174375-cd915e80-7dde-11eb-83b3-904360bb36c7.png)

**Additional context**
I'm running the scrip in Jupyter Notebook 7.2 using Google Chrome as browser, and in a Windows 10.

**Comment by ShirsenduP** [comment]
Hi, you have simply not imported `RandomActivation`. In your first cell, just add `from mesa.time import RandomActivation` and you should be good to go!

**Comment by Corvince** [comment]
I am closing this, @ShirsenduP should have provided the correct details for the solution. If not feel free to re-open this issue @rpmeira

**Comment by zhuhuang-11** [comment]
> 您好，您根本没有导入 .在您的第一个单元格中，只需添加，您就可以开始了！`RandomActivation``from mesa.time import RandomActivation`

![屏幕截图 2024-09-16 150653](https://github.com/user-attachments/assets/2ea3985e-8bfa-4ae1-a1a8-59d1cb4ff112)
Why doesn't this work
