### ISSUE TITLE
Using the iteration number from BatchrunnerMp inside the model class.

### ISSUE THREAD

**Issue by adprabhak** [projectmesa/mesa#1003]
Hi,
I have also run into a similar problem. I'm trying to save the some parts of the model data every time the model step function is called. 
How exactly do you use the run_iter_args[3] to track the iteration number? 
Because of huge RAM consumption, I'm trying to save the data into different files for every "time step" and iteration. By using self.schedule.steps i can seperate different time steps, how do I do this for iterations as well?

_Originally posted by @adprabhak in https://github.com/projectmesa/mesa/issues/881#issuecomment-790915316_

**Comment by adprabhak** [comment]
The main idea is to save certain data point at every time step inorder to cut down RAM usage.
However, to do this, we need "iteration number" to be availalbe inside the model class to avoid confusion if we are saving to file every time the step function is called.

how can we do this?

**Comment by tpike3** [comment]
@adprabhak Theoretically every processor should be able to save instride, but they would not necessarily distinguish from each other so may be overwriting each other. Could you add the model parameters to the file name when you save in stride to see if  the output is being saved across multiple processors?

**Comment by tpike3** [comment]
@adprabhak Were you able to resolve this?

**Comment by adprabhak** [comment]
Hi,
Sorry for the late reply. I added a seperate new parameter to my model for filenames. Now, instead of using the default iteration setup for MPbatchrunner, I use a list of filenames as a variable parameter. 
Thanks for the help!
