### ISSUE TITLE
BatchRunnerMP swaps content of variable_params columns

### ISSUE THREAD

**Issue by JustHereForAI** [projectmesa/mesa#1015]
**Describe the bug**
When I run BatchrunnerMP it swaps the contents of the values the similar batches are run with as described in issue #978 that should have been fixed with #979. Unfortunately this behaviour still occurs. As in the  original issue it appears only in some of the tries but but more often than not.

**Expected behavior**
I expect the BatchRunner model vars dataframe to give back the variable parameter values that correspond with a certain parameter. Instead, the parameter values of one parameter are swapped with the parameter values of another parameter.

**To Reproduce**
```
variable_params = {
    "p2": [0.1, 0.9],
    "pMLtoCode": [0.1, 0.9],
    "p1": [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]
    }

model_params = dict(num_agents=50,
                 num_AIagents=15,
                 num_dimensions=30,
                 p3=0.1,
                 turb=0.03,
                 extern=0.1,
                 turno=0.1,
                 p1alt=0.9,
                 qinit=0.5,
                 alpha=0.1)

batch_run = BatchRunnerMP(
    TimoModel,
    nr_processes=CPU_COUNT,
    variable_parameters=variable_params,
    fixed_parameters=model_params,
    iterations=80,
    max_steps=1000,
    model_reporters={"Performance": compute_similarity}
)
```

Calling
```

run_data = batch_run.get_model_vars_dataframe()
run_data.head()
```

returns:

pMLtoCode | p1 | p2 | Run | Performance | num_agents | num_AIagents | num_dimensions | p3 | turb | extern | turno | p1alt | qinit | alpha
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
0.1 | 0.1 | 0.1 | 50 | 93.333333 | 50 | 15 | 30 | 0.1 | 0.03 | 0.1 | 0.1 | 0.9 | 0.5 | 0.1
0.9 | 0.1 | 0.6 | 50 | 100.000000 | 50 | 15 | 30 | 0.1 | 0.03 | 0.1 | 0.1 | 0.9 | 0.5 | 0.1
0.9 | 0.1 | 0.6 | 50 | 100.000000 | 50 | 15 | 30 | 0.1 | 0.03 | 0.1 | 0.1 | 0.9 | 0.5 | 0.1
0.9 | 0.1 | 0.6 | 50 | 100.000000 | 50 | 15 | 30 | 0.1 | 0.03 | 0.1 | 0.1 | 0.9 | 0.5 | 0.1
0.9 | 0.1 | 0.6 | 50 | 100.000000 | 50 | 15 | 30 | 0.1 | 0.03 | 0.1 | 0.1 | 0.9 | 0.5 | 0.1

As you can see p2 gets a value of 0.6 which should not have been possible.

**Additional context**
I use Mesa 0.8.8.1 on Windows.

**Comment by rht** [comment]
cc @YannickJadoul

**Comment by YannickJadoul** [comment]
>  I use Mesa 0.8.8.1 on Windows.

0.8.8.1 was released on Nov 27, 2020, according to https://pypi.org/project/Mesa/0.8.8.1/ My PR #979 was only submitted/merged last January/February.

Have you tried using the latest commit on `master` as version?

**Comment by JustHereForAI** [comment]
Yes, that worked!

Thank you so much for the fast help and please excuse my ignorance regarding the release versions.
