### ISSUE TITLE
BatchRunnerMP error

### ISSUE THREAD

**Issue by chenyuyou** [projectmesa/mesa#1017]
**Describe the bug**

multiprocessing.pool.MaybeEncodingError

**Expected behavior**

**To Reproduce**

multiprocessing.pool.MaybeEncodingError: Error sending result: '((0.5, 10, 0.1, 3, 2), <__main__.PdNetworkModel object at 0x7f97f075ce90>)'. Reason: 'AttributeError("Can't pickle local object 'PdNetworkModel.__init__.<locals>.<lambda>'")'

**Additional context**

mesa  version=0.8.8.1

**Comment by tpike3** [comment]
@chenyuyou When you create you initiate you model does it have any complex objects? Certain objects that cannot be pickled will prevent multiprocessing from working (https://docs.python.org/3/library/pickle.html#what-can-be-pickled-and-unpickled)

**Comment by chenyuyou** [comment]
> @chenyuyou When you create you initiate you model does it have any complex objects? Certain objects that cannot be pickled will prevent multiprocessing from working (https://docs.python.org/3/library/pickle.html#what-can-be-pickled-and-unpickled)

lambda could not be pickled, so what can I do when I meet this situation “agent_reporters={"Wealth": lambda x: x.wealth}”？

**Comment by tpike3** [comment]
You can just put wealth  (e.g. {"Wealth": "wealth"}). Since it is an agent_reporter it will collect that attribute from all agents.

**Comment by chenyuyou** [comment]
> You can just put wealth (e.g. {"Wealth": "wealth"}). Since it is an agent_reporter it will collect that attribute from all agents.

thanks

**Comment by chenyuyou** [comment]
> > You can just put wealth (e.g. {"Wealth": "wealth"}). Since it is an agent_reporter it will collect that attribute from all agents.
> 
> thanks
