### ISSUE TITLE
how to customize the visualization of different types of agents.

### ISSUE THREAD

**Issue by seeingwu** [projectmesa/mesa#1031]
Hi, I want to show my respect first for your amazing work about Mesa.
 When I set up the portrayal for the agent, there is a problem making me confused.
![image](https://user-images.githubusercontent.com/52962497/116622797-268ff580-a93d-11eb-9966-7f982d04a603.png)

I want to use the text to differentiate the agent type. However, maybe I didn't get how it works, the grid visualization fails. 

The whole model can run without the text function. So I guess it is the problem of how to use text visualization.

Could you please help me check for that?

Best regards
Sijin

**Comment by rht** [comment]
>  However, maybe I didn't get how it works, the grid visualization fails.

What is your error message? Also, it'd help if you have a public code that I can look at to debug.

**Comment by rht** [comment]
Closing because there has been no reply.
