### ISSUE TITLE
Build is failing -- on pypy fail 

### ISSUE THREAD

**Issue by jackiekazil** [projectmesa/mesa#1045]
Build is failing on pypy. 
https://github.com/projectmesa/mesa/runs/2723473745?check_suite_focus=true#step:5:203

```
    ast27/Parser/tokenizer.c:17:10: fatal error: codecs.h: No such file or directory
       17 | #include "codecs.h"
          |          ^~~~~~~~~~
    compilation terminated.
    error: command 'gcc' failed with exit status 1
 ```

**Comment by jackiekazil** [comment]
@rht can you take a look at this?

**Comment by rht** [comment]
That's because the dev dependencies in setup.py has Black. typed_ast can't be installed in PyPy yet.

**Comment by jackiekazil** [comment]
We were chatting about it tonight and thought that was an issue we couldn't
fix, but didn't know about it.
Is it worth having it in the build if it fails? Wondering if we should
remove it and then add it back in later?
What do you think?

**Comment by rht** [comment]
The GitHub Actions yml already runs and manually install Black only if the version is 3.8 and it's not PyPy, so I think Black can be safely removed from the dev dependencies in setup.py.

**Comment by rht** [comment]
This hasn't happened lately because Black is only run on CPython 3.10. Closing.
