### ISSUE TITLE
Figure out why coveralls says 26%, but it looks like we are covered at 85%

### ISSUE THREAD

**Issue by jackiekazil** [projectmesa/mesa#105]
Figure out why coveralls says 26%, but it looks like we are covered at 85%?

**Comment by jackiekazil** [comment]
AH HA! 
`nosetests --with-coverage` is running tests for all things including installed packages  (scipy, pandas, etc.)

If you go to the travis build and look at the logs for the command, you will see it. 
Afterwards, the coverage gets submitted to coveralls... 
```
[0K$ coveralls
Submitting coverage to coveralls.io...
```

**Comment by jackiekazil** [comment]
This is because of 2 reasons. The first is covered in this ticket: #116. 
The second is because we are not testing all of our modules, because they are not accessible to coveralls via the __init__.py, so we should figure out how we need to restructure the files. The first iteration of this was in #106, but I realized that this needs more careful consideration. (See that PR for more details.)

**Comment by jiffyclub** [comment]
Coverage is at 56% right now according to the latest run, e.g. https://coveralls.io/builds/3033351.

**Comment by chendaniely** [comment]
`nosetests --cover-branches --with-coverage --cover-erase --cover-package=mesa` the last flag tells it to just run coverate test on the current project and not everything imported

**Comment by jackiekazil** [comment]
This is no longer relevant / done.
