### ISSUE TITLE
SingleGrid position_agent very slow for large grids

### ISSUE THREAD

**Issue by timjdavey** [projectmesa/mesa#1052]
It's fine for square widths of around 20 cells, but when you 200 it slows right down.

It appears to be caused by the line `agent.random.choice(sorted(self.empties))` where it sorts the empties first. I guess it does this so you can replicate the results using random seed?

If you don't care about replication however, it's unreasonably slow and can be fixed by using `agent.random.choice(list(self.empties))` instead (speeding it enormously).

I'm not sure of the design decisions here, but maybe it's worth having two functions to make it clear or passing some sort of bool?

https://mesa.readthedocs.io/en/stable/mesa.html#mesa.space.SingleGrid.position_agent

**Comment by rht** [comment]
In 3.8:
```python
In [1]: a = set([1,2,3,5,4])

In [2]: list(a)
Out[2]: [1, 2, 3, 4, 5]

In [3]: a.add(-5)

In [4]: a.add(10)

In [5]: list(a)
Out[5]: [1, 2, 3, 4, 5, 10, -5]

In [6]: sorted(a)
Out[6]: [-5, 1, 2, 3, 4, 5, 10]
```
it seems that the output of `list(a)` is deterministic. Maybe `set` used to be nondeterministic in the earlier version of Python.

**Comment by timjdavey** [comment]
Oh interesting, thanks! I couldn't find any specific release notes about set's now being ordered. As of 3.7+ (when dicts became ordered) they definitely weren't guaranteed. https://stackoverflow.com/questions/61414947/why-dont-python-sets-preserve-insertion-order

Guido says "Sets remain unordered. (Why? The usage patterns are different. Also, different implementation.)" so cool if that's changed.

**Comment by rht** [comment]
For comparison, this is how Agents.jl do a move to empty: https://github.com/JuliaDynamics/Agents.jl/blob/c9a7fa13493c0ba24aacd0a6a6de4ba19394d181/src/spaces/discrete.jl#L80-L88. This is how the empty positions information is obtained: https://github.com/JuliaDynamics/Agents.jl/blob/c9a7fa13493c0ba24aacd0a6a6de4ba19394d181/src/spaces/discrete.jl#L57-L64. It seems expensive to have to generate the empty positions every single time. Maybe @Libbum can explain why Agents.jl chose it to be this way.

It could be that in many models, move to empty is not a necessary movement condition. Agents can overlap with each other. But why not make 2 different kinds of grids where one has the empties cached, while the other doesn't cache.

**Comment by Libbum** [comment]
From an Agents.jl perspective this wasn't an active choice&mdash;it hasn't caused us concern at all though. `random_empty` is used in Schelling, but not too many other models use it, so it hasn't been a place in the base framework we need to optimise.

A cache on empties, for Agents.jl, would end up meaning additional operations each step for all models, on the off chance that someone *may* need lots of `random_empty` calls (and these are causing performance drops).

**If** we had to deal with this: I'd say we'd do something similar to what @rht is suggesting: we'd add a flag to our grid that was off by default and returned `nothing` for any function call that expects the cache. Switching the flag on would do such an update.

That's at least what we would test as a first go...

**Comment by rht** [comment]
I have checked the models in https://github.com/projectmesa/mesa/tree/main/examples. Only Schelling uses `move_to_empty` as well. Sugarscape does its own check for the neighborhood, and for Boltzmann wealth model, agents positions can overlap.
I think we should pick a default in Mesa where there is no `empties` caching as well.

And then there is a 3rd differentiating feature, when the grid is sparsely populated, which means that it is most performant to just pick any random coordinate, and then check if it is empty, then repeat until I find an empty coordinate, and so there is no need to iterate through the entire grid to calculate empty coordinates in `random_empty()`. The grid with `empties` is only performant when the grid is densely populated with many agents.

**Comment by Libbum** [comment]
> And then there is a 3rd differentiating feature, when the grid is sparsely populated, which means that it is most performant to just pick any random coordinate, and then check if it is empty, then repeat until I find an empty coordinate, and so there is no need to iterate through the entire grid to calculate empty coordinates in random_empty(). The grid with empties is only performant when the grid is densely populated with many agents.

That's a pretty smart idea. Even if you're not running sparse grids under the hood, you could get an idea of sparsity via `num_agents/size(space)`. My guess is you could be better off with this method until the check hits `> 0.66-0.75`.

**Comment by rht** [comment]
Bump. (Waiting for consensus on which action to take...)
@Libbum made a ~5x speedup in Agents.jl by optimizing `random_empty()`: https://github.com/JuliaDynamics/Agents.jl/pull/541, where the method can also be applied to Mesa's `Grid`, `NetworkGrid`, etc.
This will be a breaking change because of the change in the empty position algorithm.

**Comment by jackiekazil** [comment]
@rht I like your proposal.

**Comment by jnsp** [comment]
There is no change on `agent.random.choice(sorted(self.empties))` in `SingleGrid.position_agent()`. It is still too slow. The new algorithm was only applied to `Grid.move_to_empty()`, not `SingleGrid.position_agent()`.

https://github.com/projectmesa/mesa/blob/88d575d6e33c8b0e992605c043e4b60b0f802366/mesa/space.py#L515

**Comment by rht** [comment]
That's correct. Feel free to make a PR replacing that line with `move_to_empty`.
