### ISSUE TITLE
How to update model with agent data in every step?

### ISSUE THREAD

**Issue by JaslinRikkaz123** [projectmesa/mesa#1055]
Dear Mesa Users,
I'm new to MESA. I'm doing postgraduate in Electrical Engineering. I have developed Electric Vehicle ABM model.(JaslinRikkaz123
/EV_Model_inABM). Initially, i have developed for one car, it was working fine.(It read the data of speed, acceleration and run the model). Now I'm developing the model with multiple cars. now, i need to specify cars with respect to the availability data in the grid. Since I'm using BaseScheduler it runs once when it starts. what i want is, in my concept model, when i place a EV agent,(
#create ev agent
x = 5
y = 10
self.grid.position_agent(EvAgent,x,y))
i need to specify the availability data, when it is "1" car should be available otherwise it doesn't.

How can i modify it?

**Comment by rht** [comment]
You can do this:
```python
for x, y in ev_coordinates:
    agent_id = ...
    ev_agent = EvAgent(agent_id, self, check_is_available(x, y))
    self.schedule.add(ev_agent)
    self.grid.position_agent(ev_agent, x, y) 
```

Where `check_is_available()` is a function to check if that particular coordinate is available, based on the data.
So you store the availability state inside the EvAgent object.

**Comment by JaslinRikkaz123** [comment]
I have tried this concern, but I'm unable to achieve the task. In check_is_available(x, y), what i want is, I have availability data in excel sheet like if car is available = 1  and if not  = 0. With respect to this data, car should be in the grid with that (x,y) coordinates.
I'm using costumbaseschduler in schdule.py to get return value of the agents. In model.py it runs in first step only not for each steps so, how can i achieve this task?

**Comment by JaslinRikkaz123** [comment]
Is there any way to implement this in server.py?

**Comment by rht** [comment]
You can do the get availability data in excel inside the `check_is_available(x, y)`.

**Comment by JaslinRikkaz123** [comment]
its working now. Thank you
