### ISSUE TITLE
AMD Turks OpenGl 4.x support

### ISSUE THREAD

**Issue by farofaDeCachorro** [projectmesa/mesa#1062]
i use an amd video card with turks chipset, Northern Islands generation, more specifically hd 6570 desktop. Not only me, but other people on forums have had this open gl support issue, and maybe that's one of the biggest limitations for me when playing on linux. On windows, my video card supports opengl 4.6. And the only thing I'm looking for here is to make a supplication and ask them to think about it, thank you in advance.

Currently the opengl supported by me in the latest version of mesa 21.3.0-devel is 3.3 core and open gl es 3.1 . And I wish I could enjoy the superior opengl, as I believe there would be a gain and several benefits for people like me who use TURKS gpus.

Here's my glxinfo and lshw outputs:
[glxinfo.txt](https://github.com/projectmesa/mesa/files/7246901/glxinfo.txt)
[lshw.txt](https://github.com/projectmesa/mesa/files/7246902/lshw.txt)

**Comment by rht** [comment]
You posted in the wrong Mesa repo. This is probably what you meant: https://github.com/mesa3d/mesa.

**Comment by farofaDeCachorro** [comment]
> You posted in the wrong Mesa repo. This is probably what you meant: https://github.com/mesa3d/mesa.

oohhh i'm so sorry, i'll close it now, thx you so much

**Comment by doobilydo** [comment]
@apollodaniel , I'm just curious if you made progress on this issue and can link to that. 

I'm running AMD Turks XT (Radeon HD 6670/7670) on Manjaro 21.2.6 and may have run into this bug. Crazy flickering graphics problems while gaming.
