### ISSUE TITLE
Issue Placing Agents on SingleGrid

### ISSUE THREAD

**Issue by mfroid** [projectmesa/mesa#1066]
Hello. Thanks for the awesome tool!

So, I am trying to make a model of cell division on a SingleGrid. If a spot on the grid is empty next to a cell that can divide, it should be filled with a daughter cell. Below is the code that I have written. The issue I am is having is that the agent count does not seem to be counting the cells on that are on my grid. Is this an issue with Mesa, or an issue with my code? My code is probably more likely to be the culprit.  The exact error that I am getting is "TypeError: object of type 'NoneType' has no len()".

Thanks!

`class Cell(Agent):
    """ An agent that can divide and reproduce."""
    def __init__(self, unique_id, model):
        super().__init__(unique_id, model)
    
    def step(self):
      death_prob = 0.3
      div_prob =  0.5
      mut_prob = 0
      if self.random.random() < death_prob:
        self.model.grid._remove_agent(self.pos, self)
        self.model.schedule.remove(self)
      if self.model.grid.exists_empty_cells == True:
        child = Cell(self.model.next_id(), self.model)
        self.model.grid.move_to_empty(child)
        self.model.schedule(child)
      else:
        pass

class MyModel(Model):
    """A model with some number of agents."""
    def __init__(self, N, height, width):
        num_agents = N
        super().__init__()
        self.num_agents = num_agents
        self.height = height
        self.width = width
        self.schedule = RandomActivation(self)
        self.grid = SingleGrid(self.height, self.width, torus=True)
        self.make_agents()

    def make_agents(self):
    # Create agents
      id = 0
      while True:
        if id == self.num_agents:
          break
        # Add the agent to a random grid cell
        x = self.random.randrange(self.width)
        y = self.random.randrange(self.height)
        pos = (x, y)
        if self.grid.is_cell_empty(pos):
          cell = Cell(self.next_id(), self)
          self.grid.place_agent(cell, pos)
          self.schedule.add(cell)
          id += 1
          print(id)

    def step(self):
        self.make_agents()
        self.schedule.step()

model = MyModel(10, 10, 10)
for i in range(1):
    model.step()

agent_counts = np.zeros((model.grid.width, model.grid.height))
for cell in model.grid.coord_iter():
    cell_content, x, y = cell
    agent_count = len(cell_content)
    agent_counts[x][y] = agent_count
plt.imshow(agent_counts, interpolation='nearest')
plt.colorbar()
plt.style.use('seaborn-poster')`

**Comment by dmasad** [comment]
I'm having trouble replicating the bug exactly, since the formatting of the code example here is a little off. One likely issue is that your constructors are called `init` rather than `__init__` (with two underscores). The MyModel object is still being created, but none of its variables are actually instantiated.

**Comment by mfroid** [comment]
I see. I think that I was able to resolve that part, I am just having trouble figuring out how to test if there are any empty spaces around an agent, and then only duplicating the agent (i e the cell divides) if there is a free empty space to place one new agent. I am sure that it is because I am doing something wrong, not that there is something wrong with Mesa. Also kind of surprised that there isn't an example anywhere that I could see of someone doing something similar. Thanks for the help though!

**Comment by rht** [comment]
The constructor is still `__init__`, except that the `__` is interpreted as a markdown bold.

**Comment by dmasad** [comment]
Closing for now, feel free to reopen if this didn't solve it.
