### ISSUE TITLE
Git tags out of sync with conda and PyPi (0.8.8 and 0.8.9 missing on git)

### ISSUE THREAD

**Issue by EwoutH** [projectmesa/mesa#1076]
Currently [conda-forge](https://anaconda.org/conda-forge/mesa) and [PyPi](https://pypi.org/project/Mesa/#history) include tags up to 0.8.9, but on git the [tags](https://github.com/projectmesa/mesa/tags) only go to 0.8.7.

Can 0.8.8 and 0.8.9 added as git tags to bring those in sync?

**Comment by EwoutH** [comment]
@jackiekazil @tpike3 Would one of you be able to look into this?

**Comment by jackiekazil** [comment]
I can look into this.

**Comment by rht** [comment]
I think this has been resolved? Can't find the confirmation on Matrix chat, but it could be elsewhere. I think @EwoutH confirmed this already?

**Comment by jackiekazil** [comment]
Tags have been added -- https://github.com/projectmesa/mesa/tags closing this ticket. Please reopen if you see any issues that need to be resolved that I missed.

**Comment by EwoutH** [comment]
Thanks!
