### ISSUE TITLE
Use rebase-and-merge instead of merge

### ISSUE THREAD

**Issue by rht** [projectmesa/mesa#1081]
There are lots of merge commits in the commit history. Moving forward, this can be cleaned if the rebase-and-merge is selected as the default in the GitHub settings of this repo. See https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/about-merge-methods-on-github#rebasing-and-merging-your-commits. Example of projects with clean commit history: https://github.com/zulip/zulip/commits/main.

Notice that the pull request number can still be found in the commit detail even with this method: https://github.com/zulip/zulip/commit/5300ad8ca04604ac9b0a4d9505dd3c8c5bcd24d4.

**Comment by EwoutH** [comment]
Agree, _Rebase and merge_ is much cleaner for the commit history.

One disadvantage however is that _Rebase and merge_ does destroy commit signatures.

**Comment by rht** [comment]
The commit signatures can be retained if the branch is rebased (by the PR creator) on top of latest main, and then the maintainer do a `git pull --rebase` from the PR branch.

**Comment by jackiekazil** [comment]
@rht I am confused by settings in your comments. 
You are suggesting setting it as the default then also encouraging folks during the the PR Rebase -- on the command line? 
Or call all this be set in the settings and am I missing it?

**Comment by rht** [comment]
You can ignore my comment on the command line rebase. Most people don't sign their commits anyway, so using GH's rebase and merge button should work.

**Comment by EwoutH** [comment]
On recent commits the reference to the pull request is gone, so the (#PR). This makes it more difficult to find the original pull request. How can this be fixed when merging?

![32725691-D7DC-4353-8D2D-BF165879D451](https://user-images.githubusercontent.com/15776622/145992029-a677749c-9142-4e94-a8cf-5a4251cf75df.jpeg)

**Comment by rht** [comment]
If you click on the individual commit, you will see the PR number, e.g. https://github.com/projectmesa/mesa/commit/d2243971e6101e812422c0853eb7ae1a1671ffbc is #1099.

**Comment by rht** [comment]
![2021-12-14-070644_345x202_scrot](https://user-images.githubusercontent.com/395821/145995337-60a538dc-3d78-429e-928c-bd3fe24d80a2.png)

**Comment by rht** [comment]
I suppose I can close this now, since currently the default is rebase and merge.
