### ISSUE TITLE
Docs: Updates docs when the Jupyter Notebooks are modified (automatically)

### ISSUE THREAD

**Issue by EwoutH** [projectmesa/mesa#1082]
Currently, when Jupyter Notebooks (`.ipynb`) files are updated, the documentation isn't, because it's generated from the reStructuredText (`.rst`) files.

In #1078, for example, [intro_tutorial.ipynb](https://github.com/projectmesa/mesa/blob/main/docs/tutorials/intro_tutorial.ipynb) is updated but [intro_tutorial.rst](https://github.com/projectmesa/mesa/blob/main/docs/tutorials/intro_tutorial.rst) isn't, so the [Introductory Tutorial](https://mesa.readthedocs.io/en/master/tutorials/intro_tutorial.html) is still badly formatted.

Two potential solutions for this:

- When an Jupyter Notebook is modified, regenerate the reStructuredText (ideally automated in CI)
- Generate the docs directly from the Jupyter Notebooks (maybe using [nbsphinx](https://nbsphinx.readthedocs.io/en/0.8.10/)?)

**Comment by EwoutH** [comment]
#1420 might help developing this.

**Comment by rht** [comment]
Solved by only committing the .ipynb. The doc is generated via nbsphinx. See #1694.
