### ISSUE TITLE
DOCS: Read the Docs generates docs for outdated master branch instead of main

### ISSUE THREAD

**Issue by EwoutH** [projectmesa/mesa#1089]
The [Space](https://mesa.readthedocs.io/en/master/apis/space.html) API docs for the master branch are currently empty.

It looks like it uses the same system as the [Time](https://mesa.readthedocs.io/en/master/apis/time.html) docs, which is generated from [time.rst](https://github.com/projectmesa/mesa/blob/main/docs/apis/time.rst) and documents [time.py](https://github.com/projectmesa/mesa/blob/main/mesa/time.py).
But for some reason [space.rst](https://github.com/projectmesa/mesa/blob/main/docs/apis/space.rst) fails to generate the correct docs for [space.py](https://github.com/projectmesa/mesa/blob/main/mesa/space.py).

For now the [latest](https://mesa.readthedocs.io/en/latest/apis/space.html) docs still display the Space API correctly.

**Comment by EwoutH** [comment]
I suspect the default branch change from `master` to `main` to be the culprit. Is the default branch on https://readthedocs.org/dashboard/mesa/advanced/ changed to `main`? 

See for more detailed info and instructions: https://github.com/readthedocs/readthedocs.org/issues/7907#issuecomment-828827927

**Comment by EwoutH** [comment]
@tpike3 @jackiekazil There is quite a bit issue with the docs. Currently docs are still [generated](https://mesa.readthedocs.io/en/master/) for the master branch. Please check my previous reply:

> I suspect the default branch change from `master` to `main` to be the culprit. Is the default branch on https://readthedocs.org/dashboard/mesa/advanced/ changed to `main`?
> 
> See for more detailed info and instructions: [readthedocs/readthedocs.org#7907 (comment)](https://github.com/readthedocs/readthedocs.org/issues/7907#issuecomment-828827927)

**Comment by tpike3** [comment]
@EwoutH Thanks! I can't believe we did not notice this! @jackiekazil and @dmasad I do not have the sign in information to go in an make this update. If either one of you can action that would be great!

**Comment by EwoutH** [comment]
@jackiekazil and @dmasad can you please look into this? It should be straight forward and it is really important users are referred to up to date docs.

**Comment by tpike3** [comment]
@EwoutH, @jackiekazil  updated the read the docs for main and released 0.9.0 (the major muscle movement being batch_run thanks @Corvince)! My understanding is this release made it in time for the students. 

Excited to hear what they produce!
