### ISSUE TITLE
Release and version discussion

### ISSUE THREAD

**Issue by jackiekazil** [projectmesa/mesa#1108]
We need to push a release -- see #924. 
We normally just increment. 

Should we go to 0.9 OR 1.0? 
I feel like it might be time to go to 1.0. 

History file - https://github.com/projectmesa/mesa/blob/main/HISTORY.rst

**Comment by tpike3** [comment]
@EwoutH the new batchrunner does not have breaking changes it adds another simpler way to do batchrunner. We need to add a deprecation warning and update the tutorial. I hope to get it done by the new year.

**Comment by tpike3** [comment]
Concur,  and if my memory serves that was the previous discussion to get into the wild and then assess any issues. I suggested it in #1092 and for @jonahaag in issue #1109 this may be a great opportunity to run it through its paces. 

To this discussion maybe once ```batch_run()``` is put through its paces then we go to 1.0 as batch runs are a core ABM capability. So right now my vote is we should release under 0.9 with updated tutorials.

**Comment by EwoutH** [comment]
Thanks for opening this issue!

I would suggest following [Semantic Versioning](https://semver.org/). One of the principles is that starting from 1.0, API changes that are not backwards compatible are only allowed when increasing the major version. For Mesa this probably means that all existing models made on 1.0 have to keep working.

Therefore I would suggest first releasing a 0.9.0 version before jumping to 1.0.

[GitHub Milestones](https://github.com/projectmesa/mesa/milestones) are a great way to keep track which issues and PRs are scheduled for which release. Creating Milestones for 0.9.0, 0.9.1 and 1.0.0 could be very useful.

**Comment by EwoutH** [comment]
February 7th we're starting with a new ABM course at the TU Delft, with about 250 students, using Mesa. I don't know if it's realistic, but if a new release is tagged before then we could put it to use immediately!

**Comment by tpike3** [comment]
That is awesome. I will get my part done this weekend and @rht already did his, so hopefully we can get the new version out by the 1st!

**Comment by EwoutH** [comment]
Congratulations everyone on the 0.9.0 release, and thanks @jackiekazil for releasing it!

Two points:
 - Can we create a release page on [GitHub releases](https://github.com/projectmesa/mesa/releases) with the 0.9.0 change log (or linking to it)? This makes the update more visibel for users.
 - #1076 should be adressed for users wanting so see actual code changes between their versions and 0.9.0.

**Comment by tpike3** [comment]
@Ewout thanks, I will add these to the next dev meeting as it is coming up

**Comment by jackiekazil** [comment]
This ticket is no longer relevant.
