### ISSUE TITLE
Wanting to contribute, open for suggestions

### ISSUE THREAD

**Issue by jonahaag** [projectmesa/mesa#1109]
Hi everyone,

I am a Master's student in Simulation Technology from the University of Stuttgart, Germany, and currently am attending the course [Simulation Software Engineering](https://simulation-software-engineering.github.io/homepage/). For this lecture, students were asked to select an open-source simulation framework, study its RSE infrastructure and make a small, but meaningful contribution to get acquainted with modern open source software development tools, workflows and best practices. 

For this, I chose Mesa and am now looking for something to work on. There are no clear expectations as to what this contribution has to look like, neither from my side nor the lecturers. It might be a new feature or tutorial, some documentation, bug fixes,... 

I am quite new to ABM but eager to learn and would really like to contribute something useful, so I am open for suggestions of any type. Thanks 😄

**Comment by tpike3** [comment]
@jonahaag very cool and we can always use the help. You can look through the issues and see if there is one that is of interest. I would just post it here to verify there is not larger issue it addressing may create.

One item under work is the new [batch_run](https://github.com/projectmesa/mesa/blob/cda0495a4c7ca9656cbefd393d9a085b7cbf3367/mesa/batchrunner.py#L33). 

 A couple items realties to this are: 
* double-check there are no parameter issues with data collector as noted in  #1077 
* update the tutorial to reflect batch_run as the method
* add deprecation warning to older functions

Let us know what generates interest.

**Comment by jonahaag** [comment]
Thanks @tpike3 for the suggestions.

If you concur, I would like to work on updating the tutorial and, as part of the process, test and give some feedback on UX of the new batch_run as you commented in #1108. Please let me know, whether that's fine for you and whether I should open a new issue for that to discuss the details. I would try do work on this over the course of the next 2 weeks.

**Comment by tpike3** [comment]
@jonahaag works great for me thanks!

**Comment by jonahaag** [comment]
Just to make sure that we're on the same page: you are talking about the introductory tutorial, [this part](https://github.com/projectmesa/mesa/blob/main/docs/tutorials/intro_tutorial.rst#batch-run) to be precise, right? If so, this should involve only the corresponding rst and ipynb files or am I missing something?

**Comment by tpike3** [comment]
@jonahaag That is correct. I would make sure to validate the results form the tutorial as just another check of key concern is the results of the datacollector. It seems like ReadTheDocs has done a lot of updates and it looks more automated now, so at least for reference...[Read the Docs](https://docs.readthedocs.io/en/stable/index.html)

**Comment by tpike3** [comment]
@jonahaag We just did a merge to batchrunner based on contributions by @jdfoote with support from @rht. I would install from the Mesa git repo again to get those updates for the agent reporters and tutorial update.

**Comment by jonahaag** [comment]
So, I started working on this today. The `batch_run` itself seems super intuitive which is great. 

Right now, the method returns a list of dictionaries which need to be prepared for plotting. I am doing this by simply converting the list into a pandas data frame like this:

```python
results = batch_run(
    MoneyModel,
    parameters=params,
    iterations=5,
    max_steps=100
)
import pandas as pd
results_df = pd.DataFrame(results)
plt.scatter(results_df.N,  results_df.Gini)
```

Is this the way this was intended to be done or did you guys have something different (e.g. another function to bring results into more "analyzable" form) in mind? If not, wouldn't it make sense to directly return the data frame? I can't really see anybody do something with the list of dicts but maybe I am missing something.

**Comment by tpike3** [comment]
There are functions in batchrunner that convert the results to dataframes: 

For the [model](https://github.com/projectmesa/mesa/blob/818d4c5f8434b5a919e28dbd15587f513d93363c/mesa/batchrunner.py#L420)

For the [agents](https://github.com/projectmesa/mesa/blob/818d4c5f8434b5a919e28dbd15587f513d93363c/mesa/batchrunner.py#L427)

Their uses is also in the [current tutorial](https://mesa.readthedocs.io/en/stable/tutorials/intro_tutorial.html)

I would ask you to pay special attention to the model parameters and their tie to their result as that seems to be continuing issue. I think we have resolved it but I have said that before.

**Comment by jonahaag** [comment]
Thanks for the reply. 

That means I have to create a FixedBatchRunner object first though, right? Wouldn't that be against the idea of the new method?

**Comment by tpike3** [comment]
@jonahaag Sorry I had to go through all the comments in previous pull requests to refresh my memory and run some of my own tests. At this point, I would recommend keeping the tutorial as you have it where the tutorial code shows converting the results to a dataframe.

My reasoning is two fold: 
-- It helps keep core Mesa lean (e.g. less imports the better)
-- as people run larger and more complex models a single dataframe is going to quickly become too much. At this point the result is simple enough that  it provides flexibility. As we get user feedback and use cases then we can better assess the best way forward.

**Comment by jonahaag** [comment]
I already experienced the issue with the big data frame to some degree.

To illustrate this: In the tutorial, we specify a model_reporter for the Gini Coefficient and a agent_reporter for each agent's wealth in the model itself. When using `batch_run`, this results in the returned list to be of length 6186250 (= 250 average agents per population * 49 different populations * 5 iterations per population * 101 steps per iteration) if we additionally set i_steps = 1. 

The more general problem with this seems to be that if we want to collect two or more "types" of data that have different time scales, squashing everything in this one return will make analysis harder. In the example, we are only interested in 245 different values for the Gini Coefficient (collection frequency = 1/iteration, the same for entire population) but the agent's wealth needs to be collected at each time step and for each agent. For the latter, it might suffice to collect the data only for certain parameters configurations. 

If one is not too familiar with pandas then that would require him/her to search for the right way to filter only the unique data points wanted. In this case, it might be faster to run multiple batch runs with just one reporter at a time, but then the model class would need to be updated for each run. Also, this doesn't work for large models where each iteration takes much longer. One thing that comes to mind for me is to allow the user to set the frequency of the data collector for each reporter separately and then return multiple lists containing only the values needed for the individual reporters.

**Comment by jonahaag** [comment]
Btw, I haven't really used pandas before so maybe it is just super easy to do the filtering etc. That would obviously make all the stuff I just said obsolete 😄 

As for the tutorial: should I stick with both reporters, i.e. the big data frame or run multiple times? Here, we want to first look at the Gini over all iterations and then at the development of the agent's wealth and the Gini over the course of one iteration for a specific number of agents.

**Comment by jdfoote** [comment]
I agree - the default of reporting every step for every agent with all of the data stored for each agent can blow up the data and even cause memory problems for runs with lots of agents and lots of iterations.

I can think of a few things that could help:
1. Making the default reporting only every 10(?) steps plus at the end?
2. Having each run write to a file instead of staying in memory?

**Comment by jonahaag** [comment]
Actually, the default value for `i_steps` is -1, i.e. only at the end of each episode. 
This doesn't really solve the problem of how to deal with reporters that collect values which change on different time scales though.

**Comment by tpike3** [comment]
Sorry for the delay I was having to finish a paper. 

Regarding your question @jonahaag ... "As for the tutorial: should I stick with both reporters?" Yes To ensure we are snyced as I often forget there are multiple tutorials are you on the [master](https://mesa.readthedocs.io/en/master/tutorials/intro_tutorial.html#batch-run])

We want the tutorial to show the Gini plot, and the raw agent and model reporters results.

@jdfoote Those are excellent points and as there will not be a universal answer to when to save  is my stream of conscious response would be to add a parameter that saves as a json or similar (as pickle objects can have issues with multiprocessing).

**Comment by jonahaag** [comment]
Just opened a PR (#1119) to discuss changes in more detail. I'll leave this issue open for now to come back if I want to further contribute.
