### ISSUE TITLE
Agent observation

### ISSUE THREAD

**Issue by rhari008** [projectmesa/mesa#1126]
I would like to have the feature where agents can observe what other agents are doing. Currently with the kind of synchronous operations, I believe its not possible.

**Comment by jackiekazil** [comment]
If I understand your request -- have you considered adjusting the scheduler? 
https://mesa.readthedocs.io/en/master/apis/time.html 
Demo: https://github.com/projectmesa/mesa/blob/main/examples/pd_grid/analysis.ipynb

**Comment by rhari008** [comment]
Thanks for the response. Here is an example of what I requested:

There are two types of agents - Consumer and Provider. In stage 1, consumers are randomly paired with providers. A provider can either be good or bad. I want yet another type of agent introduced called the observer agent that can rate a provider by observing how it is serving a consumer.

**Comment by jackiekazil** [comment]
Is this what you are looking for? https://mesa.readthedocs.io/en/stable/apis/time.html#mesa.time.StagedActivation

**Comment by rhari008** [comment]
I explored that as well. Do you have an example, please? 

But, this requirement needs the agents to be operated in parallel.

**Comment by jackiekazil** [comment]
I don't believe there is one. Can you submit a ticket?

**Comment by quaquel** [comment]
With #2291 merged, this is straightforward to implement by a user if needed.
