### ISSUE TITLE
Rename argument nr_processes of batch_run

### ISSUE THREAD

**Issue by jonahaag** [projectmesa/mesa#1127]
As @rht proposed in #1119, the name of the variable indicating the number of processors used for [batch_run](https://github.com/projectmesa/mesa/blob/68c48e6d1de2a3b7d102a3530920b2a4f5cc08e7/mesa/batchrunner.py#L34) should be renamed:

> This is yet another variable renaming: I think `nr_processes` can either be expanded to `number_processes` or `number_of_processes` (I don't see the point of shortening 'number' to 'nr'), or use Python multiprocessing's naming, https://docs.python.org/3/library/multiprocessing.html#multiprocessing.pool.ThreadPool, which is just `processes`.

My vote is on `number_of_processes` or `processes` for the given reasons.

**Comment by tpike3** [comment]
See [1141](https://github.com/projectmesa/mesa/pull/1141)
