### ISSUE TITLE
Be able to define a scheduler in agent level data collection 

### ISSUE THREAD

**Issue by Caesar-blip** [projectmesa/mesa#1136]
**What's the problem this feature will solve?**
I have 2 different schedulers in my model, and I want to collect agent-level in both of them. However, the data collector only looks for agents in model.schedule.

**Describe the solution you'd like**
We should be able to change the default of model.schedule to another schedule object inside the model.

**Additional context**

**Comment by rht** [comment]
You can do this by writing a custom `DataCollector` class that uses both of your schedulers.
