### ISSUE TITLE
[question] how can I reset a model value every step?

### ISSUE THREAD

**Issue by MushiTheMoshi** [projectmesa/mesa#1137]
Hi there,

First of all thank you for all the work done here.

I would like to know how can I reset a model variable every step, I have agents subtracting units from it and I want to reset this variable every step. What could be a workaround here?

Thanks in advance,
Julio

**Comment by rht** [comment]
You can do it using the usual Python attribute assignment at the beginning of the model step.
```python
def step(self):
    self.some_attribute = some_value
    ....
```

**Comment by MushiTheMoshi** [comment]
Thank you, although I forgot to mention that the variable is coming from the Modular server, meaning that is dynamically assigned. Even though I manage to solved with a Class variable.
