### ISSUE TITLE
[question] Advice on saving data

### ISSUE THREAD

**Issue by MushiTheMoshi** [projectmesa/mesa#1143]
Hi there,

I looked over the documentation and closed tickets though I couldn't find any recommendation on saving data. So I'm coming here hoping someone point me in the right direction.

What is the recommendation on saving data? 
Should it be managed from the model itself ?  
When using BatchRunnerMP, model and agent reporters data not coming as DataFrames but as an OrderedDict and is truncated by the max numbers of displayed entries, how can I export export this to csv or any other useful format?

Is there any guide on saving data?

Thanks in advance,
Julio

https://mesa.readthedocs.io/_/downloads/en/stable/pdf/
![image](https://user-images.githubusercontent.com/13651419/150681910-eb07558c-8b1f-400d-87ca-c740eb8d1952.png)

**Comment by tpike3** [comment]
@MushiTheMoshi 

What is the recommendation on saving data?
For the data itself I typically use [pickle](https://www.journaldev.com/15638/python-pickle-example). This will allow you to save in the python datastructures in a more compressed format. 

What is the recommendation on saving data?
Depending on how large the model is and how much data you are collecting, you may have to save it mid stride (for which you can use pickle) and then clear the data

... how can I export export this to csv or any other useful format

The new tutorial should give you an example of converting (should on the website in a week or two) but you can see it [here](https://github.com/projectmesa/mesa/blob/main/docs/tutorials/intro_tutorial.rst)

**Comment by rht** [comment]
> .. how can I export export this to csv or any other useful format

> The new tutorial should give you an example of converting (should on the website in a week or two) but you can see it here

If you search for "csv" in that link, you won't be able to find what you need. You need to search for the word "export", which leads to Pandas DataFrame export, which is in csv format.

**Comment by MushiTheMoshi** [comment]
Thank you so much for the quick response.

On the guide I noticed is used "batch_run", I can't see that one in mine.

![image](https://user-images.githubusercontent.com/13651419/150687236-4c8ab11d-1441-4f77-9b63-f6a09555e136.png)

**Comment by tpike3** [comment]
The code to convert the results from BatchRunnerMP should be roughly equivalent to what's in the tutorial. Here is anther [helpful reference as well](https://chrisalbon.com/code/python/data_wrangling/pandas_data_structures/).  

Batch run will be in the next release but you can get by installing from github so it is `pip install 
https://github.com/projectmesa/mesa.git`

**Comment by MushiTheMoshi** [comment]
Thank you!

**Comment by rht** [comment]
> If you search for "csv" in that link, you won't be able to find what you need. You need to search for the word "export", which leads to Pandas DataFrame export, which is in csv format.

I think that tutorial would have been more informative if it says that the output is csv. It shouldn't assume that the reader knows some details about Pandas.
