### ISSUE TITLE
Batch runner depends on running

### ISSUE THREAD

**Issue by dmasad** [projectmesa/mesa#115]
The Batch Runner fails silently if the model it is running does not have a *running* parameter set to True at least by default.

**Comment by dotsdl** [comment]
I'll work on this. :D

**Comment by jackiekazil** [comment]
@dotsdl :+1:

**Comment by jackiekazil** [comment]
Open to anyone picking it up... please post if you do.

**Comment by dmasad** [comment]
I'll take it, unless nobody else does it first.

**Comment by dmasad** [comment]
Fixed.
