### ISSUE TITLE
python setup.py install step missing in the documents

### ISSUE THREAD

**Issue by pjercic** [projectmesa/mesa#1156]
**Describe the bug**
There is a setup.py install step missing in the documentation

**Expected behavior**
After installing the mesa package using `pip install mesa` it would be expected to run `python setup.py install` to use *mesa* command in the terminal `mesa runserver examples/wolf_sheep`

**To Reproduce**
Follow steps in the section: *Docs > Mesa: Agent-based modeling in Python 3+ > Using Mesa*

**Comment by rht** [comment]
Reading https://stackoverflow.com/questions/42182707/pip-not-installing-entry-points-as-executables, it might be the case that `pip install` installs the CLI to a different path from `python setup.py install`.

**Comment by pjercic** [comment]
That might be the case that the CLI is hidden somewhere, but users are left without an 'alias' to this other location of CLI.
This effectively makes mesa unusable in the command line.

**Comment by rht** [comment]
This is not a Mesa-specific problem, this is `pip install` path. `pip` installs the executable in a path that happens to not be included in your `$PATH`. You simply need to add the path into `$PATH`.

**Comment by pjercic** [comment]
Thanks for the info. I believe that the Mesa introductory tutorial (on Mesa website) should have this advice given, exactly like you have written it in your reply. Maybe as a note under the installation procedure, for the users that are not able to run Mesa directly from the command line due to this pip issue.

**Comment by rht** [comment]
I usually just run a simulation straight from the .py file itself and I have my `$PATH` defined properly. And so this has escaped my radar.

The relevant issue is https://github.com/pypa/pip/issues/3813, which is solved by https://github.com/pypa/pip/pull/4553. Are you sure `pip` didn't warn you when you did `pip install ...`?

**Comment by pjercic** [comment]
Cannot remember, sorry.
Next time installing, i will keep an eye on the pip warning.
