### ISSUE TITLE
iterate over an agent

### ISSUE THREAD

**Issue by Harshpanday** [projectmesa/mesa#1157]
Hi,
I am making a model which has 6 different types of agents, each agent has its own attribute.
One of my agents is "rich_household", which has an attribute of food availability(int), now I want to sum food availability of all the rich_households on my grid.
Is there a way I can do that?
I wrote a function for this, but it is only taking 1 rich_household into account, I tried looping but I got an error that said rich_household object is not iterable.
I will be very grateful if someone can suggest me a solution.

**Comment by rht** [comment]
You can do
```python
total_food_availability = 0
for agent in model.scheduler.agents:
    if isinstance(agent, <your rich household class>):
        total_food_availability += agent.food_availability
```
You should look up online for examples of the behavior of `isinstance`.

**Comment by Harshpanday** [comment]
Thank you very much.
