### ISSUE TITLE
CI: Python 3.6 should be removed because it has reached EOL

### ISSUE THREAD

**Issue by rht** [projectmesa/mesa#1165]
See https://endoflife.date/python.

**Comment by tpike3** [comment]
Concur

**Comment by EwoutH** [comment]
I would suggest following [NEP 29](https://numpy.org/neps/nep-0029-deprecation_policy.html). They dropped Python 3.7 on Dec 26, 2021 and will drop Python 3.8 on Apr 14, 2023. This way, there will be always at least 2 minor Python versions supported (and almost always three minor versions).

> This project supports:
> - All minor versions of Python released 42 months prior to the project, and at minimum the two latest minor versions.
> - All minor versions of numpy released in the 24 months prior to the project, and at minimum the last three minor versions.

Maybe do a 0.9.1 release as the last 3.6+ release (including RandomActivationByType and using the PyPI release workflow), and then drop Python 3.6 and 3.7 support to become Python 3.8+ onwards to 1.0.0.

**Comment by rht** [comment]
Sounds good. I wonder if NumFOCUS demands such standardized timeline for their affiliated projects.

**Comment by rht** [comment]
Removing 3.6 in #1212 because it's breaking CI. It's already EOL anyway. Let's do the NEP 29 timeline for 3.7+.

**Comment by tpike3** [comment]
This looks like it is already done and i just missed it, so closing.
