### ISSUE TITLE
update GitHub actions to auto tag releases

### ISSUE THREAD

**Issue by tpike3** [projectmesa/mesa#1172]
update GitHub actions to auto tag releases

**Comment by EwoutH** [comment]
@tpike3 Wait how do you expect this should work?

In my experience, a tag can either be created from a commit or be created when publishing a release. And publishing to PyPI is now covered in #1169.

**Comment by tpike3** [comment]
@EwoutH Thanks for the catch... I am closing this issue and linked #1169 to the March Dev.
