### ISSUE TITLE
Color gradient feature in agents portrayal is not documented properly

### ISSUE THREAD

**Issue by rht** [projectmesa/mesa#1183]
See e.g. https://github.com/projectmesa/mesa/blob/main/examples/wolf_sheep/wolf_sheep/server.py#L31

This feature was added via https://github.com/projectmesa/mesa/commit/da194e3556e7a8e61af05da3f726ef42ec7c7c0c, but is lacking documentation.

**Comment by quaquel** [comment]
this feature is not directly supported in the current matplotlib/altair style visualizations (although it could be done with some cleverness in the agent_portrayal method and refers to an older style visualization. Closing for now.

**Comment by quaquel** [comment]
I just fixed this via #2445

**Comment by EwoutH** [comment]
In that case let’s do it the proper way!
