### ISSUE TITLE
Large agent population run time

### ISSUE THREAD

**Issue by kaharrington** [projectmesa/mesa#1185]
Hello,

Is there a way to cut down run time when using very large agent populations? I am hoping to use about 2.7 million agents (the population of Chicago) but the code or more likely my computer doesn't seem up for the job. I can have it run a proportion of that population but it takes multiple days, even when running only 1 iteration through BatchRunner. Any suggestions are welcome! Thanks!

**Comment by rht** [comment]
This might not be the solution to your problem, but you might have to store your agents attributes, each in a Numpy array, and do an array operation when doing the step. Not sure of the detail of your model, whether you have to step 2.7 million times, or update the attributes altogether by a single matrix x array operation.

**Comment by kaharrington** [comment]
Thank you for the quick reply! As a brief overview, agents (which represent people) have a location around the city and they make eating decisions based on their attributes (budget, preference, proximity to food stores). Each step is one day with 6 time chunks, agents decide to eat (and where) or not to eat at each time chunk. I can send along the code as well if that could be helpful. I'm definitely not a Python expert but will look into your suggestion, if you could think of anything else that could be helpful I'd greatly appreciate it. Thanks!!

**Comment by rht** [comment]
Yes, uploading the code to a GitHub repo or gist will help.

Also, 2.7 million of Python objects definitely cost a lot of RAM, in addition to being slow.

**Comment by kaharrington** [comment]
Here is the link to the repo: https://github.com/kaharrington/Chicago-Diet-Scores 

Thanks!

**Comment by rht** [comment]
@kaharrington I profiled your model using https://github.com/pyutils/line_profiler. The slowest part is actually in the mesa-geo-specific code https://github.com/kaharrington/Chicago-Diet-Scores/blob/7c262c581bb177e10019c6177b8c500a496d82a7/agents.py#L113-L114, which took 77 s out of the total 89 s.

The best time saving strategy, IMO, is to cache the neighbors of the agents once for all, without recomputing them every time, since it seems that their location are oscillating only between `self.work` and self`home`? You should get at least 7.5x speed up.

**Comment by rht** [comment]
Hmmm. I don't think caching works out of the box, because the other agents location are also not fixed, as they oscillate between `work` and `home`. But this is a useful constraint: you can check whether an agent is at home or at work, and decide whether the agent is a neighbor accordingly.

From the profile, the next line you could optimize is `if isinstance (f, PersonAgents)`, which takes 7.2% of the time of `influences`, while the mesa-geo part takes 91.2% of the time.
```
Line #      Hits         Time  Per Hit   % Time  Line Contents
==============================================================
   137                                               @profile
   138                                               def influences(self):
   139                                                   #FRIENDS SOCIAL NETWORK
   140       388        876.0      2.3      0.0          friends = []
   141       388       7559.0     19.5      0.0          Friends_N = random.randint(1, self.model.N) #agents can have varying number of friends, from 1 to all agents             
   142       388       1348.0      3.5      0.0          PA_Friends = self.model.grid.get_neighbors_within_distance(self, 132000) #everyone in city
   143   4428164   70756530.0     16.0     91.2          for f in PA_Friends:
   144   4427776    5579420.0      1.3      7.2              if isinstance (f, PersonAgents):
   145     37670      74590.0      2.0      0.1                  friends.append(f.DietScore)
   146       388       3714.0      9.6      0.0          if sum(friends) == 0:
   147                                                       self.FriendsScore = self.DietScore
   148                                                   else:
   149       388        993.0      2.6      0.0              if len(friends) > Friends_N:
   150       367     103450.0    281.9      0.1                  Sample_Friends = random.sample(friends, Friends_N)
   151       367     153156.0    417.3      0.2                  self.FriendsScore = st.mean(Sample_Friends)
   152                                                       else:
   153        21      12449.0    592.8      0.0                  self.FriendsScore = st.mean(friends)
   154                                                   
   155                                                   #Store Proximal Neighbors' Preferences - those at work with the agent or in the store/their surroundings
   156       388        700.0      1.8      0.0          neighbors = []
   157       388       2091.0      5.4      0.0          PA_Neighbors = self.model.grid.get_neighbors_within_distance(self, 330) #PERSON AGENT NEIGHBORS (PA_Neighbors)
   158      3203     466586.0    145.7      0.6          for n in PA_Neighbors:
   159      2815       5344.0      1.9      0.0              if isinstance (n, PersonAgents):
   160       196        402.0      2.1      0.0                  neighbors.append(n.DietScore)
   161       388       1048.0      2.7      0.0          if sum(neighbors) == 0:
   162       192        301.0      1.6      0.0              neighbors_score = self.DietScore
   163                                                   else:
   164       196      22804.0    116.3      0.0              neighbors_score = st.mean(neighbors) 
   165                                                         
   166                                                   #Combine inlfuences to update preferences
   167                                                       #1: calculate environmental and social influenecs
   168       388       1567.0      4.0      0.0          InfENV = self.DietScore * self.stress
   169       388        837.0      2.2      0.0          InfSOC = ((self.DietScore + self.FriendsScore + neighbors_score) / 3) #averaging own choices with neighbors and friends
   170                                           
   171                                                       #2: combine influences (mean of food preferences, environmental, and social influences)
   172       388       4182.0     10.8      0.0          Influence = round(((InfENV + InfSOC) / 2), 3)
   173                                                   
   174                                                       #Thresholds for change = 10%
   175       388        580.0      1.5      0.0          Tup = (self.DietScore + (0.10 * self.DietScore)) #UPPER THRESHOLD
   176       388        569.0      1.5      0.0          Tlow = (self.DietScore - (0.10 * self.DietScore)) #LOWER THRESHOLD
   177                                                   
   178                                                       #3: UPDATE PREFERENCES
   179       388        475.0      1.2      0.0          if Influence >= Tup:
   180                                                       self.DietScore = round((self.DietScore * 1.05), 2)
   181       388        432.0      1.1      0.0          elif Influence <= Tlow:
   182       316       1012.0      3.2      0.0              self.DietScore = round((self.DietScore * 0.95), 2)
   183                                                   else:
   184        72        196.0      2.7      0.0              self.DietScore = round(self.DietScore, 2)       
   185                                                           
   186       388     353744.0    911.7      0.5          self.Eat()
```

**Comment by kaharrington** [comment]
This is super helpful, thank you for taking the time to look through this.
The "friends" portion I think could definitely be changed (like you
mentioned) to be set once, not each step, since the idea behind this
network is more of a person's friend group which is usually unchanging. I
am relatively new to Python and thus unfamiliar with how to cache, could
this be set up at initialization? The potential pool of "friends" would be
a random number of people from around the whole city. The "PA_neighbors"
piece represents individuals who are near the agent right before they make
an eating decision, so that piece would have to stay where it is, and
update each time.

**Comment by rht** [comment]
I think we have uncovered the underlying cause to the slowness, and the solution to it, so I'm closing this issue.
