### ISSUE TITLE
Regarding Adding agent to grid

### ISSUE THREAD

**Issue by Nagateja23** [projectmesa/mesa#1189]
Hello everyone,
I am new to Mesa, and I am facing a problem. 
When I am trying to agents to the grid, I am getting an error saying "Cell not empty", even though I am adding only 40 agents to a 50*50 grid. 
I found a workaround that is I am using "if self.grid.is_cell_empty(pos) is True:" but due to this condition, not all 40 agents are being added to the grid.
` if self.grid.is_cell_empty(pos) is True: `
                   `agent = OpioidUser(self.next_id(), pos, self, True, race,sex,age_group,per_cum,p,agent_type)`
                    `self.grid.place_agent(agent, (x, y))`
                   `self.schedule.add(agent)`
![error](https://user-images.githubusercontent.com/48374832/158523547-15dca009-df5a-4ee3-b6a1-4a98fe54aa90.png)

I'll be very grateful if someone could tell me why am I getting this error.

With Kindest regards,
Teja

**Comment by rht** [comment]
You can either:
1. stick to `SingleGrid`, which I assume you are already using, and make sure that there is no overlap when placing the agents. You can do a while loop: while occupied, pick new coordinate and try to place the agent there
2. use `MultiGrid`, which can accommodates multiple agents in 1 cell.

**Comment by rht** [comment]
Closing this issue. If you still have problem, let us know so that I will reopen the issue.
