### ISSUE TITLE
Install JS dependencies using Fanstatic

### ISSUE THREAD

**Issue by rht** [projectmesa/mesa#1195]
We currently vendor the minified JS dependencies as files. I have looked around Stackoverflow, and a more maintainable approach is to use Fanstatic, which wraps the JS resources as if they were a Python library. See http://www.fanstatic.org/en/latest/libraries.html. E.g. to include D3.js, simply add js.d3 in the requirements in setup.py. This has the following benefits:
- creates a clear separation of which JS files are Mesa-specific, and which JS files are dependencies
- reduces the size of the repo. Imagine D3.js being updated 10 times -- we'd have 10 copies of minified D3.js in the repo, making it unnecessarily bulky

**Comment by rht** [comment]
Additional benefit: we no longer need to create a THIRDPARTY file that attributes all the third party dependencies (including their license) that are vendored in Mesa, since those files will be downloaded by the users from PyPi separately.

**Comment by EwoutH** [comment]
It would be a great approach!

It looks like Fanstatic packages are not maintained however. The [latest](https://pypi.org/project/js.bootstrap/) Bootstrap version on there is 3.3.4 from April 2015 and the [latest](https://pypi.org/project/js.d3/) D3 version is 3.5.5 from July 2015.

**Comment by rht** [comment]
Fanstatic itself seems to be still actively maintained: https://github.com/fanstatic/fanstatic.
I wonder if there is a modern vendor for those JS packages. Perhaps unofficial ones.

**Comment by rht** [comment]
https://stackoverflow.com/questions/49953785/which-options-do-exist-for-defining-a-python-package-with-node-js-dependencies has an extensive answer from the author of calmjs.

However, I'm tempted to conclude that the easiest method is to just download those static js/css files on the fly during `pip install`.

**Comment by rht** [comment]
I ended up doing #1220, with follow up #1236.

**Comment by wang-boyu** [comment]
How about use `npm` to manage 3rd party javascript dependencies, which can be defined in a `packages.json` file? These libraries will be installed into the `node_modules` directory.

Or use [webpack](https://webpack.js.org) to bundle all dependencies from `node_modules` to our `visualization/templates/external/` directory.

In this way we can avoid writing code to download and unzip javascript libraries in `setup.py`.

**Comment by rht** [comment]
The problem with `npm`/Webpack is that it creates an extra hassle to install Mesa. `npm` may be an apt-get away on Debian, but is not the case with macOS/Windows.

**Comment by rht** [comment]
If we go the `npm` route, then we can require `npm` install for installing Mesa from Git, but we bundle the JS files in the releases. This is an extra hurdle for contributors, however.

**Comment by wang-boyu** [comment]
It's probably a matter of trade-off between dependency management tools vs. manual maintenance in `setup.py` for each JS package. So far there aren't too many external dependencies, so I guess it's still manageable.

**Comment by rht** [comment]
The maintenance effort in setup.py is constant, because the same code is use for all the dependencies. See https://github.com/rht/mesa/blob/31d768b3b2120296ef4962b1efaf40fa521d4524/setup.py#L37-L50.
