### ISSUE TITLE
Create a way/method to test models

### ISSUE THREAD

**Issue by jackiekazil** [projectmesa/mesa#120]
We need a standardized way of testing a model package. See #20... this is where this idea came from. 

Questions: 
- What are we trying to test? 
- How big or small should this be?

**Comment by ReblochonMasque** [comment]
*Repeat of the problem description from closed issue #20:*
> The problem with unit-testing ABMs is that all their components are so interconnected. What if Mesa had a built-in unit-testing framework designed specifically for ABMs? I don't think such a thing exists yet, but it could be very valuable.

I may be wrong, but I think unit testing usually refers to the testing of individual methods.

What you seem to mean here is a general behavior/functionality testing: does the model do what it is supposed to do?

Here, this seems to split again into two parts:
--> Does the mesa package runs a model as intended?
--> Does the model (client code) complies with its description.

In my opinion, the testing should be at all three levels, with various degrees of importance and priority:
- on top is unit testing.
- then functionality testing (do the units work well together?)
- last is client code... Netlogo, AFAIK has models submitted to them split into an endorsed category (may have a different name) and an non checked one.

Does the proposed **"built-in unit-testing framework designed specifically for ABMs"** fit in the last category, or am I misunderstanding it?

On the topic of testing, It might be a good idea to prioritize and open smaller size tickets?

**Comment by jackiekazil** [comment]
@ReblochonMasque This is a great breakdown! 
And yes....  The proposed "built-in unit-testing framework designed specifically for ABMs" fit in the last category.

Do you want to open up tickets? And we can discuss priority for each item. 
The testing framework we have in place right now, was to have SOMETHING over nothing, but that is another thing that needs to be over hauled.

**Comment by ReblochonMasque** [comment]
Well noted Jackie, thank you for the clarification.
I like your suggestion, but I think we first need 100% unit-test coverage of the base classes.

**Comment by jackiekazil** [comment]
This ticket is "boil the ocean". I am going to close it. We are progressively moving towards better test coverage.
