### ISSUE TITLE
Move Mesa-Geo

### ISSUE THREAD

**Issue by tpike3** [projectmesa/mesa#1206]
Per conversations with @Corvince We want to move Mesa-Geo to the Project Mesa repository and add CI processes.

**Comment by tpike3** [comment]
phase 1 complete...@Corvince had transferred ownership to projectmesa.

**Comment by jackiekazil** [comment]
moving this convo over to mesa-geo issues -- https://github.com/projectmesa/mesa-geo/issues/46
