### ISSUE TITLE
Help Wanted: Prevent Agent from being matched more than once in a single step

### ISSUE THREAD

**Issue by themmyloluwaa** [projectmesa/mesa#1226]
Thank you very much for this amazing package. It's been a delight to work with it ❤️.

I have a simulation that's similar to the Boltzmann Wealth Model with the following difference.

In each step
- agent who received wealth should not be available for giving other agents wealth and it should not be available for receiving wealth from other agents in that same step.--> A
- the agent who gave wealth should not be available for receiving wealth from other agents --> B

My use case is to simulate a conversation between multiple users in a system where when two users match, they should not be available for matching with other users in the system in that step (tick). 

My approach which solves the giver agent problem (B) is to have a boolean attribute called `is_matched` and only carry out matching if it's False otherwise I reset the state back to False.

```python
def step(self) -> None:
      if not self.is_matched:
         if self.quid >= 15:
            self.prematch()
         else:
            self.wait_for_quid()
      else:
         self.is_matched = False
```  

and in `prematch` method, only consider agents who have not been previously matched for conversation. 
```python
      my_cell = self.model.grid.get_cell_list_contents([self.pos])
      my_cell = list(filter(lambda x: x.is_matched == False, my_cell))
```

So far, the code snippets shared ensures that the giver agent can't be the receiver agent in that step (tick) and it can't be a giver to another agent. It also prevents the receiver agent from being the giver in that same step (tick), but it doesn't solve the case where the receiver agent can still be a receiver to a different giver agent in the same step (tick). 

For example, here's what I want to achieve.
Assuming there are 4 agents labelled A, B, C, D and in a single step the following match occurs
**_A (giver) matches B (receiver)_** 

- A should not be available for giving to other agents C and D
- A should not be available for receiving from other agents B, C, D
- B should not be available for giving to other agents A, C, D
- <ins>B should not be available for receiving from other agents C, D</ins>

The underlined item is the use case that my shared code snippet doesn't solve as B can still be the receiver for C or D in that single step. 

What I have also tried is to remove the matched agents from the scheduler after matching has occurred between them but this breaks the simulation.

I would appreciate any help in how I can solve the problem or achieve these use cases better.

Thank you.  

GH Repo - https://github.com/themmyloluwaa/chat_model/

**Comment by rht** [comment]
Did you mean that you have solved your issue, but are looking for a better way to do it?

**Comment by themmyloluwaa** [comment]
@rht No, I haven't solved the issue. My apologies if the initial explanation didn't make this clear, I will update it now. 


I haven't solved problem (A) where the agent who received the wealth should not be available for either receiving wealth from a different agent or giving wealth in each step of the simulation. For example, if they're 4 agents labelled A, B, C, D, and in a single step A matches with B, what I observe is that B can still be matched with either C or D in that same step. This shouldn't be the case as both A and B are already matched so they should be unavailable for matching with other agents. So far the code snippet ensures that B cannot be the one who initiates the match and A cannot be the receiver of the match in that step but I can't get it to prevent B from matching with C or D in the same step that produces a match with A. 

What I have also tried is to remove the matched agents from the scheduler after matching has occurred between them but this breaks the simulation.

**Comment by rht** [comment]
Have you made sure that `self.prematch()` set `is_matched` to be `True` for a pair of agents (A and B), not just agent A?

**Comment by themmyloluwaa** [comment]
Yes, I have that in place and I also move both of them to a random position.

**Comment by rht** [comment]
OK, in that case it would be faster if you can share the code in a GH repo or gist.

**Comment by themmyloluwaa** [comment]
Thank you @rht 

Here's a GH repo containing the model code and description of the model. 

https://github.com/themmyloluwaa/chat_model

**Comment by rht** [comment]
OK, I figured your problem:
```python
      if not self.is_matched:
         if self.quid >= 15:
            self.prematch()
         else:
            self.wait_for_quid()
      else:
         self.is_matched = False
```

You need to do `self.is_matched = False` of all agents only *after* all agents have done their `step()`. You just need to delete that else, and then in the model step, you set each agent's `is_matched` to `False` after `self.schedule.step()`.

**Comment by themmyloluwaa** [comment]
Yas 🎆 , just implemented the fix you suggested and it works as expected.

Thank you very much.

**Comment by tpike3** [comment]
@rht Thanks for the assist. You rock!
