### ISSUE TITLE
UX: flat Mesa namespace alternative

### ISSUE THREAD

**Issue by rht** [projectmesa/mesa#1229]
Consider that instead of
```python
from mesa import Model, Agent
from mesa.time import RandomActivation
from mesa.space import SingleGrid
from mesa.datacollection import DataCollector
```

We do a single import (like `import matplotlib.pyplot as plt`)
```python
import mesa.all as ma

self.space = ma.SingleGrid
...
self.datacollector = ma.DataCollector(...)
```
This way, we can have modular namespaces that are not polluted, while at the same time have a flat namespace for ease of use.

**Comment by rht** [comment]
Note: it's bad to only have 100% flat namespace like MATLAB does.

**Comment by rht** [comment]
My proposal is for both flat namespace (`mesa.all`) and the existing hierarchical namespace to coexist, just like `matplotlib.pyplot`, and so this won't require existing users to suddenly change their code.

**Comment by Corvince** [comment]
Hi I think it is generally a good idea, but is it necessary to have another namespace for this? Wouldn't it be easier to simply re-export everything in the mesa namespace? I think that is a more common approach, but I don't know if there are any downsides.

**Comment by rht** [comment]
I was thinking along the line of `import matplotlib.pyplot as plt`.

`import mesa; mesa.DataCollector` could work, but there is a collision with `mesa.visualization`. In #1244, I flatten all the visualization functions, classes to be inside `mesa.all.visualization`, and this will conflict with the existing `mesa.visualization` if they are to be put into `mesa` instead of `mesa.all`.

**Comment by rht** [comment]
@Corvince #1294 is an alternative implementation along the line of your recommendation.
