### ISSUE TITLE
UX: Simplify schedulers class names

### ISSUE THREAD

**Issue by rht** [projectmesa/mesa#1231]
What if, instead of
```python
from mesa.time import RandomActivation
self.schedule = RandomActivation(...)
```
we do
```python
import mesa.time
self.schedule = mesa.time.Random(...)
# or, as per https://github.com/projectmesa/mesa/issues/1229
self.schedule = ma.time.Random(...)
```
As in, the context that it is a scheduler, is reflected by the namespace, and so we don't need to redundantly say that it is an "activation":
- `StagedActivation` -> `Staged`
- `RandomActivationByType` -> `RandomByType`
- and so on.

This is inspired by the way Agents.jl name their schedulers.

**Comment by rht** [comment]
We may need to rename `mesa.time` to `mesa.scheduler` for clarity.

**Comment by quaquel** [comment]
all schedulers are deprecated with mesa 3.0
