### ISSUE TITLE
JS refactor: We should replace all usage of `var x = ...` with `const` / `let` in the JS code

### ISSUE THREAD

**Issue by rht** [projectmesa/mesa#1232]

**Comment by SangameshItagi** [comment]
Hi @rht , I can help here

**Comment by rht** [comment]
@SangameshItagi sounds good. Make sure to not do one big PR while doing it. It's better to do several small-medium sized PRs so that it is easier to review and merge.

**Comment by trickroll** [comment]
Tried to tackle a few of the files instead of a big PR!

**Comment by rht** [comment]
To avoid duplication of work:

In #1248, @SangameshItagi is working on
- mesa/visualization/templates/js/CanvasHexModule.js
- mesa/visualization/templates/js/CanvasModule.js
- mesa/visualization/templates/js/GridDraw.js
- mesa/visualization/templates/js/HexDraw.js

In #1246, @trickroll is working on
- mesa/visualization/templates/js/NetworkModule_sigma.js
- mesa/visualization/templates/js/PieChartModule.js
- mesa/visualization/templates/js/TextModule.js

**Comment by rht** [comment]
Remaining JS files up for grabs:
- [ ] BarChartModule.js
- [ ] ChartModule.js
- [ ] NetworkModule_d3.js
- [ ] runcontrol.js

**Comment by rht** [comment]
Closed via #1265.

**Comment by rht** [comment]
I missed one more JS file: there is still InteractionHandler.js. However, we should wait until #1266 is merged.

**Comment by rht** [comment]
Closed via #1273.
