### ISSUE TITLE
Consider HoloViews for your animation needs

### ISSUE THREAD

**Issue by jlstevens** [projectmesa/mesa#127]
Hi

I spotted your SciPy 2015 paper submission and decided to have a look at your project - I've previously enjoyed playing around with agent based models in [Netlogo](http://ccl.northwestern.edu/netlogo/index.shtml). Mesa looks like a nice to a way of doing ABM in Python!

In your forest fire notebook, I noticed you TODO item ("Add a MatPlotLib visualization") and as the author of a new library called [HoloViews](http://ioam.github.io/holoviews/) that is designed for exploring models and animating data, I decided to give it a go. Here is [my version of your notebook](http://nbviewer.ipython.org/gist/jlstevens/9c7835e4e21c5d844ded)

Obviously you should employ whatever approach you feel most comfortable with. That said, I think you will agree that  HoloViews has managed to generate some nice output with very little code!

It seemed worth making you aware of an new, alternative approach to tackling visualization problems that avoids working with matplotlib directly.

**Comment by dmasad** [comment]
Thanks for the heads-up. HoloViews seems really useful, and the notebook with the visualization looks excellent! Definitely something we'll explore.

**Comment by jlstevens** [comment]
Great! :-)

I'll play around with the other Mesa notebooks in my spare time and keep you up-to-date with any nice examples I come up with.

It might be a little too early, but if you have any queries about HoloViews, please feel free to ask us questions on [gitter](https://gitter.im/ioam/holoviews).

**Comment by jackiekazil** [comment]
@jlstevens Thank you for bringing this to our attention. HoloViews does look interesting! 
We will definitely consider. 

I am closing this for now since there is no action item at this time.
