### ISSUE TITLE
Only way to visualize multiple models is multiple tornado servers?

### ISSUE THREAD

**Issue by patrickkidd** [projectmesa/mesa#1306]
I'd like to show multiple models on a web page. I guess the only way to do that is to fire up one per port, each on its own process? I wonder what it would take to serve multiple models from the same port differentiated by URL path or params.... Then you could stick each one in an iframe and not have to touch the HTML or CSS.

**Comment by rht** [comment]
Good question, you can wait until #1296 is merged.

**Comment by patrickkidd** [comment]
Yes, a URL path or argument would be the preferred way to handle this. Looking forward to it.
