### ISSUE TITLE
Showing descriptions of model parameters in the web interface

### ISSUE THREAD

**Issue by anpingzzzz** [projectmesa/mesa#1307]
Would that be possible to show descriptions of model parameters in the web interface?

**Comment by rht** [comment]
This should be possible with the description param, see e.g. https://github.com/projectmesa/mesa/blob/006359b2a7e9a3b550b790c1b16c5a089521bb27/examples/wolf_sheep/wolf_sheep/server.py#L73. But looks like it's not even showing up as a tooltip. Investigating this right now.

**Comment by rht** [comment]
Check out #1308. But if you want a longer description without hover, you might have to just make the title longer.

**Comment by rht** [comment]
@anpingzzzz check out #1342. This is how to add text without hover, without the title.
