### ISSUE TITLE
Docs: Update tutorial

### ISSUE THREAD

**Issue by tpike3** [projectmesa/mesa#1315]
**EDIT**

Documentation does not match new namespace ~~or batch_run default `number_processors` to 1~~ or new datacollector

TODO:
- update documentation to reflect namespace.
- update documentation to reflect new datacollector initialization

**Comment by rht** [comment]
The `batch_run` is already described to default to 1 in the tutorial.

**Comment by tpike3** [comment]
> The `batch_run` is already described to default to 1 in the tutorial.

Yep... just realized that as I was looking to link the snippet. So all that needs to be done is the namespace.
