### ISSUE TITLE
refactor: Remove dependency on jQuery

### ISSUE THREAD

**Issue by rht** [projectmesa/mesa#1318]
We should replace the `$(...)` with vanilla JS.

**Comment by rht** [comment]
See #1319.

**Comment by rht** [comment]
See https://www.infoq.com/news/2020/08/bootsrap-5-drops-jquery/.

> Whats the motivation behind this?

jQuery is an old tech.

**Comment by Corvince** [comment]
Oh, didn't see #1325, great work! 

Old tech doesn't mean bad, but I think we definitely don't have good use cases for keeping it in and removing it should be straight forward
