### ISSUE TITLE
random.sample with a set is removed in Python 3.11

### ISSUE THREAD

**Issue by EwoutH** [projectmesa/mesa#1329]
Using [`random.sample`](https://docs.python.org/3/library/random.html#random.sample) with a set has been depreciated in Python 3.9 and was removed in Python 3.11.

> Changed in version 3.11: The population must be a sequence. Automatic conversion of sets to lists is no longer supported.

Two cases of this function being used with a set have been detected by the CI in Mesa, both in example models:

1. https://github.com/projectmesa/mesa/blob/5135be8759d9fdac551c5c6ed13e9ae5205bce3e/examples/boltzmann_wealth_model_network/boltzmann_wealth_model_network/model.py#L28
2. https://github.com/projectmesa/mesa/blob/5135be8759d9fdac551c5c6ed13e9ae5205bce3e/examples/virus_on_network/virus_on_network/model.py#L84

What would be the most efficient way to get `self.G.nodes()` in a sequence form (so probably list or tuple)? I feel like just putting it inside a `list()` isn't the proper way to do it.

**Comment by rht** [comment]
Using `list(self.G.nodes)` is recommended by https://networkx.org/documentation/stable/reference/classes/generated/networkx.Graph.nodes.html.

> If your node data is not needed, it is simpler and equivalent to use the expression for n in G, or list(G).

In both cases, the node data is not needed.
