### ISSUE TITLE
Create github.io page

### ISSUE THREAD

**Issue by jackiekazil** [projectmesa/mesa#135]
Create github.io page?

**Comment by jiffyclub** [comment]
If you're using readthedocs it's not really necessary to use GitHub pages, but I find myself mostly using GitHub pages because readthedocs can't automatically build the docs for my packages because of the complicated dependencies (like SciPy).

**Comment by TaylorMutch** [comment]
@jackiekazil Closing this as we now use readthedocs for documentation.
