### ISSUE TITLE
Docs: Remove .rst from docs for simpler build

### ISSUE THREAD

**Issue by tpike3** [projectmesa/mesa#1363]
Use of `.ipynb` transitioned to `.rst` for the Sphinx build can result in desync from readthedocs build and`.ipynb` files and large diff files.

We need to update to using just `.ipynb` with [Sphinx](https://docs.readthedocs.io/en/stable/guides/jupyter.html). 

Discussed in #1361

**Comment by Corvince** [comment]
To continue the discussion here: 

nbsphinx can can evaluate, i.e. run, notebooks once during doc generation, but does not allow interactive notebooks (this would require some backend). This still means we can provide source control friendly unevaluated .ipynb files and they will show just fine.

Re client side ABM modeling:
I think [agentscript](https://agentscript.org/) is the most popular JS ABM library, at least it was some years ago.

**Comment by rht** [comment]
#1694 is an attempt to fix this.

Regarding with having an executable tutorial, I think it would work just fine if we provide a Binder/Colab link to the .ipynb files, described in the tutorial themselves.

**Comment by tpike3** [comment]
.rst files have been removed
