### ISSUE TITLE
agent activation frequency/treatment of time axis

### ISSUE THREAD

**Issue by krober10nd** [projectmesa/mesa#1371]
Is it possible to incorporate the idea of a time axis into the scheduler? For example, the simulation will run for 1 year at hourly increments? This would be helpful for modeling applications in my case. For my particular application, it would helpful (i.e., more representative of reality) to activate agents at a specified frequency irregularly throughout the year. For example, modeling seasonal fishing activity and the transits of vessels from a set of ports. 

I'm wondering how best to tackle to this problem within the existing framework or are new abstractions are required? Any ideas/help would be greatly appreciated. Thanks.

**Comment by rht** [comment]
I think MASON has such scheduler in its library. But for now, you can add a clock to your model, then in the `step()` of your agent, you can check `self.model.clock` mod the period to decide whether it should return early, or proceed to do the actual step.

**Comment by krober10nd** [comment]
I see thank you!
