### ISSUE TITLE
Web/Jupyter UI: Allow users to replay cached simulation result

### ISSUE THREAD

**Issue by rht** [projectmesa/mesa#1393]
**What's the problem this feature will solve?**
For heavy simulations that may take hours+, exploring the outcome for given parameters set via the GUI would be extremely slow.

**Describe the solution you'd like**
We should be able to save the simulation result for a range of parameters, in a cache file, so that it can be replayed quickly for smooth exploration/demo in the GUI.

**Comment by Logende** [comment]
I'm intending to work on this topic in the close future.

**Comment by Logende** [comment]
See my current implementation regarding this issue here: https://github.com/Logende/mesa/blob/main/mesa/modelcachable.py
The tests (which also demonstrate the functionality and how it can be used) can be found here: https://github.com/Logende/mesa/blob/main/tests/test_modelcachable.py

**Comment by rht** [comment]
https://github.com/projectmesa/mesa-examples/pull/14 is an example of Mesa-Replay. Follow up discussions/feature requests should be opened in https://github.com/Logende/mesa-replay.
