### ISSUE TITLE
Bug: pip install doesn't register visualization components

### ISSUE THREAD

**Issue by jackiekazil** [projectmesa/mesa#141]
When the `pip install mesa`, then try to write code involving visualization you will get the following error:
`ImportError: No module named 'mesa.visualization'`. 

I haven't been able to find a solution, but I am wondering if [this](http://python-notes.curiousefficiency.org/en/latest/python_concepts/import_traps.html) has something to do with it: 

### How to recreate
```
pip install mesa
```
### How to test solutions
* Fork the repo 
* Then make updates in master branch to fix the issue. 
* Install your master branch version: `pip install git+https://github.com/jackiekazil/mesa`
* Run the [sample ipynb](https://github.com/projectmesa/Presentations/blob/master/scipy_2015/Schelling%20Model.ipynb) locally from [scipy2015 presentation](https://github.com/projectmesa/Presentations/tree/master/scipy_2015).
* Did the first block work? Yes? Great! No? Go back to debugging. 
* Remember to uninstall and reinstall the repo when you changed something. 

When done, submit a PR.

**Comment by jackiekazil** [comment]
This is done and in version 0.6.5. : https://pypi.python.org/pypi/Mesa/0.6.5

**Comment by SandeepaDilshanAlagiyawanna** [comment]
@jackiekazil How to solve "ModuleNotFoundError: No module named 'mesa.visualization.modules'" in mesa 3.0.3?

**Comment by jackiekazil** [comment]
@SandeepaDilshanAlagiyawanna Hello! Welcome to the project! Can you file as a new issues with extra details on what you were doing at the time? 
https://github.com/projectmesa/mesa/issues/new/choose

**Comment by SandeepaDilshanAlagiyawanna** [comment]
@jackiekazil sure, I will report a new issue, But that is the same issue as this in mesa 3.0.3

**Comment by EwoutH** [comment]
@SandeepaDilshanAlagiyawanna have you checked the [migration guide](https://mesa.readthedocs.io/latest/migration_guide.html#visualisation) and some of the [examples](https://mesa.readthedocs.io/latest/examples.html)?

**Comment by SandeepaDilshanAlagiyawanna** [comment]
@EwoutH Yeah, I have used same as new version way, but it still says it's not found

**Comment by ngyaoting** [comment]
@SandeepaDilshanAlagiyawanna I'm currently encountering the same problem. May I ask how you resolved it?

**Comment by SandeepaDilshanAlagiyawanna** [comment]
@ngyaoting I could not able to resolve the problem. So, I had to change the version to lower and it worked.

**Comment by 2guud4u** [comment]
> @ngyaoting I could not able to resolve the problem. So, I had to change the version to lower and it worked.

What version worked for you? Thanks!

**Comment by jackiekazil** [comment]
@2guud4u because this maybe related -- let me know if this is your issue. https://github.com/projectmesa/mesa/issues/2615

**Comment by DaisyH423** [comment]
Same issue encountered. With either version 3.0.3 or 3.1.3, it shows the following error. However, it runs properly with version 2.1.4

`from mesa.visualization.ModularVisualization import ModularServer`

> Traceback (most recent call last):
  File "XXX", line 1, in <module>
    from mesa.visualization.ModularVisualization import ModularServer
ModuleNotFoundError: No module named 'mesa.visualization.ModularVisualization'

**Comment by quaquel** [comment]
You are trying to use a form of model visualization that has been fully removed in mesa 3.
