### ISSUE TITLE
Enable Read the Docs generation on Pull Requests

### ISSUE THREAD

**Issue by EwoutH** [projectmesa/mesa#1420]
Read the Docs allows you to generate docs for PRs, so that you immediately can check if your code and docs changes processed right. This makes validating and reviewing PRs that include docs changes easier.

See https://docs.readthedocs.io/en/stable/config-file/v2.html

**Comment by EwoutH** [comment]
See this link for more details: [Preview Documentation from Pull Requests](https://docs.readthedocs.io/en/stable/pull-requests.html)

**Comment by rht** [comment]
@jackiekazil ^

**Comment by EwoutH** [comment]
@jackiekazil Could you take a look at this? Enabling Read the Docs on PRs will help review PRs, like #1481.

**Comment by jackiekazil** [comment]
Yes! I will take a look tomorrow.
Thank you for the ping. sometimes I miss messages.

**Comment by EwoutH** [comment]
@jackiekazil Friendly reminder :)

It should be a few clicks in 2 minutes, following these steps:

1. Go to your project dashboard
2. Go to `Admin`, then `Advanced settings`
3. Enable the `Build pull requests for this project option`
4. Click on Save

It really helps reviewing pull requests with documentation changes!

**Comment by jackiekazil** [comment]
@EwoutH you are the best. Sometimes I get so many emails that these fall thru the cracks. I need a better way to filter my github notifications. 

Now for the sad part -- it was already checked in readthedocs -- so either someone else changed it or it is not working in some way. Thoughts on running a test to trigger it?

**Comment by EwoutH** [comment]
@jackiekazil That's strange. Can you try the steps in the [Troubleshooting](https://docs.readthedocs.io/en/stable/pull-requests.html#troubleshooting) section?

**Comment by jackiekazil** [comment]
I don't know that a build hasn't happened since the box was checked, because I don't know when/who checked the box. 
Is there a PR to test it with?

**Comment by EwoutH** [comment]
It should have ran on PRs like #1517 and #1510.

The easiest way would be to open a draft PR (with a minor whitespace change or something) and push it every time you change a setting.

Otherwise maybe we can debug it during a screen sharing session. Does @tpike3 have Read the Docs admin rights? In that case we can maybe fix it in our meeting in a minute.

**Comment by EwoutH** [comment]
@jackiekazil Maybe we can do a quick screensharing session to figure it out together?

**Comment by jackiekazil** [comment]
@EwoutH I was just looking at webhook... 
The last trigger was this commit -- https://github.com/projectmesa/mesa/commit/9dbffeb54e 
<img width="277" alt="Screen Shot 2022-11-14 at 5 56 50 PM" src="https://user-images.githubusercontent.com/166734/201785350-a1161cb9-73f2-4a28-a60e-5cf2c7be0381.png">

What are you expecting to see that you don't see? It looks like it is being triggered to me.

**Comment by EwoutH** [comment]
@jackiekazil It looks like that’s all on the main branch, not on pull requests.

In the _checks_ part of a pull request the Read the Docs build should also show up. Here an example from another repo: 

![08CA122B-F01A-4F57-95B2-E67DDE9DD7B2](https://user-images.githubusercontent.com/15776622/201786462-99ebfb10-82cc-4ad0-bfb9-75c6fe53bbfa.jpeg)

**Comment by jackiekazil** [comment]
Looks like I fixed it. I created this #1525 just to test it.
Can you confirm that is how it is intended to work?

**Comment by EwoutH** [comment]
Awesome, it now works as intended!

**Comment by Corvince** [comment]
Really cool this is finally working.

Previously we also had the doc_build branch that always triggered a rebuild of the documentation. But of course this approach is much better so I went and removed the doc_build branch from RTD.

Being at it I also restructered the active and visible branches (that you can select from the slide-out menu). Previously we had `latest, main, doc_build`. (where latest and main were both pointing to the main branch). Now I have activated `stable, latest` and made stable the default document. Stable understands semantiv versioning and always points to the latest release. Latest still points to our main branch.

I hope this is fine with everyone. I am closing this now, but please reopen if someone thinks this should be differently.

**Comment by wang-boyu** [comment]
Would probably need to update the README files etc? Previously they were pointing to the `main` build if I remember correctly.

**Comment by Corvince** [comment]
Good catch! I reactivated main for now

**Comment by EwoutH** [comment]
@wang-boyu @tpike3 could we enable Readthedocs pull request builds for Mesa-geo? That would make reviewing PRs like https://github.com/projectmesa/mesa-geo/pull/217 easier.

- https://docs.readthedocs.io/en/stable/guides/pull-requests.html
