### ISSUE TITLE
Finish turning paper into tutorial 

### ISSUE THREAD

**Issue by jackiekazil** [projectmesa/mesa#143]
We wrote a paper for Scipy -- http://nipy.bic.berkeley.edu:5000/download/23
We are turning it into a tutorial in our docs -- http://mesa.readthedocs.org/en/latest/. 

We started building it out, but if someone wants to run with this -- that would be awesome! This would be a great way to learn about the library AND contribute at the same time!

Please reach out to myself or @dmasad if you have questions

**Comment by dmasad** [comment]
@chendaniely is handling this.

**Comment by jackiekazil** [comment]
:+1:

**Comment by chendaniely** [comment]
How did you get figure 4 to look the way it does? I can only get the figure below:

![download](https://cloud.githubusercontent.com/assets/5782147/8759638/ad701b7e-2cc6-11e5-842c-bdaf87bd5130.png)

I'm assuming you styled it up.  Do you have the code for that?

**Comment by dmasad** [comment]
Here's the code for that:

```python
wealth_grid = np.zeros((model.grid.width, model.grid.height))
for cell in model.grid.coord_iter():
    cell_content, x, y = cell
    cell_wealth = sum(a.wealth for a in cell_content)
    wealth_grid[y][x] = cell_wealth
plt.imshow(wealth_grid, interpolation='nearest',
          cmap=plt.get_cmap('Greys'))
plt.colorbar()
```

**Comment by chendaniely** [comment]
@dmasad do you also have the code for the `get_gini` function used in the batch runner?

**Comment by dmasad** [comment]
Yup, it's:

```python
def compute_gini(model):
    agent_wealths = [agent.wealth for agent in model.schedule.agents]
    x = sorted(agent_wealths)
    N = model.num_agents
    B = sum( xi * (N-i) for i,xi in enumerate(x) ) / (N*sum(x))
    return (1 + (1/N) - 2*B)
```

All of the code should be in the [example notebook](https://github.com/projectmesa/scipy_proceedings/blob/2015/papers/jacqueline_kazil/Sample%20Model%20Variants.ipynb) and [model code](https://github.com/projectmesa/scipy_proceedings/blob/2015/papers/jacqueline_kazil/MoneyModel.py) from the SciPy proceedings paper directory.

**Comment by chendaniely** [comment]
Ahh... got it. Thanks!

**Comment by dmasad** [comment]
@chendaniely Have you had a chance to work on this any more? I'm happy to jump in and add to it.

**Comment by jackiekazil** [comment]
Looks like this is done. Please reopen if it is not.
