### ISSUE TITLE
`OSError: Int or String expected` when running boid_flockers example

### ISSUE THREAD

**Issue by wang-boyu** [projectmesa/mesa#1431]
**Describe the bug**

Running the `boid_flockers` example results in `OSError: Int or String expected`.

**Expected behavior**

Examples should be able to run without errors.

**Additional context**

This is likely due to a breaking change introduced through https://github.com/projectmesa/mesa/pull/1403: a new parameter `port` is added before `model_params` in `ModularServer.__init__()`, i.e.,

```diff
    def __init__(
-         self, model_cls, visualization_elements, name="Mesa Model", model_params=None
+         self,
+         model_cls,
+         visualization_elements,
+         name="Mesa Model",
+         port=None,
+         model_params=None,
    ):
```

As a result, in the `boid_flockers` example, `model_params` gets passed into `__init__()` as `port`:

```python
server = mesa.visualization.ModularServer(
    BoidFlockers, [boid_canvas], "Boids", model_params
)
```

Examples such as `bank_reserves` are not affected:

```python
server = mesa.visualization.ModularServer(
    BankReserves,
    [canvas_element, chart_element],
    "Bank Reserves Model",
    model_params=model_params,
)
```

**Comment by rht** [comment]
Is it only boid_flockers? How come this is not caught by the test?

**Comment by rht** [comment]
I think the fix is to put `port=None` last, so that it is not breaking other people's code.

**Comment by wang-boyu** [comment]
> Is it only boid_flockers? How come this is not caught by the test?

Probably because the `model_params` are passed as keyword args?https://github.com/projectmesa/mesa/blob/4ce9021002171797be04b1598a44f8737c529a0a/tests/test_visualization.py#L66-L68
