### ISSUE TITLE
[1.1.0 regression] Image files from examples don't load (on Windows)

### ISSUE THREAD

**Issue by EwoutH** [projectmesa/mesa#1461]
**Describe the bug**
On Windows using Mesa 1.1.0, agent portrayal images don't load when running an example.

**Expected behavior**
Agent images load without errors in the example model.

**To Reproduce**

1. Checkout Mesa 1.1.0 (or the current main branch)
2. Run the `run.py` file of one of the examples (_sugarscape_cg_ or _wolf_sheep_) (on Windows?)

**Additional context**

### 1.0.0

<img width="300" alt="Screenshot_797" src="https://user-images.githubusercontent.com/15776622/196971492-45090e68-bae1-4150-a168-a5a3c1b98465.png"><img width="300" alt="Screenshot_798" src="https://user-images.githubusercontent.com/15776622/196971495-6870ce27-6635-4bc6-a9d6-78213b05cf10.png">

### 1.1.0

<img width="300" alt="Screenshot_799" src="https://user-images.githubusercontent.com/15776622/196971800-b04e2668-1fc2-46ec-bc86-7156662cc54c.png"><img width="400" alt="Screenshot_796" src="https://user-images.githubusercontent.com/15776622/196971554-23d7eb80-e4e9-4aed-b3e3-1f19c4e21db5.png">

**Comment by rht** [comment]
After bisecting the commits, I found this commit to be the cause: https://github.com/projectmesa/mesa/commit/3def79dd18b5f9978c7ccda0930a818082af127f. cc @wang-boyu

**Comment by rht** [comment]
I made a fix in https://github.com/projectmesa/mesa/tree/v1.1.1-hotfix, but this needs to be tested on Mesa-Geo. Once tested, let's release 1.1.1 ASAP (cc @jackiekazil ). I added back the local handler last so that hopefully the catch-all `/local/(.*)` doesn't collide with the element-specific handlers.

**Comment by wang-boyu** [comment]
How about putting these files into a dedicated folder, e.g. `local/assets/`?

This line could be updated from: https://github.com/projectmesa/mesa/blob/5ed28a6334f7a169ae39300ed1d93182d0972481/mesa/visualization/templates/js/GridDraw.js#L362
to
```python
img.src = f"local/assets/{shape}";
````

And similarly your local handler could be

```python
local_handler = (
            r"/local/assets/(.*)",
            tornado.web.StaticFileHandler,
            {"path": ""},
        )
```

**Comment by rht** [comment]
That should do. I renamed "assets" to "custom" instead. Already pushed to that branch.

**Comment by wang-boyu** [comment]
Tested and didn't see any issues with your branch and Mesa-Geo `v0.4.0`.

**Comment by wang-boyu** [comment]
I guess it's working also because there's only the `MapModule` gets loaded in Mesa-Geo, nothing in `/local/custom/` folder. But I don't have any example that needs both of these folders to test this scenario. It probably will work too.

**Comment by rht** [comment]
I have already tested on the wolf-sheep example. I created the v1.1.1 branch from the wrong HEAD. Was from current main, but now on top of the 1.1.0.

**Comment by rht** [comment]
@jackiekazil I have added the v1.1.1 tag. You can release to PyPI at any time.

**Comment by EwoutH** [comment]
Thanks for looking into and fixing this so quickly!

Is releasing to PyPI not automated? We should get that in the CI

**Comment by rht** [comment]
The PyPI automation is blocked by this question: https://github.com/projectmesa/mesa/issues/1252#issuecomment-1126715536.
