### ISSUE TITLE
v1.1.1 Release

### ISSUE THREAD

**Issue by jackiekazil** [projectmesa/mesa#1469]
Last release was -- 1.1.0 (2022-10-10) Safford
Prep v1.1.1 Release

- [ ] Tag with milestone 
- [ ] Update history 
- [ ] release

**Comment by jackiekazil** [comment]
Re: #1461  - I saw the need for a release. 
@rht we haven't done a lot of minor releases. We normally tag things to be associated with the milestone. Does that mean that things are tagged as Safford? 

I am traveling this weekend -- any help with prep, since you are engaged with #1461 will be much appreciated. 

/cc @EwoutH

**Comment by rht** [comment]
Only #1463 needs to be tagged with milestone.

**Comment by rht** [comment]
I don't think it needs an extra milestone though.

**Comment by jackiekazil** [comment]
Great. I will do a quick review and release in a few house when I get to stable situation in my travel.

**Comment by EwoutH** [comment]
I see the release [in PyPI](https://pypi.org/project/Mesa/#files) including a wheel, nice!

That's means everything is done right?

**Comment by jackiekazil** [comment]
yes
