### ISSUE TITLE
Advanced Tutorial Typo/Error

### ISSUE THREAD

**Issue by Ghabri-EL** [projectmesa/mesa#1477]
In the advanced tutorial, when creating the custom histogram class in HistogramModel.js file,  creating chart variable and defining it as constant promps issues with the reset method, as the reset method tries to change the chart variable by creating a new Chart object.

[https://mesa.readthedocs.io/en/latest/tutorials/adv_tutorial.html#id5](url)
![typo png](https://user-images.githubusercontent.com/48124793/198104366-43764979-20ec-4117-bc06-6ba30cd63144.jpg)

**Comment by rht** [comment]
That `reset` code in the advanced tutorial seems outdated. The reset in the actual implementation in library has been changed in this [commit](https://github.com/projectmesa/mesa/commit/41545ca378225981d3e014a94943071ff7a39a23). It's unclear how the change fixed the supposed bug.

And the new code could have been made clearer too. According to https://stackoverflow.com/questions/1232040/how-do-i-empty-an-array-in-javascript
```js
chart.data.labels = [];
```
would have worked. But this needs testing.
