### ISSUE TITLE
Remove deprecated functions from test, pass CI without warnings

### ISSUE THREAD

**Issue by EwoutH** [projectmesa/mesa#1520]
Currently, due to recent new features, multiple tests throw deprecation warnings in the tests. In the latest [CI run](https://github.com/projectmesa/mesa/actions/runs/3424109541/jobs/5703422944) there are warnings about the BatchRunner class, `position_agent`, `num_agents`, `find_empty` and UserSettableParameter.

To track this issue:
- [x] Remove all deprecated functions from tests
  - [x] BatchRunner class
  - [x] `position_agent`
  - [x] `num_agents`
  - [x] `find_empty`
  - [x] UserSettableParameter.
- [x] Make sure pytest passes without warnings
- [x] (optionally) run pytest with `-Werror` in CI

<details><summary>Warnings summary</summary>

> =============================== warnings summary ===============================
> tests/test_batchrunner.py::TestBatchRunner::test_agent_level_vars
> tests/test_batchrunner.py::TestBatchRunner::test_model_level_vars
> tests/test_batchrunner.py::TestBatchRunner::test_model_with_fixed_parameters_as_kwargs
> tests/test_batchrunner.py::TestBatchRunner::test_model_with_variable_and_fixed_kwargs
>   /home/runner/work/mesa/mesa/tests/test_batchrunner.py:114: DeprecationWarning: BatchRunner class has been replaced by batch_run function. Please see documentation.
>     batch = BatchRunner(
> 
> tests/test_batchrunner.py::TestBatchRunner::test_model_with_only_fixed_parameters
>   /home/runner/work/mesa/mesa/tests/test_batchrunner.py:128: DeprecationWarning: BatchRunner class has been replaced by batch_run function. Please see documentation.
>     batch = BatchRunner(
> 
> tests/test_grid.py: 13 warnings
> tests/test_space.py: 2497 warnings
>   /home/runner/work/mesa/mesa/mesa/space.py:534: DeprecationWarning: `position_agent` is being deprecated; use instead `place_agent` to place an agent at a specified location or `move_to_empty` to place an agent at a random empty cell.
>     warn(
> 
> tests/test_grid.py: 10 warnings
>   /home/runner/work/mesa/mesa/mesa/space.py:[46](https://github.com/projectmesa/mesa/actions/runs/3460530422/jobs/5777163516#step:6:47)8: DeprecationWarning: `num_agents` is being deprecated since it's no longer used inside `move_to_empty`. It shouldn't be passed as a parameter.
>     warn(
> 
> tests/test_space.py::TestSingleGrid::test_empty_cells
>   /home/runner/work/mesa/mesa/mesa/space.py:[50](https://github.com/projectmesa/mesa/actions/runs/3460530422/jobs/5777163516#step:6:51)1: DeprecationWarning: `find_empty` is being phased out since it uses the global `random` instead of the model-level random-number generator. Consider replacing it with having a model or agent object explicitly pick one of the grid's list of empty cells.
>     warn(
> 
> tests/test_usersettableparam.py::TestOption::test_checkbox
> tests/test_usersettableparam.py::TestOption::test_choice
> tests/test_usersettableparam.py::TestOption::test_number
> tests/test_usersettableparam.py::TestOption::test_slider
> tests/test_usersettableparam.py::TestOption::test_static_text
> tests/test_visualization.py::TestModularServer::test_canvas_render_model_state
> tests/test_visualization.py::TestModularServer::test_text_render_model_state
> tests/test_visualization.py::TestModularServer::test_user_params
>   /home/runner/work/mesa/mesa/mesa/visualization/UserParam.py:71: UserWarning: UserSettableParameter is deprecated in favor of UserParam objects such as Slider, Checkbox, Choice, StaticText, NumberInput. See the examples folder for how to use them. UserSettableParameter will be removed in the next major release.
>     warn(
> 
> -- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
> 
> ---------- coverage: platform linux, python 3.10.8-final-0 -----------
> Coverage XML written to file coverage.xml
> 
> ================ 127 passed, 5 skipped, 2[53](https://github.com/projectmesa/mesa/actions/runs/3460530422/jobs/5777163516#step:6:54)4 warnings in 10.14s ================</details>

**Comment by tpike3** [comment]
Fixed with #1688 all Warnings removed
