### ISSUE TITLE
Design and implement testing strategy for examples & cookiecutter 

### ISSUE THREAD

**Issue by jackiekazil** [projectmesa/mesa#1547]
We need to fix tests for the examples. There were two of them in the main repo. Now they have been deactivated until we figure this out. We need to: 

1. discuss/figure out testing strategy for examples and for cookiecutter & implement pinning at the same time (see https://github.com/projectmesa/mesa/discussions/1530)
2. Implement changes so that it is reflected in both repos (this one and the examples repo)

This ticket is to wrap up work from #963

**Comment by quaquel** [comment]
Cookiecutter got removed in #2421.

**Comment by EwoutH** [comment]
And all examples stuff is now tracked in https://github.com/projectmesa/mesa/issues/2364.
