### ISSUE TITLE
Issue congrats and thank you to all our contributors!!

### ISSUE THREAD

**Issue by jackiekazil** [projectmesa/mesa#158]
OMG - This weekend has been amazing! Thank you so much for everyone who scrubbed in and continue to scrub in!! @dmasad and I are so excited about there this project might with the help of folks from the community!!!

Thank you to... 
@jiffyclub -- ty for helping us improve our packing, CI build, clean up the code a little bit, and chiming in on tickets. Your help is invaluable!! 
@chendaniely -- for the install update, digging into the tutorial, and for suggesting the diagram!!
@ConvexHull -- for the README edits. 
@dotsdl -- for chiming in, your questions, and whatever else you might have worked on that I am not aware of since I wasn't there today. :-)

Previous contributors, that I don't know if we explicitly said thank you for... 
@davpaez, @gcallah, @DanielWeitzenfeld

To all of those mentioned above... 
![giphy](https://cloud.githubusercontent.com/assets/166734/8642556/ee5d1500-28f3-11e5-91ea-6c85c899cc76.gif)

For those who want to do on-going work with Mesa. Let's try to coordinate on the mailing list -- https://groups.google.com/forum/#!forum/projectmesa.

**Comment by dmasad** [comment]
:+1:

**Comment by dotsdl** [comment]
Awesome, joined. Very excited about this project!

**Comment by jiffyclub** [comment]
:heart:

**Comment by chendaniely** [comment]
:fireworks:

**Comment by davpaez** [comment]
I just watched your presentation at SciPy2015 on Youtube. It was awesome, congratulations!
