### ISSUE TITLE
Api documentation needs reformatting 

### ISSUE THREAD

**Issue by Tortar** [projectmesa/mesa#1582]
Subissue of #1580 to document a part that need updates:  the api documentation in the docs is not very well formatted, some parts of text are not in the place they should be (e.g. see first lines of https://mesa.readthedocs.io/en/latest/apis/space.html#) and also some parts in methods descriptions can be highlighted in a better way (for example making the arguments bold). Maybe to improve it we can take inspiration to some libraries which do a better job with Sphinx like Networkx (e.g. see how the relevant parts in this  api documentation page appears, https://networkx.org/documentation/latest/reference/classes/graph.html) ?

**Comment by quaquel** [comment]
closed via #2294
