### ISSUE TITLE
Passing information from model to agent

### ISSUE THREAD

**Issue by kkarrancsu** [projectmesa/mesa#1585]
I am new to project Mesa, and am wondering what is the correct method to pass information from the model to individual agents? At each tick, I want the agents to have access to global information that is computed in the model.  I didn't see this covered in the tutorial - any pointers to relevant documentation or best practices would be greatly appreciated!

**Comment by rht** [comment]
You can access a model from an agent by doing `agent.model`. Since you can access the model, you can also access its attributes. See https://github.com/projectmesa/mesa/blob/e3cc4d4877ace362b204aadc06d6a44b03d59d11/mesa/agent.py#L32.

**Comment by tpike3** [comment]
To add on to @rht... you can see where agents get the model attribute in there initialization in the tutorial you can see with the `super().__init__(unique_id, model)` then agents reference self.model.<global model attribute>. See [setting up the model](https://mesa.readthedocs.io/en/stable/tutorials/intro_tutorial.html#setting-up-the-model) 

Then you can see used in the [agent step](https://mesa.readthedocs.io/en/stable/tutorials/intro_tutorial.html#agent-step) where the agent references the models scheduler to find another agent to give unit of wealth.  ` other_agent = self.random.choice(self.model.schedule.agents)`

**Comment by kkarrancsu** [comment]
Thanks very much!
