### ISSUE TITLE
Rebuild docs

### ISSUE THREAD

**Issue by dmasad** [projectmesa/mesa#159]
The current docs are out of date with the current code. I built the documentation in a branch, and I'm trying to see how to see them on ReadTheDocs before merging.

**Comment by jackiekazil** [comment]
Assign #160, w/ 'accept', remove 'working' when it is ready to go. (I don't want to merge while in the middle of working.

**Comment by jiffyclub** [comment]
As I mentioned in https://github.com/projectmesa/mesa/issues/135#issuecomment-120637925, I'm not sure about building scientific projects on ReadTheDocs, though somehow AstroPy seems to get it done. I've always resorted to building the docs locally and manually pushing to [GitHub Pages](https://pages.github.com/).

**Comment by dmasad** [comment]
It seems to build and display okay on RTD. Somehow @jackiekazil managed to get it to build/display a branch as well, but I'm not managing to find how to display a new branch on it now.

**Comment by jackiekazil** [comment]
You need to activate the branch here:
https://readthedocs.org/dashboard/mesa/versions/
Then hit build on the branch here: https://readthedocs.org/builds/mesa/

**Comment by dmasad** [comment]
@jackiekazil Not seeing the new branch there, though...

**Comment by dmasad** [comment]
This looks good: http://mesa.readthedocs.org/en/update_docs_0713/
It is failing to build the PDF, not clear to me why.
 (well, it looks updated -- see #162 for looking good).

**Comment by dmasad** [comment]
Seems to be fixed now.

**Comment by jackiekazil** [comment]
@dmasad is this done w/ the merge of #160? (meaning this can be closed?)

**Comment by dmasad** [comment]
Yup!
