### ISSUE TITLE
v1.2.0 Taylor Release

### ISSUE THREAD

**Issue by jackiekazil** [projectmesa/mesa#1599]
Last release was [v1.1.1  (2022-10-10) Safford](https://github.com/projectmesa/mesa/milestone/31?closed=1) 
^^ This was the last release.

Prep v1.1.2 Release

- [x] #1600
- [x] Tag with milestone - @rht, @tpike3 has everything been tagged since the last release with this milestone https://github.com/projectmesa/mesa/milestone/32
- [x] Update history
- [x] release

**Comment by rht** [comment]
There are lots of recent PRs that are not tagged (https://github.com/projectmesa/mesa/pulls?page=1&q=is%3Apr+no%3Amilestone+is%3Aclosed). Though I forgot the reason why all of them have to be tagged to a milestone for a release. I thought issues in milestone are reserved for only the ones that are necessary and are blocking the release itself.

**Comment by jackiekazil** [comment]
@rht I had always done it as a tracking mechanism to try to correlate with history -- it is mostly focused on PRs so they are easy to find.

**Comment by rht** [comment]
We could collect them all by the timestamps (all recent merged PR's after the release PR) and put them in the HISTORY.rst. I don't see having to find the release tag of a PR to be a common use case. But I'm fine with having to tag the recent merged PRs as usual too.

**Comment by jackiekazil** [comment]
@rht I think what you are suggesting is an automated process. We talked about that... let's revisit setting that up. I am going to do a manual tag for now before we switch to something new.

**Comment by jackiekazil** [comment]
@rht, @tpike3 can either of you do a review of everything I tagged?
I wanted to pull in the errors too since they can impact things even though they were undone.
If there is something that shouldn't be tagged, please untag.
https://github.com/projectmesa/mesa/milestone/32?closed=1.

**Comment by jackiekazil** [comment]
@rht - do you have any preference of history format?

**Comment by rht** [comment]
There are old PRs/issues that have been accidentally tagged in https://github.com/projectmesa/mesa/milestone/32?closed=1. I have untagged them.

One feature with associating PRs with a milestone of a release is that you can track which release a PR is a part of, from its milestone. But this info is not used that often. Other projects use them for blocking issues:
- https://github.com/psf/black/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22Release+23.1.0%22
- https://github.com/pandas-dev/pandas/issues?q=is%3Aopen+is%3Aissue+milestone%3A1.5.4
- https://github.com/numpy/numpy/issues?q=is%3Aopen+is%3Aissue+milestone%3A%221.25.0+release%22

I have no preference for the history format (at the moment).

**Comment by jackiekazil** [comment]
Currently on a plane, but unable to push PRs. Here is a draft on history -- Feel free to this directly & comment generally on the changes.  Also, what do we want to highlight in the Special notes? 

-------------

1.2.0 (2023-03-09) Taylor
++++++++++++++++++++++++++

**Special notes**

TODO:.... 

**Improvements**

* ci: Add testing on Python 3.11 #1519
* Remove auto-update GH Actions for Pipfile.lock #1558 
* examples: Initialize Sugarscape ({G1}, {M, T}) #1290
* ruff
    * ruff: Add isort #1594
    * ci: Replace flake8 with Ruff #1587
    * ruff: Add more rules based on Zulip's config #1596
* perf: faster is_integer function for common cases #1597
* Use getattr for attribute strings in model data collection #1590
* Remove _reporter_decorator #1591
* Change index at DataFrame creation in get_agent_vars_dataframe #1586
* Refactor iter/get_cell_list_contents methods #1570
* Make Grid class private #1575
* Make the internal grid and empties_built in Grid class private #1568
* Implement radius for NetworkGrid.get_neighbors #1564
* Evaluate empties set more lazily #1546
* Simplify code in ContinuousSpace #1536
* Improve docstrings of ContinuousSpace #1535
* Simplify accept_tuple_argument decorator in space.py #1531
* Enhance schedulers to support intra-step removal of agents #1523
* perf: Refactor iter_cell_list_contents Performance #1527
* Replace two loops with dictionary comprehension, list- with generator comprehension #1458
* Make MultiGrid.place_agent faster #1508
* Update space module-level docstring summary #1518
* Update NetworkGrid.__init__ docstring #1514
* Deprecate SingleGrid.position_agent #1512
* Make swap_pos part of Grid instead of SingleGrid #1507
* Refactor NetworkGrid docstrings and iter/get_cell_list_contents #1498
* Hexgrid: use get_neighborhood in iter_neighbors #1504
* Auto update year for copyright in docs #1503
* Refactor Grid.move_to_empty #1482
* Put "Mesa" instead of "it" in README #1490
* Batchrunner: Remove unnecessary dict transformation, .keys() in len() #1460
* Add Dependabot configuration for GitHub Actions update check #1480
* Use list transformation only when shuffled is True #1478
* Implement swap_pos #1474
* Clean up DataCollector #1475


**Fixes**

* Fix accident from https://github.com/projectmesa/mesa/pull/1488 #1489
* pre-commit autoupdate #1598, #1576, #1548, #1494
* Fix docstring of DataCollector #1592
* Update Pipfile.lock (dependencies) #1495 #1487
* build(deps): 
    * build(deps): bump codecov/codecov-action from 2 to 3  dependencies Pull requests that update a dependency file #1486
    * build(deps): bump actions/upload-artifact from 2 to 3  dependencies Pull requests that update a dependency file #1485
    * build(deps): bump peter-evans/create-pull-request from 3 to 4  dependencies Pull requests that update a dependency file #1484
    * build(deps): bump actions/setup-python from 3 to 4  dependencies Pull requests that update a dependency file #1483
* Establish reproducibility for NetworkGrid.get_neighbors when radius > 1 #1569
* Format js code #1554
* Add some missing const declarations #1549
* fix tutorial url in examples #1538
* Update cookiecutter to flat import style. #1525
* Fix bug in Grid.get_neighborhood #1517
* Revert changes of #1478 and #1456 #1516
* Fix return types of some NetworkGrid methods #1505 
* Update year for copyright #1501
* Add default_value function to NetworkGrid #1497
* Remove extraneous spaces from docstrings in modules 2 #1496
* Remove extraneous spaces from docstrings in modules #1493
* SingleGrid: Remove extraneous attribute declaration (empties) #1491

**Comment by jackiekazil** [comment]
@tpike3 ^^ Can you make sure any updates you pushed over the weekend are included?

**Comment by rht** [comment]
> examples: Initialize Sugarscape ({G1}, {M, T}) https://github.com/projectmesa/mesa/pull/1290

This one was merged in the examples repo.

**Comment by rht** [comment]
New features:
- https://github.com/projectmesa/mesa/pull/1564

Some highlights for the perf improvements:
- https://github.com/projectmesa/mesa/pull/1590 this is a 2x speedup over the relevant line, but not sure if compared to the rest of the function
- https://github.com/projectmesa/mesa/pull/1570 at least 1.3x speedup for iter/get_cell_list_contents
- https://github.com/projectmesa/mesa/pull/1546#issuecomment-1344548112 ~1.3x speedup for place_agent, remove_agent, and move_agent

Those are harder to find from the PR list because the PR titles don't explicitly have "perf:" prefix.
Overall, seems to be mainly perf, refactors, and bug fixes.

**Comment by tpike3** [comment]
@rht Thanks! @jackiekazil I have nothing else to add. That is an impressive list.

**Comment by jackiekazil** [comment]
@rht I believe I made your changes. Can you review the PR?

RE: perf:, etc -- do we want to try to enforce this to for automate history writes in the future?  

@tpike3 It was a lot more than I was expecting.

**Comment by rht** [comment]
Yes, I will make sure that perf commits will have perf: prefix in the future.

**Comment by jackiekazil** [comment]
https://pypi.org/project/Mesa/
^^ 1.2 is published. Closing this ticket. Please reopen if you notice any issues.
