### ISSUE TITLE
Urgent: Update project size

### ISSUE THREAD

**Issue by henrykironde** [projectmesa/mesa#1601]
Please add the missing required, 175 or 350 hr designation. 

Example is https://github.com/colour-science/GSoC/blob/master/2023/GSoC-2023-Project-Ideas.md#implement-support-for-cxf---color-exchange-format
@rht, @jackiekazil, @boyu

https://github.com/projectmesa/mesa/wiki/Projects-for-Google-Summer-of-Code-2023

**Comment by rht** [comment]
I added 175 hours to the Cython one, since @Tortar preferred that time allocation. The Jupyter one could be 175 or 350 depending on how polished the outcome should be.

**Comment by henrykironde** [comment]
Pick one of 175, 350

**Comment by rht** [comment]
I know, I just haven't decided, and I am deferring it to @jackiekazil.

**Comment by jackiekazil** [comment]
I added 350. I want it to be 175, but I believe there is some complexity with both understanding user needs as well as implementation. 
Closing this ticket for now. Please let us know if you need anything else.
