### ISSUE TITLE
Reformat docstrings in reStructuredText

### ISSUE THREAD

**Issue by dmasad** [projectmesa/mesa#162]
The docstrings are currently all written more or less according to the Google Style Guide. However, Sphinx doesn't render that very nicely. We need to reformat them the way Sphinx expects. Alternatively, we need to look into [Napoleon](http://sphinxcontrib-napoleon.readthedocs.org/en/latest/index.html) or something similar to get Sphinx to build the current docstrings properly.

**Comment by chendaniely** [comment]
For reference: https://pythonhosted.org/an_example_pypi_project/sphinx.html

``` python
def public_fn_with_googley_docstring(name, state=None):
    """This function does something.

    Args:
       name (str):  The name to use.

    Kwargs:
       state (bool): Current state to be in.

    Returns:
       int.  The return code::

          0 -- Success!
          1 -- No good.
          2 -- Try again.

    Raises:
       AttributeError, KeyError

    A really great idea.  A way you might use me is

    >>> print public_fn_with_googley_docstring(name='foo', state=None)
    0

    BTW, this always returns 0.  **NEVER** use with :class:`MyPublicClass`.

    """
    return 0

def public_fn_with_sphinxy_docstring(name, state=None):
    """This function does something.

    :param name: The name to use.
    :type name: str.
    :param state: Current state to be in.
    :type state: bool.
    :returns:  int -- the return code.
    :raises: AttributeError, KeyError

    """
    return 0

```

**Comment by dmasad** [comment]
So looks like the Napoleon extension works. Testing now how it looks on RTD.

**Comment by dmasad** [comment]
Okay, Sphinx + napoleon +  RTD looks good! 
Compare the [new version](http://mesa.readthedocs.org/en/doc_reformat.162/mesa.html#module-mesa.space) with the [old version](http://mesa.readthedocs.org/en/latest/mesa.html#module-mesa.space). Some editing needs to be done, but overall I think it's much better.

Many other Python projects seem to use Sphinx formatting -- not sure if that's just a legacy thing, or if there are good reasons to prefer it to Google Style. Thoughts?

**Comment by dmasad** [comment]
Sounds like consensus is that we should stick with RST.

**Comment by jackiekazil** [comment]
It looks like there is nothing more to do on this. @dmasad if there is more on this, can you open a new ticket with the explicit task? This one is confusing.
