### ISSUE TITLE
A small issue in the Introductory Tutorial

### ISSUE THREAD

**Issue by haik** [projectmesa/mesa#1623]
In the example of Collecting Data:
`self.datacollector = mesa.DataCollector(
            model_reporters={"Gini": compute_gini}, agent_reporters={"Wealth": "wealth"}
        )`
Here, `mesa.DataCollector()` should be `mesa.datacollection.DataCollector()`.

In the example of Batch Run:
`results = mesa.batch_run(
    MoneyModel,
    parameters=params,
    iterations=5,
    max_steps=100,
    number_processes=1,
    data_collection_period=1,
    display_progress=True,
)`
Here, `mesa.batch_run()` should be `mesa.batchrunner.batch_run()`.

**Comment by tpike3** [comment]
@haik for this we added a new namespace (Mesa 1.0) so that why the simpler versions work (e.g. `mesa.DataCollector`); the longer versions (e.g. `mesa.datacollection.DataCollector()`) continues to work. 

Did you have an issue? If so, what version of Mesa are you using?

**Comment by haik** [comment]
@tpike3 That's the point. I was just using Mesa 0.9. Thanks for your answer.
