### ISSUE TITLE
broken schelling link in docs

### ISSUE THREAD

**Issue by abe-winter** [projectmesa/mesa#1624]
**Describe the bug**
in the best practices page here: https://github.com/projectmesa/mesa/blob/9a07a48526f11b78e462a9bab390366c95443814/docs/best-practices.rst

The schelling link is to https://github.com/projectmesa/mesa/tree/main/examples/schelling

It should probably be to either:
- the standalone schelling repo https://github.com/projectmesa/mesa-schelling-example
- the schelling folder inside the examples repo https://github.com/projectmesa/mesa-examples/tree/main/examples/Schelling

**Expected behavior**
link not broken

**To Reproduce**
click broken link

**Additional context**

**Comment by tpike3** [comment]
@abe-winter Good catch thanks! It should be the second the link.  We need to  probably get rid of some of the extra repos (i.e. schelling exmaples, presentations)

**Comment by tpike3** [comment]
Fixed with #1720
