### ISSUE TITLE
namespace clash between time.py and time in logging.py? 

### ISSUE THREAD

**Issue by DOSull** [projectmesa/mesa#164]
This is probably my incompetence at dealing with several python installs on one machine, and in particular with adding a 3.4 install just so I could see what mesa is like, but anyway...

When I try to run an example model (inside an IDE, so there is also  that...) I get this error

    File "/Users/dosullivan/anaconda/lib/python3.4/logging/__init__.py", line 57, in <module> _startTime = time.time()
    AttributeError: 'module' object has no attribute 'time'

which I can prevent from happening if I rename the time.py file to (say) mesatime.py
Is this a namespace clash that should be fixed?

Meanwhile, even with that tweak, I don't see the model running, but that's on me to figure out... maybe I'll look at the notebook versions.

**Comment by dmasad** [comment]
I haven't seen that before. Which model are you trying to run?

**Comment by DOSull** [comment]
It could easily be some issue with my setup - and at the moment it is hard for me to comment because I'm trying to get set up to run 3.4 and 2.7 on the same machine, and it's involved taking some steps back before I try to take some forward... which means I haven't got mesa installed just now.
It was Schelling, Flockers and the PD models - of them with the same symptom.
So... let me get back to you on this!

**Comment by DOSull** [comment]
David,
I've posted a response on github.  Basically, will need to get my 
(multiple) python installs worked out before I can be completely 
confident about what is going on.

This could take some time...

David

**Comment by DOSull** [comment]
OK... clearly it was something to do with my setup, as this problem is now gone (after several hours wrangling python installations!)
I've made the Forest Fire notebook example work and I can run other models from inside my IDE. I'm a little confused that model visualizations seem to require additional steps (as a long time NetLogo user, you come to expect visualization 'for free'), but I guess it's still early days.
Will watch this project with interest.

**Comment by dmasad** [comment]
Glad to hear that it works! If the problem is solved and doesn't seem to be a problem with Mesa itself, I'll close this ticket for now.

Yes, we're purposefully going a different route from NetLogo and separating out the visualization from the model itself. The goal is to have more flexibility on both, without the assumptions that having them always linked impose. But we do want to streamline the visualization creation.
