### ISSUE TITLE
Teach someone else to upload to PyPI

### ISSUE THREAD

**Issue by jackiekazil** [projectmesa/mesa#165]
Teach someone else to upload to PyPI -- @dmasad

**Comment by brianrusso** [comment]
Here is  the info on how to use Travis to autopush to pypi

https://docs.travis-ci.com/user/deployment/pypi/

**Comment by jackiekazil** [comment]
Ty for the link!

**Comment by EwoutH** [comment]
If you'd like, I could build a GitHub Actions workflow that automatically pushed to PyPi when tagging a release. It's quite simple nowadays!

- [Publishing package distribution releases using GitHub Actions CI/CD workflows](https://packaging.python.org/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/)
- [Automating PyPI releases with Github Actions](https://www.caktusgroup.com/blog/2021/02/11/automating-pypi-releases/)
