### ISSUE TITLE
Branch clean up

### ISSUE THREAD

**Issue by jackiekazil** [projectmesa/mesa#1653]
We have a lot of branches.  We should do a clean up.  When something is cleaned OR decided to not be (eg main) please mark off the list below.

- [x]  origin/452_reqs
- [ ]   origin/Corvince-fix-issue-855
- [ ]   origin/Corvince-patch-ga
- [x]   origin/Corvince-patch-travis
- [ ]   origin/ExampleUpdates
- [ ]   origin/Fix-#644
- [ ]   origin/FixDocs
- [x]   origin/HEAD -> origin/main (save - jackie)
- [x]   origin/PR528
- [ ]   origin/TravisUpdates
- [ ]   origin/allow-multiple-connections
- [ ]   origin/bank_reserves_about
- [ ]   origin/base_ci_cache_experiment
- [x]   origin/blackagain
- [ ]   origin/codecov_setup
- [x]   origin/continuous_space_viz
- [ ]   origin/date_update
- [x]   origin/doc_builds (save - jackie)
- [ ]   origin/esbuild
- [ ]   origin/f8-cleanup
- [ ]   origin/fix-asyncio-win-python-36
- [x]   origin/fix-readme
- [ ]   origin/fix-readme-install-command
- [ ]   origin/fix_cookiecutter
- [ ]   origin/fix_tutorial
- [x]   origin/flockers-hell
- [x]   origin/ghost_flockers
- [ ]   origin/happy-new-year
- [ ]   origin/improved_getitem
- [x]   origin/jk/examples (deleted - jackie)
- [ ]   origin/jk/history-fmt
- [x]   origin/jk/pd_readme_fix (deleted - jackie)
- [x]   origin/jk/test_random_walk (deleted - jackie)
- [ ]   origin/jk/v1.2.0
- [x]   origin/jupyter_fix
- [x]   origin/main (save - jackie)
- [x]   origin/mesa_packages_pages
- [x]   origin/mpp_jk
- [ ]   origin/new.seed
- [ ]   origin/nogales
- [ ]   origin/oct_2021_doc_update
- [ ]   origin/pr/792
- [ ]   origin/release
- [x]   origin/release_fix
- [x] origin/schedule.agent.dict
- [ ]   origin/test_examples-patch
- [x]   origin/update-pipfile
- [x]   origin/update-travis
- [x]   origin/update_reqs
- [x]   origin/v0.8.4 (deleted - jackie)
 - [x]  origin/v0.9.0 (deleted - jackie)
- [x]   origin/v1.1.1-hotfix (deleted - jackie)

**Comment by jackiekazil** [comment]
@rht @tpike3 - if any of these are branches you are aware of that can be deleted, please delete check them off the list. If it is something active -- please check off the list & add ur name behind it, so we know it doesn't need to be looked into.

**Comment by rht** [comment]
I have always created branches under my own fork (which is very messy anyway). Based on the names, I think these can be removed:
-  origin/update-pipfile
- origin/update-travis
- origin/update_reqs
- origin/blackagain
- origin/Corvince-patch-travis

Though I think I created this one: origin/base_ci_cache_experiment.

**Comment by jackiekazil** [comment]
Thank you @rht 

Did some digging... here is a list of branches with the last commit date, the author of the commit and the branch name.

```
git for-each-ref --format='%(color:cyan)%(authordate:format:%m/%d/%Y %I:%M %p)    %(align:25,left)%(color:yellow)%(authorname)%(end) %(color:reset)%(refname:strip=3)' --sort=authordate refs/remotes
```

Output:
```
04/30/2017 07:39 PM    David Masad            continuous_space_viz
01/14/2018 01:23 AM    jackiekazil            release_fix
03/15/2018 11:23 PM    jackiekazil            jupyter_fix
04/01/2018 07:43 PM    jackiekazil            update_reqs
04/05/2018 07:07 PM    jackiekazil            mpp_jk
04/06/2018 10:12 AM    Jackie Kazil           mesa_packages_pages
04/18/2018 12:34 AM    jackiekazil            ghost_flockers
05/09/2018 10:07 PM    David Masad            schedule.agent.dict
05/14/2018 01:25 PM    jackiekazil            flockers-hell
05/15/2018 01:47 PM    jackiekazil            PR528
06/05/2018 11:24 PM    jackiekazil            452_reqs
08/24/2018 11:19 AM    Jackie Kazil           fix-readme
08/24/2018 11:22 AM    Jackie Kazil           fix-readme-install-command
09/30/2018 10:30 AM    David Masad            new.seed
10/08/2018 05:09 PM    jackiekazil            bank_reserves_about
11/05/2018 10:59 PM    jackiekazil            f8-cleanup
01/01/2019 03:00 AM    Jackie Kazil           happy-new-year
02/19/2019 09:27 AM    Corvince               Fix-#644
05/12/2019 11:08 PM    jackiekazil            fix_tutorial
08/08/2019 09:54 PM    jackiekazil            codecov_setup
01/13/2020 11:50 AM    Corvince               update-travis
02/01/2020 12:49 PM    David Masad            ExampleUpdates
02/03/2020 11:58 AM    Corvince               pr/792
04/22/2020 03:22 PM    Corvince               improved_getitem
05/05/2020 07:49 PM    Corvince               release
05/09/2020 10:28 PM    Corvince               test_examples-patch
06/09/2020 11:15 PM    jackiekazil            fix_cookiecutter
06/30/2020 12:02 PM    Corvince               Corvince-patch-travis
09/24/2020 09:06 AM    Corvince               Corvince-fix-issue-855
10/30/2020 10:36 AM    Corvince               FixDocs
11/05/2020 08:46 AM    Corvince               TravisUpdates
11/07/2020 09:46 PM    Corvince               blackagain
11/22/2020 11:39 PM    jackiekazil            nogales
11/27/2020 04:28 PM    jackiekazil            date_update
01/01/2021 10:03 PM    Corvince               Corvince-patch-ga
01/02/2021 01:20 PM    Corvince               fix-asyncio-win-python-36
11/03/2021 04:09 PM    David Masad            oct_2021_doc_update
03/30/2022 10:32 PM    Corvince               allow-multiple-connections
06/07/2022 11:14 AM    rht                    base_ci_cache_experiment
10/09/2022 09:35 PM    Corvince               esbuild
02/01/2023 06:25 AM    jackiekazil            update-pipfile
03/06/2023 09:28 AM    jackiekazil            jk/v1.2.0
03/18/2023 12:29 PM    jackiekazil            jk/history-fmt
04/25/2023 10:40 PM    Jackie Kazil           revert-1669-patch-2
05/11/2023 02:18 AM    rht                    HEAD
05/11/2023 02:18 AM    rht                    main
05/14/2023 03:23 PM    rht                    doc_builds
05/14/2023 10:38 PM    Jackie Kazil           jk/testbranch
```

I was trying to figure out a way to check if a branch has a open PR using jk/testbranch as the one that I know does, but I can't find a good command to do that. 

I guess it is small enough to do manually. I will probably divide by year. 

This week - 2017. 

... Also @Corvince, please let us know if you are aware of a particularly interesting or valuable branch for whatever reason.

**Comment by jackiekazil** [comment]
Test for search: https://github.com/projectmesa/mesa/pulls?q=is%3Apr+is%3Aopen+head%3Ajk%2Ftestbranch+ 
Not open PRs for https://github.com/projectmesa/mesa/pulls?q=is%3Apr+is%3Aopen+head%3Acontinuous_space_viz

I am not worried about this branch, so I am going to use this as demo to show how I might approach the others. 

```
git push origin --delete continuous_space_viz
```
deleted.

**Comment by jackiekazil** [comment]
Branches that were cleaned out today:

release_fix
jupyter_fix
update_reqs
mpp_jk
mesa_packages_pages
schedule.agent.dict
flockers-hell
PR528
452_reqs
fix-readme

All branches were searched for in repo in the following matter:

test for search: https://github.com/projectmesa/mesa/pulls?q=is%3Apr+is%3Aopen+head%3Aghost_flockers
no open PR: https://github.com/projectmesa/mesa/issues?q=is%3Aissue+is%3Aopen+ghost_flockers

**Comment by jackiekazil** [comment]
@Corvince 

I did a run of latest commits to branches. I know there are a few associated with you making the last commit. 
To help with this clean out, can you let me know (or directly delete) which branches are no longer being used?

02/19/2019 09:27 AM    Corvince              Fix-#644
01/13/2020 11:50 AM    Corvince              update-travis
02/03/2020 11:58 AM    Corvince              pr/792
04/22/2020 03:22 PM    Corvince              improved_getitem
05/05/2020 07:49 PM    Corvince              release
05/09/2020 10:28 PM    Corvince              test_examples-patch
06/30/2020 12:02 PM    Corvince              Corvince-patch-travis
09/24/2020 09:06 AM    Corvince              Corvince-fix-issue-855
10/30/2020 10:36 AM    Corvince              FixDocs
11/05/2020 08:46 AM    Corvince              TravisUpdates
11/07/2020 09:46 PM    Corvince              blackagain
01/01/2021 10:03 PM    Corvince              Corvince-patch-ga
01/02/2021 01:20 PM    Corvince              fix-asyncio-win-python-36
03/30/2022 10:32 PM    Corvince              allow-multiple-connections
10/09/2022 09:35 PM    Corvince              esbuild
01/23/2024 09:10 PM    Corvince              experimental/cell-space

**Comment by jackiekazil** [comment]
update-pipfile (confirmed)
update-travis (deleted)
update_reqs (confirmed)
blackagain (deleted)
Corvince-patch-travis (deleted)

**Comment by quaquel** [comment]
I made a pass over all branches and removed very stale or already merged branches.
