### ISSUE TITLE
Staged activation

### ISSUE THREAD

**Issue by dmasad** [projectmesa/mesa#166]
Not every model will have agents with a single ``step`` method. Sometimes we want all agents to execute ``substep_a``, then all agents execute ``substep_b``, and so on, before going back to ``substep_c``. There should be a scheduler which implements that.

**Comment by dmasad** [comment]
I have a provisional version of this done, which needs to be generalized and tested.

**Comment by jackiekazil** [comment]
Let's move this convo to the PR & close this.
