### ISSUE TITLE
JS part of advanced tutorial tries to assign to a `const`

### ISSUE THREAD

**Issue by electric-souperman** [projectmesa/mesa#1678]
**Describe the bug**
In the advanced tutorial in the docs (`docs/tutorials/adv_tutorial.rst`), the chart is initialized as: 

```Javascript
const chart = new Chart(context, {type: 'bar', data: data, options: options});
```

Further on, the `this.reset` method contains the line:
```Javascript
chart = new Chart(context, {type: 'bar', data: data, options: options});
```

Attempting to change the value of a constant results in an `Uncaught TypeError` which stops the visualisations from working correctly:

![image](https://user-images.githubusercontent.com/63853472/234949806-02e3894b-d428-4e3c-86a2-04c70827c5f1.png)

![image](https://user-images.githubusercontent.com/63853472/234950297-7cb5cea2-ffa7-4b4c-9d15-d9640e23c634.png)

![image](https://user-images.githubusercontent.com/63853472/234950689-d17a4916-2d4c-4b1e-8e81-9ac63fe086f4.png)

**Expected behavior**
Switching `const` for `var` fixed the visualisations - as you can see below, and didn't results in any errors being logged to the console. I would therefore propose to change this syntax in the tutorial.

![image](https://user-images.githubusercontent.com/63853472/234951562-9d312917-125b-49bd-b7f0-7abcccd794d3.png)

**To Reproduce**
The issue is with a tutorial, so following the tutorial as it appears on the main branch should be sufficient to reproduce the issue.

**Additional context**
Switching `const` for `var` in this tutorial fixed the issue.

**Comment by rht** [comment]
Good catch! Fixed by #1679.
