### ISSUE TITLE
Protect main branch

### ISSUE THREAD

**Issue by jackiekazil** [projectmesa/mesa#1691]
re: #1685 - Protect main branch so no self-merges 

For params, I was thinking -- Require 1 approval 

Do we want to also add "Require review from Code Owners"?
I am kind of thinking 'no' at this point, but open to discussion -- theoretically when working with others at PyCon then, someone else could approval. So this would prevent the accidental merge out of habit, but wouldn't prevent it someone just wanted to get it done. 

Any other constraints to be added? 

/cc @rht @tpike3

**Comment by jackiekazil** [comment]
<img width="767" alt="Screenshot 2023-05-09 at 9 53 15 PM" src="https://github.com/projectmesa/mesa/assets/166734/f2046fbb-1e5a-4a31-ac9f-d42bf91fccdf">
<img width="768" alt="Screenshot 2023-05-09 at 9 53 22 PM" src="https://github.com/projectmesa/mesa/assets/166734/142c0978-1e55-499b-bea9-45d0ad849e13">
<img width="771" alt="Screenshot 2023-05-09 at 9 53 28 PM" src="https://github.com/projectmesa/mesa/assets/166734/2ce138df-ee3f-489d-9e3d-b673b6c4bd53">

**Comment by rht** [comment]
I'd stick to only "require approvals" for now.

"Require review from Code Owners" makes it more bureaucratic than is needed. It would require approval in the GH UI, where an LGTM comment wouldn't count as an approval in the UI.

**Comment by jackiekazil** [comment]
I agree.

**Comment by jackiekazil** [comment]
This is done.
