### ISSUE TITLE
Continuous space

### ISSUE THREAD

**Issue by dmasad** [projectmesa/mesa#17]
A space object where objects can have continuous position, and a *get_neighbors(...)* method equivalent which can get all the objects within a certain radius of a point.

Mason does this (I think) with a quadtree, but I don't know whether we need to worry about that at this point. A bigass agent:coords dictionary might work just as well for starters? 

If / when we add GIS (not looking forward to that), it'll probably extend this.

**Comment by jackiekazil** [comment]
Fixed.  @dmasad, please reopen or open a new ticket if more work.
