### ISSUE TITLE
Requesting for a feature of model level functions to be included in StagedActivation class

### ISSUE THREAD

**Issue by subhamonsey** [projectmesa/mesa#1709]
**What's the problem this feature will solve?**

Right now the Staged Activation class only allows for functions executed at Agent level. However, one can well want to implement a function which is executed at model level (for ex, in an Economy, adjust the wage rate of all labourers, who are agents and share the same wage rate). Hence suggesting writing "model." before the function name in the object stage_list to indicate its a model level function.

**Describe the solution you'd like**
Solution is straightforward as will be suggested via a PR shortly.

**Comment by tpike3** [comment]
Merged @subhamonsey  pull request on this. Thankyou!
