### ISSUE TITLE
Objective and automated ABM framework comparison

### ISSUE THREAD

**Issue by Datseris** [projectmesa/mesa#1714]
Hi, we are the developers of Agents.jl (cc @Tortar) and we have created an **objective, automated, and well-instructred** framework to compare various Agent Based Modelling software. Our framework is on GitHub and performs comparisons using Continuous Integration. The results of the comparison are shown in a table in the README. Our comparison allows us to make the following claims: 

* Agents.jl is faster than Mesa
 
If you believe this claims are false, then you **are welcomed to perform Pull Requests in the comparison repository to improve the code of your software.** We are opening this issue to publicly let you know of the existence of the comparison repository. We are closing this issue immediately after and won't be following any conversion in this exact issue.

**Comment by Datseris** [comment]
Oh, sorry, forgot the repo link: https://github.com/JuliaDynamics/ABM_Framework_Comparisons

**Comment by rht** [comment]
Note: I am aware of the benchmark, and we had discussed about it several times during Mesa dev meetings. I am aware of @Tortar's improvements to it. Granted, Julia is already naturally faster than Python anyway.

> We are opening this issue to publicly let you know of the existence of the comparison repository. We are closing this issue immediately after and won't be following any conversion in this exact issue.

This sounds like someone who makes a statement (as a guest) in a public forum, and then walks away while closing their ears shut.

Tangent, but I had read a reaction to your remark in https://github.com/isislab-unisa/ABM_Comparison/issues/1#issuecomment-1429328529, regarding with other researchers' benchmark procedure.

**Comment by Datseris** [comment]
I think when I wrote "this exact issue" it appeared as the "comparison of ABMs issue". That's not the case. We aren't closing our ears at all, as we state in the README, we welcome contributions from other developers. We just believe that discussions should happen at a specific place, and most importantly via a form of Pull Requests so that actual code is visible.

So, "this exact issue" meant exactly this GitHub issue over here, which was only opened for allowing us to provide concrete proof that we aren't doing shady business and secretly performing benchmarks noone has seen before.

**Comment by Datseris** [comment]
> Tangent, but I had read a reaction to your remark in https://github.com/isislab-unisa/ABM_Comparison/issues/1#issuecomment-1429328529, regarding with other researchers' benchmark procedure.

I don't understand what this means as I don't see any comment on that GitHub thread from you

**Comment by rht** [comment]
> We just believe that discussions should happen at a specific place, and most importantly via a form of Pull Requests so that actual code is visible.

This is a unilateral decision, and can't be just imposed on people. But I'm fine with further technical discussions to happen in https://github.com/JuliaDynamics/ABM_Framework_Comparisons, since I have already voiced my concern.

If you want my statement, since I have read the benchmark code, then sure, I can vouch that:
1. https://github.com/JuliaDynamics/ABM_Framework_Comparisons is an objective performance benchmark for the ABM libraries, since it is reproducible and auditable in the open.
2. Agents.jl is faster than Mesa. Which is also the result of https://github.com/isislab-unisa/ABM_Comparison (except for the forest fire case, due to not using `@btime`)

Biases in other metrics (that are harder to measure objectively), such as LOC and code simplicity, can be improved over time. Lastly, https://github.com/isislab-unisa/ABM_Comparison covers more libraries, but this too can be improved.

**Comment by Datseris** [comment]
Ah, you are correct, I see your point:

> This is a unilateral decision, and can't be just imposed on people. 

Indeed, I can see how me opening and closing the issue was like I wanted to impose this to you. I apologize. The point I was trying to make is that it is more efficient (in our opinion) to talk on PRs in this repo instead of having general discussions all over the place, in public, or even worse in non-public forums such as emails. I genuinely hope that we can use the automated CI runs that we have set up for further improvements of all frameworks. It took us a lot of work to set it up, but now it exists and we can all benefit from this.
