### ISSUE TITLE
Link to tutorial

### ISSUE THREAD

**Issue by chendaniely** [projectmesa/mesa#172]
#171 contains the code for the scipy conference paper, but the offical documentation still [links](http://mesa.readthedocs.org/en/latest/intro-tutorial.html) to the older tutorial.  Not sure what the best way to handle linking to the tutorial.

Maybe use github's built-in notebook rendering and link directly to the notebook: https://github.com/projectmesa/mesa/blob/master/examples/Tutorial-Boltzmann_Wealth_Model/Tutorial-Boltzmann_Wealth_Model.ipynb

**Comment by dmasad** [comment]
I think the Notebook tutorial is good, but that we should also have it as part of the documentation proper. Thoughts?

**Comment by chendaniely** [comment]
You can use pandoc to output a html file and paste it into the tutorial

or create a link in the docs to the notebooks.

I personally would go with the ladder, since it will allow you to link multiple tutorials from the docs, and won't have to worry as much about things going out of sync.

**Comment by jackiekazil** [comment]
@dmasad this is resolved by #198 yes?

**Comment by jackiekazil** [comment]
This is resolved!
