### ISSUE TITLE
Hi, in this tutorial's link:  https://mesa.readthedocs.io/en/main/tutorials/intro_tutorial.html, line 16 of the tutorial has a value error caused by tuple (x,y) in the for loop( we have to omit the parentheses). please check it out. thanks a lot!

### ISSUE THREAD

**Issue by KhashayarMhm** [projectmesa/mesa#1742]
**Describe the bug**

**Expected behavior**

**To Reproduce**

**Additional context**

**Comment by rht** [comment]
The `(x, y)` signifies a new backward-incompatible API in Mesa 2.0. It means your local Mesa version is outdated. You need to do `pip install -U mesa`.

**Comment by rht** [comment]
I clarified the tutorial that the version must be >=2.1 in #1743.
