### ISSUE TITLE
JupyterViz should have a reset button similar to the play/stop buttons

### ISSUE THREAD

**Issue by rlskoeser** [projectmesa/mesa#1776]
**What's the problem this feature will solve?**
Currently the only way I've found to reset/restart a simulation is to adjust model parameters. This should be provided in the standard interface for parity with mesa runsrerver.

**Describe the solution you'd like**
A reset button alongside the current play and pause buttons.

**Additional context**
Some discussion on #1772

**Comment by rht** [comment]
Implemented in #1795.

**Comment by rlskoeser** [comment]
@rht thank you!
