### ISSUE TITLE
update JupyterViz code to add support for Solara select input and document supported inputs

### ISSUE THREAD

**Issue by rlskoeser** [projectmesa/mesa#1777]
**What's the problem this feature will solve?**
Only `SliderInt` and `SliderFloat` inputs are currently available, and neither of these are documented in the user-facing documentation.

**Describe the solution you'd like**
Support for solara select and improved documentation.

**Additional context**
Some discussion on #1772 

I have the Solara select mapping implemented and working in a local fork; I will be glad to add some suggested changes to the documentation and open a pull request with these changes.

**Comment by rht** [comment]
Implemented in https://github.com/projectmesa/mesa/pull/1779.
