### ISSUE TITLE
JupyterViz grid display should be optional, since not all models use a grid or agent space

### ISSUE THREAD

**Issue by rlskoeser** [projectmesa/mesa#1778]
**What's the problem this feature will solve?**
currently JupyterViz breaks if `model.grid` is not defined

**Describe the solution you'd like**
`model.grid` should continue to be optional; space should only be drawn when the model has a grid.

From testing locally, it looks like it is sufficient to modify the `make_space` method to check for the `grid` attribute and do nothing when it is defined.  I'm willing to open a PR with this change if this solution is sufficient.

**Additional context**
Some discussion on https://github.com/projectmesa/mesa/issues/1772

**Comment by rht** [comment]
I can see your point, where some models don't have an explicit grid/space, but my concern is that some users might blunder by forgetting to create a space, and the explicit error/breakage helps to remind them. The other option is to have a flag that lets user explicitly disable drawing space.

**Comment by rlskoeser** [comment]
@rht that sounds fine to me; seems good to require users to explicitly opt out of displaying the space. Could you suggest a simple way to implement this? What about defining an argument for the `JupyterViz` `space_drawer` parameter that would disable it instead of getting the default display? Would `False` work, or is there a better way to explicitly indicate it should be disabled?

**Comment by rht** [comment]
Fixed in #1783.
