### ISSUE TITLE
Improve Contributor

### ISSUE THREAD

**Issue by tpike3** [projectmesa/mesa#1794]
**What's the problem this feature will solve?**
Improve contributor guide

**Describe the solution you'd like**
A more prominent contribution guide broken into 2 parts 
- [ ] 1. for completely new contributors a step by step from zero
- [ ] 2. for experienced users better instructions on Mesa's unique requirements

**Additional context**
@ankitk50 will provide some notes on his experiences for improvement
- We want to follow [diaxis framework](https://diataxis.fr/)
- Solara uses this and so an example is [Solara Docs](https://solara.dev/docs)

**Comment by EwoutH** [comment]
I really like this. This is one of the category "important, but not urgent", and therefore gets postponed indefinitely. Maybe we can think of some way to break that cycle (joined writing session)?

**Comment by EwoutH** [comment]
> 1- for completely new contributors a step by step from zero

I think this might have been a start? Would you say that's sufficient, or would you like to see more?
- https://github.com/projectmesa/mesa/pull/2258

**Comment by EwoutH** [comment]
@tpike3 what do you think?
