### ISSUE TITLE
JupyterViz: Allow user to customize plots via Matplotlib's Axes.set API

### ISSUE THREAD

**Issue by rht** [projectmesa/mesa#1797]
**What's the problem this feature will solve?**
Plot customization via https://matplotlib.org/stable/api/_as_gen/matplotlib.axes.Axes.set.html.

**Describe the solution you'd like**
As an example, users could specify plot title within the model's fixed parameters `{"xlabel": year, "title": "Price timeseries"}`, and the plotter could do
```python
ax.set(**user_configs)
```

Not sure if this is necessary, because currently, users could just draw Matplotlib plots by themselves if they need customization.

See also https://github.com/projectmesa/mesa-viz-tornado/issues/23.

**Comment by quaquel** [comment]
#2430 adds a posprocess keyword that takes a callable and is called with the ax on which stuff is being plotted. This gives users a hook to do any further refinement.
