### ISSUE TITLE
Custom histogram broken in Visualization Tutorial due to wrong model input

### ISSUE THREAD

**Issue by EwoutH** [projectmesa/mesa#1808]
**Describe the bug**
The [Visualization Tutorial](https://mesa.readthedocs.io/en/main/tutorials/visualization_tutorial.html) now crashes on the last cell when run in Colab.

Likely something is going wrong by inputting the `model` for the histogram, because now it's a `JupyterContainer` object instead of a `Mesa Model`.

![Screenshot_152](https://github.com/projectmesa/mesa/assets/15776622/cdcbebf8-0857-4863-b4b8-666b801e319e)

**Expected behavior**
Model runs without error and with correct histogram.

**To Reproduce**
Run the whole [notebook](https://mesa.readthedocs.io/en/main/tutorials/visualization_tutorial.html) in Colab.

**Comment by HanHuiHH** [comment]
Hi, I met the same problem last week, and I found another version of tutorial that can work well.

https://mesa.readthedocs.io/en/stable/tutorials/visualization_tutorial.html

Maybe they didn't simultaneously update two 
webpages.

**Comment by Corvince** [comment]
Yes this is the right link. The link on GitHub points to the docs of the main branch. So if you install mesa from GitHub it would work again. But the solution should be to point to the stable version of the docs. I think we had this issue several times now and I don't know if it points to the main branch/docs on purpose!?

**Comment by rht** [comment]
The problem will disappear once we release 2.1.2. We should release ASAP. I don't think there is any blocker.

**Comment by rht** [comment]
Closed via #1810.
