### ISSUE TITLE
JupyterViz: Easy way to plot multiple measures in 1 figure

### ISSUE THREAD

**Issue by rht** [projectmesa/mesa#1821]
**What's the problem this feature will solve?**
Currently, each agent variable can only be plotted in separate figures. The virus on a network example is one such use case where we want to plot everything in one figure. See https://github.com/projectmesa/mesa-examples/pull/56#discussion_r1297048939.

**Describe the solution you'd like**

Supporting this could be as simple as detecting if `measure` in https://github.com/projectmesa/mesa/blob/734496c641d0dcc5d05832d5c530b4badad08e4a/mesa/experimental/jupyter_viz.py#L287 is a list. If so, plot all of them in 1 figure.

**Comment by rht** [comment]
If there is no objection to my proposed design, this would be quick for @ankitk50 to implement.

**Comment by ankitk50** [comment]
Can you also give an example model where this can be tested?

**Comment by rht** [comment]
This example already implements the feature: https://github.com/projectmesa/mesa-examples/tree/main/examples/virus_on_network. It just needs to be ported to core Mesa.

**Comment by rht** [comment]
@ankitk50 this is very likely to be a quick merge, since the other 2 PRs are still in draft.

**Comment by EwoutH** [comment]
What's the current status of this effort?
