### ISSUE TITLE
Document possible agent reporter inputs in the datacollector

### ISSUE THREAD

**Issue by EwoutH** [projectmesa/mesa#1837]
Currently in the data collector documentation its defined very well which inputs model reporters can take:

https://github.com/projectmesa/mesa/blob/d40bc5b475f667f65efc3c6dd256f56b1fe3f724/mesa/datacollection.py#L82-L100

However, this isn't done for the agent reports. Could this documentation be added?

**Comment by rht** [comment]
I found it in https://github.com/projectmesa/mesa/blob/d40bc5b475f667f65efc3c6dd256f56b1fe3f724/mesa/datacollection.py#L179. Was added in https://github.com/projectmesa/mesa/commit/80511e2d71de85fd8d84035712ad0078fce32be6#diff-72396865b218fb20682afecba66d3b794e1306841d39490ed4037e26cba31b29L165. @tpike3 is the reason why you added the feature was for pickling issue in `multiprocessing`?

**Comment by EwoutH** [comment]
I would be fine with removing the "Functions with parameters placed in a list" behaviour by the way, as long as we keep the syntax for agent_reporters and model_reporters identical (and thus remove it from both).

**Comment by rht** [comment]
I agree with removing it in both agent and model reporters. I haven't compiled the list of breaking changes for Mesa 3.0 yet.

**Comment by EwoutH** [comment]
Then I would propose removing it for the agent-reporter immediately, and adding a deprecation warning to the model-reporter ASAP.

To summerize, we propose to remove method nr 4 as it's practically identical to nr 1.

```
Model reporters can take four types of arguments:
        1. Lambda function:
           {"agent_count": lambda m: m.schedule.get_agent_count()}
        2. Method of a class/instance:
           {"agent_count": self.get_agent_count} # self here is a class instance
           {"agent_count": Model.get_agent_count} # Model here is a class
        3. Class attributes of a model:
           {"model_attribute": "model_attribute"}
        4. Functions with parameters that have been placed in a list:
           {"Model_Function": [function, [param_1, param_2]]}

        Agent reporters can similarly take:
        1. Attribute name (string) referring to agent's attribute:
           {"energy": "energy"}
        2. Lambda function:
           {"energy": lambda a: a.energy}
        3. Method of an agent class/instance:
           {"agent_action": self.do_action} # self here is an agent class instance
           {"agent_action": Agent.do_action} # Agent here is a class
        4. Functions with parameters placed in a list:
           {"Agent_Function": [function, [param_1, param_2]]}
```

@tpike3 @jackiekazil @Corvince curious what you think.

**Comment by Corvince** [comment]
Agree with removing #4, but I think #1 and #2 are also the same, unless I am missing something. 

I would say removing #4 leaves us with two possibilities: either as an attribute string or a function-like object that takes either `model` or `agent` as its only argument. It shouldn't matter if it's a lambda type, class/instance method or normal function. Or am I missing something?

**Comment by wang-boyu** [comment]
Got a question that's related to <span>#</span>4. If a function has extra parameters, how should it be used in reporters?

For example for agent reports

```python
def some_func(agent, param_1, param_2):
    result = ... # do something with agent and parameters
    return result
```

should it be used like this

```python
from functools import partial


agent_reporters = {
    "reported_value": partial(some_func, param_1=some_value, param_2=some_other_value)
}
```

**Comment by tpike3** [comment]
> I found it in
> 
> https://github.com/projectmesa/mesa/blob/d40bc5b475f667f65efc3c6dd256f56b1fe3f724/mesa/datacollection.py#L179
> 
> . Was added in [80511e2#diff-72396865b218fb20682afecba66d3b794e1306841d39490ed4037e26cba31b29L165](https://github.com/projectmesa/mesa/commit/80511e2d71de85fd8d84035712ad0078fce32be6#diff-72396865b218fb20682afecba66d3b794e1306841d39490ed4037e26cba31b29L165). @tpike3 is the reason why you added the feature was for pickling issue in `multiprocessing`?

Sorry for the delay, but yes @rht reason was because of pickling issue for `multiprocessing`
