### ISSUE TITLE
Add terminal "echo" after server launch to instruct to visit 127.0.0.1:8888

### ISSUE THREAD

**Issue by jackiekazil** [projectmesa/mesa#184]
When running some of the examples, I realized that users may not know where to go if they are starting with the examples. 

Add something to server module that says something like... 
"Launching at 127.0.0.1:8888."
OR
"Visit 127.0.0.1:8888 in your browser for the interface."

**Comment by septra** [comment]
#187

**Comment by dmasad** [comment]
Done.
