### ISSUE TITLE
JupyterViz: after changing parameters, play button does not work

### ISSUE THREAD

**Issue by rlskoeser** [projectmesa/mesa#1845]
**Describe the bug**
Using the jupyterviz interface, when I change the input parameters the model resets but the play button does not do anything. If I use the step button once, then the play button works again after that.

**Expected behavior**
I expect to be able to change an input parameter and then hit play to start the simulation.

**Additional context**
This is with Mesa 2.1.2

**Comment by rht** [comment]
I confirmed it.

**Comment by rht** [comment]
#1851.
