### ISSUE TITLE
Clean up HexSingleGrid(HexGrid) andHexGrid

### ISSUE THREAD

**Issue by jackiekazil** [projectmesa/mesa#1847]
### Discussed in https://github.com/projectmesa/mesa/discussions/1827

<div type='discussions-op-text'>

<sup>Originally posted by **jackiekazil** October  2, 2023</sup>
Why is the HexSingleGrid subclassed from HexGrid and HexGrid has nothing in it? 
I was reading through the code and confused by this -- because it is also visible in the docs. Wondering if there was logical reason or if someone remembered why? I was thinking we should get rid of HexGrid or make it private. 

See the following two lines -https://github.com/projectmesa/mesa/blob/b2f642fd1a986f3114ba6f6f6e9bc119c037062f/mesa/space.py#L742
https://github.com/projectmesa/mesa/blob/b2f642fd1a986f3114ba6f6f6e9bc119c037062f/mesa/space.py#L768</div>

**Comment by EwoutH** [comment]
Looks like it was changed in https://github.com/projectmesa/mesa/pull/1575 and https://github.com/projectmesa/mesa/pull/1581 by @Tortar early this year. Maybe he can give some more details on the motivation and implementation nuts and bolts.

**Comment by Tortar** [comment]
Hi, the motivation to make Grid private was mainly due to the fact that only SingleGrid and MultiGrid should be used. For the same reasoning the HexGrid should be splitted in two versions. To keep retrocompatibility though a simple subclassing trick was used. But when 2.0 was released, the HexGrid class could have been dropped

**Comment by Tortar** [comment]
Ah also, `class HexSingleGrid(_HexGrid, SingleGrid): ` **shouldn't** be removed, it makes it possible to use an HexGrid + max 1 agent per position

**Comment by jackiekazil** [comment]
I am revisiting to try to wrap this up. 
Great... so remove HexGrid class, which has the deprecation warning with a 3.0 release, since 2.0 has passed.

**Comment by EwoutH** [comment]
We should check this aligns / not disrupts with the efforts in
- #1994

**Comment by EwoutH** [comment]
@quaquel can we add a HexGrid elegantly to the cell space? And maybe a triangle space also while we’re at it?

- https://github.com/projectmesa/mesa/issues/1896

**Comment by Corvince** [comment]
HexGrids are already implemented!

https://github.com/projectmesa/mesa/blob/main/mesa%2Fexperimental%2Fcell_space%2Fgrid.py#L187


Triangulars should be doable pretty easy, depending on the coordinate system

**Comment by EwoutH** [comment]
A that’s nice! Maybe I will take a shot at the triangular grids soon.

What would we think of deprecating the current HexGrids?

On other thing is visualization of all this. Can we do that in a scalable way?

**Comment by Corvince** [comment]
> What would we think of deprecating the current HexGrids in favor of the Cell space?

I wouldn't do that until cell_space is out of experimental.
