### ISSUE TITLE
Add a "To run this example" to all examples

### ISSUE THREAD

**Issue by jackiekazil** [projectmesa/mesa#185]
We need to add some instructions to the readmes to help clarify how to run examples.
Here is a simple template: https://github.com/projectmesa/mesa/tree/master/examples/WolfSheep#to-run-this-example

Feel free to get as advanced as you want, but also be keep things easy to get started quickly.

**Comment by ReblochonMasque** [comment]
A pull request is pending so this issue might be closed.
It adds a standardized Readme,md file in each of the examples folders.
Some links and descriptions were updated.
The examples using Jupyter Notebooks have a non-standard ***to run tins example*** block, but explained.
Some files are still missing a list of what mesa feature the example demonstrates, but a new issue can be opened.

I will update the readme(s) as I run through the examples & tutorials

**Comment by jackiekazil** [comment]
Closing this issue in lieu of #189.
