### ISSUE TITLE
phoneinfoga error: could not open requirements file: [errno 21] is a directory: 'requirements.txt'

### ISSUE THREAD

**Issue by itzmeashish37** [projectmesa/mesa#1850]

**Comment by itzmeashish37** [comment]
im getting this error phoneinfoga error: could not open requirements file: [errno 21] is a directory: 'requirements.txt'.
give me sloution.

**Comment by rht** [comment]
That's an error from https://github.com/sundowndev/phoneinfoga, not Mesa. And that project is not written in Python either.
