### ISSUE TITLE
Latest Mesa build is failing on conda-forge

### ISSUE THREAD

**Issue by jackiekazil** [projectmesa/mesa#1891]
I haven't had a chance to review, but I wanted to put this on the radar of others. 
Latest Mesa build is failing on conda-forge. Looks like it failed azure build. Not sure why. 

**Additional context**
https://github.com/conda-forge/mesa-feedstock/pull/19#issuecomment-1827144551

**Comment by jackiekazil** [comment]
If no one is able to review before this weekend,  I will look it at then.

**Comment by rht** [comment]
That's because the meta.yaml is outdated. https://github.com/conda-forge/mesa-feedstock/blob/0c303c1f39af8963c567ae29a28bd4d9aa2bd9b9/recipe/meta.yaml#L23-L31 doesn't have `mesa_viz_tornado` nor `solara`.

**Comment by adamamer20** [comment]
I updated the recipe in the feedstock but I'm waiting for a reviewer to merge the PR.

**Comment by estshorter** [comment]
I also checked, but the build failed because the mesa-viz-tornado package does not exist in the conda forge repo.
https://github.com/conda-forge/mesa-feedstock/pull/22

@adamamer20 
If you are motivated to use mesa, could you register the mesa-viz-tornado package in the repo?

**Comment by adamamer20** [comment]
of course, i have created the feedstock for [mesa-viz-tornado ](https://github.com/conda-forge/mesa-viz-tornado-feedstock.git) yesterday. in my PR the checks are successful. i think there are two issues in your recipe related to the python version (`python >=3.18`) and the mesa-viz-tornado version (`mesa_viz_tornado ~=0.1.0,>=0.1.3`)

**Comment by estshorter** [comment]
Thanks for the comment.
Updated to 2.1.5.

**Comment by jackiekazil** [comment]
thannk you @estshorte!
