### ISSUE TITLE
JupyterViz: disabled space drawer is ignored when rendering in the browser

### ISSUE THREAD

**Issue by rlskoeser** [projectmesa/mesa#1906]
**Describe the bug**
As of v2.1.5, when initializing `JupyterViz`  with `space_drawer=False` the empty space is still drawn when rendering in the browser.

**Expected behavior**
Expect the space drawer to not be rendered.

**To Reproduce**
Currently visible in my risky food simulation, which doesn't have an agent space: https://simrisk.pulcloud.io/riskyfood

**Additional context**
PR with proposed fix : #1907

**Comment by rht** [comment]
Fixed by #1907.
