### ISSUE TITLE
jupyterviz: best practices for model layout

### ISSUE THREAD

**Issue by rlskoeser** [projectmesa/mesa#1913]
[current best practices documentation for mesa](https://mesa.readthedocs.io/en/stable/best-practices.html#model-layout) recommends model layout with `model.py`, `server.py` and `run.py` . Is there a recommendation for models using jupyterviz? Would you recommend only creating `model.py` and `app.py` ?

**Comment by rht** [comment]
Prior discussion: #1269. I suppose that there are 2 conventions until the experimental `JupyterViz` has become sufficiently stable.

**Comment by EwoutH** [comment]
We should probably do this, and then also update our recommended model layout.

Including that coockiecutter thing and/or (?) that thing in mesa-examples that generates a template for you.

**Comment by quaquel** [comment]
cookiecutter is gone and best practices is updated. all examples on read the docs follow this structure.
