### ISSUE TITLE
AttributeError: 'Model' object has no attribute 'agents'

### ISSUE THREAD

**Issue by thetoblin** [projectmesa/mesa#1921]
Not sure this is a bug, but it sure seems like one.

Context: I'm attempting to access agent objects through the `self.agents` dictionary in the Model class.

**Describe the bug**
Attribute `self.agents` missing in Model class despite code declaration.

**Expected behavior**
Class instance should have the attribute `self.agents` - based on observing the `__init__` method of the Model class here: https://github.com/projectmesa/mesa/blob/main/mesa/model.py

**To Reproduce**
Open a python interface and do:
```
import mesa
m = mesa.Model(10)
print(m.agents)
>AttributeError: 'Model' object has no attribute 'agents'
```

**Additional context**
I'm using mesa version 2.1.5, which is the same version as the below screenshot of the code of the Model class (see https://github.com/projectmesa/mesa/blob/main/mesa/model.py):
![model_init](https://github.com/projectmesa/mesa/assets/61850783/b543d923-b418-4903-ac83-37ff758af6cf)

Also note: when I run a copy of the Model class source code, there is indeed the `self.agents` attribute (which isn't surprising, given its declaration).

**Comment by Corvince** [comment]
Hey there! You are looking at the latest code, which does indeed include the agents attribute, but this change is not released yet. 

So your local version (2.1.5.) doesn't include it. You could install the latest version from GitHub, but please note that the agents attribute is about to change very soon.

**Comment by thetoblin** [comment]
Hi - and thanks for a quick reply =).

In which way is the agents attribute expected to change? If the answer is long (and you don't want to provide it here) - is there documentation I can read?
