### ISSUE TITLE
Problem with MultiGrid._place_agent

### ISSUE THREAD

**Issue by glaubius** [projectmesa/mesa#195]
Found an issue in space.py under the MultiGrid(Grid) class line 428. Code reads 

`self.grid[y][x].add(agent)`, but there is no add method under MultiGrid or Grid. Should this line be changed to `self.grid[y][x] = agent`, which would be the same as _place_agent function in Grid class??

**Comment by ReblochonMasque** [comment]
As far as I can tell, the `.add` called on `self.grid[y][x]` is the builtin `set.add` method as all `grid[y][x]` elements are sets.

Did you get an error? Can you post the trace?

**Comment by glaubius** [comment]
Here is the error I get when I use MultiGrid._place_agent:

```
<ipython-input-5-247d9f18331a> in __init__(self, torus, LEM)
     44                 new_segment = WallSegment((x, y))
     45                 self.grid[y][x] = new_segment
---> 46                 self.grid._place_agent((x, y), new_segment)
     47                 self.schedule.add(new_segment)
     48                 self.elevation[y, x] += 2.0   # add elevation for the terrace riser wall

C:\Anaconda3\lib\site-packages\mesa\space.py in _place_agent(self, pos, agent)
    427         x, y = pos
    428         #self.grid[y][x] = agent  ##This line changed from self.grid[y][x].add(agent)
--> 429         self.grid[y][x].add(agent)
    430 
    431     def _remove_agent(self, pos, agent):

AttributeError: 'WallSegment' object has no attribute 'add'
```

You can see the fix I made to the code commented out above, which is to change the _place_agent in the MultiGrid class to be the same as it is in the Grid class `self.grid[y][x] = agent`.

**Comment by dmasad** [comment]
You're assigning the agent directly to the grid, in ``self.grid[y][x] = new_segment`` when you should only be using the ``place_agent`` method. As it is, you're overwriting the set that the grid uses to hold the contents of a cell and replacing it with your WallSegment object.

You should replace lines 45 and 46 with:
```
self.grid.place_agent(new_segment, (x, y))
```
And that should resolve the problem.

**Comment by glaubius** [comment]
Finally got a chance to try out the changes you suggested and they work. Thank you!!!
