### ISSUE TITLE
Clean up labels to. make release labeling easier

### ISSUE THREAD

**Issue by jackiekazil** [projectmesa/mesa#1961]
We have a lot of labels in the repo -- lets clean up few to make the release note management easier.

**Comment by EwoutH** [comment]
Agreed. I've added "Release notes label" to the description of all labels that are used for the release notes, which should also make them more recognizable when tagging.

![Screenshot_350](https://github.com/projectmesa/mesa/assets/15776622/b21f9077-77ec-4062-995e-624d822cf94e)

**Comment by jackiekazil** [comment]
@EwoutH - how do you feel about starting all release notes label with "_" so it would be `_bug` `_breaking`? -- This would group them together alphabetically.

**Comment by rht** [comment]
> @EwoutH - how do you feel about starting all release notes label with "_" so it would be _bug _breaking? -- This would group them together alphabetically.

That makes sense to me. But how will the labels show up in the release note?

**Comment by EwoutH** [comment]
That would work. You just have to remove the _ when generating the release notes, but that’s minor.

In my experience it just takes a few weeks to get familiar with them. So maybe reevaluate if this is needed early February.
