### ISSUE TITLE
Unit-testing framework

### ISSUE THREAD

**Issue by dmasad** [projectmesa/mesa#20]
Another 3am insomnia idea, but: The problem with unit-testing ABMs is that all their componentsare so interconnected. What if Mesa had a built-in unit-testing framework designed specifically for ABMs? I don't think such a thing exists yet, but it could be very valuable.

**Comment by jackiekazil** [comment]
I like this a lot.

**Comment by jackiekazil** [comment]
I am going to close this in lieu of more descriptive tickets.
