### ISSUE TITLE
How to import external data and define as model attributes at each step?

### ISSUE THREAD

**Issue by lovedavidsilva** [projectmesa/mesa#201]
Thanks for developing this great ABM framework in Python. I am trying to transfer my model from NetLogo to Mesa. It is a model that simulates trading in stock market. I have historical stock prices and other information as input (model level attributes), and based on the information, calculate some derived model level attributes. Each step after the model level attributes are imported and calculated, then each agent start trading according to the model level attributes and its own preference.

To start with, I only tried to import model level information and computed one of the derived attributes. I used data collector and chart visualization to check if my codes worked. However, it seemed that I did not import the data successfully. So my question for now is that how to import external data and define as model attributes? I also upload my code here. Thanks.
[bac_model1.txt](https://github.com/projectmesa/mesa/files/212435/bac_model1.txt)

**Comment by dmasad** [comment]
We don't have that functionality built in yet (though it would be a nice thing to have).

Looking at your code, it looks like you're missing a couple ``self``s in the agent step method. (In Python, every method and variable that belongs to an object needs to be prefaced with a ``self`). It should read:

```.python
def step(self, model):
    self.market_update(model)
    self.rsi_update(model)
    self.indi_trade()
```

I can't test your code without the data, but that might be enough to solve the problem.

Two more quick suggestions: If you're working with tabular data, you may also want to look at the [pandas](http://pandas.pydata.org/) library, which lets you load data into an R-style data frame. 

And for future code uploading, you may want to check out the [GitHub gist feature](https://gist.github.com/), which lets you quickly copy-paste files to upload them for sharing. 

Hope that helps!

**Comment by lovedavidsilva** [comment]
Thanks David. I have added the prefix to each function now. However, the data still cannot be read.

Here is how I test the data import now:
At each step, 1)read a line from data and give the values to model attributes ("bac" for example), then 2)collect the value of the attribute using datacollector, finally 3)use chart module to visualize the data, thus checking if data was correctly imported.

It turns out that the output chart is still a line at 0. Since I went through the code so many times, it is hard to tell where is the problem. Is it possible for you to run the test and see what's wrong with it? I have uploaded several lines of the external [data](https://gist.github.com/lovedavidsilva/e68ed944092e0f124835c2eb9131d844).

Thanks!

**Comment by dmasad** [comment]
One other bug is that you aren't actually adding agents to the schedule, so when you run the model, no agents are actually running. That section of the init method should be:

```.python
'''create agents'''
for i in range(self.num_agent):
	a = BACagent(i)
	self.schedule.add(a)
```

The rest seems pretty specific to your model, so I'll shoot you an email about it.

**Comment by dmasad** [comment]
I think this has been resolved.
