### ISSUE TITLE
Update tutorials to include super().__init__() when subclassing mesa.model

### ISSUE THREAD

**Issue by davidbailey** [projectmesa/mesa#2017]
**Describe the bug**
The tutorials (e.g. https://mesa.readthedocs.io/en/stable/tutorials/intro_tutorial.html) instruct users to subclass mesa.model. However they do not say to include super().__init__(). In https://github.com/projectmesa/mesa/blob/main/mesa/model.py#L62-L77 it states you should "Always start with super().__init__() to initialize the model object properly."

**Expected behavior**
The documentation should tell users how to properly use the mesa.model class. The examples should include super().__init__() when subclassing mesa.model

**To Reproduce**
Not applicable.

**Additional context**
None.

**Comment by rht** [comment]
Closed via #2024.
