### ISSUE TITLE
plt.show() - which library is this?

### ISSUE THREAD

**Issue by gac55** [projectmesa/mesa#202]
I am working my way through the [introduction tutorial](http://mesa.readthedocs.org/en/tutorial_update/intro-tutorial.html).

I set up the first model but cannot plot the first graph. What library is 'plt' from?  

I tried installing matplotlib.pyplot as plt but ran in to a host of matoplotlib virtualenv issues, as documented [here](http://stackoverflow.com/questions/33100969/matplotlib-example-code-not-working-on-python-virtual-environment).

**Comment by jackiekazil** [comment]
interesting.

Yes. it is from Matplot lib.
Can you share your code?

**Comment by dmasad** [comment]
Yes, that's unfortunately a known issue with Matplotlib. You can also read more about it here:
http://matplotlib.org/faq/virtualenv_faq.html#osx

Another workaround is installing the older version of matplotlib, i.e.:
```
$ pip install matplotlib==1.4.3
```

**Comment by gac55** [comment]
Thanks @dmasad, that worked!

Now I just need to look at the best way of actually seeing the output. plt.show() doesn't work on the command line

**Comment by dmasad** [comment]
Terrific!

```plt.show()``` should work from the command line -- but if you want to work with the models interactively,  I strongly suggest you check out [IPython / Jupyter Notebooks](http://jupyter.org/).

**Comment by gac55** [comment]
I checked out and concur. Thanks!
