### ISSUE TITLE
DiscreteEveImprovements to the DiscreteEventScheduler classntScheduler class 

### ISSUE THREAD

**Issue by chenyuyou** [projectmesa/mesa#2031]
**What's the problem this feature will solve?**

In each step process in some very complex scenarios, the functions a1 and a2 of agent_A are executed first, then the functions b1 and b2 of agent_B are executed, and then the functions a3 and a4 in agent_A are executed again.
**Describe the solution you'd like**

**Additional context**

**Comment by rht** [comment]
Is staged activation sufficient? https://github.com/projectmesa/mesa/blob/9d4f6e1a579693c9d6495755fcb3110bfb16e9e9/mesa/time.py#L211

**Comment by quaquel** [comment]
This also sounds like something you might want to do through an AgentSet (assuming agent_A and agent_B both belong to some definable group).

**Comment by chenyuyou** [comment]
> This also sounds like something you might want to do through an AgentSet (assuming agent_A and agent_B both belong to some definable group).

Thanks for your help!!
