### ISSUE TITLE
Question/request

### ISSUE THREAD

**Issue by jmclip** [projectmesa/mesa#2085]
I'm wondering if there are other input options other than sliders in mesa 2.2+ I feel like this is completely obvious but I'm missing it. If I recall correctly, there was a checkbox and maybe numeric entry option. I just wanted to see what exists for design options.

**Comment by rht** [comment]
There are others, it's just that they are not yet documented:
- The wolf-sheep example has static text and checkbox: https://github.com/projectmesa/mesa-examples/blob/cd09aba92b1f63a98fa4400c00d93d3fc1dd5c19/examples/wolf_sheep/wolf_sheep/server.py#L49-L73.
- https://github.com/projectmesa/mesa-examples/blob/cd09aba92b1f63a98fa4400c00d93d3fc1dd5c19/gis/urban_growth/urban_growth/server.py#L26 has number input.
- https://github.com/projectmesa/mesa-examples/blob/cd09aba92b1f63a98fa4400c00d93d3fc1dd5c19/examples/pd_grid/pd_grid/server.py#L12 has choice

Help in documenting these in the tutorial/how-to is appreciated.

**Comment by jmclip** [comment]
Wonderful -- thank you! I'm teaching a course this term using MESA. I'm working on some overview resources and will share what I develop.

**Comment by quaquel** [comment]
I also teach MESA at my university. You can find some of the resources I use [here](https://github.com/quaquel/EPA123a_open).

**Comment by jmclip** [comment]
Thank you! Here's [my course repo](https://github.com/jmclip/MACSS-40550-ABM/).
