### ISSUE TITLE
Broken Links in Mesa Documentation

### ISSUE THREAD

**Issue by knightwayne** [projectmesa/mesa#2098]
A few links in the documentation of Mesa are broken, they redirect to incorrect links.
Particularily, on the website of Introduction to Mesa Documentation under [Using Mesa Section](https://mesa.readthedocs.io/en/latest/index.html#using-mesa), the links appear to redirect at the wrong web-page.

[index](https://mesa.readthedocs.io/en/latest/index.html)
- [ ] Mesa Introductory Tutorial
- [ ] Mesa Visualization Tutorial

[overview](https://mesa.readthedocs.io/en/latest/overview.html)
- [ ] mesa.time
- [ ] mesa.space
- [ ] mesa.datacollection
- [ ] mesa.batchrunner

**Comment by EwoutH** [comment]
Thanks for reporting. Sorry we haven't replied. Just checked this. I added the links that don't work to the issue report. Might be more, only checked the pages in the header.

**Comment by EwoutH** [comment]
I'm triggering a new release anyways, so let's see if we can fix this before 2.3.4.

**Comment by EwoutH** [comment]
@knightwayne I think I found a fix. Could you confirm that https://github.com/projectmesa/mesa/pull/2274 solves this issue for you?
