### ISSUE TITLE
Build docs for experimental modules (including cell space)

### ISSUE THREAD

**Issue by EwoutH** [projectmesa/mesa#2122]
Currently [docs](https://mesa.readthedocs.io/) aren't build for features in [mesa/experimental](https://github.com/projectmesa/mesa/tree/main/mesa/experimental), particularly the [cell_space](https://github.com/projectmesa/mesa/tree/main/mesa/experimental/cell_space) and [devs](https://github.com/projectmesa/mesa/tree/main/mesa/experimental/devs). It would be really usefull to have those docs build in Read the Docs.

It probably requires modifying [docs/conf.py](https://github.com/projectmesa/mesa/blob/main/docs/conf.py).

**Comment by EwoutH** [comment]
Thanks! Our docs are build in CI so just opening a PR should show us if that’s the case.

**Comment by stephenfmann** [comment]
Tried this locally and it seems to work. Pull request is https://github.com/projectmesa/mesa/pull/2154

**Comment by EwoutH** [comment]
Yes, thanks!
