### ISSUE TITLE
SolaraViz: Visualize PropertyLayers

### ISSUE THREAD

**Issue by EwoutH** [projectmesa/mesa#2138]
Our new (and current) visualization doesn't support visualising PropertyLayers yet. It would be really great if it could do that. 

- PropertyLayers: https://github.com/projectmesa/mesa/blob/290ceddaf26e9d23e5dade6a39a03ccdcd8e6b65/mesa/space.py#L569
- Visualization: https://github.com/projectmesa/mesa/tree/main/mesa/visualization

I think you need to decide if you want to use matplotlib or altair for it, and then add it either here:
https://github.com/projectmesa/mesa/blob/002d3f4832bf83e6169aaa387f869f138ddb6874/mesa/visualization/components/matplotlib.py#L13-L23
or here 
https://github.com/projectmesa/mesa/blob/002d3f4832bf83e6169aaa387f869f138ddb6874/mesa/visualization/components/altair.py#L10-L14

**Comment by EwoutH** [comment]
If I'm correct three people implemented a custom `space_drawer` recently: 
- @zjost in https://github.com/projectmesa/mesa-examples/pull/157
- @vitorfrois in https://github.com/projectmesa/mesa-examples/pull/118
- @rmhopkins4 is working on https://github.com/projectmesa/mesa/pull/2242

Would one at you give it a go for the `PropertyLayer`? It's currently blocking us from updating more examples to use the `PropertyLayer` (and the `PropertyGrid`), because we can't visualize them in a convenient way yet.

(@Corvince this wouldn't conflict with your work right?)

**Comment by EwoutH** [comment]
@Corvince maybe we need to have some layer system for the visualization, with the grids and layers being in the background and agents moving on top of those. Each layer/grid can have some transparency and an order in which they are stacked.

**Comment by Corvince** [comment]
I think thats a bit too far into the realms of a visualization library. This should preferably handled by one of those. But this goes into the direction of some previous discussions on how to restructure our plots so they don't redraw from scratch every time. Need to do some more research into that direction.

I think its also important that we soon provide a PropertyLayer for the experimental cell_space, that would make things a lot more future proof and more motivating to work on

**Comment by EwoutH** [comment]
Implemented in https://github.com/projectmesa/mesa/pull/2336! Example: https://github.com/projectmesa/mesa-examples/pull/214, and now available in Mesa `3.0.0b0`.
