### ISSUE TITLE
Enhance Visualization Tutorial and use of new visualizations with Mesa Examples

### ISSUE THREAD

**Issue by tpike3** [projectmesa/mesa#2139]
**What's the problem this feature will solve?**
Improve visualization tutorial to make it easier for new users

**Describe the solution you'd like**
- Description of setting up a server
- Description of using different shapes or adding gifs
- More uses with the [Mesa-Example repo](https://github.com/projectmesa/mesa-examples) showing different functionality 

**Additional context**
Numerous options for PyCon sprints

**Comment by quaquel** [comment]
the new tutorial is done, what still remains after #2430 is to update mesa.examples (See #2432 which covers this issue).
