### ISSUE TITLE
Rename JupyterViz to SolaraViz

### ISSUE THREAD

**Issue by EwoutH** [projectmesa/mesa#2175]
I want to propose to rename `JupyterViz` to `SolaraViz` in the [visualization](https://github.com/projectmesa/mesa/tree/main/mesa/visualization). We build heavily onto Solara, and it's also used outside Jupyter notebook environments. I regularly call it the "Solara-based visualisation" right now, and you also enable it from the cli by running `solara run`. So it's a more descriptive and fitting name.

JupyterViz has't been published as a stable release (since https://github.com/projectmesa/mesa/pull/2090 hasn't been included in a stable release), so we can rename it relatively safely, albeit with proper announcements and a alias with a warning.

It's also gives credit where credit is due to the hard work of @maartenbreddels and his team.

**Comment by maartenbreddels** [comment]
It's an honour 🙏
