### ISSUE TITLE
Hide the dividing lines between cells

### ISSUE THREAD

**Issue by sd235634** [projectmesa/mesa#2182]
Hello, how can I hide divide lines between cells when visualizing using a normal grid (instead of ContinuesSpace)? For example, it looks like running on ContinuesSpace but actually on MultiGrid? Thanks!

**Comment by rht** [comment]
Are you using the Tornado-based visualization? (i.e. run.py and server.py in e.g. https://github.com/projectmesa/mesa-examples/tree/main/examples/schelling). The newer Solara-based visualization, see https://github.com/projectmesa/mesa-examples/tree/main/examples/schelling_experimental, doesn't have grid separator for discrete space (SingleGrid, MultiGrid).

**Comment by sd235634** [comment]
> Are you using the Tornado-based visualization? (i.e. run.py and server.py in e.g. https://github.com/projectmesa/mesa-examples/tree/main/examples/schelling). The newer Solara-based visualization, see https://github.com/projectmesa/mesa-examples/tree/main/examples/schelling_experimental, doesn't have grid separator for discrete space (SingleGrid, MultiGrid).

Thanks for your reply! I think i'm using theTornado-based visualization? Because I run the simulation though the run.py in examples\epstein_civil_violence. I am wondering that can I  hide the grid separator for for discrete space? Many thanks.

**Comment by rht** [comment]
Can you use the new visualization instead? The Tornado one is starting to be no longer supported starting the next release anyway. If you insist on the old visualization, you can fork mesa-viz-tornado, comment out this line https://github.com/projectmesa/mesa-viz-tornado/blob/c45f38187d697e5e03df1418675cafc8ee2a14b3/mesa_viz_tornado/templates/js/CanvasModule.js#L64, and install your fork of mesa-viz-tornado.

**Comment by sd235634** [comment]
I see, many thanks for your reply.
