### ISSUE TITLE
Integrate tutorial ipynb and tutorial rst files

### ISSUE THREAD

**Issue by lowcloudnine** [projectmesa/mesa#219]
As of Anaconda 4 Jupyter notebooks can now export directly to rST files.  Merge all of the tutorial information into a ipynb file and then use it as the source for creating rST files.

**Comment by jackiekazil** [comment]
@lowcloudnine this has been resolved yes? (I wanted to check before closing.)

**Comment by lowcloudnine** [comment]
Yes, this one is done.

**Comment by jackiekazil** [comment]
YAY!
