### ISSUE TITLE
Problem in Documentation

### ISSUE THREAD

**Issue by AlABarazi** [projectmesa/mesa#2192]
The visualizations on this link is not working :  
https://mesa.readthedocs.io/en/stable/tutorials/visualization_tutorial.html

And the documentation is missing many APIs related to visualization library.

**Comment by rht** [comment]
There is not enough information of which Mesa version you used. It should work with the latest release, but doesn't work with the Git version because `JupyterViz` has been moved from `mesa.experimental` to `mesa.visualization`.

**Comment by AlABarazi** [comment]
Thanks for the clarification. JupyterViz in the link that I shared with you is not working . The run button is not working, and the reset button is not working. Only the slider is working. Is this intentional to share clickable buttons that do nothing? This is tested on safari, desktop opera, and mobile browser (android Opera ).

**Comment by rht** [comment]
If you want the unreleased tutorial, check out https://mesa.readthedocs.io/en/latest/tutorials/visualization_tutorial.html instead. (notice that it's "latest", not "stable" in the URL)

**Comment by rht** [comment]
It's not meant to be clickable. If you want an interactive version, you have to run the tutorial in Google Colab. Please read the first list just before the word "Important:".

**Comment by rht** [comment]
I meant *after Important:.

**Comment by rht** [comment]
I tested. The unreleased tutorial doesn't work because it's installing release Mesa. As such, can you install release Mesa instead of from Git?

**Comment by AlABarazi** [comment]
I think I already have the released MESA on my system (poetry add mesa). I will check the exact version.
I noticed that there is an issue with the  responsiveness of visualization/UI. These are  screen shots for the UI from my mobile which is not able to recognize my device and render the components properly. 
![Screenshot_20240803-121349](https://github.com/user-attachments/assets/a7d33b80-ae8d-4485-bcce-d90a06cc89db)
![Screenshot_20240803-121028](https://github.com/user-attachments/assets/7e123f28-83d1-4301-b433-2abff0fc3e74)

**Comment by AlABarazi** [comment]
Now there are error when I open the tutorial from my mobile (opera browser)
[Open Browser Console for more detailed log - Double click to close this message]
Failed to load model class 'HtmlModel' from module 'jupyter-vuetify'
Error: Script error for "jupyter-vue", needed by: jupyter-vuetify
http://requirejs.org/docs/errors.html#scripterror
    at makeError (https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js:1:1067)
    at HTMLScriptElement.onScriptError (https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js:1:13218)

**Comment by rht** [comment]
Have you tried a different mobile browser, e.g. Firefox/Chrome? Is it specific to Opera?

**Comment by quaquel** [comment]
There are two seperate issues here. The docs are now fixed via #2340. The rendering on mobile is hard to diagnose and most likely an upstream solara issue.
