### ISSUE TITLE
How to achieve visualization on PyCharm？

### ISSUE THREAD

**Issue by mikevlan** [projectmesa/mesa#2202]
As shown in the picture, I want to run BoltzmannWealthModel on pycharm. I run app-py but it doesn't display a visual interface. What should I do?
![屏幕截图 2024-08-11 225220](https://github.com/user-attachments/assets/eee65cf3-7af9-4321-b035-e7d1bcabc1ee)

**Comment by rht** [comment]
@EwoutH has done it in #1853.

**Comment by EwoutH** [comment]
Which PyCharm version are you running?

**Comment by EwoutH** [comment]
In general, you need to do this:

- Go to the Terminal in PyCharm
- Go into the example forlder: `cd examples/boltzmann_wealth_model_experimental`
- Run app.py with Solara: `solara run app.py`

**Comment by mikevlan** [comment]
thank you！ i will try later

**Comment by EwoutH** [comment]
Let me know if it works!
