### ISSUE TITLE
Clean-up private variables (`_agents`, `_step`)

### ISSUE THREAD

**Issue by EwoutH** [projectmesa/mesa#2212]
To keep backwards compatibility with Mesa 2.x, we added some attributes as private ones, like `_agents` and `_step`. We should clean that up for 3.0.

See:
- https://github.com/projectmesa/mesa/pull/2026

**Comment by EwoutH** [comment]
Partly done in https://github.com/projectmesa/mesa/pull/2251 (`agents_` removal) and https://github.com/projectmesa/mesa/pull/2223 (`_time` removal and `_steps` renamed to `steps`).

**Comment by quaquel** [comment]
What's still remaining?

**Comment by EwoutH** [comment]
It’s mentioned in the migration guide, but I think we want to enforce this somehow.

**Comment by EwoutH** [comment]
That would actually be
- https://github.com/projectmesa/mesa/discussions/2230

So closing this one.
