### ISSUE TITLE
Update all examples to follow model standard file setup

### ISSUE THREAD

**Issue by jackiekazil** [projectmesa/mesa#223]
We created stand file setups for our models. You can see these in [Schelling](https://github.com/projectmesa/mesa/tree/pyconsprints/examples/Schelling) and [WolfSheep](https://github.com/projectmesa/mesa/tree/pyconsprints/examples/WolfSheep). 

Schelling is an example of a very simple model setup, while WolfSheep is an example of a more complex setup. To update you will need to do the following... 
- Update the model & server files
- Update the notebook to analysis and to use the new file structure
- Update the Readme

This is a multi-effort ticket, so feel free to pick one, claim it then check it off when you submit a PR.

It looks like the following projects need to be updated:
- [x] [Color patches](https://github.com/projectmesa/mesa/tree/master/examples/color_patches)
- [x] [Conways Game of Life](https://github.com/projectmesa/mesa/tree/master/examples/conways_game_of_life)
- [x] [Epstein Violence model](https://github.com/projectmesa/mesa/tree/master/examples/epstein_civil_violence) #255
- [x] [Flockers](https://github.com/projectmesa/mesa/tree/master/examples/Flockers) #254
- [x] [Forrest Fire](https://github.com/projectmesa/mesa/tree/master/examples/forest_fire)
- [x] [PD Grid](https://github.com/projectmesa/mesa/tree/master/examples/PD_Grid)
- [x]  [Schelling](https://github.com/projectmesa/mesa/tree/master/examples/Schelling)
- [x] [Boltzmann_Wealth_Model](https://github.com/projectmesa/mesa/tree/master/examples/boltzmann_wealth_model)
- [x] [WolfSheep](https://github.com/projectmesa/mesa/tree/master/examples/wolf_sheep)

**Comment by strixcuriosus** [comment]
I'll take on updating color patches!

**Comment by strixcuriosus** [comment]
I created a follow-up issue to consider making a cookiecutter template: https://github.com/projectmesa/mesa/issues/225

**Comment by jackiekazil** [comment]
\o/ Color patches is done!!

**Comment by nvrzm** [comment]
I've opened a PR for updating the Game of Life example.

**Comment by nvrzm** [comment]
Flockers PR'd... on to Epstein.

**Comment by nvrzm** [comment]
Aaaaand that's done. More soon!

**Comment by jackiekazil** [comment]
Forest Fire was fixed w/ #288.

**Comment by jackiekazil** [comment]
Tutorial Example does not exist, because it was moved to the docs. This was updated and renamed as "Boltzmann_Wealth_Model", because that is what the tutorial example maps too.

**Comment by chrisvoncsefalvay** [comment]
Happy to do Boltzmann aka Tutorial.

**Comment by chrisvoncsefalvay** [comment]
Ps. I'm new to this project, so I'm sure this is a silly question... but I wonder whether doing the demo models as separate repos (like the separate Schelling repo) then adding them in as submodules might actually be beneficial in terms of structure?

**Comment by dmasad** [comment]
@chrisvoncsefalvay Not a silly question at all! We've actually talked about doing that. The main thing that we were concerned about is keeping the repositories in synch, so that any changes to the framework API were reflected in the examples. But if you have some experience with that, it's definitely something we'd like to pursue.

**Comment by tojo13** [comment]
Hello from the PyCon sprints! I'm aiming to refactor the PD Grid example to fit the standard.

**Comment by jackiekazil** [comment]
YAY! We are done! The rest of these are in PRs. <3 <3 <3
