### ISSUE TITLE
Redirect Link is not working on home page

### ISSUE THREAD

**Issue by creativechirag26** [projectmesa/mesa#2244]
On clicking Visualisation tutorial option in header, it redirects to correct page, but on clicking on "Visulation Tutorial" in the home page documentation (https://mesa.readthedocs.io/en/latest/#tutorials/intro_tutorial.html), it doesn't redirect.

On clicking "Visulisation Tutorial" it should have redirected to (https://mesa.readthedocs.io/en/latest/tutorials/visualization_tutorial.html) but it didn't.
![Screenshot from 2024-08-24 18-29-54](https://github.com/user-attachments/assets/23a92b19-210a-4c98-bc26-63202e8b7fe4)

**Comment by rht** [comment]
It seems to be working in [Mesa-Geo RTD](https://mesa-geo.readthedocs.io/en/latest/). @wang-boyu what did you do make it work?

**Comment by creativechirag26** [comment]
But its not working on the specific page I mentioned.

**Comment by wang-boyu** [comment]
It's probably because the cross-references didn't work: https://github.com/projectmesa/mesa/blob/a48dd80a6ce424638e78ae962225d099551dfe46/docs/index.md?plain=1#L101-L102

Mesa-Geo uses absolute url for redirection. But I think it's better to fix the cross-reference issue.

**Comment by EwoutH** [comment]
Thanks for reporting!

Can we use the solution used in Mesa-Geo?

**Comment by rht** [comment]
> Can we use the solution used in Mesa-Geo?

Not feasible because absolute URL also hardcodes the latest/stable branch in it.

**Comment by EwoutH** [comment]
@creativechirag26 I think I found a fix. Could you confirm that https://github.com/projectmesa/mesa/pull/2274 solves this issue for you?

**Comment by creativechirag26** [comment]
Yes, it works now @EwoutH
