### ISSUE TITLE
Web front-end controls sometimes don't work

### ISSUE THREAD

**Issue by max-orhai** [projectmesa/mesa#233]
This sequence of button clicks works as expected:
reset, run, pause, run

But this one seems to disable the controls entirely:
reset, run, run

Reproduced with ConwaysGameOfLife and ForestFire models. There may be other sequences that don't work, too. Looks to me like an issue with the dat.gui.js. I will investigate.

**Comment by max-orhai** [comment]
I don't think the problem's with dat.gui per se, but more about our interface to it in the inline script in modular_template.html. From a UX perspective, having two buttons (*run* and *pause*) is harder to manage than a single button which toggles `control.running`.

**Comment by nvrzm** [comment]
This *should* be fixed by my PR #238.

**Comment by TaylorMutch** [comment]
Closing now that PRs #310 and #383 are merged.
