### ISSUE TITLE
Update introduction tutorial for Mesa 3.0

### ISSUE THREAD

**Issue by EwoutH** [projectmesa/mesa#2335]
Update the [Introductory Tutorial](https://mesa.readthedocs.io/latest/tutorials/intro_tutorial.html) (source: [`intro_tutorial.ipynb`](https://github.com/projectmesa/mesa/blob/main/docs/tutorials/intro_tutorial.ipynb)) to Mesa 3.0 best practices

### Critical
- [ ] New way to activate Agents

### Nice to have
- [ ] Useful AgentSet stuff
- [ ] Multi-agent data collection
- [ ] PropertyLayers
- [ ] Split off data collection and/or batch run parts of the tutorial

**Comment by Gui-FernandesBR** [comment]
Any related PR or solution suggestion for this issue?

I was trying to run the intro example to have a quick start on MESA, but it's not working.

![image](https://github.com/user-attachments/assets/0b80b6b7-f7e0-40c2-bfbe-da014f045fdb)

**Comment by EwoutH** [comment]
Update to the latest pre-release `pip install --upgrade --pre mesa`

**Comment by Gui-FernandesBR** [comment]
> Update to the latest pre-release `pip install --upgrade --pre mesa`

Worked as a charm, thx a lot!!

**Comment by EwoutH** [comment]
Glad to hear, make sure to check out the [Migration guide](https://mesa.readthedocs.io/latest/migration_guide.html),  [Release notes](https://github.com/projectmesa/mesa/blob/main/HISTORY.md) and updated [Mesa overview](https://mesa.readthedocs.io/latest/overview.html).

**Comment by Gui-FernandesBR** [comment]
> Glad to hear, make sure to check out the [Migration guide](https://mesa.readthedocs.io/latest/migration_guide.html), [Release notes](https://github.com/projectmesa/mesa/blob/main/HISTORY.md) and updated [Mesa overview](https://mesa.readthedocs.io/latest/overview.html).

Do you have any idea when the v3.0 may be released? Perhaps still this year?

**Comment by EwoutH** [comment]
@tpike3 stated he is going to work on this, awesome!

**Comment by quaquel** [comment]
It might be good to also add something on the cell spaces as a replacement for the current grids.
