### ISSUE TITLE
Experimental documentation

### ISSUE THREAD

**Issue by PeakEwan** [projectmesa/mesa#2360]
The documentation for Cell Space and DEVS in Experimental is duplicated. 

[page](https://mesa.readthedocs.io/stable/apis/experimental.html#experimental.__init__.Slider) 

Example of priority being duplicated. 
![image](https://github.com/user-attachments/assets/a9362ed1-3b89-4c0b-8ea7-44159d6a4199)

Happy to help if needs be!

**Comment by quaquel** [comment]
yes I can confirm. Not sure what is going on that explains this. My hunch is that we should not include the `__init__` files in experimental.md?
