### ISSUE TITLE
Codecov upload broken - needs token from someone with admin access

### ISSUE THREAD

**Issue by Corvince** [projectmesa/mesa#2363]
**Describe the bug**
Working on #2361 I now discovered that our latest commit uploaded to codecov is 2 months old. Regularly posting coverage reports stopped working in January

**Expected behavior**
Codecov reports should be uploaded by github actions everytime they are run 

**To Reproduce**
```Error: Codecov token not found. Please provide Codecov token with -t flag.``` 
can be seen for every GA action under "codecov", for example
https://github.com/projectmesa/mesa/actions/runs/11346031665/job/31554205137?pr=2362

**Additional context**
Here are the required steps to add a codecov token to our CI
https://docs.codecov.com/docs/github-2-getting-a-codecov-account-and-uploading-coverage#add-the-codecov-token-to-your-repo-or-your-org
This can only be done by someone with admin access to mesa.

**Comment by quaquel** [comment]
Good point. I ran into this as well a few week aga and completely forgot about opening an issue about it.

**Comment by EwoutH** [comment]
Apparently I have acces to the tokens ([here](https://app.codecov.io/github/projectmesa/mesa/config/general)), so I added it to the repository secrets.

![image](https://github.com/user-attachments/assets/1e49c03a-43b9-4178-b7cc-025c572dc2e2)

If I'm correct you can now access it in GitHub Actions with `${{ secrets.CODECOV_TOKEN }}`.

**Comment by Corvince** [comment]
Thanks for the quick response @EwoutH! It works (#2366)
