### ISSUE TITLE
Code coverage and example move

### ISSUE THREAD

**Issue by quaquel** [projectmesa/mesa#2388]
With the move of examples to mesa.examples, we currently don't meet the code coverage target. 

I guess the best solution is to explicitly add a test_examples.py to `mesa.tests`, which tests all examples. Curious what other think.

**Comment by Corvince** [comment]
We already have such tests! But I guess they stopped working since the examples are now in basic and advanced folders? But now that the models are importable the logic can probably be vastly simplified.

**Comment by quaquel** [comment]
the current `test_examples` in `mesa.tests` is currently explicitly skipped. I'll rewrite the tests given the new structure and make them work again hopefully somewhere this weekend.
