### ISSUE TITLE
file duplication

### ISSUE THREAD

**Issue by tpike3** [projectmesa/mesa#2412]
**Describe the bug**
reads the docs is producing a folder called .virtualdocuments that duplicates the tutorial notebooks

**Expected behavior**
no duplication of files

**To Reproduce**
Do a read the docs build locally 

**Additional context**
Identified in #2411

**Comment by EwoutH** [comment]
Removed the files in #2425, if they turn out to be really needed somewhere we can revisit how to approach this without duplication.
