### ISSUE TITLE
unable to start solara app when model cannot be pickled

### ISSUE THREAD

**Issue by wang-boyu** [projectmesa/mesa#2427]
**Describe the bug**

When a model or agents have attributes that cannot be pickled, Solara app won't start due to

```bash
TypeError: cannot pickle '_thread.lock' object
```

**Expected behavior**

Should be able to run model with Solara regardless it can be deep copied or not

**To Reproduce**

Take the Schelling model as an example, add the following into the `__init__()` method in `model.py`:

```python
import threading
self.t = threading.Thread(target=print, args=("Hello"))
self.t.start()
```

Then run `solara run app.py` in the command line.

**Additional context**

It appears to be related to https://github.com/projectmesa/mesa/blob/1d985608db1abe346a6e817bf5bb12c18cad556d/mesa/visualization/solara_viz.py#L188 and https://github.com/projectmesa/mesa/blob/1d985608db1abe346a6e817bf5bb12c18cad556d/mesa/visualization/solara_viz.py#L212

where we try to create deep copies of the model object.

If we remove all usages related to deepcopy:

```diff
diff --git a/mesa/visualization/solara_viz.py b/mesa/visualization/solara_viz.py
index 4bca98d..c2d4960 100644
--- a/mesa/visualization/solara_viz.py
+++ b/mesa/visualization/solara_viz.py
@@ -183,14 +183,6 @@ def ModelController(model: solara.Reactive[Model], play_interval=100):
     running = solara.use_reactive(True)
     original_model = solara.use_reactive(None)
 
-    def save_initial_model():
-        """Save the initial model for comparison."""
-        original_model.set(copy.deepcopy(model.value))
-        playing.value = False
-        force_update()
-
-    solara.use_effect(save_initial_model, [model.value])
-
     async def step():
         while playing.value and running.value:
             await asyncio.sleep(play_interval / 1000)
@@ -205,18 +197,11 @@ def ModelController(model: solara.Reactive[Model], play_interval=100):
         model.value.step()
         running.value = model.value.running
 
-    def do_reset():
-        """Reset the model to its initial state."""
-        playing.value = False
-        running.value = True
-        model.value = copy.deepcopy(original_model.value)
-
     def do_play_pause():
         """Toggle play/pause."""
         playing.value = not playing.value
 
     with solara.Row(justify="space-between"):
-        solara.Button(label="Reset", color="primary", on_click=do_reset)
         solara.Button(
             label="▶" if not playing.value else "❚❚",
             color="primary",
```

Then the Solara app runs but without the `Reset` button.

Probably need a better way to create or save the initial model object?

**Comment by EwoutH** [comment]
@quaquel you looked into deepcopy stuff recently, is this related?

**Comment by quaquel** [comment]
The only relation is that it's triggered by deepcopy. This one is not fixable within mesa itself, unless there is a way fo getting rid of deepcoy in `solara_viz` and there are no further deepcopy operations inside solara. @Corvince, might you be able to explain why deepcopy is used in solara_viz?

**Comment by Corvince** [comment]
Previously we called SolaraViz with the model class and init parameters. Now we pass in a model instance. So I thought the easiest way to reset a model was to restore the initial state through deepcopy. 

But this also causes a problem if you call SolaraViz with a model step where already some steps have passed (say 5). Because now you can only reset to step number 5. So we should really reconsider. I think we can derive the model class through from the instance, but we don't necessarily have access to all init parameters, which makes this a bit challenging

**Comment by quaquel** [comment]
Thanks for the clarification. I'll try to take a closer look over the weekend and see what is possible.

**Comment by EwoutH** [comment]
Now that we have tried both, it might be useful to clearly list and weigh the benefits and disadvantages of calling with a model class and calling with an model instance.
