### ISSUE TITLE
rename altair.py and matplotlib.py

### ISSUE THREAD

**Issue by quaquel** [projectmesa/mesa#2434]
The naming of `mesa.visualization.components.altair` and `mesa.visualization.components.matplotlib` can cause namespace clashes. They thus need to be renamed to e.g., `altair_components` and `matplotlib_components`.

**Comment by Corvince** [comment]
Also note that I would suggest the naming "component" to refer to solara components specifically. But we now also provide general drawing functions that return matplotlib figures, so the file name is outdated and should be reconsidered more generally

**Comment by quaquel** [comment]
It might then make sense to move the draw_space and draw_x functions into their own module (e.g., space_drawing) and leave the solara specific stuff in matplotlib_components
