### ISSUE TITLE
Dead link to "Core Mesa examples"

### ISSUE THREAD

**Issue by hiltonlamf** [projectmesa/mesa#2455]
Hello!

Thanks for the great work. I noticed that the link to "core mesa examples" is dead. See the screenshot attached. I don't even see an example folder in the mesa repo.

<img width="948" alt="Screenshot 2024-11-04 at 7 01 47 PM" src="https://github.com/user-attachments/assets/bfaa74f9-e6b9-4927-8f99-0837e4dca855">

The link takes us to a page that doesn't exist:

<img width="1254" alt="Screenshot 2024-11-04 at 7 02 25 PM" src="https://github.com/user-attachments/assets/3c896c51-fbc3-48f1-810a-c978a206b887">

Can you please fix the link when you get a chance? Thank you!

**Comment by quaquel** [comment]
yes that should be changed to https://github.com/projectmesa/mesa/tree/main/mesa/examples

**Comment by quaquel** [comment]
and it is fixed

**Comment by EwoutH** [comment]
Thanks for reporting!
