### ISSUE TITLE
Error running the code from the introductory tutorial page

### ISSUE THREAD

**Issue by Ricky-790** [projectmesa/mesa#2464]
Hi!
So I was following along the introductory tutorial from the link in the readme file, and I encountered an error when running the code from the website (MoneyAgent and MoneyModel) , when i tried running the model.

It was easily fixed by passing an additional argument, but I still thought of mentioning it.
![image](https://github.com/user-attachments/assets/d952b4fe-dabe-4a74-8f1e-926fab72a458)

Would be happy to work on this if it needs fixing! thanks!

**Comment by EwoutH** [comment]
Which Mesa version are you using, and which version of the tutorial (stable or latest)?

**Comment by Ricky-790** [comment]
> Which Mesa version are you using, and which version of the tutorial (stable or latest)?

I am using mesa version 2.4.0
and this is the tutorial I was referring to: https://mesa.readthedocs.io/latest/tutorials/intro_tutorial.html#create-agent

**Comment by quaquel** [comment]
You are looking at the tutorial for the latest version of mesa, so 3.0, while using mesa 2.4. Please update to the latest release (or wait a few hours to get the official stable release of MESA 3 later today).
