### ISSUE TITLE
Example models should call super in init

### ISSUE THREAD

**Issue by drewrey** [projectmesa/mesa#248]
Some example models are not calling `super()` in their respective `__init__` methods.

**Comment by nvrzm** [comment]
One detriment of this is that random.seed() isn't getting called for these examples, so they're not deterministic. Another is that each subclass must remember to set self.running = True. On the other hand, it's not clear that Model.__init__ is the best place for these things to be happening - maybe it would be better for the base class to have no __init__ and to add, for instance, set_seed and set_running methods.

**Comment by dmasad** [comment]
The base classes are more there as placeholders, and the constructors aren't necessarily intended to be initialized via super() -- especially when in some cases (e.g. WolfSheep) there are multiple inheritances between the base class and the actual agent class. If we want to require agents to call ``super().__init__()``, we need to make sure that it actually contains something useful.

At the moment, I also don't think the examples need to be deterministic.

**Comment by jeetu7** [comment]
This message is just to document the error message that the system will print once I run the web visualization and hit reset. (if i miss setting self.running = True in my model subclass)

```
  File "/home/user/learn/venvs/mesa3_venv/lib/python3.5/site-packages/tornado/gen.py", line 282, in wrapper
    yielded = next(result)
  File "/home/user/learn/venvs/mesa3_venv/lib/python3.5/site-packages/mesa/visualization/ModularVisualization.py", line 270, in run_model
    while self.model.schedule.steps < self.max_steps and self.model.running:
AttributeError: 'RoboModel' object has no attribute 'running'
```

**Comment by dmasad** [comment]
@jeetu7 That issue is fixed in master, so the fix will be included in the next release.

**Comment by jackiekazil** [comment]
And that release should have been released a few days ago.
Let me know if it still needs to be addressed.

On Tue, Jun 21, 2016 at 2:39 PM, David Masad <notifications@github.com>
wrote:

> @jeetu7 <https://github.com/jeetu7> That issue is fixed in master, so the
> fix will be included in the next release.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/projectmesa/mesa/issues/248#issuecomment-227580796>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAKLTr6WrIgEEbStYoTlztU7TKb1D15Lks5qOFoQgaJpZM4IuAh0>
> .
>



-- 
Jacqueline Kazil | @jackiekazil

**Comment by jeetu7** [comment]
Still one small confusion. Which one is the recommended thing to do now?
1) Call super in the subclassed model class
2) specify self.running = True (as evident from latest examples in repo)

**Comment by dmasad** [comment]
At the moment, 2.

**Comment by joelostblom** [comment]
I just ran into the error message @jeetu7 reported when using the MoneyModel example from the tutorial on ReadTheDocs. I instlled the latest version of mesa from Github, but I still run into the same issue. Adding `self.running = True` under the MoneyModel `__init__` method as in the updated Github MoneyModel example solves the problem.

**Comment by jackiekazil** [comment]
Newer discussion is here-- #443. I am closing this convo.
