### ISSUE TITLE
SolaraViz: Add Slider controlling `play_interval` by default

### ISSUE THREAD

**Issue by EwoutH** [projectmesa/mesa#2497]
Aside from the current buttons, having by default a Slider which controls the `play_interval` in SolaraViz would be very useful. It would allow controlling the speed directly from SolaraViz, not only on initialisation.

**Comment by wang-boyu** [comment]
Hi @EwoutH would you like to close this? Or is there anything missing from https://github.com/projectmesa/mesa/pull/2540 that needs to be further developed

**Comment by EwoutH** [comment]
Yes, can indeed be closed!
