### ISSUE TITLE
"pip install --pre mesa[viz]" doesn't work 

### ISSUE THREAD

**Issue by yssysu** [projectmesa/mesa#2498]
**I can't use this command to install 'SolaraViz'**

i first installed the 'mesa', without doing anything, just 'import mesa' and run, something went wrong , like this:Could not import SolaraViz. If you need it, install with 'pip install --pre mesa[viz]', then I tried the command at the computer terminal, then it told me that :
`user % pip install --pre mesa[SolaraViz]`
`zsh: no matches found: mesa[SolaraViz]`

i have tried the command "pip install -U --pre mesa[all]", it report an error as above.

`zsh: no matches found: mesa[all]`

I have uninstalled and tried again several times, but the problem still hasn't been resolved after watching the tutorial, so I submit the issue.

My computer system is Mac 2022 M2 15Sequoia.

**Comment by yssysu** [comment]
use python = 3.10

**Comment by quaquel** [comment]
This is a Mac issue. Put mesa[rec] between quotes.  Like this '"mesa[rec]"'.

**Comment by EwoutH** [comment]
Agreed, weird that it doesn't work on macOS but also doesn't harm.

**Comment by quaquel** [comment]
The issue is with the terminal used on mac. See e.g., [here](https://stackoverflow.com/questions/30539798/zsh-no-matches-found-requestssecurity).

**Comment by yssysu** [comment]
And I have something strange to say , even i didn't install the specific one, it can be run on Jupyter, however ".py" can't.
