### ISSUE TITLE
homophily parameter in basic schelling example

### ISSUE THREAD

**Issue by wang-boyu** [projectmesa/mesa#2515]
**Describe the bug**

The agents in our basic schelling example compare number of similar agents in their neighborhood, against a `homophily` parameter set by users: https://github.com/projectmesa/mesa/blob/a1da4345ad5b8a9f8853145c049fbccc5cd1334e/mesa/examples/basic/schelling/agents.py#L24-L27

where `homophily` is default to 3: https://github.com/projectmesa/mesa/blob/a1da4345ad5b8a9f8853145c049fbccc5cd1334e/mesa/examples/basic/schelling/app.py#L29

Now consider the following example agent at the center cell:

```
X |   |
---------
X | X |
---------
  |   |
```

It has two surrounding agents with the same type, which is smaller than 3, so the agent at the center is considered as "unhappy" in our model.

**Expected behavior**

[Wikipedia](https://en.wikipedia.org/wiki/Schelling%27s_model_of_segregation) uses fraction of neighbors, instead of absolute number of similar neighbors:

 > Each round consists of agents checking their neighborhood to see if the fraction of neighbors $B$ that matches their group - ignoring empty spaces - is greater than or equal $B_a$.

In the example above, the agent has a fraction of 100% neighbors with the same type, so it is very happy. This leads to different results from our model.

Essentially our model counts empty spaces as valid neighbors, while Wikipedia says otherwise. I think NetLogo's Segregation example uses fraction too, following Wikipedia.

Is our segregation model intentionally designed this way?

**Comment by EwoutH** [comment]
Thanks for the detailled write-up. I don’t know why it was implemented this way or by whom (maybe in the git history somewhere, but I agree a fraction would make more sense.

**Comment by quaquel** [comment]
I agree, let's fix this.
