### ISSUE TITLE
Readme links not working in mesa/examples directory.

### ISSUE THREAD

**Issue by Sahil-Chhoker** [projectmesa/mesa#2527]
**Describe the bug**
None of the example links work in [ReadMe](https://github.com/projectmesa/mesa/blob/main/mesa/examples/README.md), they just take you to a non-existent page.

**Expected behavior**
They should link to the actual examples.

**To Reproduce**
Go to : [ReadMe](https://github.com/projectmesa/mesa/blob/main/mesa/examples/README.md) and click any kind of example.

**Comment by EwoutH** [comment]
Yeah this is a known problem. See https://github.com/projectmesa/mesa/pull/2448.

> To make this work, I had to slightly change the links in the example headers. They don't work anymore on GitHub, but do work on RTD. I think this is a worthwhile tradeoff. If you read the readme on github, you have the file explorere at the top of the page anyway. I tested six or so versions of the links but none worked for both.

If you find a solution that works for both that would be great, but not sure if there is one.

**Comment by Sahil-Chhoker** [comment]
Thanks @EwoutH for clarifying, I will see what I can do.
