### ISSUE TITLE
Update create agents in tutorials

### ISSUE THREAD

**Issue by tpike3** [projectmesa/mesa#2537]
**What's the problem this feature will solve?**
Make Mesa tutorial consistent with 3.1 release

**Describe the solution you'd like**
Update create agents  

![image](https://github.com/user-attachments/assets/55221447-489c-423c-a64f-ee9429e772ca)

to 
```

class MoneyModel(mesa.Model):
    """A model with some number of agents."""

    def __init__(self, n=10, seed=None):
        """Initialize a MoneyModel instance.

        Args:
            N: The number of agents.
            width: width of the grid.
            height: Height of the grid.
        """
        super().__init__(seed=seed)
        self.num_agents = n
        

        # Create agents --- Change this line
        MoneyAgent.create_agents(self,n)
```

**Additional context**
Needs to be changed at all agent instantiations such as when space is a added to the model

**Comment by ashish-nagmoti** [comment]
I would love to do that , would you mind assigning this issue to me

**Comment by EwoutH** [comment]
Great, go ahead!

**Comment by tpike3** [comment]
Thanks @ashish-nagmoti

**Comment by EwoutH** [comment]
This can also be updated in the [advanced examples](https://github.com/projectmesa/mesa/tree/main/mesa/examples/advanced), for which see also:
- #2530 

@ashish-nagmoti if you want you can pick that up.

**Comment by peach280** [comment]
I am eager to contribute to this...but I had a query, do we just have to replace MoneyAgent with MoneyAgent.create_agents? I have generated a pull request for that but I don't know if its right or not..It would be great if you could guide me. I would love to gain more knowledge about this.

**Comment by EwoutH** [comment]
@peach280 the function creates an AgentSet of multiple agents. Checkout the PR where it was added:
- https://github.com/projectmesa/mesa/pull/2351

A bit of familiarity with Mesa itself is also highly recommended. Start here: https://github.com/projectmesa/mesa/blob/main/CONTRIBUTING.md#i-have-no-idea-where-to-start

**Comment by peach280** [comment]
Thank you so much I will learn more about it then.

**Comment by ashish-nagmoti** [comment]
@EwoutH thanks for heads up,  i will love to solve  #2530 , see you on comments of #2530 :)

**Comment by ashish-nagmoti** [comment]
@EwoutH as we have merged, the pr , why not close this issue

**Comment by EwoutH** [comment]
Certainly!
