### ISSUE TITLE
Separate "Model-Core-Runner" from GUI, from Analysis from Data Collection...

### ISSUE THREAD

**Issue by ReblochonMasque** [projectmesa/mesa#256]
I think we should aim to separate the GUI components from the "Model-Core-Runner" components of the project and place them in their respective repositories.

That will 
- help clarify the interface and API between the views and the "Model-Core-Runner". 
- decouple the various components of the project
- facilitate the work on one part in isolation of the rest
- allow for other than in browser GUI to be developed 

Maybe we could consider separating the data collection as referenced here #186, and the data analysis too?

Succinctly, I think the "Model-Core-Runner" part should be made rock solid while the more peripheral parts are still evolving and maturing.

Proposed tag: **Defining 1.0**

**Comment by jackiekazil** [comment]
Someone brought this up during Pycon sprints. The purpose of this was to be
able to use the visualization all over the place -- like in Ipython
notebooks.

Ticket: https://github.com/projectmesa/mesa/issues/239

Related conceptual PR for applying abm in a notebook
- https://github.com/projectmesa/mesa/pull/247
- https://github.com/projectmesa/mesa/issues/246


On Mon, Jun 6, 2016 at 7:49 PM, FredInChina <notifications@github.com>
wrote:

> I think we should aim to separate the GUI components from the models
> components of the project and place them in their respective repositories.
>
> That will
>
>    - help clarify the interface and API between the views and the model.
>    - decouple the various components of the project
>    - facilitate the work on one part in isolation of the rest
>    - allow for other than in browser GUI to be developed
>
> We should maybe consider separating the analysis too.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/projectmesa/mesa/issues/256>, or mute the thread
> <https://github.com/notifications/unsubscribe/AAKLTtDwl186NfeiGsBaRULBBMZCYS8mks5qJLH1gaJpZM4IvbOc>
> .
>



-- 
Jacqueline Kazil | @jackiekazil

**Comment by ReblochonMasque** [comment]
Yes, these tickets are about adding more features, this one is to solidify the core so it can support these features.
Not as sexy, I am afraid O_o

**Comment by dmasad** [comment]
These are slightly different issues. However, I think at this point it makes sense to keep the core and the tools in the same repository, for two reasons:

1. Visualization (and data collection, to a lesser extent) are considered integral parts of every other ABM framework; I think users would expect access to those without dealing with additional packages to install.

2. At the moment, the API is still in flux enough that changes to the core may require changes to the visualization and analysis tools. I worry that breaking them off into separate repositories will make it much harder to synch different versions of each.

I suggest revisiting this idea once we're more confident in the API.
