### ISSUE TITLE
Tutorial Sticking Point

### ISSUE THREAD

**Issue by shrogers** [projectmesa/mesa#257]
In going through the Tutorial Boltzman Wealth Model in a Jupyter Notebook I've reached a sticking point in the Collecting Data section.

##########################################
# My code at this point
from mesa import Agent, Model
from mesa.time import RandomActivation
from mesa.space import MultiGrid
from mesa.datacollection import DataCollector

import random
import matplotlib.pyplot as plt
import numpy as np

% matplotlib inline

class MoneyAgent(Agent):
    """An agent with fixed initial wealth."""
    def __init__(self, unique_id):
        self.unique_id = unique_id
        self.wealth = 1
        #print(self.unique_id)
        
    def step(self, model):
        # ...
        self.move(model)
        if self.wealth > 0:
            self.give_money(model)
    
    def move(self, model):
        possible_steps = model.get_neighborhood(self.pos, moore=True, include_center=False)
        new_position = random.choice(possible_steps)
        model.grid.move_agent(new_position)
    
    def give_money(self, model):
        cellmates = model.grid.get_cell_list_contents(self.pos)
        if len(cellmates) > 1:
            other = random.choice(cellmates)
            other.wealth += 1
            self.wealth -= 1
            
def compute_gini(model):
    agent_wealths = [agent.wealth for agent in model.schedule.agents]
    x = sorted(agent_wealths)
    N = model.num_agents
    B = sum(xi*(N-i) for i,xi in enumerate(x)) / N*sum(x)
    return 1 + (1/N) - 2*B

class MoneyModel(Model):
    """A model with a number of agents."""
    def __init__(self, N, width, height):
        self.num_agents = N
        self.running = True
        self.grid = MultiGrid(width, height, True)
        self.schedule = RandomActivation(self)
        self.datacollector = DataCollector(model_reporters={"Gini", compute_gini},
            agent_reporters={"Wealth": lambda a: a.wealth})
        # Create agents
        for i in range(self.num_agents):
            a = MoneyAgent(i)
            self.schedule.add(a)
            x = random.randrange(self.grid.width)
            y = random.randrange(self.grid.height)
            self.grid.place_agent(a, (x,y))
    
    def step(self):
        '''Advance model by one step.'''
        self.datacollector.collect(self)
        self.schedule.step()

# Running it with:
model = MoneyModel(50, 10, 10)
for i in range(100):
    model.step()

# yields the following error:
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-81-c410d4958aec> in <module>()
----> 1 model = MoneyModel(50, 10, 10)
      2 for i in range(100):
      3     model.step()

<ipython-input-80-61bd1ea9e564> in __init__(self, N, width, height)
     50         self.schedule = RandomActivation(self)
     51         self.datacollector = DataCollector(model_reporters={"Gini", compute_gini},
---> 52             agent_reporters={"Wealth": lambda a: a.wealth})
     53         # Create agents
     54         for i in range(self.num_agents):

/home/steve/anaconda3/lib/python3.5/site-packages/mesa/datacollection.py in __init__(self, model_reporters, agent_reporters, tables)
     86         self.tables = {}
     87 
---> 88         for name, func in model_reporters.items():
     89             self._new_model_reporter(name, func)
     90 

AttributeError: 'set' object has no attribute 'items'

# Running in:
The version of the notebook server is 4.1.0 and is running on:

Python 3.5.1 |Anaconda 4.0.0 (64-bit)| (default, Dec  7 2015, 11:16:01) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]

Current Kernel Information:

Python 3.5.1 |Anaconda 4.0.0 (64-bit)| (default, Dec  7 2015, 11:16:01) 
Type "copyright", "credits" or "license" for more information.

IPython 4.1.2 -- An enhanced Interactive Python.

**Comment by nvrzm** [comment]
It looks like you just have a small typo, on the line labeled 51 in the traceback. It currently reads:
```python
self.datacollector = DataCollector(model_reporters={"Gini", compute_gini}, ...
```
which is passing in model_reports as a set rather than as a dictionary. The comma after "Gini" needs to be a colon instead:
```python
self.datacollector = DataCollector(model_reporters={"Gini": compute_gini}, ...
```
This should solve your problem.

**Comment by shrogers** [comment]
Yes it does. Thanks.
