### ISSUE TITLE
web visualization examples does not show grid in offline mode

### ISSUE THREAD

**Issue by jeetu7** [projectmesa/mesa#260]
I installed mesa on a offline m/c and found that the grid is not visible in web version of visualization.
The reasons might be that the server is trying to fetch jquery from online (check the 4th line on following link)

https://github.com/projectmesa/mesa/blob/master/mesa/visualization/templates/modular_template.html#L4

Is it possible to include jquery in static part alongside dat.gui.min.js so that the examples/code work offline.

**Comment by jackiekazil** [comment]
PR #261 takes care of this.
