### ISSUE TITLE
Provide support for text overlays on shapes in CanvasGrid.

### ISSUE THREAD

**Issue by jeetu7** [projectmesa/mesa#263]
It would be nice to have text overlay on grid cells objects on CanvasGrid. For example we can show the unique_id of agents on the rectangles/circles.

**Comment by jeetu7** [comment]
I have almost completed this. I will submit PR in a few days.

**Comment by jackiekazil** [comment]
Awesome!!

On Tue, Jun 21, 2016 at 10:35 AM, jeetu7 <notifications@github.com> wrote:

> I have almost completed this. I will submit PR in a few days.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/projectmesa/mesa/issues/263#issuecomment-227514126>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAKLTrGG-wFGEe4pI8e8RBwb8kSLYibrks5qOCDngaJpZM4I6_QY>
> .
>



-- 
Jacqueline Kazil | @jackiekazil

**Comment by jackiekazil** [comment]
Fixed by #265
