### ISSUE TITLE
Broken tutorial link

### ISSUE THREAD

**Issue by snargleplax** [projectmesa/mesa#266]
The link to the intro tutorial in the readme is broken.  It references http://mesa.readthedocs.io/en/latest/intro-tutorial.html rather than http://mesa.readthedocs.io/en/latest/tutorials/intro_tutorial.html.

I see that issue #172 is related and may obviate this, but for now a simple fix to the link would do.

**Comment by jackiekazil** [comment]
#267 supersedes this issue.
