### ISSUE TITLE
x-tick=1 corresponds to step=0 in Chart plotting in Canvas

### ISSUE THREAD

**Issue by jeetu7** [projectmesa/mesa#268]
I tried to plot the chart wherein the y axis represents number of cells remains unexplored. Effectively this translates to requirement where output is non-zero(y=100 on y-axis) at step 0. But while plotting, the point corresponding to step 0 was plotted at tick 1 (on x-axis). Therefore a line was visible from (0,0) to (1,100) on (x, y) plot. But ideally the plot should start from (0,100). Seems some indexing is getting lost while calling Chart.js library.  This could be taken up with #77 issue.

**Comment by jackiekazil** [comment]
👍
