### ISSUE TITLE
Upgrade chart library to Chart.js version 2

### ISSUE THREAD

**Issue by jeetu7** [projectmesa/mesa#284]
As the latest stable version is 2.1.6 we should upgrade to it. The one shipped with mesa is v 1.0.2 

https://github.com/chartjs/Chart.js
http://www.chartjs.org/docs/

minified versions are available at https://cdnjs.com/libraries/Chart.js

I tried to drop-in the new versions, but they are not compatible in api. Somebody expeirenced with javascript can help.

**Comment by jeetu7** [comment]
I tried hacking the code. But was unable to succed. Here is my unfinished effort.

https://gist.github.com/jeetu7/e9ae9deec68ed0d5b94b11a5e7a0ff6e

**Comment by TaylorMutch** [comment]
Closed #284.
