### ISSUE TITLE
variable name heading0/1 in ArrowHead shape is not intuitive.

### ISSUE THREAD

**Issue by jeetu7** [projectmesa/mesa#295]
Because, they are actually unit vectors in the x & y direction, I am thinking of replacing them with heading_x and heading_y. Any suggestions?

Ref: https://github.com/projectmesa/mesa/blob/master/mesa/visualization/templates/GridDraw.js#L65

**Comment by jackiekazil** [comment]
The fix in #301 looks good to me.
