### ISSUE TITLE
Clean up branches

### ISSUE THREAD

**Issue by jackiekazil** [projectmesa/mesa#298]
We have a lot of unused branches hanging out. We should do a clean up. 

Can someone to through and assess, when is the last time a branch was touched? (I am sure there are some obvious candidates for destruction.

**Comment by njvrzm** [comment]
My assessment:

## Branches with no unmerged commits - definitely safe to delete
* boltzmann_pep_updates
* fix-docs
* gitignore
* model-rewrite
* pyconsprints
* tempate-text-update
* zero_state

## Likely active branches
* networks
> Several commits from this month, no conflicts.

* doc_update_2016
> Three commits from June 2016, all or mostly documentation. Conflicts look easy.

* user_params.32
> Six commits from March, significant code changes. Moderate conflicts.

## Possibly obsolete branches
* 134.subrepo
> Two commits from September 2015 moving the examples directory into a subrepo.

* doc_rst.162
> Eleven commits from November 2015, all or mostly documentation. Significant conflicts.

* docs_update
> Five commits from May 2015, all or mostly documentation. Significant conflict.

**Comment by jackiekazil** [comment]
OMG THIS IS AWESOME! I will do this right now!!

**Comment by jackiekazil** [comment]
so much better now. Thank you for going through all of those!!

networks -- is in dev.
doc_update_2016 -- @dmasad, can this be deleted or is this active? / what is status of this branch
user_params.32 -- @dmasad -- what is the status of this branch? Are you still working on this or can it be deleted?

**Comment by dmasad** [comment]
user_params.32 is still in development, and probably pretty close to being ready to PR. It does change the server API in a somewhat substantial way, so it'll be worth looking at closely.

Let me dig into doc_update_2016 and check.

**Comment by TaylorMutch** [comment]
Cleaned up a bunch of stale branches. Closing #298.
