### ISSUE TITLE
Error in reference in Time.py

### ISSUE THREAD

**Issue by karmkhanna** [projectmesa/mesa#306]
The latest commit has introduced an error in time.py.  Here are the details:

/site-packages/mesa/time.py in step(self)
    100         random.shuffle(self.agents)
    101         for agent in self.agents:
--> 102             agent.step()
    103         self.steps += 1
    104         self.time += 1

This occurs even when you run the sample MoneyModel code on the site.

**Comment by jackiekazil** [comment]
Just to verify, can you send an explicit link to the code that you are talking about?

**Comment by jackiekazil** [comment]
There is one in the tutorial and one in the examples, which is why I am asking for it.

**Comment by jackiekazil** [comment]
And can you share a full stack trace?

**Comment by karmkhanna** [comment]
Hi Jackie,

 

Thanks for the quick follow-up.  We can close this issue.  The readthedocs link I was referring to for the first few tutorials did not correctly reflect the code changes that were committed to the repo.  Reconciling it with the docs available on Github resolved the issue.

 

Best,

Karm

 

-----------------------------
Karm Khanna
Founder & CEO, Famcom
http://www.famcominc.com <http://www.famcominc.com/>  
Phone: 323.459.2686
LinkedIn - http://www.linkedin.com/in/karmk

**Comment by jackiekazil** [comment]
Awesome... just to clarify... where did you get the link and where was it pointing to? (I want to make sure you don't have a bad link out there.)

**Comment by karmkhanna** [comment]
Sorry, I've been swamped...this is the link I was referring to - http://mesa.readthedocs.io/en/latest/.  Since it's been a few months, I'm not sure if you've already updated the docs.

**Comment by jackiekazil** [comment]
Thank u so much for the update! I am going to close for now, because I think that is the case.

**Comment by jackiekazil** [comment]
Thank u so much for the update! I am going to close for now, because I think that is the case.
