### ISSUE TITLE
trouble with the tutorial: TypeError: step() missing 1 required positional argument: 'model'

### ISSUE THREAD

**Issue by mahasamoot** [projectmesa/mesa#308]
```
from mesa import Agent, Model
from mesa.time import RandomActivation

class MoneyAgent(Agent):
    """ An agent with fixed initial wealth."""
    def __init__(self, unique_id):
        self.unique_id = unique_id
        self.wealth = 1

    def step(self, model):
        # The agent's step will go here.
        pass

class MoneyModel(Model):
    """A model with some number of agents."""
    def __init__(self, N):
        self.num_agents = N
        self.schedule = RandomActivation(self)
        # Create agents
        for i in range(self.num_agents):
            a = MoneyAgent(i)
            self.schedule.add(a)

    def step(self):
        '''Advance the model by one step.'''
        self.schedule.step()

```
```
Jupyter QtConsole 4.2.1
Python 3.5.2 (default, Jun 28 2016, 08:46:01) 
Type "copyright", "credits" or "license" for more information.

IPython 5.0.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: %cd ~/Python/Mesa/Tutorial/
/home/philo/Python/Mesa/Tutorial

In [2]: from MoneyModel import MoneyModel

In [3]: empty_model = MoneyModel(10)

In [4]: empty_model.step()
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-4-3dc9a15a1ee6> in <module>()
----> 1 empty_model.step()

/home/philo/Python/Mesa/Tutorial/MoneyModel.py in step(self)
     24     def step(self):
     25         '''Advance the model by one step.'''
---> 26         self.schedule.step()

/usr/lib/python3.5/site-packages/mesa/time.py in step(self)
    100         random.shuffle(self.agents)
    101         for agent in self.agents:
--> 102             agent.step()
    103         self.steps += 1
    104         self.time += 1

TypeError: step() missing 1 required positional argument: 'model'
```

**Comment by devforfu** [comment]
I guess that happens because agent instance should have another signature. Your signature is `step(self, model)` but now Mesa waits for signature `step(self)` as you can see from traceback, i.e. without extra arguments. For example: 

```python
class MoneyAgent(Agent):
   
    def __init__(self, unique_id, model):
        super().__init__(unique_id, model)
        self.pos = None
        self.wealth = 1

    def step(self):
        self.move()
        if self.wealth > 0:
            self.give_money(self.model)
```
Tutorials (including original paper) and the wiki pages are a little bit outdated now.

**Comment by mahasamoot** [comment]
Thanks!

**Comment by jackiekazil** [comment]
This looks resolved to me for the time being. 
If there are issues that you notice with the tutorial, etc. Please file a ticket or submit a PR to help us keep it up to date. 

@devforfu -- ty for chiming in and helping!!!

**Comment by Aradhana-Senapati** [comment]
import matplotlib.pyplot as plt
import numpy as np

import pandas as pd






df = pd.read_csv('H:/PR3/Dataset/dataset_Facebook.csv', sep=";")

df['Type'] = df['Type'].astype('category')
df['Type'] = df['Type'].cat.codes

# Drop all rows with NaN fields
df = df.dropna(axis=0, how='any')

X = df[['Category','Page total likes','Type','Post Month','Post Hour','Post Weekday','Paid']]
y = df[['Lifetime Post Total Reach','Lifetime Post Total Impressions','Lifetime Engaged Users','Lifetime Post Consumers','Lifetime Post Consumptions','Lifetime Post Impressions by people who have liked your Page','Lifetime Post reach by people who like your Page','Lifetime People who have liked your Page and engaged with your post','comment','like','share','Total Interactions']]

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

from sklearn import linear_model
from sklearn.metrics import mean_squared_error
ols = linear_model.LinearRegression()
model = ols.fit(X_train, y_train)
y_pred = model.predict(X_test)
mean_squared_error(y_test, y_pred, multioutput='raw_values')
def mean_absolute_percentage_error(y_true, y_pred): 
    y_true, y_pred = np.array(y_true), np.array(y_pred)
    return np.mean(np.abs((y_true - y_pred) / y_true)) * 100

for trueVals, predVals in zip(y_test.values.T, y_pred.T):
     print(trueVals, predVals)
     #print(mean_absolute_percentage_error(trueVals, predVals)) 
# x axis values
a = [mean_absolute_percentage_error(trueVals)]
# corresponding y axis values
b = [mean_absolute_percentage_error(predVals)]
 
# plotting the points 
plt.plot(a, b) 
 
# naming the x axis
plt.alabel('true values')
# naming the y axis
plt.blabel('predicted values')
 
# giving a title to my graph
plt.title('Mean_Absolute_Error')
 
# function to show the plot
plt.show()

But I got this error. New to python. Please help.

  File "C:/Users/user/practise plot.py", line 47, in <module>
    a = [mean_absolute_percentage_error(trueVals)]

TypeError: mean_absolute_percentage_error() missing 1 required positional argument: 'y_pred'
