### ISSUE TITLE
Most class variables are unnecessary

### ISSUE THREAD

**Issue by njvrzm** [projectmesa/mesa#311]
A handful of the class-level variables in the project are actual class-level configuration, but most of them are shadowed by the `__init__` methods of their classes. This is untidy and could lead to confusion. I'd be happy to clean them up, unless there are objections.

**Comment by jackiekazil** [comment]
Can you give an brief example & how it would change?

**Comment by njvrzm** [comment]
Sure! It shouldn't affect the behavior of the code at all. One example would be BaseScheduler. The beginning of that class looks like this:
```python
class BaseScheduler:
    """ Simplest scheduler; activates agents one at a time, in the order
    they were added.

    Assumes that each agent added has a *step* method which takes no arguments.

    (This is explicitly meant to replicate the scheduler in MASON).

    """
    model = None
    steps = 0
    time = 0
    agents = []

    def __init__(self, model):
        """ Create a new, empty BaseScheduler. """
        self.model = model
        self.steps = 0
        self.time = 0
        self.agents = []
```

The class attributes set before the `__init__` are clobbered. It's mostly an aesthetic thing, but it could be confusing, especially to someone relatively new to Python, that making changes to those values won't do anything.

**Comment by TaylorMutch** [comment]
I added #381 to start resolving this. Definitely agree with @njvrzm, a newcomer to Python would easily question whether this was necessary across all implementations, especially if one is coming from something like C/C++.

**Comment by TaylorMutch** [comment]
@njvrzm I believe the unused class variables have been removed. Closing this issue.
