### ISSUE TITLE
API Docs  'Time' page shoes Python's time module

### ISSUE THREAD

**Issue by rdotsch** [projectmesa/mesa#313]
I noticed that the API documentation at [http://mesa.readthedocs.io/en/latest/]  is incomplete compared to the internal documentation in the mesa python module. There's nothing on the various schedulers in the API docs, and when I go to the 'Time' page ([http://mesa.readthedocs.io/en/latest/apis/time.html]), I get the documentation of python's time module, instead of a mesa specific page.

**Comment by jackiekazil** [comment]
OMG that is a good catch! Thank you for highlighting! We will look into it!

**Comment by devforfu** [comment]
Not sure if it is already known but this guys (from the landing page):

1) http://mesa.readthedocs.io/en/latest/intro_tutorial.html
2) http://mesa.readthedocs.io/en/latest/adv_tutorial.html

Also lead to nowhere.

**Comment by jackiekazil** [comment]
This has been fixed.
