### ISSUE TITLE
Feature request: Display progress of BatchRunner.run_all() 

### ISSUE THREAD

**Issue by rdotsch** [projectmesa/mesa#314]
I have now run a couple of simulations using BatchRunner, taking several hours of computing time. It would be very helpful if the BatchRunner.run_all() method would display a text progress bar, updated after each single simulation run, preferably with remaining time estimation.

**Comment by jackiekazil** [comment]
That is a great point! Any interest in developing that? :-D If not, we can add it our list. I love this feature.

**Comment by rdotsch** [comment]
Absolutely, when I find time.

Ron Dotsch, PhD | Associate Professor | Department of Psychology | Utrecht University | Office: Langeveld H1.11, Heidelberglaan 1 | +31 30 253 4198 | http://ron.dotsch.org/

**Comment by njvrzm** [comment]
[tqdm](https://pypi.python.org/pypi/tqdm) looks like a nice option here!

**Comment by rdotsch** [comment]
Yes, that’s an excellent suggestion. I’ve implemented it just now and it looks great. I’ll test it a bit, and submit the new code soon.

Ron

**Comment by dmasad** [comment]
Done!
