### ISSUE TITLE
Visualization can run after 'Stop' is pressed

### ISSUE THREAD

**Issue by dmasad** [projectmesa/mesa#319]
From #310:

>  if you set the FPS to faster than the server can accommodate, the get_step calls pile up and the front end doesn't stop when you hit "stop" until it's processed all of them. To see this in action, try starting up the Game of Life model, setting the FPS to 20, click "run", let it run for a few seconds, and click "stop". The view will keep advancing for quite a while. I'd like to fix that but I'm not sure the best approach to take and I'm not sure it's worth holding this PR up for it. Any thoughts?

**Comment by dmasad** [comment]
One possible solution: change ```controller.running``` from a boolean variable to holding several states, e.g. {Stepping, Running, Halted}; then only rendering incoming ``viz_state`` messages when the controller is in Stepping or Running states. This doesn't actually put the server in synch, but prevents the visualization server from continuing to render after Stop is pressed.

Another solution is to put in some sort of check that keeps the front-end from sending a new "get_step" message to the server until the previous step finishes running.

**Comment by TaylorMutch** [comment]
@dmasad Is this still occurring within the new UI? I have not observed this myself, but perhaps others have?

**Comment by jackiekazil** [comment]
@TaylorMutch this seems to have been resolved with the new UI. Thank you for all your work on that. Closing this ticket.
