### ISSUE TITLE
User-settable parameters in visualization

### ISSUE THREAD

**Issue by dmasad** [projectmesa/mesa#32]
In many cases, we want the user to be able to set some (though not necessarily all!) model parameters via the visualization interface. There should be a way to easily annotate which parameters ought to be interactive, what their data type is, and what their legal range is.

**Comment by dmasad** [comment]
Working on this in the [user_params.32 branch]{https://github.com/projectmesa/mesa/tree/user_params.32).

The approach I'm taking is creating a new UserParam class, which can be a model input when setting up a server.

**Comment by dmasad** [comment]
This was mostly working in the branch, but that branch is way out of date at this point and needs to be aligned with everything else. It's been on my to-do list for a while, so if you want to take it on, go for it.

The main other hesitation with this is that it changes the server API. I think it's ultimately a change that makes things clearer, but I don't want to push it forward without also changing the documentation and examples to match.

**Comment by Corvince** [comment]
Just to keep you updated:

I finally managed to bring the branch up to date and have already included the newer examples.

Next step: Documentation

So it shouldn't be merged just yet, but should I already make a PR? My branch is [here](https://github.com/projectmesa/mesa/compare/master...Corvince:UserParams_0.8)

**Comment by TaylorMutch** [comment]
Closing as this seems to be resolved by #383 and other related work.
