### ISSUE TITLE
Standardizing Model Naming

### ISSUE THREAD

**Issue by jackiekazil** [projectmesa/mesa#324]
I want to standardize the way we do modeling naming to create a "best practice". 

This is what we currently have.... 
```
Boltzmann_Wealth_Model ConwaysGameOfLife      Flockers               PD_Grid                Schelling              WolfSheep
ColorPatches           EpsteinCivilViolence   ForestFire             Readme.md              Shape Example
```

Do you like.... 
1. Awesome_Cats
2. AwesomeCats
3. Awesome Cats
4. awesome_cats
5. awesome-cats
6. awesomecats

**Comment by jackiekazil** [comment]
I like 4, b/c python, then 2, because it is a norm, then 1.

**Comment by dmasad** [comment]
I basically agree; option four is the most Pythonic.
