### ISSUE TITLE
Review tutorial documentation and update to reflect new model format

### ISSUE THREAD

**Issue by jackiekazil** [projectmesa/mesa#333]
Go through the tutorial and update to reflect the new "standard" for modeling packages. 
http://mesa.readthedocs.io/en/latest/tutorials/intro_tutorial.html
http://mesa.readthedocs.io/en/latest/tutorials/adv_tutorial.html

Standards... 
https://github.com/projectmesa/mesa/issues/324
https://github.com/projectmesa/mesa/issues/223

**Comment by chrisvoncsefalvay** [comment]
I'm happy to chip in if nobody else has picked up on this, @jackiekazil.

**Comment by djmitche** [comment]
I'll jump on this..
