### ISSUE TITLE
Minor forest fire fix

### ISSUE THREAD

**Issue by jackiekazil** [projectmesa/mesa#338]
From email list..... 

In the demo "Forest Fire", there are two errors in "Model.py" and in "run.py", both can be solved replacing "examples.ForestFire.forest_fire.agent"  by "forest_fire.agent".
Greetings and thank you for your work with MESA.

From: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/projectmesa/LJDBpzsnE50/dAo7WYqEBAAJ

**Comment by djmitche** [comment]
This was addressed incidentally in #346, and can now be closed.  I was able to run the example without issue.

**Comment by jackiekazil** [comment]
@djmitche Ty for the note!
