### ISSUE TITLE
Add grass to Wolf-Sheep Predation Model

### ISSUE THREAD

**Issue by dmasad** [projectmesa/mesa#34]
The wolf-sheep predation model does not currently have the sheep eating grass. Add in the grass, and have it reduced by sheep eating it, and grow back at a fixed rate.

**Comment by davpaez** [comment]
I'm working on this ;)

**Comment by dotsdl** [comment]
@davpaez are you still working on this? Otherwise, happy to dig into it.

**Comment by jackiekazil** [comment]
@dotsdl, I assume you were at the sprint? Would you still be interested if @davpaez does not chime in soon?

**Comment by dotsdl** [comment]
Yup. Still interested. :D

**Comment by davpaez** [comment]
Hi, I'm sorry for the delay. I just submitted a pull request. It seems to be working. I'd like to hear your toughts on the custom schedule that I added.

**Comment by dmasad** [comment]
@davpaez are you still working on the changes to the pull request, and/or do you want someone else to jump in and work on it?

**Comment by jackiekazil** [comment]
Let's move this convo to #169
