### ISSUE TITLE
Allow methods of the model class to be passed as model reporters

### ISSUE THREAD

**Issue by wwelsh** [projectmesa/mesa#341]
Hello! I am trying to implement the [Tutorial](http://mesa.readthedocs.io/en/latest/tutorials/intro_tutorial.html). In the Tutorial, under the [Collecting Data](http://mesa.readthedocs.io/en/latest/tutorials/intro_tutorial.html#collecting-data) header, the sample code defines `compute_gini` *outside* the `MoneyModel` class, then passes `compute_gini` to the `DataCollector` as a model reporter. However, I would like to define `compute_gini` as a method of the `MoneyModel` class (it feels more intuitive for me to write `model.compute_gini()` than to put `compute_gini` into the global namespace). 

When I attempt this, I receive an error (pasted below). Reading the error, I find that `datacollection.py` calls `reporter(model)`. This fails if the reporter is a method of the model class. So my question is: Is there a way to allow methods of the model class to be passed as model reporters? 

My code: (uncomment last line to receive error)

```python
import random
import mesa
from mesa.time import RandomActivation
from mesa.space import MultiGrid
from mesa.datacollection import DataCollector

class MoneyAgent(mesa.Agent):
    """An agent with fixed initial wealth."""
    def __init__(self, unique_id, model): 
        super().__init__(unique_id, model)
        self.wealth = 1

    def step(self): 
        """Not relevant to question"""
        return None

class MoneyModel(mesa.Model): 
    """A model with `N` agents of size width * height."""
    def __init__(self, N, width, height):
        self.initial_size = N
        self.grid = MultiGrid(width=width, height=height, torus=True)
        self.schedule = RandomActivation(self)
        # Create Agents
        for i in range(N):
            a = MoneyAgent(i, self)
            # Add to schedule
            self.schedule.add(a)
            # Add to grid
            x = random.randrange(self.grid.width)
            y = random.randrange(self.grid.height)
            self.grid.place_agent(a, (x,y))
        # Create DataCollector
        self.datacollector = DataCollector(
            model_reporters={"Gini": self.compute_gini},
            agent_reporters={"Wealth": lambda a: a.wealth},
        )

    def step(self): 
        """Advance the model by one step."""
        self.datacollector.collect(self)
        self.schedule.step()

    def wealth_list(self):
        return [x.wealth for x in self.schedule.agents]

    def compute_gini(self):
        """Return the Gini coefficient of 
        the current wealth distribution."""
        data = sorted(self.wealth_list())
        N = self.initial_size
        something = sum(x * (N - i) for i,x in enumerate(data))
        something /= (N * sum(data))
        return (1 + (1 / N) - (2 * something))

model = MoneyModel(50, 20, 20)
model.compute_gini()
# model.step()
```

The error I received with the last line of the above uncommented: 

```python
TypeError                                 Traceback (most recent call last)
<ipython-input-15-afbaa6032eb3> in <module>()
     58 model = MoneyModel(50, 20, 20)
     59 model.compute_gini()
---> 60 model.step()

<ipython-input-15-afbaa6032eb3> in step(self)
     41     def step(self):
     42         """Advance the model by one step."""
---> 43         self.datacollector.collect(self)
     44         self.schedule.step()
     45 

# C:\Users\Me\Anaconda3\lib\site-packages\mesa\datacollection.py in collect(self, model)
    135         if self.model_reporters:
    136             for var, reporter in self.model_reporters.items():
--> 137                 self.model_vars[var].append(reporter(model))
    138 
    139         if self.agent_reporters:

TypeError: compute_gini() takes 1 positional argument but 2 were given
```

Thanks for your attention! 

I am using Mesa 0.7.8.1 installed via `pip`; Python 3.5.1 :: Anaconda 4.0.0 (64-bit); Jupyter Notebook; Windows 10.

**Comment by dmasad** [comment]
Sorry for the late response to this! That's definitely a feature that should be incorporated. The ugly way to do it would be to have a lambda function call the model function, i.e.

```
    model_reporters={"Gini": lambda m: m.compute_gini()}
```

But that's not ideal. The other (equally ugly) solution is to have the model's ``compute_gini`` method take an argument that the DataCollector can pass to it, which it just ignores, e.g.:

```
     def compute_gini(self, _):
        """Return the Gini coefficient of  the current wealth distribution."""
        #etc
```

I'm not 100% sure what the best way to change ``DataCollector`` to address this is, though. Using ``inspect`` to see whether a function belongs to the model, or to check what argument it takes?

**Comment by njvrzm** [comment]
A slightly cleaner way of accomplishing the same thing:
```python
model_reporters = {"Gini": MoneyModel.compute_gini}
```

`MoneyModel.compute_gini` is an unbound method, meaning that it expects to be called with its `self` argument, which is effectively what the collect method is doing.

**Comment by jackiekazil** [comment]
I am thinking that maybe we should add this to the docs?... if there was a nice way to do this. However, if there isn't a nice way, the maybe we don't. Whomever picks this up should do that determination.

**Comment by rht** [comment]
This seems to be one of the 2 conflicting design choices. i.e. Have the `.collect()` method expects its constituents to be:
1. external functions taking in a `model` as an argument (current choice; basically how methods of objects are defined in julialang)
2. methods from the model itself. And possibly that the `DataCollector` could have `model` as its attribute and hence no need to pass in the model every single time (this issue), just like every other non-model object always has `model` attribute

In most cases, the data collection functions tend to be mercurial and so shouldn't be tightly coupled to the model specification. The case of `compute_gini()` where it is the bread-and-butter measure that always needs to be calculated by the model in any situation, is rare, and not common enough to justify choice 2).

The solution https://github.com/projectmesa/mesa/issues/341#issuecomment-273388490 requires a python-specific knowledge of using unbound method (which is not a bad thing, but adds to the learning curve).
I think an alternative recommended convention would be to make a named version of this
```
model_reporters={"Gini": lambda m: m.compute_gini()}
```
into
```
def do_compute_gini(model):
    # perhaps, the compute_gini() method is used for other purpose, e.g. in some internal steps of agents
    return model.compute_gini()
...
model_reporters = {"Gini": do_compute_gini}
```

**Comment by quaquel** [comment]
This has been possible for a while now, so I am closing this.
