### ISSUE TITLE
Agents placed by an Agent are not added to the scheduler

### ISSUE THREAD

**Issue by Ryanjrittenhouse** [projectmesa/mesa#344]
First let me say thank you for all of your hard work on this project.  I am a geography grad student that is attempting to adapt a couple of the examples to model  the reorganization of populations due to sea level rise.  This project is for an introductory python class, so please forgive me if the answer is obvious.  

I would like a new agent placed in empty cells that are neighboring a cell with the condition "Under Water".  This script places them, but they are never added to the scheduler.  Any help is greatly appreciated.

from mesa.space import SingleGrid
from mesa.time import RandomActivation

class HouseCell(Agent):
def __init__(self, pos, model):
       super().__init__(pos, model)
        self.pos = pos
        self.condition = "Middle Income"
        self.schedule = RandomActivation(self)
        
    def step(self):
        """
        If the house is Under Water, spread it to Middle Income houses nearby.
        """
        
        similar = 0
        steps = 0
        neighbors = self.model.grid.neighbor_iter(self.pos)
        neighborcell = self.model.grid.iter_neighborhood(self.pos,True)
        mtcell = self.model.grid.is_cell_empty(self.pos)
        
        # If unhappy, move:
        if self.condition != "Under Water":
            for neighbor in neighbors:
                if neighbor.condition == "Under Water":
                    self.model.grid.move_to_empty(self)
                elif neighbor.condition == self.condition:
                    similar += 1 
            if similar < self.model.homophily:
                self.model.grid.move_to_empty(self)
            else:
                self.model.happy += 1                  
        if self.condition == "Under Water":
            for neighbor in neighbors:
                neighbor.condition = "Under Water"
            print("ONFIRE")
            for neighbor in self.model.grid.get_neighborhood(self.pos,True):
                x = neighbor[0]
                y = neighbor[1]
                pos = x,y
               # print(x)
                #print(y)
                print(neighbor)
                if self.model.grid.is_cell_empty((x,y)) == True:
                    print("YAY")
                    new_house = HouseCell((x, y), self)
                    new_house.condition = "Under Water"
                    self.model.grid._place_agent((x, y), new_house)
                    self.schedule.add(new_house)
                    print(x,y)
                #neighbor.condition = "Under Water"
        # for neighbor in neighbors:
            #if neighbor.condition == self.condition:
                #similar += 1
            
                    
                   
        
    def get_pos(self):
        return self.pos

**Comment by dmasad** [comment]
Hi Ryan,

Thanks for using Mesa! It looks like you're giving each HouseCell agent its own schedule, then adding the new agents to that. Your model should generally only have one schedule, which should belong to the overall Model object. 

So the line 
```.python
    self.schedule.add(new_house)
````
should be 
```.python
    self.model.schedule.add(new_house) 
````

I hope that helps!

**Comment by Ryanjrittenhouse** [comment]
Thank you so much!  You were a tremendous help.  I have a couple of other issues that I may need help addressing later.  For now, it's working well enough to satisfy the requirements of this project.
