### ISSUE TITLE
Multiple type agents with time attribute

### ISSUE THREAD

**Issue by yzhou316** [projectmesa/mesa#350]
I have Multiple type agents and one of them has time attribute. The agent with time attribute will influence other type of agents.  And I want to build a model that run by discrete time, and in each step of the model, only the agents whose time attribute is equal to this discrete time to run its own step. How can I build this model with Mesa? Is there any example?(I read the examples you written but didn't find similar one) Thanks so much！

**Comment by rht** [comment]
@yzhou316  you could modify any of the examples to have this constraint.
Say, https://github.com/projectmesa/mesa/blob/5a3a62c6dd9dcb3b310a5526d37dc4c7bcfc43c0/examples/Flockers/flockers/boid.py#L92.
```
# self.discrete_time = [1, 1, 2, 3, 5, 999, 3000]
if self.model.schedule.time in self.discrete_time:
    self.model.space.move_agent(self, new_pos)
```

**Comment by jackiekazil** [comment]
This issue seems to be resolved to me.
