### ISSUE TITLE
Create agents only once

### ISSUE THREAD

**Issue by larsasp** [projectmesa/mesa#357]
Hi!
I'm new to python, and mesa. I can't for the life of me figure out how to make the model create N number of agents only in the first model cycle. I've managed to make the transitions function correctly, however at each step it introduces a new group of N agents. How can I fix this?

Also, if I want all of my agents to start in one state at step = 0, is there a way to do this?

Thank you in advance!

**Comment by dmasad** [comment]
Hi! Sorry for the late reply on this. In general, if you put your agent creation in the model's `__init__` method, they should all be created only once. It sounds like the issue is specific to your code -- if you post it (or a link to it) here, we can help pinpoint how to fix it.

**Comment by larsasp** [comment]
Hi, I managed to fix this. You are right, I had specified the model incorrectly,  but it works very well now. 
Thank you anyway!
