### ISSUE TITLE
[New Feature request] Evolutionary models

### ISSUE THREAD

**Issue by bennati** [projectmesa/mesa#359]
Hello everyone,

I have seen the sheep-wolf example and it looks quite complex.
I thought that one could simplify it by creating custom classes that take care of the evolutionary process.
If you are interested I can prepare a pull request, let me know!

Cheers,
Stefano

**Comment by dmasad** [comment]
Hi Stefano,
That sounds like an interesting idea ! Can you explain what you mean by evolutionary process? I'm not sure I see how that would simplify the wolf-sheep example.

**Comment by dmasad** [comment]
The model as it is now doesn't have any selection component, and is mostly focused on population size dynamics -- but if you're interested in implementing an extension that adds an evolutionary submodel, I think that could be a great additional example to have alongside the current wolf-sheep model!

**Comment by jackiekazil** [comment]
Looking back at the notes in #360. I am going to close this ticket. 
However, after rereading this, I want to encourage you once again to create this as a separate library. If you need help figuring out how to set this up.
