### ISSUE TITLE
Fix network agent assignment

### ISSUE THREAD

**Issue by dmasad** [projectmesa/mesa#362]
@jackiekazil Currently, the new MesaNetwork class maps agents to network nodes by referencing their attribute dictionary (https://github.com/projectmesa/mesa/blob/network/mesa/space.py#L644). The node contents (i.e. `agent` attribute) should be the entire agent object, in the same way that grid cells work.

**Comment by cauemello** [comment]
@dmasad and @jackiekazil, I think this has been addressed already.

**Comment by jackiekazil** [comment]
Yes. Ty!
