### ISSUE TITLE
problem with loading the visulisation

### ISSUE THREAD

**Issue by Giase** [projectmesa/mesa#365]
I am following the advanced tutorial and trying to experiment with visulisation. I copied the code as is in the tutorial, but the server port 127.0.0.1:8889 keeps loading and never shows the visualisation page. I am using google chrome Version 58.0.3029.110 (64-bit). I also tried on Microsoft Edge (version 38.14393.1066.0) without success. 
I use the Spyder IDE form which I ran the script. 
Then I also tried using the command prmpt and the visualisation page loaded succesfully. It seems that the Spyder causes the problem. Any ideas why this is happneing?

**Comment by njvrzm** [comment]
Hello, and thank you for the report! This is actually an issue with our documentation. The tutorial hasn't been updated for a change we made to how the visualization server runs. I'll fix that as ASAP. Meanwhile, if you delete the line `server.port = 8889` from the tutorial code the server should run properly, and it should launch a browser window automatically with the correct port (which is now 8521).

Please try this and let us know if you still encounter problems.

**Comment by jackiekazil** [comment]
It looks like this has been fixed, but this ticket was never closed. Please reopen if I am wrong.
