### ISSUE TITLE
Seeding when using numpy

### ISSUE THREAD

**Issue by larsasp** [projectmesa/mesa#368]
I am using np.random. a lot in my model, and I want to set a seed, np.random.seed to get consistent line of random numbers. This does not seem to work to great, and many people seem to dislike np.random vs just random. Has anyone had a similar problem?

**Comment by larsasp** [comment]
Update: specified np.random.RandomState and passed it instead of numpy.random function. It works beautifully, however, I am still getting too much variation in modelled outcomes, and I suspect it is due to the activation of the agents not being seeded. Is there a plan to include such a function, or does anyone have any idea how to work around it in the mean time?

**Comment by djmitche** [comment]
`RandomActivation` uses Python's random number generator, not numpy's, so you will need to seed that in order to get stable activation.

Note that the Model parent class seeds this generator by default.  I'm making a pull request to seed the numpy generator, too.

**Comment by jackiekazil** [comment]
Fixed by #373 -- @larsasp, this fix will be in our next release, which will happen post PyCon... approximately next week. 

Ty @djmitche for the fix!
