### ISSUE TITLE
Add several agents to scheduler at one

### ISSUE THREAD

**Issue by lmzintgraf** [projectmesa/mesa#369]
I think it would be nice to have the option to pass a list of agents to the scheduler, instead of just a single agent. I propose the following adaption of the add() function in the BaseScheduler:

```
if type(agent) == list:
    self.agents.extend(agent)
else:
    self.agents.append(agent)
```

instead of, as it is now, just `self.agents.append(agent)`. Maybe also then rename 'agent' to 'agents'.

**Comment by jackiekazil** [comment]
What would be the purpose of this change? Can you provide an example use case to help illustrate?

**Comment by lmzintgraf** [comment]
I thought about it a bit more, and maybe it's not necessary. I decided for my project to directly mess with the `schedule.agent` variable, instead of going via functions for adding/removing agents.

The reason I thought this would be a useful feature is for example if you have many agents, but only some of them are put into the scheduler in every step of the model. I.e., in a step of the model, you put in all of the agents you want to do something at once, and afterwards remove them from the scheduler again. But I am not sure if this is intended use of the mesa framework.

I just needed it because I store my agents not in the scheduler but somewhere else, and do not want to loop through the list when adding them to the scheduler. But as I said, I will just work with the `schedule.agent` variable directly, so maybe the suggested change is not necessary. The add method as it is right now shows basic wanted behaviour, and if more is needed it can be extended by the individual users of mesa for their application I guess.

**Comment by rht** [comment]
Closing because the workaround to apply the bulk agents adding can be easily implemented on the scheduler if needed. This issue is not a blocker to some model implementations.
