### ISSUE TITLE
Release notes discussion for Flagstaff (PyCon Sprints & then some)

### ISSUE THREAD

**Issue by jackiekazil** [projectmesa/mesa#387]
@dmasad @njvrzm 

I never pushed a post Pycon release. I was putting together release notes and wanted to pass them by you you all. Can you review and check if I am missing anything? (There are open PRs that still need to be merged, but we can always do another release. I didn't want to not do a release for that reason.

Next release - 0.8.1 (2017-06-?) Flagstaff (PyCon Sprints & then some)
++++++++++++++++++

**Improvements**

* Add best-practices document and describe models. #371
* Refactored & model standards related:
    * Prisoner's Dilemma refactor to meet new model standard format. #377
    * refactored boltzmann wealth model to new layout #376
    * Update tutorial to follow new model standards #370
    * Moving wolf sheep pngs to sub-folder for better organization #372
    * Add best-practices document and describe models. #371

**Fixes**

* Fix math problems in flockers; use numpy in space #378
* Seed both global random number generators #373, #368
* Dictionary parameters fix #309
* Downgrade setuptools to fix #353
* Minor forest fire fix #338, #346
* Allow fixed seed for replication #107

**Comment by jackiekazil** [comment]
Also, I have these notes from the history, but I am not sure which PR's they are attached to. I have been created the release notes based off of PRs. Do you know anything about these? Do you have ticket numbers or PRs for these? Are these from a previous release I mixed them up with the current one? Let me know..... 

* Modified loop over agents in schedule step method
  * If agents are deleted while looping over agents list in the model schedule,
    looping becomes unpredictable and agents step methods for some agents may not
    be called for a given model step
* Fix tutorial and example readme for port change

* Added function to use local images as shapes in GridDraw
* Added drawImage function to GridDraw
    * Enables to draw a local imagefile as shape for agents

**Comment by rht** [comment]
> Modified loop over agents in schedule step method

https://github.com/projectmesa/mesa/pull/356

I rechecked the changelog via `git log v0.8.0...HEAD | grep -v Merge`:
```
- d0e3ca7 changed modular vis to rst and moved to docs (Brian Russo, 5 weeks ago)
- 9b705bd refactored to model.py (Brian Russo, 5 weeks ago)
- e069c08 rename notebook to standard analysis.ipynb (Thomas Johnson, 5 weeks ago)
- 7039485 fixed flake errors (Brian Russo, 5 weeks ago)
- c9580d4 refactored boltzmann wealth model to new layout (Brian Russo, 5 weeks ago)
- 300c2f5 no need to import random in model (Thomas Johnson, 5 weeks ago)
- 600c62b Fix math problems in flockers; use numpy in space (Nathan Verzemnieks, 5 weeks ago)
- e70a915 small styling change in readme (Thomas Johnson, 5 weeks ago)
- b7ae65c update readme to reflect new model organization (Thomas Johnson, 5 weeks ago)
- fa5b6b4 make jupyter notebook example work with new model standard format (warning: jupyter notebook example changes result in a lot of lines of code) (Thomas Johnson, 5 weeks ago)
- aa7ab47 add agent model and delete no longer needed model/agent combined pg_grid.py (Thomas Johnson, 5 weeks ago)
- 8db1349 finish model (model is now seperate from agent) (Thomas Johnson, 5 weeks ago)
- dffae33 add server in the style of conways GOLife server (Thomas Johnson, 5 weeks ago)
- 8738b87 add agent portrayal in the style of conways GOLife portrayal (Thomas Johnson, 5 weeks ago)
- cfe5a2a rename PD_Grid outer example folder to pd_grid (standard) (Thomas Johnson, 5 weeks ago)
- 70b0e37 add entry point for pris dilemma model (Thomas Johnson, 5 weeks ago)
- 9899d11 create package for component modules (Thomas Johnson, 5 weeks ago)
- 5cabad7 Seed both global random number generators (Dustin J. Mitchell, 6 weeks ago)
- 3deb576 Refactor tutorials to use properly named model, files (Dustin J. Mitchell, 6 weeks ago)
- 9d1a928 Moves png graphics to sub folder for organizing. (jackiekazil, 6 weeks ago)
- aa835e7 Updating history. (jackiekazil, 6 weeks ago)
- 569c472 Add best-practices document and describe models. (Dustin J. Mitchell, 6 weeks ago)
- 63ae794 Updating history for v0.8.1. (jackiekazil, 6 weeks ago)
8b57aa8 Fix tutorial and example readme for port change (Nathan Miller, 7 weeks ago)
8bb80bc Downgrade setuptools to fix #353 (Nathan Miller, 4 months ago)
- 3c87997 Modified loop over agents in schedule step method (Paolo Gervasoni Vila, 5 months ago)
9d373d7 Added drawImage function to GridDraw (Corvince, 5 months ago)
```

There are 3 commits that are not based on any PR's. (Also, while commit msgs should be imperative, changelog statements should be a past record of actions.)

**Comment by rht** [comment]
CHANGELOG += [#383, #385]

**Comment by jackiekazil** [comment]
@rht this is exactly what I needed! Thank you!

**Comment by jackiekazil** [comment]
Release notes are here: https://github.com/projectmesa/mesa/blob/master/HISTORY.rst#081-2017-07-03-flagstaff-pycon-sprints--then-some
