### ISSUE TITLE
No Module: UserParam

### ISSUE THREAD

**Issue by narc98** [projectmesa/mesa#392]
Thanks for your work on this project.  I'm just getting into ABM and am not sure what's driving my problem. 
 I can only run the sugarscape model and all others fail for a variety of errors. The most common error (found when running Boltzman, Schelling, Wolf) is "ImportError: No module named 'mesa.visualization.UserParam'" from the example's server.py module (this import line: from mesa.visualization.UserParam import UserSettableParameter).  I don't know if I'm doing something wrong or if this issue is related to #354 (User params 0.8 #354).  The UserParam.py file is in the mesa/visualization directory and unchanged  

Thanks for any help anyone can offer.  I'm particularly interested in running the Wolf/Sheep model to start framing my work.  Happy 4th to those of you in the US.

Regards,
Nate

Ubuntu LTS 16.04
Python 3.5.2

**Comment by dmasad** [comment]
The UserParameters class is very new. If you installed Mesa via pip (or just installed an older version) but downloaded the examples from GitHub, you won't be using a version of Mesa that already has UserParams.

The best way to fix it should be to reinstall the most recent version directly from GitHub:
```$ pip install git+https://github.com/projectmesa/mesa```

**Comment by narc98** [comment]
Thanks.  I'm not sure what wasn't working.  I downloaded the zip file from git yesterday and had the issues.  Just cloned again and no problems.  Sorry for the trouble.
