### ISSUE TITLE
Review AB-CE & Mesa examples

### ISSUE THREAD

**Issue by jackiekazil** [projectmesa/mesa#396]
Review AB-CE & Mesa integration examples.... 

* https://github.com/AB-CE/examples/tree/master/examples/sugarscape
* https://github.com/AB-CE/examples/tree/master/examples/mesa_example 

Questions:

* What can Mesa learn from this? Should Mesa offer any additional features? 
* What can AB-CE do differently? Should something be moved from AB-CE to Mesa?
* Is Mesa being used in an unexpected way? If so, would others want to use it in this way?

**Comment by tpike3** [comment]
Added to Mesa PAckages
