### ISSUE TITLE
Visualization Tutorial: too many arguments for ModularServer?

### ISSUE THREAD

**Issue by dstrohmaier** [projectmesa/mesa#397]
I tried to follow visualization tutorial but the following line did not work:
```
server = ModularServer(MoneyModel,
                       [grid],
                       "Money Model",
                       100, 10, 10)
```
I get the following error:
`TypeError: __init__() takes from 3 to 5 positional arguments but 7 were given`
However, it goes away, if I turn the last three arguments into an dictionary:
```
 server = ModularServer(MoneyModel,
                        [grid],
                        "Money Model",
                        {"N": 100,
                         "width": 10,
                         "height": 10})
```

Then the visualization runs without problems.

**Comment by rht** [comment]
@dstrohmaier you are running on an outdated version. This appears to have been fixed:
```
server = ModularServer(MoneyModel, [grid, chart], "Money Model", model_params)
```
at https://github.com/projectmesa/mesa/blob/ffe5ca13ba17ed4c598d2974744c5174826d9390/examples/boltzmann_wealth_model/wealth_model/server.py#L36.

**Comment by clmerlos** [comment]
I have the same issue.
Uninstalled and reinstalled using 

> $ pip install git+https://github.com/projectmesa/mesa

I have Mesa-0.8.0 currently installed

**Comment by TaylorMutch** [comment]
I am closing this issue. As rht said, model parameters are specified using the `model_params` dictionary, which is then passed along to create, modify, and reset the underlying model from the browser. Non-keyword arguments are not passed to the model's constructor.

**Comment by kdhoore** [comment]
Maybe the advanced tutorial code can be changed in order to avoid everyone to end up on this issue page?

**Comment by rht** [comment]
Even if the tutorial's readme is updated in the repo warning such, there is however no way to update a stale `git clone` in someone's machine.

**Comment by maiscelo** [comment]
> I tried to follow visualization tutorial but the following line did not work:
> server = ModularServer(MoneyModel,
>                        [grid],
>                        "Money Model",
>                        100, 10, 10)
> 
> I get the following error:
> TypeError: __init__() takes from 3 to 5 positional arguments but 7 were given
> However, it goes away, if I turn the last three arguments into an dictionary:
>  server = ModularServer(MoneyModel,
>                         [grid],
>                         "Money Model",
>                         {"N": 100,
>                          "width": 10,
>                          "height": 10})
> 
> Then the visualization runs without problems.

Hi, I've got the same symtom. And your trick solve it. Run the algorithm on jupiter note book and last version of MESA 0.8.3. Thank you!
