### ISSUE TITLE
Update Introductory Tutorial - Set up and run the BatchRunner

### ISSUE THREAD

**Issue by clmerlos** [projectmesa/mesa#403]
Following the Intro Tutorial, tried running
```python
parameters = {"width": 10,
              "height": 10,
              "N": range(10, 500, 10)}

batch_run = BatchRunner(MoneyModel,
                        parameters,
                        iterations=5,
                        max_steps=100,
                        model_reporters={"Gini": compute_gini})
batch_run.run_all()
```

Resulted in the following error

> Traceback (most recent call last):
  File "<stdin>", line 5, in <module>
  File "/Users/.../mesa-master/mesa/batchrunner.py", line 83, in __init__
    self.variable_parameters = self._process_parameters(variable_parameters)
  File "/Users/.../mesa-master/mesa/batchrunner.py", line 107, in _process_parameters
    raise VariableParameterError(bad_names)
mesa.batchrunner.VariableParameterError: variable_parameters must map a name to a sequence of values. These parameters were given with non-sequence values: ['width', 'height']

Alternatively,  running this seemed to work
```python
fixed_parameters = {"width": 10, "height": 10}
var_parameters ={"N": range(10, 500, 10)}

batch_run = BatchRunner(MoneyModel,
                        var_parameters,
                        fixed_parameters,
                        iterations=5,
                        max_steps=100,
                        model_reporters={"Gini": compute_gini})

batch_run.run_all()
```

Consider updating Tutorial

**Comment by dmasad** [comment]
Good catch! The tutorial update was written, but looks like it didn't make its way to readthedocs for some reason. Thanks for letting us know!
