### ISSUE TITLE
DataCollector should be able to create multiple columns from a single function call

### ISSUE THREAD

**Issue by prototaxites** [projectmesa/mesa#406]
First of all, thank you all for writing such a useful package - it has massively streamlined my modelling efforts and I'm really impressed by how easy it is to rapidly prototype models in mesa.

Normally, a function for DataCollector takes in a model or agent as a parameter, and returns a single value, e.g. the number of agents, or the value of some agent's internal variable. However, in the models I'm writing, agents of the same class are divided into separate "species" (agent.species = 1, agent.species = 2, etc.). If the number of species were hard-coded into the model, this would not be a problem - I could hard-code a couple of functions that returns a value for each species and be done with it. 

However, the number of species in my model is a user-settable parameter, which makes hard-coding things difficult. Currently I have a work-around that involves returning a list or a dictionary, and then messing with the Pandas dataframe after the model has run to split them into separate columns, which is a pain. Instead, it would be useful if a reporter function could return a dictionary, and then the dictionary keys are used as headings for separate columns. For example:

`self.datacollector = DataCollector(model_vars={"Population": population})`

The population function could return the number of agents of each species as a dictionary (e.g. `dict = {"1": 7, "2": 3, "3": 9})` and the resulting Pandas dataframe could have columns Population1, Population2, and Population3. Obviously it is possible to calculate these data using agent reporters instead of model reporters, but given the maximum number of agents in my model (16000 for 200 steps) this quickly makes the resultant dataframe exceedingly large.

I don't know if this suggestion fits in with the general feeling of how mesa ought to work (perhaps I'm missing something really obvious about collecting data!), but it would be a very useful addition if so.

**Comment by jackiekazil** [comment]
RE: library -- You are welcome. :-) 

RE: suggestion -- not sure if I understand or not. 
Would something like this work for you? 
```
        
    def __init__(self, height, width, species_types)
        .... 
        
        # species_types = {"cats": 3, "dogs": 2, "birds": 1}
        dc_dict = {}
        
        for species in species_types: 
            dc_dict[species] = lambda m: self.count_type(m, species_types[species])
        
        self.dc = DataCollector(dc_dict)
        ... 
  ```

If not, then can you share your code, so I can understand better?

**Comment by jackiekazil** [comment]
I am closing this, because there is a lack of info. There maybe something here. Things that might be here if someone was inspired... 
1. An example that illustrates what I proposed?
2. Something explicit in core that does what @prototaxites proposed? 
 🤷‍♀
