### ISSUE TITLE
Stop server when using Jupyter notebook?

### ISSUE THREAD

**Issue by zhiyzuo** [projectmesa/mesa#407]
How can I stop a `ModularServer` when using it in Jupyter notebook? I am following the Advanced Tutorial [here](http://mesa.readthedocs.io/en/latest/tutorials/adv_tutorial.html#changing-the-agents).

**Comment by clmerlos** [comment]
Usually to stop the ModularServer I press ctrl-c. This stops run.py which calls ModularServer. I believe the equivalent to ctrl-c in Jupyter notebook is either "Ctrl-m i" which interrupts the kernel (that is, the sole letter "i" after "Ctrl-m") or pressing "I" twice works as well.

[Source](https://stackoverflow.com/questions/17561212/is-there-an-equivalent-to-ctrlc-in-ipython-notebook-in-firefox-to-break-cells-t)

**Comment by zhiyzuo** [comment]
@clmerlos Thanks for the information but I was thinking about is it possible just to stop the process underlying `server.lauch()`, instead of killing the entire notebook.

Would you say using scripts would be better, when using the visualization of Mesa?

**Comment by clmerlos** [comment]
I would say running from terminal is better. For example, I have run the visualization from terminal, edited some python code, saved the file, and the changes appeared after refreshing the browser. (without having to type "python file.py" in terminal after every minor change) . 

Like I mentioned before ctrl-c would end the viz process, close the browser socket, etc.

**Comment by zhiyzuo** [comment]
Thanks. I will stick with scripts and terminal then.
