### ISSUE TITLE
[FIXED] Error with Batchrunner.py

### ISSUE THREAD

**Issue by Vasco09** [projectmesa/mesa#411]
If you are using mesa 0.8.1, the module batchrunner might be outdated. It was giving me an issue when using it (something with fixed_parameters) and to fix it you just need to go [here](https://github.com/projectmesa/mesa/blob/master/mesa/batchrunner.py), click on [RAW](https://raw.githubusercontent.com/projectmesa/mesa/master/mesa/batchrunner.py) and then substitute that text for the one you have in your old batchrunner.py file (open it with notepad, delete everything and paste it -> You may find this file under C:\ProgramData\Anaconda3\Lib\site-packages\mesa ).

Hope this helps.
Vasco C.

**Comment by clmerlos** [comment]
Alternatively you can uninstall mesa and reinstall from source by running the following:
`pip install git+https://github.com/projectmesa/mesa`
This reverts to the github version, which is 0.8.0.
You can check which mesa version you have installed by running `pip show mesa`
Note: Running `pip install mesa==0.8.0` if you currently have 0.8.1 keeps the outdated batchrunner.py

**Comment by jackiekazil** [comment]
Thank you for relabeling the ticket! That is helpful to us! <3 <3 <3
