### ISSUE TITLE
Slow ContinuousSpace

### ISSUE THREAD

**Issue by JamesArruda** [projectmesa/mesa#412]
When using Mesa for its `ContinuousSpace` simulations with many agents and many steps take a while to run. Reducing the run time is valuable to me for performing Monte Carlo analyses and the like. Looking at the profiling, it appears that most of the time is spent in `get_distance` (I ran this for 100 steps on the Boids example):

              3018122 function calls in 4.453 seconds  
    
       Ordered by: internal time
    
       ncalls  tottime  percall  cumtime  percall filename:lineno(function)
       136798    1.017    0.000    2.259    0.000 space.py:561(get_distance)
       146798    0.670    0.000    1.186    0.000 linalg.py:2014(norm)
        10000    0.261    0.000    4.423    0.000 <ipython-input-20-2c3c5a099d5f>:86(step)
    ....
        10000    0.184    0.000    2.548    0.000 space.py:524(get_neighbors)

This issue is being submitted according to the contribution guidelines that asks for tickets to be made for items that will be a PR. I have a proposed solution that'll be up as a PR.

**Comment by Corvince** [comment]
I think the speedup from your PR is quite impressive

**Comment by dmasad** [comment]
Merged!
