### ISSUE TITLE
Visualization Server: Sidebar missing in Edge browser

### ISSUE THREAD

**Issue by Corvince** [projectmesa/mesa#415]
As the title suggests for some reason the sidebar is missing in Edge. Don't know if this has any real relevancy for mesa or if it is an issue with bootstrap, but I just noticed this and wanted to drop a note.

**Comment by clmerlos** [comment]
This might be an Edge Issue. You can change `webbrowser.open(url)` from ModularVisualization line 334 to `webbrowser.get('chrome').open(url)` or some other browser such as 'firefox'.

**Comment by TaylorMutch** [comment]
It looks like this is an Edge with `jQuery` and Edge. I am looking into this.

**Comment by TaylorMutch** [comment]
@Corvince thank you for bringing this up. I will be submitting some fixes.

**Comment by TaylorMutch** [comment]
@Corvince please checkout #436 and see if this issue can be resolved with it's merge.

**Comment by TaylorMutch** [comment]
Closed #415.
