### ISSUE TITLE
Blinking Visualization

### ISSUE THREAD

**Issue by narc98** [projectmesa/mesa#416]
Hello.  I'm hoping that others are having this issue as well but I'm having a problem now (on my model and the "wolf-sheep" one) where the entire grid flashes when refreshing between each step.  I know that this didn't happen on my code or the example previously and am curious if it's maybe some sort of incompatibility with newer browser versions (I've tested Win10 with Chrome 62.0.3202.62 and Firefox 56.0.1, flickering is less pronounced in Ubuntu versions of same two browsers)?  I didn't test in Edge because I have this problem too (https://github.com/projectmesa/mesa/issues/415).  I don't see this issue in the forest fire, wealth model, or civil unrest to name a few.    

Here is a video showing what I'm talking about.  You can see that the default simulation is choppy, but not as clean as I remember it being.  The model appears to be okay with very small numbers of agents, and then unusable at higher numbers.  I don't have video evidence, but am certain that this used to not be the case and would love to know if anyone else is seeing this issue?  

Video (unlisted on YouTube): https://youtu.be/OzQjoJNAzHU

Thanks much,
Nate

**Comment by TaylorMutch** [comment]
@narc98 What version of Mesa were you using that experienced this issue? I seem to be unable to recreate the blinking visualization you recorded. Note that #415 should be resolved at this point as well on Mesa's `master` branch.

**Comment by jackiekazil** [comment]
Because of the lack of activity on this ticket. I am going to assume this is no longer an issue and close it out.
