### ISSUE TITLE
[Bug Report] Torus adjustment check in Grid class problem

### ISSUE THREAD

**Issue by Moody1021** [projectmesa/mesa#420]
It seems like a torus adjustment is not being made in Grid class in move_agent or _place_agent. Stack trace and code that shows problem can be referenced in a [mesa googlegroups](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/projectmesa/KUltKSC3MKg) thread.

**Comment by TaylorMutch** [comment]
Closing now that #429 is merged.
