### ISSUE TITLE
[Enhancement] Include fixed parameters in Batchrunner.get_model_vars_dataframe()

### ISSUE THREAD

**Issue by Corvince** [projectmesa/mesa#422]
Hey all,

I really come to like the mesa included Batchrunner. However, I also want to keep track of the fixed parameters I used for the simulation run. Maybe others feel the same so I added a `include_fixed` option to the Batchrunner.get_model_vars_dataframe() function. Feel free to use my branch or even merge it.

Best
Vincent

**Comment by TaylorMutch** [comment]
Closing as #423 has been merged.
