### ISSUE TITLE
How to host visualization?

### ISSUE THREAD

**Issue by msradam** [projectmesa/mesa#426]
Hi, 
I was able to create a simulation and view it on a browser via importing a server.py and calling server.launch(). However, I would like to host the fully functional simulation on the web and allow others to access it, perhaps via Heroku? Is there any way I can do that?

**Comment by dkrichards86** [comment]
Mesa's server implementations use [Tornado](http://www.tornadoweb.org/en/stable/index.html) as the underlying web server. You should be able to treat it like you would any other web app in Python.

I haven't used Heroku, so I can't speak to that specifically.

**Comment by msradam** [comment]
Thanks, so how would I treat it as a web app? Let's say I have model.py, server.py, and run.py (a basic model), where would I access the Tornado code? I've taken a look at the source code in ModularVisualization but I'm assuming I don't need to alter it.

**Comment by dmasad** [comment]
Deploying as a web app isn't officially supported, though it is on the to-do list. Šimon Podhajský wrote some notes on how to deploy a model with Heroku, which you can read on the Mesa list-serv [here](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/projectmesa/IAnrBEIGFKs/fPcCkwD1CQAJ). However, that doesn't address ensuring that either all users are seeing the same model state or each user launches a new model instance; and I don't think we really even know what kind of security a public-facing deployment would need.

**Comment by msradam** [comment]
Hi, thanks! I was able to host the app on Heroku [here](https://carceral-contagion.herokuapp.com/) but it only shows the basic Grid and not the visualization or any of its options. 

When clicking 'step', nothing happens, though I notice these specific errors in the Chrome debugger:
![image](https://user-images.githubusercontent.com/19861960/32997685-26e737ca-cd61-11e7-8dc1-a208a9522f0a.png)

Any ideas on how to fix this?

**Comment by shippy** [comment]
You can fix the display failure by merging in PR #421 :) @dmasad is correct that this doesn't address the fact that Mesa only runs one simulation, but fixing the socket hard-coding would allow for (at least trying out) the one-containerized-deployment-per-visitor model.

**Comment by TaylorMutch** [comment]
@msradam Please try install `mesa` via git and see if you can now run via Heroku - https://github.com/projectmesa/mesa.git

**Comment by TaylorMutch** [comment]
Closing this issue unless folks run into issues hosting `mesa`.
