### ISSUE TITLE
Network Topology

### ISSUE THREAD

**Issue by dkrichards86** [projectmesa/mesa#428]
Are there any network topology implementations currently in development? It seems like a few were started, but none of them ever came to fruition.

For reference, see https://github.com/projectmesa/mesa/issues/15, https://github.com/projectmesa/mesa/pull/388 and https://github.com/projectmesa/mesa/tree/network

**Comment by cauemello** [comment]
I am working on #388. There are some pending requested changes, but I
intend to finish.
The code is working. Have you tried it?

**Comment by dkrichards86** [comment]
Hi @cauemello,

I'm about to start work on a model that is reliant on a network topology.  I'm hesitant to build around a branch with pending changes. Do you have a timeline for completion of #388 ? Or do you mind if I take a crack at wrapping it up?

Thanks,
-Keith

**Comment by cauemello** [comment]
Hi @dkrichards86,

#388 is ready for review. Waiting for @jackiekazil.

You are welcome to test the models that use network topology:
boltzmann_wealth_model_network and virus_on_network

**Comment by dkrichards86** [comment]
Thank you for your great work on this!

**Comment by dkrichards86** [comment]
Closing this since #388 was meged into master.
