### ISSUE TITLE
cannot import name 'NetworkModule'

### ISSUE THREAD

**Issue by chenyuyou** [projectmesa/mesa#435]

**Comment by cauemello** [comment]
The latest release (0.8.2) doesn't contain the NetworkModule. While we wait for a new one, you can install the up-to-date code using:
pip install git+https://github.com/projectmesa/mesa.git

**Comment by TaylorMutch** [comment]
Closing unless this becomes an issue in the future. The `NetworkModule` should be available in the next release of `mesa`, barring an unforeseen issues with the release.

**Comment by hannantahir** [comment]
I have tried to install the up to date mesa version from git but still missing NetworkModule.  Any update on this?
