### ISSUE TITLE
[Enhancement] Easier Visualization 

### ISSUE THREAD

**Issue by Corvince** [projectmesa/mesa#441]
Hey there,

I think the mesa visualizations are quite neat, but are a bit clumsy to set up. I don't know what the exact problem was, but when I created my first chart viz I struggled quite a bit. I think this was partly because the set-up is quite un-pythonic. When I finally managed to get it to work, I was underwhelmed. Nothing I couldn't have done with matplotlib in less then 5 minutes. 

Therefore I propose we make the visualization part more Netlogo-ish ready to go and leave the details to be worked out programmatically. My ideas:

1. Create a visualization server with a one-liner (create grid viz by default, model parameters as user-settable)
2. Change limits of user-settable parameters in the visualization
3. Allow to add visualizations interactively (see #440 )
4. Drag-and-Drop visualization elements and save layout
5. Create more default visualization elements (e.g. histograms)

I think this could greatly improve the usability for novice users of mesa. Fine-grain control should of course still be remained as is now, but I see the Viz element more as a playground for the model. I don't want to spend a lot of time with it when I need to use different tools anyway to create publication-ready graphs. 

What you think?

**Comment by rht** [comment]
Solved by the Solara frontend. For custom viz, users just need to use Matplotlib.
