### ISSUE TITLE
Create Mesa packages tab in docs 

### ISSUE THREAD

**Issue by jackiekazil** [projectmesa/mesa#448]
- [x] Create Mesa packages tab in docs & write baseline for how to create a package in Mesa. (@tpike3)
- [x] Create wiki page to list 3rd party packages that folks have written. 
- [x] Make sure there is a link from the mesa packages tab to the list of packages in the wiki. 

... One day, we will have a proper place, but for now, we just don't have the content to justify it.

**Comment by tpike3** [comment]
Complete 

In the docs: https://mesa.readthedocs.io/en/master/packages.html
Wiki page:  https://github.com/projectmesa/mesa/wiki/Mesa-Packages
