### ISSUE TITLE
Minor Syntax fix for space.NetworkGrid class

### ISSUE THREAD

**Issue by BalazsHoranyi** [projectmesa/mesa#449]
Hi there, 
I was going through the `boltzman_wealth_model_network` example and noticed that there was a minor syntax error that was causing it to error out.

    def __init__(self, G):
        self.G = G
        for node_id in self.G.nodes:
            G.nodes[node_id]['agent'] = list()`

should be 

    def __init__(self, G):
        self.G = G
        for node_id in self.G.nodes():
            G.node[node_id]['agent'] = list()`

I'm happy to make a PR if you would like.

**Comment by cauemello** [comment]
Hi, 
Maybe you are using NetworkX 1.X instead of 2.0 version. 
We have updated Mesa code to the new version, which uses G.nodes instead of G.nodes(). You can see it here: https://networkx.github.io/documentation/stable/release/migration_guide_from_1.x_to_2.0.html

Try updating the NetworkX library in your machine.

Thanks for the feedback.

**Comment by jackiekazil** [comment]
@cauemello maybe we should explicitly add the version that to the requirements file? do you want to or should I?

**Comment by cauemello** [comment]
I did it already in requirements.txt:
https://github.com/projectmesa/mesa/blob/master/requirements.txt

**Comment by jackiekazil** [comment]
I see you did. :-) I was looking at this -- https://github.com/projectmesa/mesa/blob/master/examples/boltzmann_wealth_model_network/requirements.txt. 

I guess since networkx is a mesa requirement, we can remove that from the boltzmann reqs?

**Comment by BalazsHoranyi** [comment]
Gotcha, Sorry for not taking a look at the requirements. 
Thanks for the help.

**Comment by cauemello** [comment]
@jackiekazil
I think so, and also from virus_on_network requirements. Can you do this, please?

@BalazsHoranyi
Thank you for the feedback. I’m glad I could help.

**Comment by jackiekazil** [comment]
See #452 ... I started to look at it and it is a bigger clean up. :-)
