### ISSUE TITLE
[Bug report] Setting iterations greater than 1 in Batchrunner has no effect 

### ISSUE THREAD

**Issue by wesselklijnsma** [projectmesa/mesa#454]
If the iteration parameter for a Batchrunner is greater than 1, the model will immediately reach max_steps after one run of a parameter combination. This is because the model is initialised once per parameter combination.  See code below (from run_all() in batchrunner.py):          

```
            for param_values in product(*param_ranges):
                kwargs = dict(zip(param_names, param_values))
                kwargs.update(self.fixed_parameters)
                model = self.model_cls(**kwargs)

                for _ in range(self.iterations):
                    self.run_model(model)
                    # Collect and store results:
```

I think moving the model initialisation to the inner loop would be a solution to this problem. See code below:

```
            for param_values in product(*param_ranges):
                kwargs = dict(zip(param_names, param_values))
                kwargs.update(self.fixed_parameters)

                for _ in range(self.iterations):
                    model = self.model_cls(**kwargs)
                    self.run_model(model)
                    # Collect and store results:
```

**Comment by ericmjl** [comment]
I will concur on this; moving into inner loop solved a problem that I encountered with my batchruns giving identical results and running for order-of-magnitude shorter-than-expected amount of time.

**Comment by ihopethiswillfi** [comment]
I just found out about this issue.
I used the same solution in this PR: https://github.com/projectmesa/mesa/pull/486

**Comment by jackiekazil** [comment]
It looks like this is fixed. Please tell me otherwise if it is not. 
Thank you everyone for your work on this! YAY!
