### ISSUE TITLE
[Feature Request]: Agent data on mouse over visualization

### ISSUE THREAD

**Issue by Moody1021** [projectmesa/mesa#457]
Is it possible to bundle agent data into the web browser side json so that when I mouse over an agent I can view that agent's data? Seems like it would mean adding some more fields to the portrayal method to include data that would only available on a mouse over. And of course javascript code to display that data on a mouse over. I don't know if the performance penalty would be too great? This would be particularly useful in early stages of model debugging and perhaps even later. If performance is an issue, it could be feature invoked only if needed.
Thanks

**Comment by RMKD** [comment]
This seems pretty doable with a second canvas layered over top and and a lookup table to map mouse coordinates back to the agent array. I can put together a pull request.
