### ISSUE TITLE
Is it possible for an agent to know the current model global timestep?

### ISSUE THREAD

**Issue by ericmjl** [projectmesa/mesa#460]
The use case I'm thinking of is this: I have agents stepping through various stages in a model, and I'd like to record the "global" time that one agent moves from one stage to the next. I was thinking of recording this data in the Agent's object definition - is this the recommended way to do so? Or should I do it in the Model object definition?

**Comment by Maarten-vd-Sande** [comment]
Take a look at the docs of [scheduler](https://github.com/projectmesa/mesa/blob/master/mesa/time.py). Maybe you can use the steps/time attribute of your scheduler?

**Comment by WouterVrielink** [comment]
Yes this is possible. I would use the [Datacollector class](https://github.com/projectmesa/mesa/blob/master/mesa/datacollection.py) to report these values.

**Comment by ericmjl** [comment]
Thank you everybody! Issue is solved.
