### ISSUE TITLE
Error using list parametters in a model.

### ISSUE THREAD

**Issue by merinom** [projectmesa/mesa#462]
Hi, using the next code...
...
server = ModularServer(xModel,
                       [grid],
                       "Model x",
                       1, 2, [ 1, 2])
...

The following error is displayed:
     TypeError: unhashable type: 'list'

How can I give a list as a parameter to the server?
Greetings

**Comment by clmerlos** [comment]
You have to convert the list to a dictionary. 
Below is taken from Schilling example:

``` python 
model_params = {
    "height": 20,
    "width": 20,
    "density": UserSettableParameter("slider", "Agent density", 0.8, 0.1, 1.0, 0.1),
    "minority_pc": UserSettableParameter("slider", "Fraction minority", 0.2, 0.00, 1.0, 0.05),
    "homophily": UserSettableParameter("slider", "Homophily", 3, 0, 8, 1)
}

server = ModularServer(SchellingModel,
                       [canvas_element, happy_element, happy_chart],
                       "Schelling", model_params)
```
Another example is like this 

``` python
server = ModularServer(xModel,
[grid],
"Model x",
model_params = dict(key1 = 1, key2 = 2, key3 = [ 1, 2]) )

```

**Comment by merinom** [comment]
That works perfect¡
Thank you very much.
