### ISSUE TITLE
Is anybody considering d3.js for visualization?

### ISSUE THREAD

**Issue by Moody1021** [projectmesa/mesa#470]
I need to get different types of visualization for  my models. I was looking for a rich visualization framework in javascript for that. D3 seems to be such a framework. Is anybody working on hooking up mesa to a d3.js front end? I would be happy to collaborate on that work.
Thanks,

**Comment by cauemello** [comment]
We are using D3 to render network. Have you taken a look at the _virus on network_ example?
https://github.com/projectmesa/mesa/tree/master/examples/virus_on_network

**Comment by jackiekazil** [comment]
@cauemello's example is great.. but I think there is the possibility of so many more examples. Did you have something specific in mind @Moody1021?

**Comment by Moody1021** [comment]
The network example was great. If I understand the doc and the code, what I have to do to get d3 visualization is to create a javascript module for my visualization. What I am hoping to do is use various visualization schemas from d3 for my modeling. I'll try getting that going and see if that gives me all the capability I need. 
Thanks

**Comment by jackiekazil** [comment]
@Moody1021  .... 💯 to what @cauemello said! Please keep us informed! Also, we accept PRs back and would love to incorporate generic visualization components back into Mesa!  

For now I am going to close this issue.
