### ISSUE TITLE
[Bug Report] Chart not correctly resetting

### ISSUE THREAD

**Issue by joekroese** [projectmesa/mesa#473]
After being reset once, the chart visualisation element is not properly reset for any further resets. It will correctly do the first simulation and correctly adapt to one reset. However it then repeats past values for all subsequent runs.

This can easily be seen by changing the 'Number of agents' in the virus_on_networks example. Note that by the second run, the number of agents in the chart will not add up to the number of agents in the parameters.

Simulation with 100 nodes with chart displaying correctly (no reset):
![1-correct](https://user-images.githubusercontent.com/7649772/36644537-b5acaf6e-1a53-11e8-83c1-8170d3883b68.png)

Simulation with 10 nodes (after reset from previous simulation):
![2-incorrect-after-reset](https://user-images.githubusercontent.com/7649772/36644550-d541abcc-1a53-11e8-994e-c74cd5d00f87.png)

**Comment by cauemello** [comment]
Hi @joekroese, 
This was fixed in PR #438. But, unfortunately, the correction is out of release 0.8.3.
For now, we can wait for release 0.8.4 or install mesa directly from github using: 
pip install git+https://github.com/projectmesa/mesa.git

**Comment by cauemello** [comment]
Hi @jackiekazil,
Do we have a date for release 0.8.4?

**Comment by jackiekazil** [comment]
@cauemello I will get that out in the next week or two! :-) Closing for now, but will reference in a release ticket so folks can follow for updates.
