### ISSUE TITLE
[Bug Report] appearance of grass in wolf-sheep model

### ISSUE THREAD

**Issue by tethig** [projectmesa/mesa#474]
Small issue, but I've noticed, when running the wolf-sheep example with grass enabled, that the grass appears black and obscures the sheep. I believe I have fixed this in the corresponding server script.

I made the changes in my fork, but reading the contrib guidelines I've opened this issue first. I presume I should also create a new branch before making the pull request? I am sorry: I am still learning GitHub etiquette. Many thanks for your work.

**Comment by tethig** [comment]
Also noted width/height entered into CanvasGrid in wrong order in model.py. Fixed as above. None of this is core mesa.

Trying to understand intermittent fault with server runs in which sheep recover from population=0. Working to make this behaviour reproducible and wonder if anyone else has seen.

**Comment by jackiekazil** [comment]
RE: Learning github --  🎊 WELCOME!!!  🎊
 
RE: Grass issue --  @tethig are you the same as @janusd or are you two different people? I wrote in PR #475 that I think the issue might be with the grass. If you are NOT the same person, can you let me know what browser you are having this issue in?  ... browser, version, and Operating system please. 

RE: Second issue -- we try to keep one issue per issue. :-) ... can you break the second comment off into a new issue with more details for further discussion?

**Comment by tethig** [comment]
Hi @jackiekazil,
Thank you!

I am not the same person as @janusd. The grass issue arose on Safari 11.0.3, MacOS 10.13.3. I installed some dependencies via conda - happy to indicate also. I believe the issue was related to a list being passed to ```portrayal["Color"]``` in server.py. It looks like @janusd has addressed this and I will re-test and post back here if any problems persist.

I understand re multiple issues - I will raise those as separate issues.

many thanks for the welcome!
Ben

**Comment by jackiekazil** [comment]
Thank you for providing your versions. I just tested it with the repo and it was fine, but it wasn't fine with the version that is `pip install mesa` ... so this should be fixed the next time we push an update.
