### ISSUE TITLE
Information about capability of MESA for optimization problems

### ISSUE THREAD

**Issue by vaihav** [projectmesa/mesa#487]
Dear Sir/Madam,

I have a disaster resource allocation problem in hand. I wanted to use agent based modeling for this. I am a beginner. I searched and got some information related to JADE which can use agents to perform optimization tasks to achieve results in NP hard problems. I wanted to know can MESA help me in the same as I am more comfortable with python rather than JAVA. Can optimization libraries coupled MESA to solve such problems? How do we do it in MESA is their any tutorial or documentation?

Thank you in advance

Vaibhav

**Comment by jackiekazil** [comment]
Right now there are two basic/potential ways to pair a library with Mesa. This is a gross summary. 

1. Apply functions objects in Mesa... ie apply an optimization function from another library to the agent object to help make their decision. 
2. Create a custom library that creates "pre-made" objects... ie agents that already have optimization built in and you can subclass those. 

You question fits in the first one, and yes, I believe it is possible. 
As you explore the possibility, I would love to learn more about your research and your experience with Mesa to integrate. if you are interested, please fill out this form --- https://docs.google.com/forms/d/e/1FAIpQLSe94Y3gAGNH0LDbHuAP50OhySJrgzvM3iQ7YPF0Zz5_giv8fQ/viewform 

Also, a good place to ask questions is the email list -- https://groups.google.com/forum/#!forum/projectmesa
