### ISSUE TITLE
Update all requirements to most recent versions

### ISSUE THREAD

**Issue by jackiekazil** [projectmesa/mesa#488]
Go this file and update the requirements one by one to the most recent versions and test them with Mesa. 

https://github.com/projectmesa/mesa/blob/master/requirements.txt 

- [ ] setuptools<34
- [ ] numpy
- [ ] pandas==0.17.1
- [ ] jupyter==1.0.0

- [ ] coverage==4.1
- [ ] nose==1.3.7
- [x] tornado
- [ ] flake8==2.5.2
- [ ] tqdm
- [x] networkx==2.1

**Comment by jackiekazil** [comment]
Networkx was done here: https://github.com/projectmesa/mesa/commit/3380f6ced3386b6a93320a166e010dd4cbb45d5e

**Comment by jackiekazil** [comment]
Tornado was/is addressed here: https://github.com/projectmesa/mesa/pull/497/commits/73f153018ded792fb1b5f0026f7bb8af734b599a

**Comment by Corvince** [comment]
This is obsolete now!
