### ISSUE TITLE
Add additional chart types -- bar & pie

### ISSUE THREAD

**Issue by jackiekazil** [projectmesa/mesa#490]
We have line charts, but we should also have bar charts and pie charts
Add some pie and bar charts. Base them off of the way we did line charts OR update our line charts as well.

**Comment by jackiekazil** [comment]
Related: https://github.com/projectmesa/mesa/issues/515

**Comment by digitaldust** [comment]
is there currently any example of barchart in mesa?

**Comment by jackiekazil** [comment]
No. That is why this ticket exists. Were you thinking of adding one? 😃

**Comment by markblack96** [comment]
I'd be interested in helping. Does Mesa interface well with matplotlib and pyplot? Is this basically asking for wrappers for those implementations within Mesa?
