### ISSUE TITLE
[BUG] !Important: Patches/colors are not working

### ISSUE THREAD

**Issue by jackiekazil** [projectmesa/mesa#494]
Wolf sheep in Chrome... 
<img width="516" alt="screen shot 2018-03-30 at 10 52 34 am" src="https://user-images.githubusercontent.com/166734/38141964-866c628e-3408-11e8-951f-16d1daf3b79f.png">

Wolf sheep in Safari...
<img width="521" alt="screen shot 2018-03-30 at 10 52 24 am" src="https://user-images.githubusercontent.com/166734/38141966-87c9c1bc-3408-11e8-8aeb-4e2f6630fb8b.png">

This might be related, but it was working after I looked into this... https://github.com/projectmesa/mesa/pull/475

**Comment by jackiekazil** [comment]
@TaylorMutch ... if you have any time, can you take a look at this? Hoping it is a quick fix for you since you are more familiar with the front end code.  (If not, I will try to do this over the weekend as well.)

**Comment by jackiekazil** [comment]
Is the model broken? If checked then yes, it might not be working properly...
- [ ] Schelling
- [ ] bank_reserves
- [ ] boltzmann_wealth_model
- [ ] boltzmann_wealth_model_network
- [ ] color_patches
- [ ] conways_game_of_life
- [ ] epstein_civil_violence
- [ ] flockers
- [ ] forest_fire
- [ ] hex_snowflake
- [ ] pd_grid
- [ ] shape_example
- [ ] sugarscape_cg
- [ ] virus_on_network
- [ ] wolf_sheep

**Comment by jackiekazil** [comment]
sugarscape - uncertain

**Comment by jackiekazil** [comment]
color patches.... 
<img width="417" alt="screen shot 2018-04-01 at 9 39 50 pm" src="https://user-images.githubusercontent.com/166734/38179808-4dcaa910-35f5-11e8-8ae8-477aa493ebd8.png">

**Comment by jackiekazil** [comment]
schelling... 
<img width="401" alt="screen shot 2018-04-01 at 9 35 25 pm" src="https://user-images.githubusercontent.com/166734/38179811-58fc6e18-35f5-11e8-872c-65318cff99a7.png">

**Comment by jackiekazil** [comment]
flockers -- is not working, but I don't think it is related to this bug.

**Comment by jackiekazil** [comment]
shape example doesn't have color and it is supposed to... 
<img width="671" alt="screen shot 2018-04-01 at 10 10 05 pm" src="https://user-images.githubusercontent.com/166734/38180288-7a861922-35f9-11e8-93b8-077efd1b3b8d.png">

**Comment by jackiekazil** [comment]
Before I dig further into this, I found myself looking at GridDraw.js. 
@dkrichards86 I noticed you [were working on adding supports for gradients](https://github.com/projectmesa/mesa/commit/76a35c73254a6adef844428e4507c085bd59b628#diff-cb77756d078136ca5b2ae3ad1eb7feec), as I was trying to figure out what happened. 

Any insight into what happened would be helpful. So far, I haven't been able to identify the bug so far Hoping you have some great insight. :-(

**Comment by dkrichards86** [comment]
@jackiekazil I see colors in each of the examples above. Have you ruled out browser caching?

**Comment by dmasad** [comment]
These are all looking okay for me in both Chrome and Safari.

**Comment by jackiekazil** [comment]
@dkrichards86 @dmasad ... I have started contributing to this project from two different computers. I can't remember which computer I was on when I filed this issue and I never thought of making a note of it. I checked it on my 13 inch macbook pro. I will check it on my 15 inch tomorrow, when I have it in front of me.  It seems to work find for me on the 13 inch.

**Comment by Shermjj** [comment]
If anyone else is getting this error, clear your browser's cache. This is a caching issue.

**Comment by jackiekazil** [comment]
Thank @Shermjj!
I just did a check on all the models. They seem to be all working, except for flockers. I suspect that is a different issue though. So, I am going to open a ticket just for that.
