### ISSUE TITLE
Issue Running Examples

### ISSUE THREAD

**Issue by jmcnabb3** [projectmesa/mesa#495]
I am learning to use Mesa for a project so I am working through some of the examples but I get this error when trying to run it:
C:\Users\jmcnabb3\Desktop\mesa_tutorial\Wolf_Sheep\wolf_sheep\resources\mesa-master\mesa-master\examples\wolf_sheep>python3 run.py
Traceback (most recent call last):
  File "run.py", line 3, in <module>
    server.launch()
  File "C:\Python3\lib\site-packages\mesa\visualization\ModularVisualization.py", line 317, in launch
    startLoop = not tornado.ioloop.IOLoop.initialized()
AttributeError: type object 'IOLoop' has no attribute 'initialized'

I was looking through some past issues and couldn't find any method to resolve this.

**Comment by clmerlos** [comment]
what version of tornado are you running?
type ``` pip freeze |grep tornado to check```

If your version is greater than 5, try running "pip install tornado>=4.0,<5.0" to downgrade tornado version. 

New version of tornado breaks mesa see #493

**Comment by jmcnabb3** [comment]
I checked and realized I had tornado 5 installed so I rolled back to tornado 4. Everything works perfectly now!
