### ISSUE TITLE
[Feature Request] Allow cells to have properties

### ISSUE THREAD

**Issue by Moody1021** [projectmesa/mesa#501]
Is it possible to create a space class that will allow cells to have properties? Is there any easy way to do this with a metaclass? Suggestions appreciated. Thanks!

**Comment by jackiekazil** [comment]
When you say properties, can you be more explicit? I ask, because Python has something called properties and I don't know if you are explicitly asking for that or if you want attributes.

**Comment by Moody1021** [comment]
Sorry for the delay in responding. We were traveling for a couple of weeks.

What I am looking for is attributes. In particular, the basic notion in abms is mostly that the background (space) is featureless. The agents have rules / policies / attributes. The kind of modeling that I am doing is expanding that notion a bit. The context can have attributes / features. One of those features is memory, i.e., what has happened in that space. Potentially, this memory may have a time constant over which it degrades. 

I have implemented a framework for doing this. Here is what I have so far:
- Dimensions - a multi dimensional space along the lines of space. At init, the number of dimensions is specified. The way I keep track of cells allows me to add attributes  to the cells. I have not fully implemented this or tested this yet.
- dynspace (dynamic space) used for movement calculations in n dimensions. It is a subclass of dimensions. 
- realspace - that keeps coordinates as real numbers but is a subclass of dynspace. 
I have done some real basic testing. And the framework seems to be working so far. I have not done any performance analysis, cleanup, testing framework,  etc. yet.

Right now I am trying to get the graphics to work a bit more easily.

At some point, when the code is a bit more polished, I could ship it to you to review  to see if you think it would be helpful to add to mesa.

**Comment by quaquel** [comment]
This is now supported in MESA 3.
