### ISSUE TITLE
Add examples to Travis

### ISSUE THREAD

**Issue by dmasad** [projectmesa/mesa#509]
The formal tests test the basic functionality of each component individually, but not how they are used together in practice. The examples do use these components together, and additionally provide an example of the API. 

At the moment, verifying that changes to the core code don't break the examples is done by running the examples by hand. It would be helpful to automate this, and have Travis call a script that sets up and runs each example. Unlike the tests themselves, this wouldn't need to check the actual model output, only that the examples can be launched and run without throwing errors.

**Comment by dmasad** [comment]
Yes, I think so.

**Comment by djmitche** [comment]
This will also require being able to run examples without a browser attached.  That might be easiest with an option to the `mesa` command, a la #242.

**Comment by djmitche** [comment]
> This will also require being able to run examples without a browser attached. That might be easiest with an option to the mesa command, a la #242.

Turns out that's kind of useless for anything but testing (since it just spews websocket messages)
