### ISSUE TITLE
ModularVisualization not working on tutorial example

### ISSUE THREAD

**Issue by Tobimaru** [projectmesa/mesa#512]
Hi,

I'm trying out the tutorial example with the spatial MoneyModel in a jupyter notebook in Mesa 0.8.3. I have combined the definitions of MoneyAgent, MoneyModel and the visualisation server into a single notebook. But when I launch the server I get the following error message:

File "/usr/local/anaconda3/envs/mesa/lib/python3.6/site-packages/mesa/visualization/ModularVisualization.py", line 196, in on_message
    if not self.application.model.running:
AttributeError: 'MoneyModel' object has no attribute 'running'

Does the ModularServer not work in a jupyter notebook?

**Comment by jackiekazil** [comment]
Looks like you are missing `self.running = True`.
