### ISSUE TITLE
Create an example of Geo-Mesa for the examples folder

### ISSUE THREAD

**Issue by jackiekazil** [projectmesa/mesa#513]
Fun for someone that is interested in this space. 
This awesome thing started by @Corvince -- https://github.com/Corvince/mesa-geo

It would be great to... 
1. create an example in the examples folder.
2. Figure out how we can extend it further.

If you need to find potential examples to create, look at Netlogo's example folder for ideas. (You can also search for geospatial models in Netlogo on the internet. Each Netlogo model has their own web page.)

**Comment by jackiekazil** [comment]
@ljwolf this is the work that I mentioned. I haven't looked at it much. I would like to make it an official thing, but looking at it now, it looks more developed than I first thought. So, I would love your input on some possible next steps for making Geo Mesa more operational and making people aware of it. @Corvince is pretty accessible as well.

**Comment by ljwolf** [comment]
Sure. 

There are a few things I can think of that'd probably be helpful:

1. implement agents from geopandas geodataframes, which are like pandas plus geometries. This shouldn't be too difficult thanks to the existing [geojson method](https://github.com/Corvince/mesa-geo/blob/master/mesa_geo/geospace.py#L72).
2. consider fast precomputed topological relations in PySAL, or use geopandas directly for the spatial queries. Geopandas already uses the spatial index and for some types of spatial relations, PySAL is faster than the `rtree` library.

**Comment by Corvince** [comment]
Hey @ljwolf thanks for your feedback. 

1. Yes, the idea of that method was to create agents from any GeoJSON source, so creating them from geopandas should already work
2. Agreed, I think the current implementation tries to reinvent the wheel at a lot of places. I think in the long run switching over to geopandas for handling the spatial data will be much easier. I have never used PySAL before so I don't know their spatial model but I would guess PySAL and geopandas should work together? So users could use PySAL for their analysis while GeoMesa stores its data in a geopandas DataFrame?

**Comment by ljwolf** [comment]
OK! If there is interest, I can definitely help with this change. 

1 .OK; I think that's pretty straight forward, then! I can help implement this as needed, but I do not have the same amount of time for this stuff now that the scipy sprints are over :smile:  
2. I'm referring to [fast precomputation/caching of things like spatial adjacency graphs](http://ljwolf.org/notebooks/perftesting_graphs.html). This would give a which is currently being done using rtrees. This can make a big difference for even moderately-sized data, on the order of a hundred or a thousand observations and, depending on how you're using the spatial operations, it could save a ton of computation time. Or, if you're already building on geopandas... you could use that spatial index and not have to maintain your own for on-demand recalculations?

Let's move this discussion over to Corvince/mesa-geo.
To keep from going off topic from **this** issue, a full example is definitely needed help me get my head around how mesa-geo is expected to be used & where I can help.

**Comment by rht** [comment]
Closing because you can find the examples in the mesa-geo repo, https://github.com/projectmesa/mesa-geo/tree/master/examples.
