### ISSUE TITLE
Interactively add visualizations 

### ISSUE THREAD

**Issue by jackiekazil** [projectmesa/mesa#537]
This was started in #440. Hoping that this gets completed and added one day. I am adding a ticket to make sure that it is not forgotten about. 

Please refer to #440 for where this left off. If you continue this work, please update this ticket. 

/cc @Corvince

**Comment by Corvince** [comment]
I updated [my branch](https://github.com/Corvince/mesa/tree/InteractiveViz) to the latest version of mesa without a problem. At this moment I am waiting for some feedback on how to finish this :-)

**Comment by jackiekazil** [comment]
Because there are some front-end changes happening, I am going to close this ticket out for now.
