### ISSUE TITLE
[Help Wanted] Example of multi-agent interaction

### ISSUE THREAD

**Issue by kyleweise** [projectmesa/mesa#538]
Hello all,

As a first foray into Python / Agent-based Modeling, I'm trying to recreate an ABM I stumbled upon in a paper that consists of two agents, Patches and Cells. Cells can be of type Normal, Mutated, or Cancerous, and Patches can be of type Tissue or Blood Vessel. According to the rules of the model, the Cells need to check the nutrient level of of the Patch they are on, and if no nutrients exist, die with some probability. I am a bit lost on how to check an attribute of a Patch agent while within the logic for a Cell agent. Most of the examples I've looked into contain only 1 agent, so are not very helpful for this kind of thing. Are there any examples of this type of multi-agent interaction? I would greatly appreciate any help.
 
[Here](
https://pdfs.semanticscholar.org/5ea4/00d10d39d67fc5e148e3bf17d07a7e1f657e.pdf) is the paper for those interested. 

Thanks!

-Kyle

**Comment by clmerlos** [comment]
[WolfSheep](https://github.com/projectmesa/mesa-examples/tree/master/examples/WolfSheep) is an good example of multi-agent system.

**Comment by jackiekazil** [comment]
+1 to WolfSheep. Ty @clmerlos! 

For now I am closing this. Please reopen if you need additional assistance or post to the listserv https://groups.google.com/forum/#!forum/projectmesa
