### ISSUE TITLE
Help wanted: An example for multi agent on a network[different types of agents]

### ISSUE THREAD

**Issue by wanghaoLisa** [projectmesa/mesa#540]
The two types of agents all stay within the graph network. One type of agent is the node, its location is fixed (the node in the figure below). Another type of agent is moving along the links and nodes, it moves across the system along the network (the white dots in the figure below). The example "Virus on network" is one type of agent on the network, and "WolfSheep" is multi-agent, but the agent does not move on the network. Do you have an example of multiple types of agent on a network?
![image](https://user-images.githubusercontent.com/12989147/40294406-c79d005e-5d18-11e8-8e87-5bbdd42affbf.png)

**Comment by dmasad** [comment]
I think the easiest way to do it is to create two agent classes:  one mobile and one fixed. The fixed agents get placed at nodes and stay there (as in the Virus on a Network example); the mobile agents also get placed at starting nodes, but can move around using the [`NetworkGrid.move_agent` method](https://github.com/projectmesa/mesa/blob/master/mesa/space.py#L798). Does that make sense?

**Comment by jackiekazil** [comment]
@wanghaoLisa please reopen/resubmit or use the email list if you have further questions -- https://groups.google.com/forum/#!forum/projectmesa
