### ISSUE TITLE
Different datatypes for User Settable Parameters

### ISSUE THREAD

**Issue by Shermjj** [projectmesa/mesa#541]
My model takes a list of values for its parameters. I can't seem to figure out a good way of implementing the data visualization's user settable parameters to provide a list of values to my model. Anyone mind giving me some guidance?

**Comment by dmasad** [comment]
Take a look at the pd_grid model: it has an example of using the [`choice` parameter in the visualization](https://github.com/projectmesa/mesa/blob/master/examples/pd_grid/pd_grid/server.py#L15), which gives you a drop-down menu of options.

**Comment by jackiekazil** [comment]
@Shermjj -- please reopen if you need additional assistance or post to the list serv https://groups.google.com/forum/#!forum/projectmesa

**Comment by Shermjj** [comment]
@dmasad @jackiekazil 
Thanks for your advice. Since my parameter was a list of integers, I was thinking more of being able to use multiple individual number inputs and then passing on the resulting parameters as a list. (As opposed to having to specify the parameters explicitly).
