### ISSUE TITLE
Exemple to Mesa: Animate the output

### ISSUE THREAD

**Issue by dsmello** [projectmesa/mesa#547]
I don't now if i post right.

After basic tutorial you had : 
for model.py :
`
# model.py
from mesa.space import MultiGrid
from mesa import Agent, Model
from mesa.time import RandomActivation
import random

class MoneyModel(Model):
    """A model with some number of agents."""
    def __init__(self, N, width, height):
        self.num_agents = N
        self.grid = MultiGrid(width, height, True)
        self.schedule = RandomActivation(self)
        # Create agents
        for i in range(self.num_agents):
            a = MoneyAgent(i, self)
            self.schedule.add(a)
            # Add the agent to a random grid cell
            x = random.randrange(self.grid.width)
            y = random.randrange(self.grid.height)
            self.grid.place_agent(a, (x, y))

    def step(self):
        self.schedule.step()

class MoneyAgent(Agent):
    """ An agent with fixed initial wealth."""
    def __init__(self, unique_id, model):
        super().__init__(unique_id, model)
        self.wealth = 1

    def move(self):
        possible_steps = self.model.grid.get_neighborhood(
            self.pos,
            moore=True,
            include_center=False)
        new_position = random.choice(possible_steps)
        self.model.grid.move_agent(self, new_position)

    def give_money(self):
        cellmates = self.model.grid.get_cell_list_contents([self.pos])
        if len(cellmates) > 1:
            other = random.choice(cellmates)
            other.wealth += 1
            self.wealth -= 1

    def step(self):
        self.move()
        if self.wealth > 0:
            self.give_money()
`
And for run.py
`# run.py
from model import MoneyModel
import numpy as np
import matplotlib.pyplot as plt

model = MoneyModel(50, 10, 10)
for i in range(20):
    model.step()

agent_counts = np.zeros((model.grid.width, model.grid.height))
for cell in model.grid.coord_iter():
    cell_content, x, y = cell
    agent_count = len(cell_content)
    agent_counts[x][y] = agent_count
plt.imshow(agent_counts, interpolation='nearest')
plt.colorbar()

# If running from a text editor or IDE, remember you'll need the following:
plt.show()
`
Now we will made this new file : 
`
# animator.py
import matplotlib.pyplot as plt
import matplotlib.animation as animation

def animator(data):
	fig = plt.figure()
	ims = []
	for add in data:
		ims.append((plt.pcolor(add),))
	im_ani = animation.ArtistAnimation(fig, ims, interval=100, repeat_delay=300, blit=True)
        # If you want save the animation
	# im_ani.save('im.mp4')
	plt.show()
`
--------=========--------

Now we need to change the run.py file to : 
`# run.py
from model import MoneyModel
import numpy as np
import matplotlib.pyplot as plt
from animator import animator

frame = []

model = MoneyModel(50, 10, 10)
for i in range(20):
	model.step()
	agent_counts = np.zeros((model.grid.width, model.grid.height))
	for cell in model.grid.coord_iter():
		cell_content, x, y = cell
		agent_count = len(cell_content)
		agent_counts[x][y] = agent_count
	frame.append(agent_counts)

animator(frame)
`
Now you had a easy way to see a video, from each step of your model.

**Comment by dmasad** [comment]
That looks cool! Just FYI -- you can have GitHub preserve code formatting by using the "<> insert code" button at the top of the edit window, or by marking the code with three ``` marks (see also: https://help.github.com/articles/creating-and-highlighting-code-blocks/)

**Comment by jackiekazil** [comment]
I want to encourage you to submit the animation as a pull request to the examples folder. If you need help with this, please let us know and someone will walk you through the process. Here is more info: https://github.com/projectmesa/mesa/blob/master/CONTRIBUTING.rst
