### ISSUE TITLE
AttributeError: type object 'IOLoop' has no attribute 'initialized'

### ISSUE THREAD

**Issue by bagjohn** [projectmesa/mesa#551]
After navigating to the desired folder where we want to download the repository :
`git clone https://github.com/projectmesa/mesa.git`

Now navigating to a random example e.g. :
`cd mesa/examples/Schelling`

the example should run by typing :
`python3 run.py`

For some reason I get an unexpected error :
`AttributeError: type object 'IOLoop' has no attribute 'initialized'`

And it's true because : 
1. in visualization/ModularVisualization.py in the class ModularServer in def launch() there is 
`startLoop = not tornado.ioloop.IOLoop.initialized()`
2 but in tornado/ioloop.py in the class IOloop there is no attribute initialized!

Any help?

**Comment by bagjohn** [comment]
Fixed that at least temporarily by adding this to tornado/ioloop.py in class IOloop:

def initialized() :
        return False

**Comment by bagjohn** [comment]
A friend fixed it, it's a tornado version problem. Downgrade with this command: pip install tornado==4.5.3

Solution from [here](https://github.com/jupyter/notebook/issues/3407)

**Comment by jackiekazil** [comment]
@bagjohn Ty for this! This is fixed in our next release. Hopefully no one will run into this problem again!
