### ISSUE TITLE
Mesa run command is not working

### ISSUE THREAD

**Issue by jackiekazil** [projectmesa/mesa#553]
```mesa run``` is not working. Not sure why. 

It was added in #522. Reported not working in #552, #542.

**Comment by djmitche** [comment]
@justinhastings have you "installed" mesa into the virtualenv?  Something like `pip install mesa` or (as it looks like you're working in the git repository) `pip install -e .` in the "Mesa" directory.

**Comment by mciancia** [comment]
FYI While I had the same problem in the past, looks like everything is working after installing latest version from github

**Comment by djmitche** [comment]
I'm guessing it was a missed "install" step.  It's possible for lots of things to work if you only install the requirements and not the app itself -- but command-line tools is not one of those things.

**Comment by jackiekazil** [comment]
`pip3 install -e .` was the solution. Ty @djmitche! Closing.
