### ISSUE TITLE
Create a docker container with mesa to deploy easily

### ISSUE THREAD

**Issue by jackiekazil** [projectmesa/mesa#558]
A few people have requested functionality to deploy Mesa more easily -- specifically docker has been requested. Please post if you have questions or if you want to "own" this.

**Comment by alee** [comment]
Would be happy to contribute to this but I'm not too familiar with Mesa yet. What should be bundled in a Mesa docker image besides a basic Python 3 container that has mesa pip installed already? Jupyter notebooks, GIS tools?

**Comment by dmasad** [comment]
Thanks for offering! 
1. The only GUI Mesa uses is via the browser. I'm not familiar with containerization at all; but if it can run a local server that the user can access in the browser, it should work fine.

2. At the moment, I don't _think_ anything is necessary besides Python + Mesa's dependencies. However, if anyone with specific use-cases for containers need something else, hopefully they'll say so here.

**Comment by jackiekazil** [comment]
Sorry for the delay in our response. This look great. Hoping to have a chance to test soon. 
Is this something you would interested in submitting to the main repo as a PR?

**Comment by alee** [comment]
Sure, I'd be happy to though should the Dockerfile that lives in this main repo be tailored for Mesa developers vs. Mesa model developers?

**Comment by wincdev** [comment]
Hi,
I would like to work on this task. Can you assignees this task to me?

**Comment by rht** [comment]
I'd say if it is possible to run the GUI in a Jupyter notebook, then it can be run+edited without any setup via Colaboratory / mybinder.org / Azure notebook.

**Comment by MichaelJCole** [comment]
Hi, was there a reason not to use the official python image as a base?

https://hub.docker.com/_/python

**Comment by alee** [comment]
The official Python image would have been fine, though I've been happy with the phusion base image for reasons mostly outlined here:

https://github.com/phusion/baseimage-docker

That said, it's probably unnecessary for the phusion image's additional services just to run / develop a mesa model. 

It's straightforward to create additional tagged images that mirror the latest Debian-based Python images.. we've got a dockerhub automated build set up at https://github.com/comses/docker-mesa so if you'd like to submit a PR for that please feel free!

**Comment by MichaelJCole** [comment]
@alee There is an attack pattern that works like this:

1) Create useful public library/package/docker image
2) People use the package
3) Update package dependencies to include malicious code

Here's two recent examples: 

https://snyk.io/blog/malicious-code-found-in-npm-package-event-stream/
https://www.cryptoninjas.net/2019/06/06/npm-thwarts-malware-attempt-helps-komodo-protect-13-million-in-crypto-assets/

I can't use base Docker images that aren't from "official" repos.  It's not personal :-)

**Comment by jackiekazil** [comment]
@MichaelJCole - and I just realized that I left my comment in the other repo, which wasn't helpful since it doesn't relate to this project. 😂 😂 😂 

Ty for starting this convo. I agree with you. Any interest in submitting a PR? If not, any interest in submitting a ticket that clearly defines what needs to happen (as opposed to being buried in comments)?

**Comment by MichaelJCole** [comment]
Hi Jackie, ok yes.  I submitted a PR that shows how to use Mesa w/ Docker.  It covers 2 use cases:

1) Packaging a model inside an image for "static" deployment.
2) Mounting a model inside an image using docker compose "at run-time"

My understanding is that by packaging Mesa in Pip, and then having models require it, there isn't a need for a specific "Mesa Docker Image".  We can cover the two use cases above with these examples.

If I'm missing something, PM or email me michaelcole a t michaelcole d o t c o m

**Comment by rht** [comment]
Closing since we now have a functioning Dockerfile and docker-compose.yml.
