### ISSUE TITLE
Agent "Zooming" Too Fast In Simulation Despite Correct Step Count

### ISSUE THREAD

**Issue by seifely** [projectmesa/mesa#559]
(Copied from the ProjectMesa Google group let me know if more info needed!)

> I have a single-agent simulation and a grid-world in which the agent uses two navigational strategies to move around. One of these strategies is reactive (it sets a goal, then step by step moves towards it) and the other is deliberative (it plans ahead using many epochs of A* algorithm navigation then moves there). My problem is, whilst reactive works fine, A* zooms madly on the simulation. A* is designed to take a step to plan ahead, which provides a vector of x,y coordinates the agent should follow as a path, then take each of these a step at a time. Instead, even though my code is telling me the agent is taking the true number of steps it should do, the agent zips along super fast along its designated path instead of moving at a regular 'step-by'step' pace. Which really throws off my external timer!
> 
> There are of course a lot of other components to this system, but hopefully this is enough information for someone to provide some help. Am I cramming too much into one step, and that's why the simulation is playing catch-up or something? The A* planner does take a second or two in some cases as it sometimes generates thousands of planning steps in one go. Do I just not have a sufficient understanding of how the mesa.time module works?

My current working branch of this project can be found at the master [here](https://github.com/seifely/mesa_boxworld); merged it recently so it would be easier for someone helping to sort through. **The agent should be run on 'navigation_mode=2' for it to use the A* algo, which I have set as the branch default.** If any more description or comments are needed please let me know and I can add some!

[EDIT]: Added note, please ignore the astar_alt.py and astar_nav.py files in the branch, they're basically my testing and playground files to mess about in and don't actually contribute to the system!

**Comment by dmasad** [comment]
I'm looking through the code, and the problem isn't jumping out at me either. However, I'm also not clear how to run it -- are you installing it as a package, or running it locally? Can you post instructions on how it's intended to be run and where you're seeing the problem, and I'll try to replicate?

To make sure I understand the problem -- the model is showing that  single step has elapsed, but the agent takes multiple discrete steps.

**Comment by JamesArruda** [comment]
It does look like you are cramming too much into one step.  If you look here: 

https://github.com/seifely/mesa_boxworld/blob/master/mesa_boxworld/mesa_boxworld/agents.py#L1229

you'll automatically pass that `if` check since you just found a path. That means your agent will have planned and moved in one model step. If you change that to an `elif`, then your agent should wait until the next step to make a move.

**Comment by seifely** [comment]
That seems to have cleared things up a little - thank you so much!
