### ISSUE TITLE
Multiprocessing doesn't seem to work

### ISSUE THREAD

**Issue by vahuja4** [projectmesa/mesa#567]
**Describe the bug**
I have REST calls in my agent's `step()` function which are blocking in nature. And it seems that when a particular agent issues the REST call, the execution of other agents is also stalled.

**Expected behavior**
Since mesa has multiprocessing support, other agents should also continue to execute their respective `step()` functions.

**To Reproduce**
Just add a blocking call in the agent's step function and see if that prevents other agent's from executing their logic.

**Additional Context**
I am using `RandomActivation()` because I want all the agents to be woken up once per epoch.

**Comment by dmasad** [comment]
At the moment, Mesa's multiprocessing support is limited to batch runs, where multiple model instantiations can be run in parallel. Within a single model, the agents are run sequentially.
