### ISSUE TITLE
Error with Tornado IOLoop - please help!

### ISSUE THREAD

**Issue by seifely** [projectmesa/mesa#569]
**Describe the bug**
My code was functioning a day ago, and then I had a hardware failure and have had to set up a brand new environment so I'm running into some bugs on my end with running the code again. Specifically, whereas my server was running yesterday, I'm now getting this error:

```
` File "C:/Users/grace/Documents/GitHub/mesa_boxworld_updated/mesa_boxworld/run.py", line 3, in <module>
    server.launch()

  File "C:\Users\grace\Anaconda3\envs\mesa_boxworld\lib\site-packages\mesa\visualization\ModularVisualization.py", line 317, in launch
    startLoop = not tornado.ioloop.IOLoop.initialized()
AttributeError: type object 'IOLoop' has no attribute 'initialized'`
```

**To Reproduce**
Unfortunately, I'm not quite sure what I've done to cause this. It's undoubtedly my fault as I have been moving code around and understand this may be the result of a pathing problem or something accidentally being deleted. Maybe even in how I've set up my new project interpreter (I'm using **PyCharm**) Is there someone out there who knows what this error is? And how I might fix it?

**Comment by dmasad** [comment]
Check the version of Tornado that you have installed. I *think* this is an issue with Tornado 5.0 and above, and you need to install version 4.5.3 in your Mesa environment. (If you do have tornado <5.0 or downgrading it doesn't help, let us know).

**Comment by seifely** [comment]
This perfectly did the trick - thank you!
