### ISSUE TITLE
[ENH] Let Agents move on their own! 

### ISSUE THREAD

**Issue by Corvince** [projectmesa/mesa#581]
The question is as old as agent-based modeling. Who moves agents on a grid? The grid itself or the agent themselves? Why not both!

**What's the problem this feature will solve?**
Let agents directly call grid functions

**Describe the solution you'd like**
Imagine a simple agent wanting to move to an empty spot. With the current implementation it would call something like

    agent.model.grid.move_to_empty(agent)

A more intuitive way would be to simply call

    agent.move_to_empty()

(Notice also the missing agent argument) 

**Additional context**
I thought about a way how to achieve this and put my solution into a [jupyter notebook](https://gist.github.com/Corvince/424b9972063c3e85f6c8035241ff3882). 
What do you think about this?

**Comment by Maarten-vd-Sande** [comment]
I think wrappers seem okay. If you want to make use of the function `get_methods` I think it is better to call the method on the class, instead of on each agent.

**Comment by Corvince** [comment]
I actually think the get_methods is way to hackish to include in mesa. I just thought maybe someone has a better idea. 

One alternative would be for mesa to provide some Agents by default and users could just subclass them. For example a GridAgent that already has some default grid functions (as wrappers). I guess that would be much cleaner and came up before somewhere else.

**Comment by Maarten-vd-Sande** [comment]
Probably even more hackish, and less desired:
```
def check_for_gridfunc(Cls):
    class NewCls(Cls):
        def __getattribute__(self, attr):
            # try to call the method on the class
            try:
                return super(NewCls, self).__getattribute__(attr)
            except AttributeError:
                pass

            # if that didn't work, try to call on the grid
            try:
                return self.model.grid.__getattribute__(attr)
            except AttributeError:
                pass

            # if that failed, raise error
            raise AttributeError(f'\'{Cls.__name__}\' object has no attribute \'{attr}\'')
    return NewCls



@check_for_gridfunc
class Agent:
    ...
```

We make a decorator 'check_for_gridfunc', which we can give to the Agent class. This overwrites the getattribute, first checking whether attribute exists in the class itself, then whether it exists in the model.grid, otherwise raising an error.

It is probably possible to put it inside the actual Agent as well with some adaptations.

**Comment by Corvince** [comment]
I think wrappers are indeed the way to go.

If someone wants to work on this, a collection of re-usable agents could be a good idea
