### ISSUE TITLE
Network Visualization for Agents on the Network Nodes

### ISSUE THREAD

**Issue by DrTao** [projectmesa/mesa#591]
**What's the problem this feature will solve?**
It looks as though the current Network Visualization shows the base network but cannot show the agents.

**Describe the solution you'd like**
I'd developed a workable extension for Swarm (GeoGraphs) a while back that solved this nicely.  

We showed agents as circles smaller than the nodes (relative radii are parms), where each agent's pos=(x,y) was centered on the node's center and then each agent's pos varied by a specified radius and tiny random scatter so they were not all right on top of one another.  We also allowed different colors/types of agents to display at different quadrants / directions from the node, so we could see the relative size of the blue-agent crowd on each node, etc.  

See image below, where base network nodes are white and agents are smaller and with colors.

![viz-agents-on-network-nodes__geographs_dibble_2001](https://user-images.githubusercontent.com/2191986/46445794-90749e00-c746-11e8-9d6f-45a52b294267.PNG)

**Additional context**
This could very greatly extend the power of mesa in cool ways.   :)

**Comment by quaquel** [comment]
#2430 reimplements the network visualization to now use ax.scatter. It does not by default do this offset for multiple agents, but it would be quite easy to build a custom visualization by using the existing matplotlib network visualization as a template.
