### ISSUE TITLE
Model doesn't auto-run

### ISSUE THREAD

**Issue by Albertolopezs** [projectmesa/mesa#592]
Hi, i'm starting learning mesa and python, and i wanted to create my first simulation from modifying mesa's tutorial example. I have already written the self.running commando on the Model.__init__() but it takes no result.
Would appreciate help, thanks.

```

#model.py
import random 
from mesa.datacollection import DataCollector
from mesa.space import MultiGrid
from mesa import Agent, Model
from mesa.time import RandomActivation 

#We define Model class
class KillModel(Model):
    """Una simulacion de un coliseo"""
    def __init__(self, N, width, height):
        
        
        self.num_agents = N
        self.grid = MultiGrid(width, height, False)
        self.schedule = RandomActivation(self)
        #Create agents
        for i in range(self.num_agents):
            a = KillAgent(i, self)
            self.schedule.add(a)
            #Add the agent to a random grid cell
            x = random.randrange(self.grid.width)
            y = random.randrange(self.grid.height)
            self.grid.place_agent(a ,(x, y))
            
            self.datacollector = DataCollector(
            model_reporters = {"Gini" : "compute_gini"},
            agent_reporters = {"Life": "life", "Killed": "killed"})
        self.running = True   
    def step(self):
        
        self.datacollector.collect(self)
        self.schedule.step()
    

    
#We define Agent class
class KillAgent(Agent):
    
    def __init__(self, unique_id, model):
        super().__init__(unique_id, model)
        self.life = True
        self.killed = 0
    
    def move(self):
        possible_steps = self.model.grid.get_neighborhood(
            self.pos,
            moore=True,
            include_center=True)
        new_position = random.choice(possible_steps)
        self.model.grid.move_agent(self, new_position)
            
    
    def kill(self):
        cellmates = self.model.grid.get_cell_list_contents([self.pos])
        if len(cellmates) > 1:
            enemy = random.choice(cellmates)
            p1 = random()
            p2 = random()
            if p1>p2:
                enemy.life = False
                enemy.killed +=1
                return
            else:
                self.life = False
                self.killed +=1
                return
        else:
            return
        
    def step(self):
        self.move()
        if self.life == False:
            return
        
        self.kill()
    
    def compute_gini(model):
        agent_wealths = [agent.killed for agent in model.schedule.agents]
        x = sorted(agent_wealths)
        N = model.num_agents
        B = sum( xi * (N-i) for i,xi in enumerate(x) ) / (N*sum(x))
        return (1 + (1/N) - 2*B)       


#server.py

from mesa.visualization.modules import CanvasGrid
from mesa.visualization.ModularVisualization import ModularServer
#Chart
from mesa.visualization.modules import ChartModule
#Number of agents slider
from mesa.visualization.UserParam import UserSettableParameter

#Define portrayal
def agent_portrayal(agent):
    portrayal = {"Shape": "circle", "Filled": "true", "r": 0.5}

    portrayal["Color"] = "blue"
    portrayal["Layer"] = 0
    return portrayal       
n_slider = UserSettableParameter('slider',"Numero de Agentes",100,2,200,1)

grid = CanvasGrid(agent_portrayal, 10, 10, 500, 500)

chart = ChartModule([{"Label": "Gini",
                        "Color": "Black"}],
                   data_collector_name="datacollector")
server = ModularServer(KillModel,
                      [grid,chart],
                      "KillModel",
                      {"N" : n_slider, "width": 10, "height":10})
```

**Comment by dmasad** [comment]
We'll try to take a look at this ASAP. In the mean time -- can you select your code in the example above and format it all as as code (see the example here: https://help.github.com/articles/creating-and-highlighting-code-blocks/)? Alternatively, you can upload your code as a gist and link to it: https://gist.github.com/

**Comment by Albertolopezs** [comment]
Done. Would appreciate your help asap, i need to know my mistake.

**Comment by Corvince** [comment]
Hey there, 

sorry for the inconvenience of your model not running. I am not completely sure what your expected behavior is and what is happening. I am just guessing here: But is the code above all in a single file? And you are trying to run it by calling `python filename.py`? In that case you should simply add the line 
```Python
server.launch()
```
at the end of your file. 

You can also take a look at the examples to find out how other models seperate into different files and are run.

There are also some programming errors in your code, but you should be able to work these out from the error messages. For example, you have the model reporter "compute_gini", but have not defined this function (and I think it makes no sense for your model). Also you call `random()` instead of `random.random()` (I guess)

Hope that helps

**Comment by Albertolopezs** [comment]
It's in the same file because i'm working on a notebook.
It has the computer_gini function because of the example, but i dont need it. The problem is with the auto run, when i press start/step it doesn`t work, the model can't step into.

**Comment by Albertolopezs** [comment]
it's in the same file because i'm working on a Notebook, that's why i dont import diferent files.
Computer_gini is a methid of the example, i don't use it in this simulation.
The problem is when I launch the server, I have no response when i press Start/Step button, getting this log from the notebook

> Interface starting at http://127.0.0.1:8535
Socket opened!
{"type":"get_params"}
{"type":"reset"}
{"type":"get_step","step":1}

**Comment by Albertolopezs** [comment]
I've found the error in the code, in the kill method I had not init p1 and p2. It's solved


thanks.
