### ISSUE TITLE
Update documentation: Breaking changes in "patch" version 0.8.4

### ISSUE THREAD

**Issue by arthur-e** [projectmesa/mesa#595]
**What's the problem this feature will solve?**
When upgrading from 0.8.3 to 0.8.4, manual shuffling of agents in the Scheduler, which worked in 0.8.3, [no longer works since agents are now tracked via an OrderedDict](https://github.com/projectmesa/mesa/commit/73fa7a056f45f80833ff80c5f7e170520ec0393d).

That is, the following which worked under 0.8.3, no longer works, i.e., **the changes in 0.8.4 are breaking changes and should NOT have been included as a "patch" version, [according to semantic versioning.](https://semver.org/)**

```py
# No longer a valid way to extend BaseScheduler
class RandomSingleActivation(BaseScheduler):
    def step(self):
        random.shuffle(self.agents) # Randomly shuffle agents
        self.agents[0].step() # Select first and activate
        self.steps += 1
        self.time += 1
```

**Describe the solution you'd like**
At the very least, the documentation should be updated to reflect this new, backwards-incompatible behavior; two places relevant to this issue that need to be updated are:
- https://mesa.readthedocs.io/en/master/apis/time.html
- https://mesa.readthedocs.io/en/master/_modules/mesa/time.html#BaseScheduler

**Additional context**
**Better yet, "patch" version 0.8.4 should actually be made into a minor version update: 0.9.**

**Comment by Corvince** [comment]
Hey, thanks for the bug report!

Since mesa is still version 0.x.y rules 4 and 7 of semantic versioning apply

>    4. Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.
>    7. Minor version Y (x.Y.z | x > 0) MUST be incremented if new, backwards compatible functionality is introduced to the public API [...]

Notice the x > 0. Therefore I don't see a conflict with semantic versioning here. 

That being said, you are still correct that the documentation needs to be updated! @jackiekazil @dmasad Couldn't we update the audo-generated docs automatically whenever code changes?

Regarding your code, try:
`random.shuffle(self._agents)`

which should shuffle the keys of the OrderedDict

**Comment by alee** [comment]
This is a bit of a side issue, but how about offering the option for ordered or randomized iteration in the public `BaseScheduler` API?

**Comment by EwoutH** [comment]
To read more on our current versioning approach, for anyone interested:
- https://github.com/projectmesa/mesa/discussions/1909
