### ISSUE TITLE
Importing agent attributes and variables from .csv in mesa

### ISSUE THREAD

**Issue by MPakravan** [projectmesa/mesa#598]
In some applications of agent based modeling agents will be assigned attributes based on observations or experiments, or social surveys. For example, researcher may visit a village and observe certain behaviors among villagers. He/She records such attributes (let's say family sizes, number of cattle each family has, and trade records of cattle owners). In order to develop an agent based model of such trade behavior researcher needs to import recorded data in Mesa in a nonrandom form. Let's say each row of data is one family and each column of data includes recorded data related to each attribute like family size, number of cattle, traded cattle, etc. 

The question is how we can define agents and their attributes in Mesa using a csv file. Currently, all the available examples of Mesa randomly generate and assign agents' attributes.

Below is the example of such request from another person:
https://stackoverflow.com/questions/51507567/creating-agents-from-a-csv-file-in-mesa-python [https://stackoverflow.com/questions/51507567/creating-agents-from-a-csv-file-in-mesa-python](url) 

Thank you @jackiekazil

**Comment by tpike3** [comment]
@MPakravan thanks for pointing out the stackoverflow question. I provided an answer. 

I also have two models which read in datafiles file to create my agent population. The one which is a little more readable is [(https://github.com/tpike3/Kibera)]. If you look at Main.py and slumagent.py. You will see several pickle objects read in and then translated to agent attributes. Will rok similar with a .csv you just need the data to become an object. ( I like using the pandas library for reading in csv typically) 

The other one is at [https://github.com/tpike3/Libya-CoalitionFormation], if you go into the libya_coalition folder and look at Groups.py, I read in .csv files to make an agnet population (but my coding was not as good then so it is a little hard to decipher)
