### ISSUE TITLE
How to import a map as space

### ISSUE THREAD

**Issue by Albertolopezs** [projectmesa/mesa#599]
Hi, i'm looking for a way to use a map of a city as space to move the agents, but i don't know if any feature of mesa could help me, anyone could bring me help?

**Comment by jackiekazil** [comment]
Hello @Albertolopezs! @Corvince created Mesa-geo (https://github.com/Corvince/mesa-geo). There maybe some additional work that you need to do to make that work for your use case. And we (Mesa and Mesa-geo) are always looking for PRs and issues to improve. 

If Mesa-geo does not fill your need, then there is no library or functionality that I can think of .... well. However, streets are a network and you could try a model using Mesa/NetworkX functionality, but that is a stretch and messy. I can't imagine that you would make a Mesa Network work more quickly than you would get Mesa geo to work. 

For now, I am going to close this ticket and consider it "resolved".
