### ISSUE TITLE
model visualization not working in tutorial example

### ISSUE THREAD

**Issue by vklimaj** [projectmesa/mesa#605]
Hi,

I'm trying to run the basic visualization in section 4.1 of the tutorial. 
When I try to run this I get an error.

Code:
```
def agent_portrayal(agent):
    portrayal = {"Shape": "circle",
                 "Filled": "true",
                 "Layer": 0,
                 "Color": "red",
                 "r": 0.5}
    return portrayal

grid = CanvasGrid(agent_portrayal, 10, 10, 500, 500)
server = ModularServer(MyModel,
                       [grid],
                       "My Model",
                       {100, 10, 10})
server.launch()
```

Error:

```
  File "<ipython-input-72-47efee48f9bf>", line 8, in <module>
    {100, 10, 10})

  File "/anaconda3/lib/python3.6/site-packages/mesa/visualization/ModularVisualization.py", line 276, in __init__
    self.reset_model()

  File "/anaconda3/lib/python3.6/site-packages/mesa/visualization/ModularVisualization.py", line 294, in reset_model
    for key, val in self.model_kwargs.items():

AttributeError: 'set' object has no attribute 'items'
```

Important to note: I made one change to the tutorial code, which is shown above. I placed {100,10,10} in a dictionary to avoid an error that had previously been showing up ( **"__init__() takes from 3 to 5 positional arguments but 7 were given"**).
 But it seems like this change could have introduced the new attribute error I'm having now.

Any ideas on what to do?

Thanks!

**Comment by tpike3** [comment]
I think the issue is you are trying to instantiate a dictionary as a list. You need to add your keys which are the parameters N (number of agents), height and width. 
{"N": 100, "width": 10, "height": 10}

**Comment by vklimaj** [comment]
Thanks for catching that!
Although now that I fixed it, another error is showing up. Not sure how to address this:

```
File "/anaconda3/lib/python3.6/site-packages/mesa/visualization/ModularVisualization.py", line 302, in reset_model
    self.model = self.model_cls(**model_params)

TypeError: __init__() got an unexpected keyword argument 'N'
```

**Comment by tpike3** [comment]
So the arguments "N", "width", and "height" need to match your class Money Model inputs: 
class MoneyModel(Model):
    """A model with some number of agents."""
     def __init__(self, N, height, width):
------------------------
{"N": 100, "width": 10, "height": 10}

If the parameter inputs do not match you will get an error.

**Comment by jackiekazil** [comment]
I am going to assume that this is wrapped up. Please reopen if you are still having issues.
