### ISSUE TITLE
Image in Readme not showing up on PyPI

### ISSUE THREAD

**Issue by jackiekazil** [projectmesa/mesa#606]
When I did the release this evening, I noticed that the image in the ReadMe that is pulled into the PyPI description text is now showing up on PyPI. Not sure why. 

See: https://pypi.org/project/Mesa/ 

Screenshot -- you can see the alt text.
<img width="798" alt="screen shot 2018-11-26 at 11 25 57 pm" src="https://user-images.githubusercontent.com/166734/49058592-ad6f9f80-f1d2-11e8-82e0-5966e86f116a.png">

**Comment by rht** [comment]
I just checked https://pypi.org/project/Mesa/. The image displays correctly.
