### ISSUE TITLE
ReadTheDocs latest

### ISSUE THREAD

**Issue by dmasad** [projectmesa/mesa#611]
My understanding was that the readthedocs [`latest`](https://mesa.readthedocs.io/en/latest/) branch was supposed to point to the most recent release. For some reason, though, it seems very out of date, and rebuilding it doesn't update to the newest version.

Does anyone know what options need to be set where to have it build off of the correct version?

For now, I've changed the readme links to point to the [`master`](https://mesa.readthedocs.io/en/master/index.html) branch  to keep people pointed in the right direction

**Comment by jackiekazil** [comment]
The default view if you visit read the docs is master. You can see that setting here: https://readthedocs.org/dashboard/mesa/advanced/. 

So, if we link to master and default view is set to master. Do we even have to worry about the latest? We could disable it in fact. 

Thoughts?

**Comment by Corvince** [comment]
I have been reading up on this on readthedocs and `latest` and `master` should actually be the same. However, I would recommend to point to `stable` which (with tagged releases) should automatically refer to the latest release (and probably to the version users have installed from PyPi). All builds should happen automatically if the webhooks between readthedocs and GitHub are set correctly (see [webhooks on rtd](https://docs.readthedocs.io/en/stable/webhooks.html) and my comment in #684 )

**Comment by rht** [comment]
Closed via #1810.
