### ISSUE TITLE
Create template for README.md for examples

### ISSUE THREAD

**Issue by jackiekazil** [projectmesa/mesa#62]
To complete this... 
- [ ] Create general template for example READMEs
   - brief description
   - how to demo the example; how do I run this
   - anything else that is important
   - citations?
- [ ] Implement one -- the forest fire
- [ ]  Create tickets for all the other Readme files to be created (or create them) :-)

**Comment by jackiekazil** [comment]
@dmasad -- should we follow the netlogo model of doing this? (Or other suggestions)

**Comment by dmasad** [comment]
This should also be a documentation page.

**Comment by jackiekazil** [comment]
Looking to get this kicked out this week or next.

**Comment by jackiekazil** [comment]
@dmasad question... Do we want to do copyright on these? If so, what does that look like for general ones that already exist AND ones that might exist in the future? And what does copyright mean?  I am not sure that I want to use that language.... b/c according to wikipedia -- "legal right created by the law of a country that grants the creator of an original work exclusive rights for its use and distribution" <--- Could that cause issues / legal conflict with examples that have been submitted back to Mesa?

**Comment by ReblochonMasque** [comment]
Does changing the license to MIT solve the problem?

**Comment by jackiekazil** [comment]
No. Right now, the whole repo is under Apache 2.0, but w/ Apache, there is still copyright. 
The question is... what is copyright when a model is a "common" model? The person who wrote the code? What happens when multiple people write the code? (Does that make sense?) Maybe we should move this conversation to the google group?

**Comment by ReblochonMasque** [comment]
Good idea.

**Comment by dmasad** [comment]
Readme template being tested out in the [model-rewrite branch](https://github.com/projectmesa/mesa/tree/model-rewrite/examples).

**Comment by jackiekazil** [comment]
closing in favor of #190

**Comment by jackiekazil** [comment]
omg... black rock is done!
