### ISSUE TITLE
'MoneyModel' object has no attribute 'running'

### ISSUE THREAD

**Issue by martin-c-harvey** [projectmesa/mesa#627]
If you create a MoneyModel for the Introductory Tutorial and then re-use it for the Advanced Tutorial while trying out the Visualization in a browser you encounter an error ''MoneyModel' object has no attribute 'running'' when attempting to Step or Start the model from the browser. This error is only visible when running the code from, for example, Visual Studio (and not from Jupyter).
NB: Aha. I've just been looking at someone else's error and was puzzled. They have self.running=True in the MoneyModel __init()__. I got to where I was because I did not try out the Batch Run; It's not something I was thinking of using.

```
ERROR:tornado.application:Uncaught exception in /ws
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\tornado\websocket.py", line 494, in _run_callback
    result = callback(*args, **kwargs)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\mesa\visualization\ModularVisualization.py", line 196, in on_message
    if not self.application.model.running:
AttributeError: 'MoneyModel' object has no attribute 'running'
```

This error is not visible when running in Jupyter because it happens in the Visualization Server. So what you see in Jupyter is something like this. Once you receive the get_step, nothing further happens:
```
Interface starting at http://127.0.0.1:8521
Socket opened!
{"type":"get_params"}
{"type":"reset"}
{"type":"get_step","step":1}
```

The browser window running the visualization will perform Reset correctly, however, Step and Start both cause this error. It is fixed if you initialise the parent Model with super().__init()__ as follows...

```
class MoneyModel(Model):
    """A model with some number of agents."""
    def __init__(self, N, width, height):
        super().__init__()   # this fixes the problem 
        self.num_agents = N
```

**Expected behavior**
When I press Start or Step with tutorial code I expect the model to animate and not to fail.

**To Reproduce**
Create the MoneyModel from the Introductory Tutorial and run it in the Advanced Tutorial. NB: As above: don't do the Batch Runner bit so that you omit self.running=True!

**Suggested Fix**
Assuming the diagnosis is correct (I'm fairly new to Python, Jupyter etc...) then update the tutorial (and any other related documentation). I am, however, not 100% sure I understand how '__new__()' and '__init__()' are used in Python. It seems quite different to C#. My instinct says that calling '__init__()' on the parent object should always happen.

**Comment by rht** [comment]
By interpolating from the rest of the examples, it seems that the solution should instead be to set `self.running = True`. `super().__init__()` is never called (which probably should have for all of them).

Another alternative is to use `hasattr(self.application.model, 'running')`.

**Comment by zmanx** [comment]
I've run into a similar roadblock by simply following the tutorial and adding in the scheduler lines "self.scheudle.add(a)" PyCharm Community Edition complains that "object has no attribute 'schedule'"

**Comment by josse7cz** [comment]
Hi! I please you. I have the same error. Where can I edit this setting? https://replit.com/@JosefJanda/MesaTuto#MoneyModel.py

**Comment by rht** [comment]
@josse7cz you put the `self.running = True` in the wrong place. It should be inside the `__init__` of `MoneyModel`, not `MoneyAgent`.

**Comment by josse7cz** [comment]
Yes! It work!

class MoneyModel(Model):
    """A model with some number of agents."""

    def __init__(self, N, width, height):
        self.num_agents = N
        self.grid = MultiGrid(width, height, True)
        self.schedule = RandomActivation(self)
        **self.running = True**
