### ISSUE TITLE
Class Money Model code

### ISSUE THREAD

**Issue by n-abm** [projectmesa/mesa#629]
**Describe the bug**

class MoneyModel(Model):
    """A model with some number of agents."""
    def __init__(self, N):
        self.num_agents = N
        # Create agents
        for i in range(self.num_agents):    # param must be (self.num_agents + 1)
            a = MoneyAgent(i, self)

**Expected behavior**

**To Reproduce**

**Additional context**

**Comment by Corvince** [comment]
Hmm, looks like something went wrong with this issue?? Maybe posted too early? Please feel free to edit your issue, otherwise I will close it in the next days.

NB You can use the "insert code" button to format code appropriately (or use back ticks: `` directly)
