### ISSUE TITLE
How can I configure the visual elements' rendered positions?

### ISSUE THREAD

**Issue by kumom** [projectmesa/mesa#630]
I was trying to plot a chart using the ChartModule without the grid (because there is really no spacial dimension in the model). But the chart was placed in the lower part of the page with the upper part left blank. By a quick look of the source code I did not find any place I can configure the positions rendered for the chart. Did I miss anything?

**Comment by Corvince** [comment]
Every visualization element should be displayed in a row with the same order you specify for the server.

What you describe, however, is a bug that should already be resolved in the latest version on GitHub, but has not been released to PyPi yet. See #612 and #615 

So either upgrade to the GitHub version or wait for the next release 👍
