### ISSUE TITLE
DataCollector.get_agent_vars_dataframe()

### ISSUE THREAD

**Issue by kumom** [projectmesa/mesa#637]
I am trying to get each agent's opinion at all time steps using data collector. However, I found the returned dataframe is indexed by a tuple `(step, agent_id)`, which makes it hard to retrieve data if I want to plot agent_0's opinion of all time steps.

[The workaround I found](https://stackoverflow.com/questions/44012099/creating-a-dataframe-from-a-dict-where-keys-are-tuples) is using `reset_index()`.

Can we change the indexing of the dataframes?

**Comment by Corvince** [comment]
Does either of the ones below work? Or are you asking for something different?

```python
df.loc[(slice(None), id_you_want), :]
df.xs(id_you_want, level='agent_id')

```
Source https://pandas.pydata.org/pandas-docs/stable/user_guide/advanced.html

**Comment by kumom** [comment]
Thank a lot! Both work except the second one should be `df.xs(id_you_want, level='AgentID')`

**Comment by Corvince** [comment]
Great! And thanks for the correction
