### ISSUE TITLE
Viewing multiple agents within the same cell in MultiGrid

### ISSUE THREAD

**Issue by mmerrittsmith** [projectmesa/mesa#639]
**What's the problem this feature will solve?**
I would like to be able to view all of the agents within a state at the same time when using MultiGrid. Currently the only way to do this visually is using the mouseover tooltip. You can, of course, output the data as to where each agent is, but I believe a more visual approach might prove beneficial.

**Describe the solution you'd like**
I would like each cell to have a sort of invisible grid within it, where each of the individual agents may be placed so all of them can be viewed at the same time.

**Additional context**
I've written this functionality already, and will be creating a pull request referencing this shortly.

**Comment by quaquel** [comment]
solved via #2430 and even before
