### ISSUE TITLE
NetworkGrid not correct output

### ISSUE THREAD

**Issue by ammarqureshi** [projectmesa/mesa#653]
**Describe the bug**
NetworkGrid is not graphing the nodes properly.

**Expected behavior**

@jackiekazil  @dmasad I am trying to model a smart grid, the consumer(black circle) connecting to the supplier(purple circle) which connects to the generator(red circle). 

I have a directed graph from consumer-->supplier and supplier-->generator. I graphed it using matplotlib and get the following: 
<img width="602" alt="Screenshot 2019-03-10 at 20 37 40" src="https://user-images.githubusercontent.com/17296281/54091165-864d7000-4374-11e9-9d10-4e06afaec2b3.png">

Which is the correct behaviour, as each consumer points to a supplier and each supplier is pointing to the generator. 

However, this is what I get when I run mesa server: 
<img width="342" alt="Screenshot 2019-03-10 at 20 39 30" src="https://user-images.githubusercontent.com/17296281/54091172-ab41e300-4374-11e9-9086-d2b58b1c4bd3.png">

What i expected was this: 
![Expected Diagram](https://user-images.githubusercontent.com/17296281/54091209-3e7b1880-4375-11e9-9c39-a15a292d8b39.png)

**To Reproduce**

id 0:Generator
id 1:Supplier 1
id 2:Consumer of Supplier id 2
id 3: Supplier 3
id 4: Consumer of Supplier id 3

`      
graph = nx.DiGraph()
graph.add_edges_from([ (1, 0), (3,0), (2,1), (4,3)]) 
`
Am I doing something wrong or is this a bug? If not how can I graph the above expected diagram.

**Comment by Corvince** [comment]
Hey there, 

can you share the code for your model for example as a [gist](https://gist.github.com/)? 

At least it looks like mesa currently does not support directed graph visualizations, which is already something we should work on.

**Comment by ammarqureshi** [comment]
@Corvince I have tried to clone the repo again and tried running the virus_on_network and on the browser I get ```ReferenceError: Can't find variable: NetworkModule```

**Comment by jackiekazil** [comment]
@ammarqureshi  you maybe have to `pip install networkx`

**Comment by jackiekazil** [comment]
@ammarqureshi for now, I am going to close this ticket. 
Please reopen if you are still working though this problem and need help.
