### ISSUE TITLE
class StagedActivation bug: extra 'random'

### ISSUE THREAD

**Issue by prakharmehta95** [projectmesa/mesa#656]
**Describe the bug**
While running the StagedActivation  scheduler, I encounter an
**AttributeError: 'builtin_function_or_method' object has no attribute 'shuffle'**
which leads me to the time.py source code line 178 inside the StagedActivation class

**Expected behavior**
Did not really expect this to go wrong, I pass through all attributes. random is imported at the start of my code. However, a small edit in the time.py file makes my code work properly.

**To Reproduce**
Here is the StagedActivation class, the issue seems to be an extra 'random' written in the source code

class StagedActivation(BaseScheduler):
    ...

    def step(self):
        """ Executes all the stages for all agents. """
        agent_keys = list(self._agents.keys())
        if self.shuffle:
            self.model.random.shuffle(agent_keys)
        for stage in self.stage_list:
            for agent_key in agent_keys:
                getattr(self._agents[agent_key], stage)()  # Run stage
            if self.shuffle_between_stages:
                **self.model.random.random.shuffle(agent_keys)**
_"""This works for my case when I remove the extra random"""_

            self.time += self.stage_time

        self.steps += 1

**Additional context**

**Comment by jackiekazil** [comment]
This was just resolved in #654. I will push a deployment to pypi soon. For now, please use master in the repo.

**Comment by jackiekazil** [comment]
There is a fix for this in the next release. The master branch in the
github repo currently has the fix, which you can update from.
I am aiming to push the release on Sunday.
