### ISSUE TITLE
Push next release to PyPI

### ISSUE THREAD

**Issue by jackiekazil** [projectmesa/mesa#658]
This is what I have for the next release.... 

**Improvements**
* add docker-compose + Dockerfile support #593
* install: Minimize install footprint #614

**Fixes**
* Year update. Happy New Year! #613
* Fixed problem with grid and chart visualization javascript #612 #615
* removed extra" .random" on line 178. #654

**Comment by jackiekazil** [comment]
*Question 1: This feels more like a minor release than a major one. What do you think?*

Is this 0.8.5.1 OR 0.8.6? 
And if we name our major releases, do we also name the minor ones? 
Major ones are cities in Arizona. 

0.8.5 was Kearny. 
All of these issues are currently tagged Lake Havasu City.

**Comment by dmasad** [comment]
This definitely feels like a minor release to me: it cleans up a few bugs, but doesn't add any new features or change the API.

**Comment by Corvince** [comment]
Here are some more things I found

> This is what I have for the next release....
> 
> **Improvements**
> 
> * add docker-compose + Dockerfile support #593
> * install: ~~Minimize install footprint~~ Remove jupyter requirement #614
> * Add Bar and Pie Chart visualization #594 #490 
> * Make models pickleable #582 
>  
> **Fixes**
> 
> * Year update. Happy New Year! #613
> * Fixed problem with grid and chart visualization javascript #612 #615
> * removed extra" .random" on line 178. #654
> * updated requirement for networkx #644 #646 

I think this is not any less major than previous releases AND I think 0.8.5.1 looks unusual. I think in the future we should refer to [semantic versioning](https://semver.org/) to determine what kind of update a release is (also pre 1.0.0 we are free to do more or less anything)

**Comment by jackiekazil** [comment]
Based off of the couple of things that @Corvince highlighted it is a larger release than expected. So, i am now leaning towards 0.8.6. I will submit a PR and close this ticket b/c the PR will supersede this ticket.

**Comment by jackiekazil** [comment]
PR is #665

**Comment by jackiekazil** [comment]
First PR was #665, but then that was closed, b/c I forgot to merge one thing in. 
New PR is #666.
