### ISSUE TITLE
Can you write a demo model about An application of agent-based simulation to knowledge sharing?

### ISSUE THREAD

**Issue by flyfish0087** [projectmesa/mesa#659]
Can you write a demo model about An application of agent-based simulation to knowledge sharing?
https://www.sciencedirect.com/science/article/pii/S0167923608001711
thank you

**Comment by flyfish0087** [comment]
Can you write a demo model about An application of agent-based simulation to knowledge sharing?
https://www.sciencedirect.com/science/article/pii/S0167923608001711

**Comment by flyfish0087** [comment]
Can you write a demo model about An application of agent-based simulation to knowledge sharing?
https://www.sciencedirect.com/science/article/pii/S0167923608001711
thank you

**Comment by dmasad** [comment]
That looks like an interesting project. Is there something specific about it that you think would make a good addition to the example library? Do you know if the original Repast code is available? It looks like the paper is behind a paywall, so it might be difficult for non-academic contributors to access.

**Comment by flyfish0087** [comment]
Hello, I want to know your e-mail address, I can send you the documents.thank you

**Comment by flyfish0087** [comment]
Hello, I want to know your email address. I can send you the document. Thank you


> That looks like an interesting project. Is there something specific about it that you think would make a good addition to the example library? Do you know if the original Repast code is available? It looks like the paper is behind a paywall, so it might be difficult for non-academic contributors to access.

**Comment by dmasad** [comment]
My worry is that a paywalled paper in general might not be the best example. Is there a reason you think it should be included? If you're working on implementing it yourself and having trouble, we'd be happy to try and help.

**Comment by flyfish0087** [comment]
> My worry is that a paywalled paper in general might not be the best example. Is there a reason you think it should be included? If you're working on implementing it yourself and having trouble, we'd be happy to try and help.


My friend's current doctoral thesis needs to be processed using the mesa module. I hope to help him with it, but I am a system engineer. I am not very familiar with this type of modeling, so I want you to help me.

**Comment by jackiekazil** [comment]
That is not something we normally do. There are some books out there and papers where someone can learn about this type of modeling. More than happy to provide some recommendations. 

 Specifically, I would look into this one: https://www.amazon.com/Introduction-Agent-Based-Modeling-Natural-Engineered/dp/0262731894 

For now, I am going to close this ticket.
