### ISSUE TITLE
Wrong examples directory reference in the intro tutorial docs

### ISSUE THREAD

**Issue by sosey** [projectmesa/mesa#670]
**Describe the bug**
I'm running through the intro tutorial and the directory referenced for the boltzmann model didn't exist as listed.  

**Expected behavior**
original text: `examples/Tutorial-Boltzmann_Wealth_Model/requirements.txt`

I couldn't find this directory in the repo, however this location does exist:
`examples/boltzmann_wealth_model`

It might be more clear to also make this an html link in the docs, I can make a PR for this change if it's acceptable.

**Comment by jackiekazil** [comment]
Would love these updates. This went bad when we tried to standardize the naming of projects.

**Comment by jackiekazil** [comment]
This is fixed by #671.
