### ISSUE TITLE
[DISCUSS] Create cookie cutter repo for libraries that work with Mesa

### ISSUE THREAD

**Issue by jackiekazil** [projectmesa/mesa#673]
RE: #360 & #359 - This would be a great contribution, but telling someone to do this can be overwhelming. 

I think it would be good to create a cookie cutter project that stubs out a repo to help them get started with project. 

Twitter has something like this here: https://github.com/twitter/repo-scaffolding 

Thoughts?

**Comment by jackiekazil** [comment]
Paging @Corvince & @tpike3, because of the libraries that you two have built out.

**Comment by quaquel** [comment]
in #2421 this was removed again
