### ISSUE TITLE
Add docs for BatchRunner to support Variable and Fixed Parameter Contribution

### ISSUE THREAD

**Issue by djfurman** [projectmesa/mesa#679]
As a user looking to leverage the latest features for mesa; since #651 has been merged for functionality, documentation should be enhanced to show the usage of this new feature.

**Comment by djfurman** [comment]
Linking in issue #607

**Comment by djfurman** [comment]
Picking this one up

**Comment by jackiekazil** [comment]
Looks like this one has been merged in.
