### ISSUE TITLE
How to keep PyPI up to date

### ISSUE THREAD

**Issue by dmasad** [projectmesa/mesa#69]
Figure out how to update the mesa available on PyPI -- is there a way to synch it to GitHub? Does Jackie need to update it every so often with a new zip file? What's the best practice on that?

**Comment by jackiekazil** [comment]
Travis? http://docs.travis-ci.com/user/deployment/pypi/

**Comment by jiffyclub** [comment]
Most projects only put official releases on PyPI, it's not synced with GitHub development. I generally go through the manual process of setting a release version number, creating a release tag, and generating source and wheel versions of the release to upload to PyPI. There are probably tools for automating that a bit but I haven't looked into them.

**Comment by jackiekazil** [comment]
We will update manually ... #165
