### ISSUE TITLE
(Firefox Only) Visualization Elements Overlap Even When Installing from GitHub

### ISSUE THREAD

**Issue by TAThor** [projectmesa/mesa#690]
**Describe the bug**
I've created a simple model similar to the money model in it's visualization (i.e. a CanvasGrid with a single ChartModule), but if I change the size of the CanvasGrid (from 500x500 to 700x700) then the ChartModule overlaps.  Similarly, if I place two separate ChartModules then they overlap each other.

[#615](https://github.com/projectmesa/mesa/pull/615) is said to fix this issue. However, I uninstalled mesa via pip, and reinstalled from the source (setup.py), and am still experiencing the same problem.

**Expected behavior**
Visualization Elements will be placed in a column without overlap.

**To Reproduce**
Create a server visualization, and try to place two separate ChartModules. They will overlap perfectly. You can also make a CanvasGrid of size 700x700 with a single ChartModule and see my exact issue.

**Additional context**
//I'm using the latest version of Firefox, but I wouldn't think this is the issue. 
**EDIT:** I've just tested the script using Chrome, and it works fine; no overlap. I'm not sure why it doesn't work in Firefox, but it does appear to be browser related.

I'm not sure if I did something wrong trying to install directly from source. All I did was run `python setup.py install` from the mesa directory.

**Comment by Corvince** [comment]
Can't reproduce (with Firefox v60). I guess it is a caching issue. Can you do a "hard" reload of the page with [Ctrl]+[F5] and see if that solves the issue

**Comment by TAThor** [comment]
> 
> 
> Can't reproduce (with Firefox v60). I guess it is a caching issue. Can you do a "hard" reload of the page with [Ctrl]+[F5] and see if that solves the issue

This resolved the issue. Thank you for the help!
