### ISSUE TITLE
Improve Readme documentations

### ISSUE THREAD

**Issue by RaulRC** [projectmesa/mesa#695]
Some typos observed in some of the examples.

**Comment by jackiekazil** [comment]
We have a few tickets open relating to specifics with docs, but nothing related to typos. Would love to have a direct submission, but if you aren't into submitting directly, can you provide a list or copy and paste into google doc and correct with the suggested edits function on, so one could directly see where the errors that you see are without hunting for all of them? 

This would be super helpful.

If you do do this, please reopen this ticket with that content.

**Comment by jackiekazil** [comment]
This ticket is being resolved/worked on in #696.

**Comment by RaulRC** [comment]
Done!
