### ISSUE TITLE
Introductory Tutorial

### ISSUE THREAD

**Issue by taliaborofsky** [projectmesa/mesa#697]
**Describe the bug**
The DataCollector isn't working because the program keeps saying that compute_gini isn't defined

**Expected behavior**
The model should be initiated without errors, and then I should be able to extract data from the data frame
**To Reproduce**
Run Model(50,10,10)

**Additional context**
The part of the code in the class definitions causing problems:

```python
class MoneyModel(agent):
    def __init__(self, N, width, height):
         ...
        self.datacollector = DataCollector(
            model_reporters = {"Gini": compute_gini}, 
            agent_reporters = {"Wealth": "wealth"}) # An agent attribute
```

**Comment by Corvince** [comment]
Thanks for the bug report.

If you look at the whole file/code section from which you extracted the model code, you can see that `compute_gini` is defined above (outside the model definition) as

```python
def compute_gini(model):
    agent_wealths = [agent.wealth for agent in model.schedule.agents]
    x = sorted(agent_wealths)
    N = model.num_agents
    B = sum( xi * (N-i) for i,xi in enumerate(x) ) / (N*sum(x))
    return (1 + (1/N) - 2*B)
```

I`ll note down that this could be highlighted and/or explained more in the intro section.

**Comment by jackiekazil** [comment]
@Corvince agreed. I am going to open a new ticket for this and ref this ticket, so the task needing to be done is clear.
