### ISSUE TITLE
Update docs to address left over concerns

### ISSUE THREAD

**Issue by jackiekazil** [projectmesa/mesa#698]
In PR #684, @Corvince had some concerns that are all valid. Please update the docs to address those concerns. *Please submit as separate PRs to follow best practices.*

- [x] Concern 1: change to `pipenv install mesa`
- [x] Concern 2: The literature references (line 35 and line 162 are still broken)
- [ ] Concern 3: Update figure

More details can be found here: https://github.com/projectmesa/mesa/pull/684#pullrequestreview-240660475

**Comment by Gigi1111** [comment]
Concern 2 is no longer an issue, as the [intro_tutorial.rst](https://github.com/projectmesa/mesa/blob/main/docs/tutorials/intro_tutorial.rst) has been rewritten. Please ignore the 2 PR #1655, #1657.

**Comment by jackiekazil** [comment]
@Gigi1111 Thank you! I marked it off the list.
