### ISSUE TITLE
Confusion with BatchRunner

### ISSUE THREAD

**Issue by EthanG30** [projectmesa/mesa#701]
So I'm working through the Introductory Tutorial, and can't get the BatchRunner to work correctly. Where should I be adding this code segment? 

fixed_params = {
        "width": 10,
        "height": 10
        }

        variable_params = {"N": range(10, 500, 10)}

# The variables parameters will be invoke along with the fixed parameters allowing for either or both to be honored.
        batch_run = BatchRunner(
        MoneyModel,
        variable_params,
        fixed_params,
        iterations=5,
        max_steps=100,
        model_reporters={"Gini": compute_gini}
        )

        batch_run.run_all()

It was sort of unclear, and keeps throwing an error when I just add it outside of the Model class:
'MoneyModel' object has no attribute 'running'

**Comment by tpike3** [comment]
Did you add the attribute self.running to your model class? A self.running attribute is necessary as it enables conditional shut off of the model once a condition is met. In the example it is set as True indefinitely. 

The self.running attribute allows the model to reach a certain number of steps or a condition (e.g. all agents died or a price equilibrium was met) to stop the model then move onto the next one. 

`
     class MoneyModel(Model):`
          `"""A model with some number of agents."""`
              `def __init__(self, N, width, height):`
                       `self.num_agents = N
                       self.grid = MultiGrid(width, height, True)`
                       `self.schedule = RandomActivation(self)`
                        `self.running = True  #This attribute needs to be added for batch runner`
`

**Comment by EthanG30** [comment]
Ah that would be it; I figured it was something simple like that. Thanks for your help!
