### ISSUE TITLE
Fresh install errors

### ISSUE THREAD

**Issue by BlaHaws** [projectmesa/mesa#703]
I have cloned the current repo and attempt to run one of the example models provided. I continue to receive these errors:

Interface starting at http://127.0.0.1:8521
WARNING:tornado.access:404 GET /static/js/jquery.min.js (127.0.0.1) 1.00ms
WARNING:tornado.access:404 GET /static/js/bootstrap-switch.min.js (127.0.0
WARNING:tornado.access:404 GET /static/js/bootstrap-slider.min.js (127.0.0
WARNING:tornado.access:404 GET /static/js/GridDraw.js (127.0.0.1) 2.99ms
WARNING:tornado.access:404 GET /static/js/Chart.min.js (127.0.0.1) 2.99ms
WARNING:tornado.access:404 GET /static/js/bootstrap.min.js (127.0.0.1) 1.9
WARNING:tornado.access:404 GET /static/js/InteractionHandler.js (127.0.0.1
WARNING:tornado.access:404 GET /static/js/ChartModule.js (127.0.0.1) 0.00m
WARNING:tornado.access:404 GET /static/js/CanvasModule.js (127.0.0.1) 0.00
WARNING:tornado.access:404 GET /static/js/runcontrol.js (127.0.0.1) 1.00ms
WARNING:tornado.access:404 GET /static/js/bootstrap.min.js (127.0.0.1) 1.0
WARNING:tornado.access:404 GET /static/js/bootstrap-switch.min.js (127.0.0
WARNING:tornado.access:404 GET /static/js/bootstrap-slider.min.js (127.0.0
WARNING:tornado.access:404 GET /static/js/GridDraw.js (127.0.0.1) 0.00ms
WARNING:tornado.access:404 GET /static/js/Chart.min.js (127.0.0.1) 0.00ms
WARNING:tornado.access:404 GET /static/js/InteractionHandler.js (127.0.0.1
WARNING:tornado.access:404 GET /static/js/ChartModule.js (127.0.0.1) 0.00m
WARNING:tornado.access:404 GET /static/js/CanvasModule.js (127.0.0.1) 1.00
WARNING:tornado.access:404 GET /static/js/runcontrol.js (127.0.0.1) 1.02ms

I have no clue how to correct these issues locally in order to run.

command line used: python run.py

**Comment by jackiekazil** [comment]
I just did the following.... 
1. Clone repo
2. In master branch, did `pip install mesa`
3. cd-ed into examples/Schelling
4. Ran `mesa runserver` 

... and it ran fine in Python 3.7.3. 

Right now, this ticket does not contain enough information to be able to troubleshoot this further. My hypothesis is that this is a local issue not a Mesa issue. If it is a local issue, please post to the mailing list. It looks like tornado can't access the static files. Maybe someone has come across this before, but put a bandaid on and never shared it.

**Comment by pratik-ingle** [comment]
This happens when the file path is not proper. Try giving the absolute path instead of the relative paths ```/static/js/jquery.min.js```
