### ISSUE TITLE
Remove random seed construct from library?

### ISSUE THREAD

**Issue by rht** [projectmesa/mesa#709]
In most cases, it is sufficient to specify the global random seed in the beginning of the entry point `server.py`

```
SEED = 1970
random.seed(SEED)
np.random.seed(SEED)
```

and the random scheduler could just call `random.random()` instead of `self.model.random()` and the result would still be deterministic.
This is probably more transparent, and reduce the model parameter that people need to read.
In the scenario when people do use the seed-fixing above, it is by default overridden by
```
        model._seed = time.time()
```
at model.py, which result in the simulation being non-deterministic, and would result in confusion.

The remaining corner case would be when the scheduler is multi-processed, but even this could be remedied by passing a randomly generated int from the parent process.

**Comment by dmasad** [comment]
The main situation where having the random seed in the model object is useful is side-by-side model runs (see #585). In that case, multiple model instances are running side by side in a single thread, so calls directly to random from one model affect the results in the other model. If you later instantiated just one model with the same seed, it would produce different results. Automatically setting a seed at instantiation means that if a user forgets to instantiate a random seed, it's still recoverable. Finally, it allows for serializing an entire model state to drive, loading it later, and having the random numbers stay consistent.

In most cases, a user probably doesn't care about having a consistent random seed, so they won't worry about it either way (and won't need to worry about the argument either). But if someone does need to fix or store a random seed, having it be a model-level variable seems to provide more flexibility than setting it globally.

**Comment by rht** [comment]
> Finally, it allows for serializing an entire model state to drive, loading it later, and having the random numbers stay consistent.

Ok, I think this should be the main reason.

> In that case, multiple model instances are running side by side in a single thread, so calls directly to random from one model affect the results in the other model.

Alternatively, the instances can be further isolated from each other via multiprocessing, and an explicit `copy.deepcopy` is no longer needed since the model is automatically deep-copied, but this implicit knowledge could potentially cause pithole for anyone reading the code.
