### ISSUE TITLE
Advanced tutorial modular server TypeError: __init__() takes from 3 to 5 positional arguments but 7 were given

### ISSUE THREAD

**Issue by StuartMesham** [projectmesa/mesa#717]
**Describe the bug**
https://mesa.readthedocs.io/en/master/tutorials/adv_tutorial.html
In the provided code snippet:
```
server = ModularServer(MoneyModel,
                       [grid],
                       "Money Model",
                       100, 10, 10)
```

There is an error (incorrect number of parameters). The code does not run.

**Expected behavior**
The final parameters (`100, 10, 10`) should be in a dictionary of the model parameters. eg:
```
model_params = {
    "width": 10,
    "height": 10,
    "N": 100
}

server = ModularServer(MoneyModel,
                       [grid],
                       "Money Model",
                       model_params)
```

**To Reproduce**
Try run the tutorial with the latest version of Mesa (0.8.6).

**Comment by Corvince** [comment]
Thanks for the report, the advanced tutorial was updated with #711
