### ISSUE TITLE
Update Webhooks to integrate w/ Github

### ISSUE THREAD

**Issue by Corvince** [projectmesa/mesa#720]
There are currently two GitHub Webhooks that should be enabled/updated

1. [ReadtheDocs ](https://docs.readthedocs.io/en/stable/webhooks.html) - there is a webhook but it does not work in terms of automatically rebuilding the docs after a new PR is merged or a new release
2. [CodeCov](https://github.com/apps/codecov) - Presumably the best way to integrate is installing the codecov GitHub App.

**Comment by jackiekazil** [comment]
I hope you don't mind... I broke this into two tickets.
