### ISSUE TITLE
Create github hook to rebuild docs after a new PR is merged or new release

### ISSUE THREAD

**Issue by jackiekazil** [projectmesa/mesa#722]
Figure out how to integrate [ReadtheDocs ](https://docs.readthedocs.io/en/stable/webhooks.html) to automatically rebuild the docs after a new PR is merged or a new release. 

(This requires admin access, so few can work on this.) 

This issue fixes 1/2 of #720. 
This is related to #721.

**Comment by Corvince** [comment]
It works!
