### ISSUE TITLE
filter agents based on one variable and then loop over them: Multi-agent model

### ISSUE THREAD

**Issue by hannantahir** [projectmesa/mesa#727]
I have a multi agent model similar to Wold sheep model. I wanted to loop over one type of agent and apply some filter criteria to select only the agents which meet the condition. For example:

```
for wolves in self.schedule.agents_by_breed[wolf]:
            if wolves.age >= 2:
```

Here I am looping over wolf agents in a multi agent model and then looking at the age variable of each wolf. After the if condition, I can change or do something else with this particular wolf agent which met the condition. 

But what I want is a loop-able list of all the wolf agents which have age >= 2. Once the list is made, I want to randomly select one wolf agent from that specific list. Is there any fast function or method available that can do that in Mesa? Or should I do it by creating a list containing Unique_Id of the wolf agents which met the condition. Then randomly pick one unique_id from that list and later in another loop over all wolf agents, I search for that specific randomly chosen Unique_ID and do further things. Or is there any better way of doing it?

**Comment by Corvince** [comment]
If I understand your question correctly you can create a list of old wolves with a list comprehension and then select one randomly

```python
old_wolves = [wolf for wolf in self.schedule.agents_by_breed[wolf] if wolf.age >= 2]

mywolf = self.random.choice(old_wolves)
```

**Comment by hannantahir** [comment]
@Corvince,

Yes, thank you. I was looking for that.
