### ISSUE TITLE
`BatchRunnerMP` not working in local due to `Dictionary can not be broadcast to list` error

### ISSUE THREAD

**Issue by SebastianoF** [projectmesa/mesa#742]
Hello!

**Describe the bug**

When calling `BatchRunnerMP` I'm getting the error in the object:
at the line:

`for model_vars, agent_vars in list(task)`

Debugging step by step also shows that `task` can not be broadcasted to list.

**To Reproduce**
Please see TODO `test_batchrunner.py` in branch: https://github.com/projectmesa/mesa/pull/735

**Comment by tpike3** [comment]
@SebastianoF closing based on batchrunner update. Mesa release 0.8.8.1 on Nov 27. Apologies  for not responding earlier.
