### ISSUE TITLE
Visualisation with matplotlib

### ISSUE THREAD

**Issue by SebastianoF** [projectmesa/mesa#743]
The embedded visualization tools are awesome!

Although, do you think it would make sense to have some matplotlib / networkX / other lib based visualisation tools? 

This would open to more visualization possibilities and would allow to quickly extend to more graphical options.

As I see it, graphs do not need to be embedded in the GUI where the agents are moving around. They can live in their popup windows connected to push-buttons in the GUI (siemens plant simulation works this way). With the interactive mode they can refresh real-time.

Thanks!

**Comment by rht** [comment]
The new Mesa 2.1 has a pure Python viz, as documented in https://mesa.readthedocs.io/en/stable/tutorials/visualization_tutorial.html, which runs either on a Jupyter notebook or a standalone web server. See https://github.com/projectmesa/mesa-examples/tree/main/examples/boltzmann_wealth_model_experimental.

It is powered by Matplotlib, so you can do anything you can with Matplotlib, on it. This includes using Seaborn.
