### ISSUE TITLE
Returning a random and real-time list of `agent_keys` in every `step()`

### ISSUE THREAD

**Issue by LangLEvoI** [projectmesa/mesa#751]
Hi there,

I was wondering if the `mesa` lib should return a list of `agent_keys` for the following situation:

Considering a simple `RandomActivation` mode, for agents `[A, B]`, a `sender` and a `perceiver` would be randomly picked up in each `RandomActivation.step()`, which means the **only one** `Agent.step()` could exchange agents' signal (`perceiver_signal = sender_signal`).

Thus if I could get a real-time and random list (`agent_keys`) of `self.agent_buffer(shuffled=True)` (no.112 line, `mesa/time.py`, v0.8.6), I could use the following judgement to finish one signal exchange.

```python
#Class _Agent(Agent):#
def step():
    # Let the index of sender-perceiver pair is always `n` and `n+1`
    role = 'sender' if agent_keys.index('A') % 2 == 0 else 'perceiver'
    if role == 'sender':
        perceiver_signal = sender_signal
        sender_signal = random_signal
    else:
        pass
```

For now, I defined a cache list in `Model` and use `StagedActivation` to implement the above function. Do you think it should be a universal requirement? Looking forward to your comments :)

**Comment by quaquel** [comment]
With the shift to agentset, model.agents allways contains the agents in the model. Its easy to implement this on top of that in a user's model.step method.
