### ISSUE TITLE
Add ContinuousSpace visualization

### ISSUE THREAD

**Issue by jdfoote** [projectmesa/mesa#753]
The boids example visualizes ContinuousSpace.

I'm wondering why a class to visualize continuous space is not part of the main library, and I'd suggest that it be added.

**Comment by EwoutH** [comment]
This is our most upvoted open issue! @ankitk50 have you by any chance been looking at ContinuousSpace visualization?

Does anyone know how that's currently done in flocking?

**Comment by rht** [comment]
ContinuousSpace in the Tornado viz just needs to incorporate https://github.com/projectmesa/mesa-examples/blob/main/examples/boid_flockers/boid_flockers/simple_continuous_canvas.js.
 
ContinuousSpace in JupyterViz has already been implemented. A showcase of it: https://github.com/projectmesa/mesa-examples/pull/81.

**Comment by EwoutH** [comment]
Right, so we have this implemented? Fully? If so, can we close this issue as completed?

**Comment by rht** [comment]
Assuming that:
1. mesa-viz-tornado is on feature freeze
2. the JupyterViz, with an API that is similar to mesa-viz-tornado, is the official recommended way to do visualization

then this issue can be closed.

**Comment by EwoutH** [comment]
Okay, let's do that once we have the updated example in mesa-examples.

**Comment by coderbeta1** [comment]
Is someone currently working on this issue? Or is it open to all? Please share any updates related to this.

**Comment by EwoutH** [comment]
@Corvince @rht do we have this in SolaraViz currently?

**Comment by rht** [comment]
As said in https://github.com/projectmesa/mesa/issues/753#issuecomment-1902788996, it's already implemented.

**Comment by rht** [comment]
https://github.com/projectmesa/mesa/blob/3d19edc8976f41ea88463661b9aaa3c299b71380/mesa/visualization/components/matplotlib.py#L111
