### ISSUE TITLE
Error in runing shape_example 

### ISSUE THREAD

**Issue by YasinEnigma** [projectmesa/mesa#756]
**Describe the bug**

When I run shape_example encountered with this error.
from shape_example.server import launch_shape_model
ImportError: cannot import name 'launch_shape_model'

**Expected behavior**

**To Reproduce**

**Additional context**

**Comment by tpike3** [comment]
At the end of the the server.py file (~ line 44) add `server.launch()`

You may also need to change line 4 of the server.py file to : 

`from shape_example.model import Walker, ShapeExample` if you get `No module named '__main__.shape'; '__main__' is not a package` error

Thanks for letting us know and remember the example really just shows what arrowheads look like with a visualization. 

Let me know if this doesn't work

**Comment by YasinEnigma** [comment]
Thanks, problem solved by adding `server.launch` to server.py file and create an __init__.py to shape_example directory (to create a python package and use it in run.py).

> At the end of the the server.py file (~ line 44) add `server.launch()`
> 
> You may also need to change line 4 of the server.py file to :
> 
> `from shape_example.model import Walker, ShapeExample` if you get `No module named '__main__.shape'; '__main__' is not a package` error
> 
> Thanks for letting us know and remember the example really just shows what arrowheads look like with a visualization.
> 
> Let me know if this doesn't work

Thanks, problem solved by adding `server.launch()` to server.py file and create an __init__.py file in shape_example directory (to create a python package and use it in run.py).
