### ISSUE TITLE
D3 Network Visualization overwrites rather than updating

### ISSUE THREAD

**Issue by jdfoote** [projectmesa/mesa#765]
**Describe the bug**
At every tick the Network Visualization receives a new set of nodes and edges but doesn't remove the previous nodes and edges.

**Expected behavior**
The previous network should be updated rather than appended to.

**To Reproduce**
The virus_on_network example shows this behavior. If you inspect the page you will see a proliferation of <g> elements.

**Additional context**

I believe that the problem is in NetworkModule_d3.js and is likely very simple to fix. I just don't know enough JS to be the one to fix it.

**Comment by tpike3** [comment]
Fix merged #767
