### ISSUE TITLE
Batch_runner limiting the number of agents 

### ISSUE THREAD

**Issue by rafaelcbfc** [projectmesa/mesa#766]
Hi everyone, 

I am new to mesa but have some experience with python. I am developing an ABM for my Master thesis and in a nutshell, I have 2 types of agents (Industries and communities) placed on a grid interacting between them (industries activate communities and communities start to perform actions).

My model has 2 instances: n_industries ; n_communities and create both types of agents at the start with a specific geographical location or for each type of agent.

    class Modelrun(Model):
        def __init__(self, n_industries, n_communities, max_ticks = 240):
     
    #Add industries        
            for i in range(n_industries):
                ind = Industry(i, geo_i[i], self)
                self.schedule.add(ind)
                self.grid.place_agent(ind, geo_i[i])

      #Add community       
            for c in range(n_communities):
                com = Community(c, geo_c[c], self)
                com.active = "No"
                self.schedule.add(com)
                self.grid.place_agent(com, geo_c[c])  
            self.datacollector.collect(self)

Running on the server, everything presents smoothly and both types of agents are plotted.

My issue goes on the batch_run. On the code below, I realized that the batch run caps the maximum number of agents. I need to have one type of agent smaller than the other for it to run as the larger number caps the number of agents to be inserted. For example: if I add 10 industries and 1 community, my batchrun will return to me that there were 9 industries and 1 community (as it capped the number of agents to 10). The situation below simply brings me back 10 communities and 0 industries.

    m_step_data = pd.DataFrame()
    n_industries = [10]
    n_communities = [10]
    total = n_industries + n_communities

    model_param = {"n_industries": n_industries, "n_communities": n_communities} 

    batch_run = BatchRunner(Modelrun, model_param, iterations = 1, max_steps = 13, model_reporters = {"Data Collector": lambda m: m.datacollector}, display_progress=True)

I am not sure if I did something wrong, or if this is a limitation on the batch runner itself. 

Can someone help me with this situation?

Thanks!

**Comment by rafaelcbfc** [comment]
PS: On the visualization, to run over my datacollector I realized the same issue occurs. So My suspicion is that mesa can only handle one number of total agents. Is this correct?

**Comment by rafaelcbfc** [comment]
Using a MultiGrid allows for, in my case, 2 types of agents to be placed. @jackiekazil  and @dmasad, could you guys update this type of information on https://mesa.readthedocs.io/en/master/apis/space.html? 
Thanks!

**Comment by rht** [comment]
@rafaelcbfc can you share a runnable example script in a repo/gist?

**Comment by tpike3** [comment]
@rafaelcbfc You could insert an activation by breed as in the wolf sheep predation https://github.com/projectmesa/mesa/blob/master/examples/wolf_sheep/wolf_sheep/schedule.py.

If you want the industries to be inside a community you could also use multi-level mesa which allows for more nuanced interactions. https://github.com/tpike3/multilevel_mesa. Let me know if this helps.

**Comment by tpike3** [comment]
@rafaelcbfc I will assume this issue has been resolved. Please let me know if otherwise.
