### ISSUE TITLE
Make the charting visualization not suck

### ISSUE THREAD

**Issue by dmasad** [projectmesa/mesa#77]
The charting module (currently using [Charts.js](http://www.chartjs.org/) is (barely) functional, but ugly. The defaults should be made nicer, and the configuration should be more Pythonic.

**Comment by jeetu7** [comment]
When number of steps are large (say 100 or 1000) the ticks on x-asix looks very cluttered. The autoSkip option might help in this case. See http://www.chartjs.org/docs/#scales-ticks-configuration

**Comment by jackiekazil** [comment]
@jeetu7 That sounds like a great idea!

**Comment by jackiekazil** [comment]
This has made progress forward thanks to @cauemello!!
For now, I am closing this ticket lieu of more specific tickets.
