### ISSUE TITLE
Broken link to pipenv docs

### ISSUE THREAD

**Issue by josiahvinson** [projectmesa/mesa#771]
**Describe the bug**
The link to `pipenv` docs in the intro tutorial is broken.

**Expected behavior**
I expect clicking the link to `pipenv` to reference a valid url.

**To Reproduce**
Click on the `pipenv` link on https://mesa.readthedocs.io/en/master/tutorials/intro_tutorial.html.

**Additional context**

**Comment by Corvince** [comment]
Thanks for the report and fix!
