### ISSUE TITLE
Why mesa is called mesa?

### ISSUE THREAD

**Issue by SebastianoF** [projectmesa/mesa#774]
OK, that's a silly one! Thanks for the patience!

The issue is that I am keep on being asked about the name by anyone I tell about the library, and could not find the meaning of the name anywhere!

**Comment by dmasad** [comment]
The name was pretty arbitrary. Jackie Kazil and I wanted something that was
short and available; and Mesa resonated with 'Mason' (we were both doctoral
students at George Mason University at the time) and evoked the Santa Fe
Institute, where a lot of ABM and complexity work was pioneered. It doesn't
stand for anything (hence Mesa, not MESA).
