### ISSUE TITLE
ChartModule multiple labels don't display properly

### ISSUE THREAD

**Issue by sjgenco** [projectmesa/mesa#776]
**Describe the bug**
When running the bank_reserves example, I noticed the 3 labels for graphing numbers of rich, poor, and mid agent do not align properly

**Expected behavior**
space them out properly

**To Reproduce**
just run the bank_reserves example (see attached snapshot)

**Additional context**
I am running the example code on a MacBook Pro 2018 edition, OS = 10.15.2, from Spyder 4.0.0 in Anaconda, Python v 3.7.
![bank_reserves_portrayal](https://user-images.githubusercontent.com/19754884/72183795-b9e99400-33a3-11ea-8144-83866e91da01.jpg)

**Comment by sjgenco** [comment]
Quick update on this ...
I forgot to mention I was rendering the visualization in Brave.
I just ran it in "real" Chrome, and the problem disappears.
So this may not really be a problem for mesa.
I'll leave this here in case others run into the same or similar rendering problems in Brave vs. Chrome.
![bank_reserves_portrayal_chrome](https://user-images.githubusercontent.com/19754884/72184746-0209b600-33a6-11ea-8040-c7f5d2e5184c.jpg)

**Comment by sjgenco** [comment]
one more comment here for posterity.

I found if I changed the browser url in Brave from **127.0.0.1 :8521** to **localhost:8521**, the display rendered correctly. Go figure.

**Comment by Corvince** [comment]
That is very strange indeed! I won't try to figure this one out, but at least I can confirm the behavior. I would bet this will eventually be sorted out by Brave.
