### ISSUE TITLE
mean field simulation in Cellular Automata models

### ISSUE THREAD

**Issue by mcb63-maarten** [projectmesa/mesa#778]
Hi,

I am looking for ways to implement mean field simulation within mesa. One (clean) way is to use random cells instead of neighbours for the next state function, i.e.
self.neighbourhood = rd.sample(self.model.measure_CA, 8)

However, I would like to also be able to randomise (shuffle) the entire field after each timestep (that is, randomise positions of agents, without loosing or adding individuals). This is slightly dirty, but proves very intuitive for students, and is visually attractive (as mean field means complete mixing)

Any ideas / code?

**Comment by rht** [comment]
Sounds doable. There could be a class `MeanFieldGrid` that redefines the method `iter_neighborhood()` to use `rd.sample` instead. The shuffling can also be readily implemented by looping through each agent and update their position randomly.
Are agents' positions allowed to overlap with each other?

**Comment by mcb63-maarten** [comment]
I am currently using it for a classic cellular automaton model with each cell occupied with one state variable. For the random update I need to be able to swap agent positions. I noticed the swap_pos() function, but did not find examples on how to correctly implement this.

**Comment by rht** [comment]
There is no implementation of `swap_pos()` in the codebase. It might have existed in the early version, but gone in latest master.

I'd do it this way:
```python
def swap_pos(a1, a2):
    pos1 = a1.pos
    pos2 = a2.pos
    self.move_to_empty(a2)
    self.position_agent(a1, *pos2)
    self.position_agent(a2, *pos1)
```
Where the 2 agents are picked randomly by chance.

**Comment by tpike3** [comment]
example provided
