### ISSUE TITLE
any examples of datacollector 'tables' implementation?

### ISSUE THREAD

**Issue by sjgenco** [projectmesa/mesa#784]
**Describe the bug**
Not really a bug, more like a documentation request. In the examples folder, there are lots of examples of the model and agent datacollectors, but I couldn't find any examples of the tables datacollector. I read the documentation in the datacollection.py code, but was unable to implement it.

**Expected behavior**
For model and agent data collectors, it's pretty clear. You create a function that delivers the values you want to collect and you identify that function in the data collector instantiation. For instance, in the bank_reserves example model, you count 'rich people' with this function
```
def get_num_rich_agents(model):
    """ return number of rich agents"""

    rich_agents = [a for a in model.schedule.agents if a.savings > model.rich_threshold]
    return len(rich_agents)
```
then you point to that function in the datacollector instantiation:
```
self.datacollector = DataCollector(model_reporters={
                                           "Rich": get_num_rich_agents, ...
```
Finally, to display the variable in a chart, you map the data into a chart visualization element in the server.py module:
`chart_element = ChartModule([{"Label": "Rich", "Color": RICH_COLOR}, ...`

To build a datacollection table, it seems you use the instantiation to create an empty table with a name and column headings, like this:
```
self.datacollector = DataCollector(tables=
                                          {"Strategies": ["step", "strategy", "count", "score"]})
```
That does create an empty table with the 4 columns, but how exactly do I append rows to it? I have a function that extracts values for the variables at each step in the model, but I don't see how to get those values into a new row in the table. My function ends with this return:
```
return "Strategies", {'step': step, 
                                  'strategy': strat, 
                                  'count':strat_count, 
                                  'score': avg_score}
```
but I can't see how to get that data into the table.
I think just one functioning example would clear this up, but I haven't been able to find one.
Any help would be greatly appreciated!

**Comment by tpike3** [comment]
I think it is your data structure. What if you tried a dictionaries of dictionary with a list: 
data collector structure: 
`self.datacollector = DataCollector(tables=
                                          {"Strategies": {"step":[], "strategy":[], "count":[], "score":[]}})`

Then in your return process you append each value (e.g. `self.datacollector["Strategies"]["step"].append(step),  self.datacollector["Strategies"]["strategy"].append(strategy) etc`

If you give it a try let me know if it works.

**Comment by sjgenco** [comment]
Thanks! This is very helpful. But I still need one (very newbie) piece of info.

I've altered the data collector instantiation per your suggestion:
```
self.datacollector = DataCollector(tables=
                    {"Strategies": {"step":[], "strategy":[], "count":[], "score":[]}})
```
I have a function for collecting the data called `get_table_row`. Again, per your recommendation, this function looks like this, with the datacollector append statements at the end:
```
def get_table_row(model):
        step = model.schedule.steps
        agents = model.schedule.agents
        strats = [a.strategy for a in model.schedule.agents]
        all_strats = model.strategies_list
        ...
        strat = ''
        for i in range(len(all_strats)):

            ... loop thru each strategy active at this step & extract table variables ... then ...

            model.datacollector["Strategies"]["step"].append(step), 
            model.datacollector["Strategies"]["strategy"].append(strat)
            model.datacollector["Strategies"]["count"].append(strat_count)
            model.datacollector["Strategies"]["score"].append(avg_score)
```
(Since this function is standalone, I use `model.` rather than `self.` in the datacollector statements.)

Here's my question. **Where and how do I call this method as part of data collection?** With model and agent data collection, the variable-calculation function is identified in the instantiation statement, e.g., in the Introductory Tutorial MoneyModel example, the function called `compute_gini` is identified like this:
```
self.datacollector = DataCollector(
            model_reporters={"Gini": compute_gini}, 
```
How do I let mesa know my `get_table_row` function is where the datacollector needs to look to append a new row to the table? My guess is this is so easy or obvious that I'm completely missing it. 

I think there is one benefit to my confusion. If the table datacollector were better documented, I wouldn't be here asking for one-on-one help. Thanks again.

**Comment by sjgenco** [comment]
I figured out an answer to this question, so I thought I would post it here for others who might be looking for documentation for the 'tables' `datacollector` in mesa. Here's how you can get it to work.

First, in the model's __init__ method, you add a 'tables' `DataCollector` definition to your model/agent reporter definitions, like this:
```
        # setup data collector
        self.datacollector = DataCollector(
            model_reporters={"avg score overall":get_avg_score,
                             "avg score, leading strategy":get_top_score},
            tables={"Strategies": {"step":[], "strategy":[], "ncount":[], "score":[]}})
```
(note the table is defined as a dictionary, as noted above by @tpike3)

Next, in your `step()` method, you call `self.datacollector.collect` to activate your model/agent reporters, but you call a different method,  `self.datacollector.add_table_row`, to add a row to any table (or tables) you defined in __init__. Here's the `step()` method for my model:
```
    def step(self):
        if self.num_strategies == 1:
            self.running = False
        else:
            self.schedule.step()
            
            # collect model_reporters data
            self.datacollector.collect(self)
            
            # collect "Strategies" table data
            step_num = self.schedule.steps
            agents = self.schedule.agents
            strats = [a.strategy for a in self.schedule.agents]
            active_strats = list(set(strats))
            strat = ''
            for i in range(len(active_strats)):
                strat = active_strats[i]
                strat_pop = [a for a in agents if a.strategy == strat]
                strat_ncount = len(strat_pop) 
                strat_scores = [a.score for a in strat_pop]
                avg_score = round(stats.mean(strat_scores),2)
                next_row = {'step': step_num, 'strategy': strat, 
                       'ncount': strat_ncount, 'score': avg_score}
                self.datacollector.add_table_row("Strategies", next_row, ignore_missing=False)
```
Since my particular model needs to grab multiple rows of data for each step (depending on how many strategies are active during that step) I have to collect some parameters first and run them thru a loop to write mulitple `next_row` values, which then get added to my table using the `self.datacollector.add_table_row` command,  with parameters as documented in comments in the mesa `DataCollector` module code. 

I don't know if this is the easiest or most efficient way to do this, but it seems to get the job done.
