### ISSUE TITLE
Bringing in Vital Dynamics in the Virus infection Example

### ISSUE THREAD

**Issue by adprabhak** [projectmesa/mesa#785]
**What's the problem this feature will solve?**
The NetworkGrid class doesn't allow adding new nodes with agents easily

**Describe the solution you'd like**
An ideal solution would allow changing the network by adding new nodes (preferentially) and deleting new nodes in the network. This would mean the networkgrid to be initiated with more nodes at the beginning.

**Additional context**
Add any other context, links, etc. about the feature here.

**Comment by rht** [comment]
@adprabhak  `NetworkGrid` contains a `networkx` graph, so you can modify the graph like one usually would in `networkx`.

**Comment by tpike3** [comment]
Closing, as mentioned by @rht please  use networkx functionality for network manipulations
