### ISSUE TITLE
Modular visualization JavaScript in the HTML file or separate?

### ISSUE THREAD

**Issue by dmasad** [projectmesa/mesa#79]
Right now, the JavaScript to render each visualization module is included in the template HTML file as a script tag. This means that on the final page, each visualization div has its own separate script tag. This is ugly, and also not very standard for web development. But none of the alternatives are great:

- Include the code in a separate JavaScript template. This means that each module needs at least two external files: an HTML template, and a JavaScript template.

- Have users write template code directly in Python, as a string. This seems non-ideal, since it involves writing JavaScript in a Python environment, as a long and hard-to-debug string.

- Other ideas?

**Comment by jackiekazil** [comment]
After our convo.... 
Let's make visualization have.... 
.html file
.js file
and .py file

**Comment by dmasad** [comment]
I've found a way to embetter this, and get rid of the ugly templated JavaScript. Each module will now consist of a .py and .js file. The JavaScript file defines an object, which creates the appropriate element on construction and stores an internal reference to it, along with associated render() and reset() methods. The object created and stored in a list of all elements, so that rendering data involves matching each incoming data element to the render method of the corresponding visualization element.
