### ISSUE TITLE
agent_reporters in BatchRunner

### ISSUE THREAD

**Issue by nadaa** [projectmesa/mesa#797]
The error appears when I use agent_reporters with BatchRunner
```
batch_run = BatchRunner(model,
                        iterations=2,
                        max_steps=10,
                        model_reporters = {"model_var": lambda m: m.modelvar},
                        agent_reporters = {"agent_var": lambda a: a.agentvar}
                        )
```
I got this error:
" agent_record[var] = getattr(agent, reporter)
TypeError: getattr(): attribute name must be string"

Any suggestion on how to solve it?

**Comment by tpike3** [comment]
What is your a.agentvar referring to? 

I believe since you are not using the Datacollecter and just want a specific agent attribute if should mirror the tutorial instead https://mesa.readthedocs.io/en/master/tutorials/intro_tutorial.html#batch-run
`
batch_run = BatchRunner(model,
                        iterations=2,
                        max_steps=10,
                        model_reporters = {"model_var": lambda m: m.modelvar},
                        agent_reporters = {"agent_var": "agentvar"}
                        )
`
