### ISSUE TITLE
Project meeting discussion for this friday

### ISSUE THREAD

**Issue by jackiekazil** [projectmesa/mesa#80]
Things to discuss
* Project organization
* Testing testing testing 
* Docs
* New features
* Upcoming milestones
* Conferences to submit to
* Tutorials to write
etc. 

If you have feelings about these, please chime in even if you are not able to make the discussion.

**Comment by dmasad** [comment]
Meeting postponed, so the agenda is still open!

**Comment by jackiekazil** [comment]
Milestones are being updated to reflect our convos and notes are here: https://hackpad.com/Mesa-fP1IJeVLeGu
