### ISSUE TITLE
Mesa visualization with spyder IDE

### ISSUE THREAD

**Issue by MartijnBloothoofd** [projectmesa/mesa#800]
I am following the advanced tutorial and trying to experiment with visulisation. I copied the code as is in the tutorial. I got the visualization as shown in the tutorial, but it is not able to update. I use the Spyder IDE form which I ran the script. Any idea what can cause this problem?

**Comment by MartijnBloothoofd** [comment]
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-10-1a0f1200ebeb> in <module>
     19                        {"N": 100, "width": 10, "height": 10})
     20 server.port = 8709 # The default
---> 21 server.launch()

~\AppData\Local\Continuum\anaconda3\lib\site-packages\mesa\visualization\ModularVisualization.py in launch(self, port)
    322         webbrowser.open(url)
    323         tornado.autoreload.start()
--> 324         tornado.ioloop.IOLoop.current().start()

~\AppData\Local\Continuum\anaconda3\lib\site-packages\tornado\platform\asyncio.py in start(self)
    146             self._setup_logging()
    147             asyncio.set_event_loop(self.asyncio_loop)
--> 148             self.asyncio_loop.run_forever()
    149         finally:
    150             asyncio.set_event_loop(old_loop)

~\AppData\Local\Continuum\anaconda3\lib\asyncio\base_events.py in run_forever(self)
    519         self._check_closed()
    520         if self.is_running():
--> 521             raise RuntimeError('This event loop is already running')
    522         if events._get_running_loop() is not None:
    523             raise RuntimeError(

RuntimeError: This event loop is already running

**Comment by pancho111203** [comment]
Hi, I'm running into the same issue. Could you tell me what you did to solve this? @MartijnBloothoofd 
Thanks

**Comment by terivan2006** [comment]
In case somebody has a similar issue - try making sure that your ipython graphics are set to 'inline', not 'automatic'. (Tools -> Preferences -> Ipython Console -> Graphics)

**Comment by christoschronopoulos** [comment]
Thanks a lot @terivan2006! The webserver now shows the visualisations automatically! Indeed, the graphics settings was "Automatic" in my case. 

A workaround that I was using before I find your comment was to re-run the `server.launch()` line several times. Not ideal, but at least I could see the iterations. Thanks again!

**Comment by rht** [comment]
The documentation needs to be updated somehow. Maybe add a few lines of code that asserts that the settings is `inline`. I don't use Jupyter that much, but I wonder if the settings used to be `inline`?
