### ISSUE TITLE
Introductory Tutorial Issues

### ISSUE THREAD

**Issue by pmbaumgartner** [projectmesa/mesa#805]
Hey Mesa team -

I spent the last weekend going through the basic tutorial and working my way through creating some models. As I went through the tutorial, I noticed a few places where I think the clarity of instruction could be improved. I'm just going to list my points below.

1. **How do users get the requirements.txt**? There's instructions on how to access it, but should they clone the repository, download the file from the example, or copy paste it into their own local file? 
2. **`MoneyModel.py` - is the casing correct following coding standards for python files?** The closest I could find is this: https://www.python.org/dev/peps/pep-0008/#package-and-module-names - which indcates it should be something like `money_model.py`.
3. **Citation link is broken: Comer2014.** URL: https://mesa.readthedocs.io/en/master/tutorials/intro_tutorial.html#comer2014 - the link goes to this, which is not found: http://gradworks.umi.com/36/23/3623940.html
4. **"Every agent is expected to have a step method, which takes a model object as its only argument"**. The way this is worded is unclear. The step method doesn't have to take the model as an argument, it takes the agent it's defined on as `self`. I also think this part could use some better sequencing to build on a users knowledge. For example, the user defines a step function that doesn't do anything, then the model is executed. How is the user able to know whether the step function is working properly? Rather than build a step function that's just a `pass`, could they build one that prints the model id? Then for the exercise add a line to the `step` function that prints the wealth (which should be 1 at this point for all agents)? I think it's important to give the user feedback that the step function is working, but a step function that does nothing when the model is run doesn't help here.
5. In **"Running your first model"** at the phrase: "You’ll probably see something like the distribution shown below." the plot is actually **above** this part in the narrative.
6. **The `moore` argument to `get_neighborhood` might be unclear what this does for new users.** Should this be changed to `diagonal`? It requires them to understand the difference between Moore and Von Neuman, but a new user is more likely to understand "can they move diagonal or not?"
7. **defining `give_money`** - the other agent is now called `other`, but is called `other_agent` in the `step` method. It might help new users if other agents are defined consistently.
8. **In "Adding Space", after the line "Now, putting that all together should look like this:"** - the defintion order of `MoneyModel` and `MoneyAgent` is switched. Previously the agent was defined first, then the model. In this snippet, the Model is defined first, then the Agent. The remaining code snippets define Agent first.
9. **Under "Batch Run" - `from mesa.batchrunner import BatchRunner` gets imported, but not used in the next code block.** The snippets make it unclear which file should be importing `BatchRunner` - the snippet right after the import is the model definition file, which is **not** where this should be imported. For clarity, this snippet with the import could wait until the block of code that executes the model.
10. **In the batch runner example, we do not import `compute_gini`**.  This is related to the above point - `compute_gini` is defined in the model definition program, but not in the model execution program. At this point in the tutorial, it's not clear whether new code goes in the model definition script or the model execution script. When we use the batch runner and define the reporter to capture the Gini Coefficient, the execution script has not imported `compute_gini` from the model definition script.

I was able to make it through the tutorial with some assumptions on my end, so none of these are mission critical, but I could see where beginner python programmers might get confused with some of the assumptions needed to make it through.

**Comment by dmasad** [comment]
Thanks for doing a deep dive and documenting the issues -- that looks really helpful! Hopefully we'll be able to go through and fix those quickly. 

If anyone is looking for low-hanging fruit, fixing any one of those is probably fairly quick and easy. Putting them into a check-box list, which we can update as individual issues are fixed.

- [ ] How do users get the requirements.txt? 
- [ ] MoneyModel.py - is the casing correct following coding standards for python files? 
- [ ] Citation link is broken: Comer2014. URL: https://mesa.readthedocs.io/en/master/tutorials/intro_tutorial.html#comer2014 
- [ ] "Every agent is expected to have a step method, which takes a model object as its only argument". 
- [ ] In "Running your first model" at the phrase: "You’ll probably see something like the distribution shown below." the plot is actually above this part in the narrative.
- [ ] The moore argument to get_neighborhood might be unclear what this does for new users.
- [ ] In "Adding Space", after the line "Now, putting that all together should look like this:" 
- [ ] Under "Batch Run" - from mesa.batchrunner import BatchRunner gets imported, but not used in the next code block. 
- [ ] In the batch runner example, we do not import compute_gini.

**Comment by Corvince** [comment]
Awesome work! That is a very reasonable and actionable list. New to programming or not, the basic tutorial should really just work when you follow it and not require any guess-working!

**Comment by pmbaumgartner** [comment]
If I get time this week, I'll make a PR for any of the documentation issues. I think the only item on the list that's a code-based update would be Item 6 with changing the `moore` argument to something like `diagonal`, which I'm not sure is inline with what the maintainers want for the library.

**Comment by Corvince** [comment]
Looking forward to that PR! 

RE: `moore` vs `diagonal`. I see two issues with `diagonal`

1. It might be equally confusing, since it is not clear if it means also the diagonal or only the diagonal
2. Calling it diagonal is only meaningful for a radius of 1, if you compare [moore and von neumann for larger radii](https://www.researchgate.net/figure/The-two-most-common-neighborhood-structures-are-the-Von-Neumann-and-Moore-which-can-be_fig1_333524697), it becomes more challenging to name.

For the current state and the intro tutorial, I think it would be best to just briefly describe what is meant by that. 

However, I also see it a bit problematic code-wise. Especially the implication of `moore=False`  to equal `von Neumann`. I think a better way would have been to use a `neighborhood="moore"` parameter. But I think that would be quite a large API change (also we could start to allow both ways and slowly depreciated moore). Another immediate improvement could be to have a default value, so at least for the intro tutorial we could just skim over the distinction and use the default value (probably `moore=True`)

**Comment by tpike3** [comment]
I am working on it, I should have a pull request ready in the next few days.

**Comment by pmbaumgartner** [comment]
Awesome, I didn't get a chance to get around to this and I'm glad it's been picked up.

**Comment by tcdejong** [comment]
@tpike3 are you still working on your PR? Or would (part of) this issue be available to other contributors as well?

**Comment by tpike3** [comment]
Should be pushed to doc build branch today and then happy to take any other improvements

**Comment by tcdejong** [comment]
Ah, I didn't see  #811 was linked to this! Thank you.

**Comment by tpike3** [comment]
Recommendations submitted in pull request 844. Can be viewed at https://mesa.readthedocs.io/en/doc_builds/tutorials/intro_tutorial.html
