### ISSUE TITLE
Key bug in the Virus on a Network example.

### ISSUE THREAD

**Issue by KubiK888** [projectmesa/mesa#806]
**Describe the bug**
Hi Mesa developers. When examining the behaviour of the virus spread step-by-step, sometimes the infected agent not only can infect the immediate neighbors, but also the neighbors of the immediate neighbors, and sometimes further beyond.

**Expected behavior**
The infected agent should **only** infect its immediate neighbors.

**To Reproduce**
Go to the example [URL](https://github.com/projectmesa/mesa/tree/master/examples/virus_on_network), then git clone into local drive, then run step-by-step.

**Additional context**
    Issues seem to be within the `try_infect_neighbors` function, sometimes the `susceptible_neighbors` is reassigned with the infected immediate neighbor and will further proceed with the for-loop. I attempted but was unable to resolve it. Please advise.

**Comment by KubiK888** [comment]
Upon, further examination, perhaps it is sometimes  an intended consequence? Such that the first node infect some neighbor nodes, and if the neighbor nodes happen to activate after the first node, then it may go through the try_infect_neighbors() itself, which may in terms lead to infection of its further neighbor nodes. If someone can confirm, it will be greatly appreciated.

**Comment by sd235634** [comment]
Hi,I was confused by this before I found it was caused by the method 'RandomActivation' which would activate the agents in random order. 
Use SimultaneousActivation instead and activate agents at the same time, it do works.

**Comment by KubiK888** [comment]
I realized the situation described in my original post was not intended with the activation pattern used, so I closed the issue. I did try your suggestion with using SimultaneousActivation but it didn't change anyway. Mind showing how you apply that activation in the virus on network or other example?

**Comment by KubiK888** [comment]
> Hi,I was confused by this before I found it was caused by the method 'RandomActivation' which would activate the agents in random order.
> Use SimultaneousActivation instead and activate agents at the same time, it does works.

I realized the situation described in my original post was not unintended, so I closed the issue. I did try your suggestion with using SimultaneousActivation but it didn't help. It actually made it worse, as more agents beyond the immediate neighbor connections are infected. Can you please show how you apply that activation on the virus on network or other example?

**Comment by sd235634** [comment]
```
class VirusOnNetwork(Model):
    def __init__(self,model_attributes):
        self.schedule = SimultaneousActivation(self)

class VirusAgent(Agent):
    def __init__(self, unique_id, model,initial_state,agent_attributes):
        self.state = initial_state
        self.nextstate = initial_state

    def step(self):
        if self.state is State.INFECTED:
            self.try_to_infect_neighbors()
        self.try_check_situation()

    def advance(self):
        #Set the state of the agent to the next state
        if self.state!=State.RATIONAL:
            self.state = self.nextstate
```

**Comment by sd235634** [comment]
> > Hi,I was confused by this before I found it was caused by the method 'RandomActivation' which would activate the agents in random order.
> > Use SimultaneousActivation instead and activate agents at the same time, it does works.
> 
> I realized the situation described in my original post was not unintended, so I closed the issue. I did try your suggestion with using SimultaneousActivation but it didn't help. It actually made it worse, as more agents beyond the immediate neighbor connections are infected. Can you please show how you apply that activation on the virus on network or other example?

more examples can be found in \examples\color_patches\color_patches\model
