### ISSUE TITLE
Slow when looking up list Grid.empties.

### ISSUE THREAD

**Issue by hzyrc6011** [projectmesa/mesa#807]
I tried to create a 500*500 Grid in my project. However it performs poorly when moving agents. 
I found it consums a lot when calling _place_agent() and _remove_agent in class Grid because both of them should look up in a great list, 250,000(500*500) in length.
How about convert this list to a set()?
Maybe there are better ways to avoid this slow-running bug.  Could you please  tell me that?Thankyou!

**Comment by Corvince** [comment]
yes, converting from a list to a set was the way to go, this has already been done, but unfortunately not yet released. Try installing the latest version from GitHub via `pip install -e git+https://github.com/projectmesa/mesa#egg=mesa`
