### ISSUE TITLE
Error in section "Adding the scheduler" in the tutorial

### ISSUE THREAD

**Issue by DoofCoder** [projectmesa/mesa#817]
In the third paragraph, it says: "Every agent is expected to have a step method, which takes a model object as its only argument – this is the agent’s action when it is activated." However, in all the implementations the Agent's step method takes self as a parameter, not a model object. Is that phrase correct?

**Comment by dmasad** [comment]
Good catch, thanks! Yes, that phrasing needs to be fixed.

**Comment by tpike3** [comment]
Wording was improved in latest tutorial update.
