### ISSUE TITLE
Push new Mesa release

### ISSUE THREAD

**Issue by jackiekazil** [projectmesa/mesa#819]
Wee are overdue for an official release. Before I push one, does anyone have anything that really want to try to get in or should I just tag and release? 

Discuss.

**Comment by Corvince** [comment]
I am fine with the current state and in full support for a new release!

**Comment by jackiekazil** [comment]
@Corvince, can you do a preliminary skim of changes in the diff file in the WIP PR  (#826) for the release? 
(Feel free to comment OR to contribute to the branch directly.)

**Comment by jackiekazil** [comment]
Also... there is a lot... I didn't realize we didn't have a release since last year :gulp:

**Comment by Corvince** [comment]
@jackiekazil I looked through it and made some very minor changes. Looks good to me!

**Comment by jackiekazil** [comment]
@Corvince Great. I did a quick review of the small changes you made. I am going to take your review of what I did and my review of what you did and merge into master

**Comment by jackiekazil** [comment]
Extra info... 
Associated milestone -- https://github.com/projectmesa/mesa/milestone/20 
Tagged release -- https://github.com/projectmesa/mesa/releases/tag/v0.8.7 
Test upload -- https://test.pypi.org/project/Mesa/ 
Official release -- https://pypi.org/project/Mesa/
