### ISSUE TITLE
Add a build-recipe to conda-forge

### ISSUE THREAD

**Issue by estshorter** [projectmesa/mesa#822]
It would be great if mesa can be installed via [conda](https://docs.conda.io/en/latest/) because it is a useful package/environment management system, especially on Windows.
So I'm planning to submit a [build-recipe](https://github.com/estshorter/staged-recipes/blob/mesa/recipes/mesa/meta.yaml) to [conda-forge](https://conda-forge.org/#contribute) as a pull request.

My questions are:
1. Is it OK to submit the recipe?
2. Who should I add as [recipe-maintainers](https://github.com/estshorter/staged-recipes/blob/mesa/recipes/mesa/meta.yaml#L59)?

**Comment by jackiekazil** [comment]
This sounds like it is a great idea, but I am less familiar with it. I have a few questions, and I can't seem to find docs to explain them to me.

To start...  
1. What does it mean to be a build-recipe? 
2. What does maintenance of this look like? (If that updating every time we do a release?)

_Also, feel free to point me to some docs on this if you know where some are._

**Comment by estshorter** [comment]
1. To my understanding, a build recipe is similar to setup.py or Pipfile. The difference is that it is for conda. (I hope this answers your question...
2. Please see this [page](https://conda-forge.org/docs/maintainer/updating_pkgs.html#pushing-to-regro-cf-autotick-bot-branch). What we should do after release is only accepting PR from a bot.
> When a new version of a package is released on PyPI/CRAN/.., we have a bot that automatically creates version updates for the feedstock. In most cases you can simply merge this PR and it should include all changes.

**Comment by estshorter** [comment]
I just submitted a PR to conda-forge.
https://github.com/conda-forge/staged-recipes/pull/11408

Please let me know if you have any problem or question.

**Comment by jackiekazil** [comment]
Thank you @estshorter ... how does one get added as a maintainer? 
(Can you add me & @dmasad? ... Not sure I can submit a PR to add myself.)

**Comment by estshorter** [comment]
I added @jackiekazil  and @dmasad as  maintainers!

**Comment by jackiekazil** [comment]
Thank you @estshorter!
