### ISSUE TITLE
Typos error in epstein_civil_violence example Jupyter Notebook

### ISSUE THREAD

**Issue by giacrava** [projectmesa/mesa#827]
**Describe the bug**
There are some minor typos in the Jupyter Notebook Epstein Civil Violence.ipynb in the epstein_civil_violence example that give errors when run. 

I'll try to fix it now with a pull request, it's my first time contributing on GitHub so if I do something not in the right way just let me know!

**Comment by jackiekazil** [comment]
@giacrava, when you are done, can you submit this as a pull request?

**Comment by jackiekazil** [comment]
Nm... you already did. :-) 
#828

**Comment by giacrava** [comment]
Yes, let me know if I followed the steps for contributing in the wrong way so next time I won't!
