### ISSUE TITLE
bug in version 0.8.7 

### ISSUE THREAD

**Issue by chenyuyou** [projectmesa/mesa#842]
**Describe the bug**

when run BatchRunnerMP in version 0.8.7,  It will report "TypeError: can't pickle dict_values objects",  however, we change version to 0.8.6, It works well.
**Expected behavior**

**To Reproduce**

**Additional context**

**Comment by tpike3** [comment]
Chenyuyou, please see issue 787. https://github.com/projectmesa/mesa/issues/787 

Could you please confirm your operating system?

**Comment by chenyuyou** [comment]
I try run BatchRunnerMP in Mac OS and Windows 10, both of them report this error.

**Comment by chenyuyou** [comment]
> Chenyuyou, please see issue 787. #787
> 
> Could you please confirm your operating system?

Traceback (most recent call last):
  File "batch_run.py", line 120, in <module>
    run()
  File "batch_run.py", line 108, in run
    br_df = br.get_model_vars_dataframe()
AttributeError: 'BatchRunnerMP' object has no attribute 'get_model_vars_dataframe'

**Comment by chenyuyou** [comment]
> > Chenyuyou, please see issue 787. #787
> > Could you please confirm your operating system?
> 
> I try two file in issue 787 and run model with them, the bug is fixed, but cause new bug， because the function get_model_vars_dataframe() in batchrunner_local.py had been deleted.
> 
> Traceback (most recent call last):
> File "batch_run.py", line 120, in
> run()
> File "batch_run.py", line 108, in run
> br_df = br.get_model_vars_dataframe()
> AttributeError: 'BatchRunnerMP' object has no attribute 'get_model_vars_dataframe'

I read the source code of batchrunner_local.py, and know how to get the result. but I think adding some code to organize result data, I add pd.concat function in batchrunner_local.py as temporary solution.
