### ISSUE TITLE
Money Model running error

### ISSUE THREAD

**Issue by HannahG1250** [projectmesa/mesa#847]
Hi all,

I am new to python and using Mesa. I am working through the advanced tutorial in the Mesa documentation however I get this:

/site-packages/mesa/visualization/ModularVisualization.py", line 314, in reset_model
    self.model = self.model_cls(**model_params)
TypeError: 'module' object is not callable

Has anyone encountered this error?

I have attached my code. Any help would be very much appreciated. Thank you in advance

[MoneyModel.zip](https://github.com/projectmesa/mesa/files/4667324/MoneyModel.zip)

**Comment by tpike3** [comment]
You import MoneyModel in two different ways with the second one overriding the first in your server.py. 

In line 1  From MoneyModel import *, in line 4 you have import MoneyModel again. Delete line 4 and it should work. 

Please let me know if it works so I can close this issue.

**Comment by HannahG1250** [comment]
Hi tpike3,

Thank you for getting back to me. I have amended the code when importing the money model however I am still getting the same error.

Do you have any other suggestions?

Many thanks

**Comment by tpike3** [comment]
Can you can you copy and paste your Tutorial.py code into a reply. I successfully replicated your error and when I made that change it eliminated the error.

**Comment by HannahG1250** [comment]
Hi tpike3 here is my code:

from mesa import Agent, Model
from mesa.time import RandomActivation
from mesa.space import MultiGrid
from mesa.datacollection import DataCollector
from mesa.batchrunner import BatchRunner


def compute_gini(model):
    agent_wealths = [agent.wealth for agent in model.schedule.agents]
    x = sorted(agent_wealths)
    N = model.num_agents
    B = sum( xi * (N-i) for i,xi in enumerate(x) ) / (N*sum(x))
    return (1 + (1/N) - 2*B)

class MoneyModel(Model):
    """A model with some number of agents."""
    def __init__(self, N, width, height):
        self.num_agents = N
        self.grid = MultiGrid(width, height, True)
        self.schedule = RandomActivation(self)
        self.running = True
        # Create agents
        for i in range(self.num_agents):
            a = MoneyAgent(i, self)
            self.schedule.add(a)
            # Add the agent to a random grid cell
            x = self.random.randrange(self.grid.width)
            y = self.random.randrange(self.grid.height)
            self.grid.place_agent(a, (x, y))
            
        self.datacollector = DataCollector(
            model_reporters={"Gini": compute_gini},  # `compute_gini` defined above
            agent_reporters={"Wealth": "wealth"})

    def step(self):
        self.datacollector.collect(self)
        self.schedule.step()

class MoneyAgent(Agent):
    """ An agent with fixed initial wealth."""
    def __init__(self, unique_id, model):
        super().__init__(unique_id, model)
        self.wealth = 1

    def move(self):
        possible_steps = self.model.grid.get_neighborhood(
            self.pos,
            moore=True,
            include_center=False)
        new_position = self.random.choice(possible_steps)
        self.model.grid.move_agent(self, new_position)

    def give_money(self):
        cellmates = self.model.grid.get_cell_list_contents([self.pos])
        if len(cellmates) > 1:
            other = self.random.choice(cellmates)
            other.wealth += 1
            self.wealth -= 1

    def step(self):
        self.move()
        if self.wealth > 0:
            self.give_money()
# MoneyModel(number of agents, gridsize, gridsize)
model = MoneyModel(50,10,10)
for i in range(100):
    model.step()

# For a jupyter notebook add the following line:

# The below is needed for both notebooks and scripts
import matplotlib.pyplot as plt

agent_wealth = [a.wealth for a in model.schedule.agents]
plt.hist(agent_wealth)

all_wealth = []
for j in range(50):
    # Run the model
    model = MoneyModel(50,10,10)
    for i in range(100):
        model.step()

    # Store the results
    for agent in model.schedule.agents:
        all_wealth.append(agent.wealth)

plt.hist(all_wealth, bins=range(max(all_wealth)+1))


import numpy as np

agent_counts = np.zeros((model.grid.width, model.grid.height))
for cell in model.grid.coord_iter():
    cell_content, x, y = cell
    agent_count = len(cell_content)
    agent_counts[x][y] = agent_count
plt.imshow(agent_counts, interpolation='nearest')
plt.colorbar()

gini = model.datacollector.get_model_vars_dataframe()
gini.plot()

agent_wealth = model.datacollector.get_agent_vars_dataframe()
agent_wealth.head()

end_wealth = agent_wealth.xs(99, level="Step")["Wealth"]
end_wealth.hist(bins=range(agent_wealth.Wealth.max()+1))

# plots the data FOR THE 14TH AGENT
one_agent_wealth = agent_wealth.xs(14, level="AgentID")
one_agent_wealth.Wealth.plot()

fixed_params = {
    "width": 10,
    "height": 10
}

variable_params = {"N": range(10, 500, 100)}

# The variables parameters will be invoke along with the fixed parameters allowing for either or both to be honored.
batch_run = BatchRunner(
    MoneyModel,
    variable_params,
    fixed_params,
    iterations=5,
    max_steps=100,
    model_reporters={"Gini": compute_gini}
)

batch_run.run_all()

run_data = batch_run.get_model_vars_dataframe()
run_data.head()
plt.scatter(run_data.N, run_data.Gini)

**Comment by HannahG1250** [comment]
from mesa import Agent, Model
from mesa.time import RandomActivation
from mesa.space import MultiGrid
from mesa.datacollection import DataCollector
from mesa.batchrunner import BatchRunner


def compute_gini(model):
    agent_wealths = [agent.wealth for agent in model.schedule.agents]
    x = sorted(agent_wealths)
    N = model.num_agents
    B = sum( xi * (N-i) for i,xi in enumerate(x) ) / (N*sum(x))
    return (1 + (1/N) - 2*B)

class MoneyModel(Model):
 
    def __init__(self, N, width, height):
        self.num_agents = N
        self.grid = MultiGrid(width, height, True)
        self.schedule = RandomActivation(self)
        self.running = True

        for i in range(self.num_agents):
            a = MoneyAgent(i, self)
            self.schedule.add(a)

            x = self.random.randrange(self.grid.width)
            y = self.random.randrange(self.grid.height)
            self.grid.place_agent(a, (x, y))
            
        self.datacollector = DataCollector(
            model_reporters={"Gini": compute_gini},  
            agent_reporters={"Wealth": "wealth"})

    def step(self):
        self.datacollector.collect(self)
        self.schedule.step()

class MoneyAgent(Agent):

    def __init__(self, unique_id, model):
        super().__init__(unique_id, model)
        self.wealth = 1

    def move(self):
        possible_steps = self.model.grid.get_neighborhood(
            self.pos,
            moore=True,
            include_center=False)
        new_position = self.random.choice(possible_steps)
        self.model.grid.move_agent(self, new_position)

    def give_money(self):
        cellmates = self.model.grid.get_cell_list_contents([self.pos])
        if len(cellmates) > 1:
            other = self.random.choice(cellmates)
            other.wealth += 1
            self.wealth -= 1

    def step(self):
        self.move()
        if self.wealth > 0:
            self.give_money()

model = MoneyModel(50,10,10)
for i in range(100):
    model.step()


import matplotlib.pyplot as plt

agent_wealth = [a.wealth for a in model.schedule.agents]
plt.hist(agent_wealth)

all_wealth = []
for j in range(50):

    model = MoneyModel(50,10,10)
    for i in range(100):
        model.step()


    for agent in model.schedule.agents:
        all_wealth.append(agent.wealth)

plt.hist(all_wealth, bins=range(max(all_wealth)+1))


import numpy as np

agent_counts = np.zeros((model.grid.width, model.grid.height))
for cell in model.grid.coord_iter():
    cell_content, x, y = cell
    agent_count = len(cell_content)
    agent_counts[x][y] = agent_count
plt.imshow(agent_counts, interpolation='nearest')
plt.colorbar()

gini = model.datacollector.get_model_vars_dataframe()
gini.plot()

agent_wealth = model.datacollector.get_agent_vars_dataframe()
agent_wealth.head()

end_wealth = agent_wealth.xs(99, level="Step")["Wealth"]
end_wealth.hist(bins=range(agent_wealth.Wealth.max()+1))


one_agent_wealth = agent_wealth.xs(14, level="AgentID")
one_agent_wealth.Wealth.plot()

fixed_params = {
    "width": 10,
    "height": 10
}

variable_params = {"N": range(10, 500, 100)}


batch_run = BatchRunner(
    MoneyModel,
    variable_params,
    fixed_params,
    iterations=5,
    max_steps=100,
    model_reporters={"Gini": compute_gini}
)

batch_run.run_all()

Hi tpike here is my code from the tutorial:

run_data = batch_run.get_model_vars_dataframe()
run_data.head()
plt.scatter(run_data.N, run_data.Gini)

**Comment by tpike3** [comment]
When you run the visualization are you commenting out everything below the MoneyAgent Class. 

starting at 
` model = MoneyModel(50,10,10)`

~line 50

**Comment by HannahG1250** [comment]
Hi tpike 3,

I wasn't, but I have just tried but I still get the same error:

    self.model = self.model_cls(**model_params)
TypeError: 'module' object is not callable

It doesn't seem to like the following line: 
server = ModularServer(MoneyModel,[grid],"Money Model",{"N":100, "width":10, "height":10})

**Comment by tpike3** [comment]
@HannahG1250 at this point it would probably be best to do like a Google Meet or similar. so you can do a screen share of you code and computer set up. Let me know if that works and some potential times, my email is tpike3@gmu.edu.

**Comment by tpike3** [comment]
Identified the issue was an error running script from bash. Code worked in typical IDE.
