### ISSUE TITLE
Improving the efficiency of  saving data

### ISSUE THREAD

**Issue by chenyuyou** [projectmesa/mesa#849]
I  spend only 5 minus to run my model 10000 iteration with BatchRunnerMP function,  but  spend over 60 minus to save data. The saving data code in my model comes from  example of  "bank_reserves". 

How do I improve my code to save data?

**Comment by chenyuyou** [comment]
I have figured out this problem

**Comment by tpike3** [comment]
Thanks for the feedback. To be clear you were able to run batchrunner_local.py on both your Mac OS and Windows OS systems?

**Comment by chenyuyou** [comment]
> Thanks for the feedback. To be clear you were able to run batchrunner_local.py on both your Mac OS and Windows OS systems?

Thank you for you help !
