### ISSUE TITLE
Cookiecutter doesn't work on 0.8.7 release

### ISSUE THREAD

**Issue by NeilW** [projectmesa/mesa#850]
**Describe the bug**
`mesa startproject` fails after `pipenv install mesa`
```
A valid repository for "/home/neil/.local/share/virtualenvs/baseline-economy-6fg_iky1/lib/python3.8/site-packages/mesa/cookiecutter-mesa" could not be found in the following locations:
...
```

**Expected behavior**
Generate the project layout

**To Reproduce**
- pipenv install mesa
- mesa startproject

**Additional context**
The cookiecutter directory from the repo is missing from the installation.
Additionally there is no help message for `startproject` when you run `mesa --help`

**Comment by jackiekazil** [comment]
@NeilW Ty for highlighting this error. I believe the pull request linked in this ticket will solve the issue in the next release. 

If you would like to use this feature before this next release, you can install from the github repo - `pip install -e git+https://github.com/projectmesa/mesa#egg=mesa`
