### ISSUE TITLE
API Documentation for Space module not available on readthedocs.io

### ISSUE THREAD

**Issue by shivanshseth** [projectmesa/mesa#855]
**Describe the bug**
The API documentation section in mesa.readthedocs.io is missing the Space module.
**Expected behavior**
Space module API should be accessible through readthedocs.io
**To Reproduce**
https://mesa.readthedocs.io/en/master/apis/api_main.html

**Comment by Corvince** [comment]
Thanks for the bug report. The API documentation for the base module are also missing.
