### ISSUE TITLE
BatchRunner: Parameter names wrong in data frame output

### ISSUE THREAD

**Issue by NeilW** [projectmesa/mesa#858]
**Describe the bug**
The parameter names are being combined with the wrong data items in `_prepare_report_table`

**Expected behavior**
The DataFrame would have the correct column heading for the parameter product

**To Reproduce**
- Create a variable parameter list with more than one parameter (I have 4). 
- Create a BatchRunner instance
- `br.run_all()`
- `output = br.get_model_vars_dataframe() `
- `print(output)`

**Additional context**
The problem is using a set to collect the parameter keys. It doesn't maintain the same order as the tuple used to store the parameter settings for a run.

**Comment by tpike3** [comment]
@NeilW Looking through the BatchRunner I am not seeing any sets only lists and dictionaries. Could you give the line(s) and module where you are seeing the set. Thanks

**Comment by NeilW** [comment]
https://github.com/projectmesa/mesa/blob/master/mesa/batchrunner.py#L228

**Comment by tpike3** [comment]
@NeilW Thanks I am going to have to dig into this a little bit as this function did not change from previous versions and we have not had this issue before.

**Comment by NeilW** [comment]
Replication code

```
param_list = [
    {'firm_liquidity': 0, 'household_liquidity': 500,
     'num_households': 1000, 'num_firms': 100},
    {'firm_liquidity': 0, 'household_liquidity': 5000,
     'num_households': 1000, 'num_firms': 100}]

cols = set()
for params in param_list:
    cols |= params.keys()
print(param_list)
print(cols)
```

Which gives here on Ubuntu 20.04

```
$ python -V
Python 3.8.2
$ python /tmp/repl.py
[{'firm_liquidity': 0, 'household_liquidity': 500, 'num_households': 1000, 'num_firms': 100}, {'firm_liquidity': 0, 'household_liquidity': 5000, 'num_households': 1000, 'num_firms': 100}]
{'household_liquidity', 'firm_liquidity', 'num_firms', 'num_households'}
```

**Comment by NeilW** [comment]
This would be my fix which uses the same ordering guarantee as the original dict

```
param_list = [
    {'firm_liquidity': 0, 'household_liquidity': 500,
     'num_households': 1000, 'num_firms': 100},
    {'firm_liquidity': 0, 'household_liquidity': 5000,
     'num_households': 1000, 'num_firms': 100}]

extra_cols = None
extra_cols = ["Run"] + (extra_cols or [])
index_cols = {}
for params in param_list:
    index_cols.update(params)
index_cols = list(index_cols.keys()) + extra_cols
print(param_list)
print(index_cols)
```

which gives here:

```
$ python /tmp/fix.py 
[{'firm_liquidity': 0, 'household_liquidity': 500, 'num_households': 1000, 'num_firms': 100}, {'firm_liquidity': 0, 'household_liquidity': 5000, 'num_households': 1000, 'num_firms': 100}]
['firm_liquidity', 'household_liquidity', 'num_households', 'num_firms', 'Run']
$ python /tmp/fix.py 
[{'firm_liquidity': 0, 'household_liquidity': 500, 'num_households': 1000, 'num_firms': 100}, {'firm_liquidity': 0, 'household_liquidity': 5000, 'num_households': 1000, 'num_firms': 100}]
['firm_liquidity', 'household_liquidity', 'num_households', 'num_firms', 'Run']
```

**Comment by Casper-Smet** [comment]
Are there any updates regarding this issue? My team is running into this issue currently.

**Comment by tpike3** [comment]
It was fixed, if you pip install from github versus pypi it will keep the columns correct. 

Let me know if you have any issues.

**Comment by Casper-Smet** [comment]
That fixed it, is there an ETA for pypi to get updated? The documentation also seems to be old.

**Comment by tpike3** [comment]
Excellent!

 As for PyPI update, I will bring it up at the next dev meeting. I would spitball latest May.
