### ISSUE TITLE
Unreasonable amount of time spent on self.empties.remove(pos) in space.py

### ISSUE THREAD

**Issue by bastiaanzwanenburg** [projectmesa/mesa#860]
**Describe the bug**
I have a grid of size 1000x700, and whenever I initialize this grid, one function that removes grid-points from the list of empty grid-points takes up about 16 seconds for 1300 calls - which is almost all of my runtime. 

The line is: self.emtpies.remove(pos) inside _place_agent() inside space.py. 

Does anyone have any suggestions for increasing the speed of this function?

**Expected behavior**
Faster!

**To Reproduce**
On a "large" grid.

**Additional context**
Python 3.7.3 on Mac OS.

**Comment by Corvince** [comment]
This shouldn't happen with the latest version of mesa. Can you confirm that you are running mesa 0.8.7 ? Otherwise please upgrade and try again.

**Comment by bastiaanzwanenburg** [comment]
I'm using 0.8.6 as BatchRunnerMP doesn't work for me in 0.8.7 (this issue: https://github.com/projectmesa/mesa/issues/842). 

I just updated to 0.8.7 to see if the model would run, however, I now get the error below. Is it something you recognize and have an easy fix / hypothesis for? If not, I will do some debugging myself.

  File "/Users/bastiaan/virtualEnvs/new/lib/python3.7/site-packages/mesa/batchrunner.py", line 356, in __init__
    ParameterProduct(variable_parameters),
  File "/Users/bastiaan/virtualEnvs/new/lib/python3.7/site-packages/mesa/batchrunner.py", line 257, in __init__
    *(copy.deepcopy(variable_parameters)).items()
AttributeError: 'NoneType' object has no attribute 'items'

**Comment by Corvince** [comment]
I think @tpike3 is working on fixing that problem and the issue #842 and  #787

In the meantime you could also try to apply PR #649 to your local version 0.8.6. This changed `empties` from a list to a set and should solve the performance issues

**Comment by bastiaanzwanenburg** [comment]
Thanks a lot! Sorry for not spotting https://github.com/projectmesa/mesa/pull/649 earlier, that is exactly the fix I was looking for.
