### ISSUE TITLE
`BatchRunner` does not accept empty or `None` as `variable_parameters`

### ISSUE THREAD

**Issue by YannickJadoul** [projectmesa/mesa#861]
**Describe the bug**
When passing an empty dictionary as `variable_parameters` argument to the `BatchRunner` constructor, or when omitting the argument, Mesa throws an `AttributeError: 'NoneType' object has no attribute 'items' `.

**Expected behavior**
Since `None` is the default argument for the `variable_parameters` parameter, it would make sense that this is a valid value, supported by Mesa. It could also be convenient to be able to pass an empty dict or `None` when running exploratory experiments, to avoid unnecessary switching between `BatchRunner` and `FixedBatchRunner`.

**To Reproduce**
```pycon
>>> mesa.batchrunner.BatchRunner(Model, fixed_parameters={'foo': 'bar'})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/yannick/.local/lib/python3.6/site-packages/mesa/batchrunner.py", line 356, in __init__
    ParameterProduct(variable_parameters),
  File "/home/yannick/.local/lib/python3.6/site-packages/mesa/batchrunner.py", line 257, in __init__
    *(copy.deepcopy(variable_parameters)).items()
AttributeError: 'NoneType' object has no attribute 'items'
```

I'm creating a (very minor) PR now, to fix this.

**Comment by tpike3** [comment]
Merged into BatchRunner_redux
