### ISSUE TITLE
How to "simply have a reporter store the model’s entire DataCollector object"?

### ISSUE THREAD

**Issue by ericmjl** [projectmesa/mesa#865]
In the docs page for [Batchrunner](https://mesa.readthedocs.io/en/master/apis/batchrunner.html#id1), one line gave me a bit of pause:

> Note that by default, the reporters only collect data at the end of the run. To get step by step data, simply have a reporter store the model’s entire DataCollector object.

May I ask, is there an example of this somewhere on the docs?

If not, would anybody here be kind enough to provide an example? I would be happy to help add this to the relevant docstrings, as an example, so that others can benefit.

**Comment by tpike3** [comment]
@ericmjl If you look in the [introductory tutorial](https://mesa.readthedocs.io/en/master/tutorials/intro_tutorial.html#collecting-data) it has a clear explanation and an example under DataCollection. 

Short version, inside the model step function you need to add: 
`self.datacollector.collect(self)`

Then in BatchRunner you will get the whole output for each step for that particular variation of the run. 

Let me know if you have any problems as I am working through some updates to BatchRunner right now.

**Comment by ericmjl** [comment]
Thank  you, @tpike3! I am going to mentally bookmark this for when I get back to my code on Tuesday. I will loop back and let you know.

Meanwhile, I think it might be helpful to add the exact line you referenced in the [Batchrunner docs](https://mesa.readthedocs.io/en/master/apis/batchrunner.html). Would you be open to a PR for this?

**Comment by tpike3** [comment]
@ericmjl  Yes, I would. Just please PR to branch BatchRunner_Redux so I can keep them all together and make sure the testing voers everything

**Comment by Corvince** [comment]
@ericmjl
I think what the docs mean is that you need to collect the DC inside the batchrunners' model reporters like so:

```python
batch_run = BatchRunner(
    MyModel, 
    parameters, 
    max_steps=10,
    model_reporters={
        "datacollector": lambda m: m.dc
    }
)
```

This also answers your side issue: The model reporter from the datacollector collects data at every step (or rather whenever you tell him so, but normally inside the `step` function), whereas the batchrunner model reporter only collects data at the end of each run.

**Comment by tpike3** [comment]
@ericmjl Thanks! The gist link you sent is not working for me, I keep getting an error.

@ericmjl and @Corvince  That is interesting, this is actually a point I am trying work through right now as it seems my batchrunner tests are causing my data collector tests to fail and vice versa. It seems the data collector and the batchrunner don't talk which as Corvince pointed out is preventing the batchrunner getting the data collector data. Interestingly, the model tests for batchrunner are not written as Corvince suggested so I will give that a try as a more elegant solution than I was thinking.

**Comment by tpike3** [comment]
Closing this issues based on batchrunner updates.

**Comment by adrien-perello** [comment]
In case it would interest some, I wrote a script to collect the entire time series for each variables in `model_reporters`


## Final result

The result looks like this:

![Screenshot from 2021-11-10 14-57-10](https://user-images.githubusercontent.com/76055749/141126562-7fad4663-b837-48ad-be74-331db6a4e0e2.png)

where 
- the coordinates represent the variable parameters  
    - here `N` (the number of agents)
    - number of iterations (`Run`)
    - each tick / time step (`Step`)
- Data variables represent the content of `model_reporters`
- The attributes represent the fixed parameters 
    - here width and height


## Script

First, in BatchRunner, I collect the data as dictionnaries

```python
batch_run = BatchRunner(
    MyModel, 
    parameters, 
    max_steps=10,
    model_reporters={
        "datacollector": lambda model: model.datacollector.get_model_vars_dataframe().to_dict()
    }
)
```

And then, I use the following functions:

```python
def generate_df(batch_run):
    # get dataframe from batch_run
    run_data = batch_run.get_model_vars_dataframe()
    # drop fixed parameters (unecessary)
    fixed_params_idx = list(batch_run.fixed_parameters.keys())
    run_data.drop(fixed_params_idx, axis=1, inplace=True)
    # convert 'Run' number (=unique id) to iteration number
    # (for use as coordinate of future xarray)
    run_data["Run"] = run_data["Run"] % batch_run.iterations
    # keep track of columns that will become indexes
    # (= all but datacollectors)
    indexes = list(run_data.drop("datacollectors", axis=1).columns)
    # unnest data contained in datacollectors into new columns
    run_data = expand_from_nested_records(run_data, "datacollectors")
    # keep track of new columns indexes (= variable names)
    variables = list(set(run_data.columns) - set(indexes))
    # reset index
    run_data.set_index(indexes, inplace=True, drop=True)
    # unnest values inside new columns (= dict) 
    return unnested_columns(run_data, variables)


def generate_xr(batch_run):
    # generate cleaned dataframe
    df = generate_df(batch_run)
    # da = df.to_xarray().drop(fixed_params_idx).squeeze()
    da = df.to_xarray()
    # set fixed params as attributes rather than coords
    da.attrs = batch_run.fixed_parameters
    return da
```

also, `generate_df` use the following 2 functions:

```python
def expand_from_nested_records(df, column, drop=True):
    df_expanded = pd.DataFrame.from_records(df[column])
    df_final = pd.concat([df, df_expanded], axis=1)
    return df_final.drop(column, axis=1) if drop else df_final


def unnested_columns(df, columns):
    return (pd.concat(
            [pd.DataFrame(df[x].tolist(), index=df.index)
                for x in columns],
            axis=1,
            keys=columns,
        )
        .stack()
        .rename_axis(index={None: "Step"})
    )
```
