### ISSUE TITLE
RuntimeError: This event loop is already running

### ISSUE THREAD

**Issue by SHSEngineering** [projectmesa/mesa#866]
I've been trying to work through the advanced tutorial on the website and can't get past this runtime error.

Here is the error listing that I get...

Interface starting at http://127.0.0.1:8521
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-3-4ed4a14b2c34> in <module>
     12                        {"N":100, "width":10, "height":10})
     13 server.port = 8521  #The default port
---> 14 server.launch()

~\AppData\Roaming\Python\Python37\site-packages\mesa\visualization\ModularVisualization.py in launch(self, port, open_browser)
    335             webbrowser.open(url)
    336         tornado.autoreload.start()
--> 337         tornado.ioloop.IOLoop.current().start()

C:\ProgramData\Anaconda3\lib\site-packages\tornado\platform\asyncio.py in start(self)
    151             self._setup_logging()
    152             asyncio.set_event_loop(self.asyncio_loop)
--> 153             self.asyncio_loop.run_forever()
    154         finally:
    155             asyncio.set_event_loop(old_loop)

C:\ProgramData\Anaconda3\lib\asyncio\base_events.py in run_forever(self)
    523         self._check_closed()
    524         if self.is_running():
--> 525             raise RuntimeError('This event loop is already running')
    526         if events._get_running_loop() is not None:
    527             raise RuntimeError(

RuntimeError: This event loop is already running

Socket opened!
{"type":"reset"}

Here is the code cell that is running when I get the error

def agent_portrayal(agent):
    portrayal = {"Shape": "circle",
                 "Color": "red",
                 "Filled": "true",
                 "r": 0.5}
    return portrayal

grid = CanvasGrid(agent_portrayal, 10, 10, 500, 500)
server = ModularServer(MoneyModel,
                       [grid],
                       "Money Model",
                       {"N":100, "width":10, "height":10})
server.port = 8521  #The default port
server.launch()

I've already coded the MoneyModel and it works fine, but the visualization part is where I'm having the trouble.  I've been coding this in Jupyter Notebooks, but have also tried Spyder and gotten the same error.

Please help

**Comment by tpike3** [comment]
@SHSEngineering I am making a couple assumptions here, but with Ipython which is used in both Jupyter Notebook and Spyder you have to reset the kernel to clear out the old visualization otherwise the port is still in use. For jupyter you need to clear with restart and clear outputs. For Spyder in the ipython window click the setting gear (upper right with standard config) and select restart kernel. The other option is to change the port number, but know you will keep putting ports in use. 

Let me know if that works.

**Comment by SHSEngineering** [comment]
Thanks for the quick response.  I’ve done what you suggested on multiple occasions with the same results.  From the web research I’ve done, I get notes on an issue with asyncio and current updates to jupyter/spyder.  I just can’t seem to fix it.  Again, hoping you can provide insight.  Thanks.

Steve Unterholzner

**Comment by dmasad** [comment]
There seems to be a known issue with tornado and the newer version of Python, but I need to look into the details (and try to reproduce it on my own). Have you tried running the same code outside of Spyder/Jupyter via a plain .py file? If that works, the problem is probably something with how it's interacting with Spyder; if not, then it's a problem with mesa and tornado.

**Comment by SHSEngineering** [comment]
When I run it as a plain .py file...I get this error

Traceback (most recent call last):
  File "C:\Users\sunte\AppData\Local\Programs\Python\Python38\MoneyModelVis2.py", line 24, in <module>
    server.launch()
  File "C:\Users\sunte\AppData\Local\Programs\Python\Python38\lib\site-packages\mesa\visualization\ModularVisualization.py", line 333, in launch
    self.listen(self.port)
  File "C:\Users\sunte\AppData\Local\Programs\Python\Python38\lib\site-packages\tornado\web.py", line 2116, in listen
    server.listen(port, address)
  File "C:\Users\sunte\AppData\Local\Programs\Python\Python38\lib\site-packages\tornado\tcpserver.py", line 152, in listen
    self.add_sockets(sockets)
  File "C:\Users\sunte\AppData\Local\Programs\Python\Python38\lib\site-packages\tornado\tcpserver.py", line 165, in add_sockets
    self._handlers[sock.fileno()] = add_accept_handler(
  File "C:\Users\sunte\AppData\Local\Programs\Python\Python38\lib\site-packages\tornado\netutil.py", line 279, in add_accept_handler
    io_loop.add_handler(sock, accept_handler, IOLoop.READ)
  File "C:\Users\sunte\AppData\Local\Programs\Python\Python38\lib\site-packages\tornado\platform\asyncio.py", line 100, in add_handler
    self.asyncio_loop.add_reader(fd, self._handle_events, fd, IOLoop.READ)
  File "C:\Users\sunte\AppData\Local\Programs\Python\Python38\lib\asyncio\events.py", line 501, in add_reader
    raise NotImplementedError
NotImplementedError

**Comment by tpike3** [comment]
@SHSEngineering sorry for the delay, were you able to resolve this?

**Comment by SHSEngineering** [comment]
not sure if resolved is the correct term ... I began playing with the examples included in the zip file and those work, but I still get the error I mentioned above.  So, since the models appear to run, I'm ignoring the error message.

**Comment by tpike3** [comment]
@SHSEngineering Thanks for the feedback!
