### ISSUE TITLE
How to remove Gridlines

### ISSUE THREAD

**Issue by SHSEngineering** [projectmesa/mesa#875]
I am trying to remove the gridlines but haven't been able to ... I've explored the javascript files and the css files, but haven't found out where I can change the code to either remove the gridlines or make them invisible.  Is there someone who might be able to provide insight into this???  i've attached a pic of the grid as it currently looks ... Ideally, I'd like to keep the grid lines but make them invisible.

![Capture](https://user-images.githubusercontent.com/58575230/88983651-780d3600-d280-11ea-861f-296ea962c970.PNG)

**Comment by majdal** [comment]
Just comment out line 31 in `CanvasModule.js` file:

https://github.com/projectmesa/mesa/blob/2e66e9f70f9b4c58d90654ba590fc011263c483c/mesa/visualization/templates/js/CanvasModule.js#L31

Maybe I'll create a pull request to make drawing the grid line optional, controlled by a boolean parameter passed to `CanvasGrid` class? (but only after I defend my thesis in a couple of weeks!)

**Comment by jackiekazil** [comment]
@majdal good luck on your thesis defense! Whenever you have a moment -- we welcome the contribution!

**Comment by LelandYan** [comment]
@majdal I had done that , but the gridlines  line still existed. Can you help me? Thanks very much!

**Comment by dmasad** [comment]
@LelandYan Have you made sure to force-refresh the page when it reruns (e.g. Ctrl/Cmd-F5)? Sometimes browsers cache some of the underlying JavaScript, and use the older version even when you've updated the code.

**Comment by rht** [comment]
Closing because https://github.com/projectmesa/mesa/issues/875#issuecomment-757079079 has the solution.
