### ISSUE TITLE
Command not found: Mesa 

### ISSUE THREAD

**Issue by fozzydiablo** [projectmesa/mesa#879]
Just trying to work from the examples given on [here](https://mesa.readthedocs.io/en/master/)
After installing mesa with pip3 I then clone the repository.
When I try to runserver I get the error zsh: command not found: mesa
This is my path 
`['',
 '/Library/Frameworks/Python.framework/Versions/3.7/lib/python37.zip',
 '/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7',
 '/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload',
 '/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages']`

**Comment by fozzydiablo** [comment]
I ran it in a ve and it worked. Not sure what the problem was

**Comment by tpike3** [comment]
Thanks, we will keep this in mind and see if any similar bugs crops up
