### ISSUE TITLE
Agent no longer receiving instructions from scheduler 

### ISSUE THREAD

**Issue by pineappleater** [projectmesa/mesa#880]
I have a transport ABM with both bikes and vans as moving agents. When only either of them is loaded, the model works perfectly as intended. These agents don't interact with each other at all in the code. When both are loaded after a all agents are loaded the first agent spontaneously stops and is no longer taking any steps( confirmed by print commands) but the rest of the model is working (also confirmed by print commands). My code is far from elegant and is quite rough but it works as can be seen when only one type of agent is loaded. My question is why does the agent stop.
Just run the code to replicate the issue and feel free to ask me to clarify anything.

[Model ABM Practice.zip](https://github.com/projectmesa/mesa/files/5075563/Model.ABM.Practice.zip)

**Comment by tpike3** [comment]
@pineappleater Could you post your init code for the model where you add agents to the scheduler? I would like to try this first so other users can more easily see your code and use it to help the with their issues.

**Comment by pineappleater** [comment]
So the agents are appended to a list which the scheduler uses to make and place agents. This is the code for the model. Please let me know if you need anything else.
`#Model


class VanByke(Model):
    """A model with some number of agents."""
    
    def __init__(self,width, height, N=20,BC=2,VC=10,R=1,T=1):
        super().__init__()
        #self.num_agents = 1
        self.Total_Parcels=N
        self.Bike_Capacity=BC
        self.Van_Capacity=VC
        self.Ratio_of_vans_to_bikes=R
        #is used to calcualte other vehicles by multiplyig the variable by the sum of vans and bikes
        self.Traffic_Level_multiplier=T
        self.Total_Bikes=find_bikes_req(self.Total_Parcels,self.Ratio_of_vans_to_bikes,self.Van_Capacity,self.Bike_Capacity)
        self.Total_Vans=find_vans_req(self.Total_Parcels,self.Ratio_of_vans_to_bikes,self.Van_Capacity,self.Bike_Capacity)
        self.Total_Cars=Traffic_Level_multiplier*(self.Total_Bikes+self.Total_Vans)
        self.Parcel_list=[*range(0,self.Total_Parcels)]
        self.grid = MultiGrid(width, height, True)
        self.place=0
        self.all_vehicles=[]
        
        self.schedule = RandomActivation(self)
        
        type_distribution = np.genfromtxt("road_map.txt")
        
        #create curb
        for _,x, y in self.grid.coord_iter():
            if type_distribution[x,y]==3: #3 is the chosen identifier for curb side in the txt doc
                new_spot=curb_border((x,y),self)
                
                self.grid.place_agent(new_spot,(x, y))
                self.schedule.add(new_spot)
        
        #create buildings
        for _,x, y in self.grid.coord_iter():
            if type_distribution[x,y]==4: #4 is the chosen identifier for buildings in the txt doc
                
                new_building=building((x,y),self,[self.Parcel_list[random.randint(0, self.Total_Parcels-1)]])
                #print(self.loading_bays)
                
                
                self.grid.place_agent(new_building,(x, y))
                self.schedule.add(new_building)
                
                
        
        
    
    
        #create vans
        
        
        for i in range(self.Total_Vans):
            nit=[]
            for l in range(self.Van_Capacity):
                if len(self.Parcel_list)>0:
                
                    nit.append(self.Parcel_list[-1])
                    self.Parcel_list.pop()
            b=vans(i, self, nit)
            
            self.all_vehicles.append(b)
        
        
        #create bikes 
        
        
        for i in range(self.Total_Bikes):
            nit=[]
            
            for l in range(self.Bike_Capacity):
                if len(self.Parcel_list)>0:
                
                    nit.append(self.Parcel_list[-1])
                    self.Parcel_list.pop()
            a=bikes(i, self, nit)
            
            self.all_vehicles.append(a)
        
           
                   
        self.running = True
    
       
    def step(self):
        print(self.all_vehicles)
        self.schedule.step()
        print("stepping in model")
        if len(self.all_vehicles)>0 and [*range(0,2000)][self.place]%2==0:
                #random.shuffle(self.all_vehicles)
                self.schedule.add(self.all_vehicles[-1])
                self.grid.place_agent(self.all_vehicles[-1],(0,0))
                self.all_vehicles.pop()
                print("placing")
        
        self.place+=1`

**Comment by pineappleater** [comment]
Different agents were receiving the same unique id. Now Solved

**Comment by tpike3** [comment]
Awesome! Glad you solved and thanks for posting. Agent "breeds"/"types" can get pretty tricky and I am sure this will help some other modelers.
