### ISSUE TITLE
Identify the iteration number when several iterations of the model are run in parallel

### ISSUE THREAD

**Issue by ranjitshanker** [projectmesa/mesa#881]
I am running several iterations of the model in parallel using BatchRunnerMP. 
Is there a variable that can be used inside the Model  class to identify the iteration number for each of the iteration?

**Comment by tpike3** [comment]
You can use pbar update. This is in the [BatchRunnerMP update](https://github.com/projectmesa/mesa/pull/871/files)  Extract from code below.

`
        results = {}

        if self.processes > 1:
            with tqdm(total_iterations, disable=not self.display_progress) as pbar:
                for params, model in self.pool.imap_unordered(self.run_wrappermp, run_iter_args):
                    results[params] = model
                    pbar.update()

                self.result_prep_mp(results)
`

**Comment by ranjitshanker** [comment]
Hi @tpike3 Tom, 
Thanks a lot for your reply. I am just learning mesa, so I didn't quite get it :)
I have a huge amount of info that is recorded at each timestep and to prevent RAM related issues, I am writing to the file at every timestep and resetting the datacollector as shown below (only relevant lines).

`class SIRSModel(Model):`
...
`def step(self):`        
        `    self.datacollector.collect(self)` 
        `    df_model_out = self.datacollector.get_model_vars_dataframe()`    
        `    df_model_out.to_csv(f, columns = ["Day","Prevalence","Diversity_index"])`
        `    self.datacollector = DataCollector(self.datacollector.model_reporters)`

I am running the 2 iterations of the model in parallel 
    `batch_run = BatchRunnerMP(SIRSModel,nr_processes, variable_params, fixed_params, iterations=2, max_steps, model_reporters,agent_reporters)`
   `batch_run.run_all()`


The csv file at the end of model run looks like this:
|Day|Prevalence|Diversity_index|
|---|---|---|
|1|8|4|
|1|9|4|
|2|9|4|
|2|8|4|
|3|9|4|
|3|9|4|
|4|10|4|
|4|10|3|

As you can see, there are two entries for each day - one each for iteration1 and iteration2. But I do not know which rows belongs to iteration1 and which rows belongs to iteration2.
I need to insert a column to the csv file indicating the iteration number. 
Can I use any built in (if any) variable inside the model or any other variable to get the iteration number inside the Model class?
Thanks and regards
Ranjit

**Comment by tpike3** [comment]
@ranjitshanker yes you can use the iteration number it is tracked. 

In the update/code above it is part of the run_iter_arg and is hes last element in the list so run_iter_arg[3]. I also use this to make the unique key for a dictionary of dataframe values. 

For the current version of Batchrunner it iterates through the total number so each run as a unique number associated with it. Hope this helps

**Comment by ranjitshanker** [comment]
Thank you very much @tpike3 !

**Comment by adprabhak** [comment]
Hi,
I have also run into a similar problem. I'm trying to save the some parts of the model data every time the model step function is called. 
How exactly do you use the run_iter_args[3] to track the iteration number? 
Because of huge RAM consumption, I'm trying to save the data into different files for every "time step" and iteration. By using self.schedule.steps i can seperate different time steps, how do I do this for iterations as well?

**Comment by adrien-perello** [comment]
> @ranjitshanker yes you can use the iteration number it is tracked.
> 
> In the update/code above it is part of the run_iter_arg and is hes last element in the list so run_iter_arg[3]. I also use this to make the unique key for a dictionary of dataframe values.
> 
> For the current version of Batchrunner it iterates through the total number so each run as a unique number associated with it. Hope this helps

@tpike3, Could you explain a bit more in details how you do this? I did not get it, and I run into a value error when I try to convert my dataframe to xarray due to non_unique multiindex
```python
ValueError: cannot convert a DataFrame with a non-unique MultiIndex into xarray
```

Where do you add that bit of code?
```python
results = {}
if self.processes > 1:
    with tqdm(total_iterations, disable=not self.display_progress) as pbar:
        for params, model in self.pool.imap_unordered(self.run_wrappermp, run_iter_args):
            results[params] = model
            pbar.update()
        self.result_prep_mp(results)

```
