### ISSUE TITLE
Run multiple iterations of the model after an initial burn-in period

### ISSUE THREAD

**Issue by ranjitshanker** [projectmesa/mesa#901]
**What's the problem this feature will solve?**
The model is scheduled to run for a long duration (e.g. 50 years) with an initial burn-in period (e.g. 20 years) for the population to settle down and reach an equilibrium state (i.e. no more initial spikes, etc.).
Only after this initial burn-in period is reached, I want to run multiple iterations (e.g. 10) of the model.
For example:, I do not want to run 10 iterations of the model each for 50 years. Instead I want to run the model once until 20th years is reached, and then (without starting from time = 0 again), I want to run 10 iterations each for the 21-50 year period,.

**Describe the solution you'd like**
`If self.schedule.steps <= burn_in_period: `
    `do stuff`
`else:`
    `for i in range(iterations):`
         `do stuff`

**Comment by majdal** [comment]
Another approach to solving the same problem would be the following: 

Run your model for the number of steps you need for the burn-in, save the agent-level data using the data collector, save it to file (pic your format: csv, npy, else?), then write a different method for `__init__` that loads the agent-level data from the file, and run it normally. You can use use the batch runner in that case too.

**Comment by ranjitshanker** [comment]
Thanks a lot Majd. This approach is very helpful and did not come to my mind at all :)
So, I need to save only the agent level data belonging to the last timestep in the burn-in period, isn't it?

**Comment by majdal** [comment]
That should be the case, but it's difficult to know exactly without knowing your model's details. 

It should work though: initialize your agents with the saved data from the last time step. 

I hope that helps!

**Comment by ranjitshanker** [comment]
Yes, thats what I thought. Thank you once again.

**Comment by Corvince** [comment]
You could also pickle your whole model and not have to think about how to reinstantiate
