### ISSUE TITLE
Improve 'Contributing' documentation

### ISSUE THREAD

**Issue by dmasad** [projectmesa/mesa#91]
Add detail (or at least links) to contributing.md, to help walk people through the actual mechanics of forking, creating a branch, and submitting the pull request.

**Comment by davpaez** [comment]
Hi guys. I'm relatively new to Python and git, but I would like to contribute to the project. It would be great to have a more detailed guide of:

1. How to set up a workspace (I'm using conda, but I'm not sure if this replaces virtualenv)
2. How to fork, create branch and submit pull request (as already mentioned)
3. Other ways to contribute

**Comment by dmasad** [comment]
Welcome -- and good questions! Definitely something we need to get on. In the mean time:

1. Other Mesa folks, has anyone used Conda for this? From some quick Googling, it looks like it [has its own virtual environment equivalent](http://davebehnke.com/using-python-anaconda-distribution.html) which looks like it should work the same way. 

2. Check out GitHub's [fork boot camp](https://help.github.com/articles/fork-a-repo/), and try doing that with Mesa.

One thing that would be really useful is for you to try and get Mesa running locally following those instructions, and make notes on what works and where you run into problems. That would already be a great addition to a 'how to contribute' guide!

**Comment by jackiekazil** [comment]
Hello @davpaez -- David and I were chatting the other day. I wanted to check in on you. Did you have any questions?  My email address is my github handle at gmail dot com.

**Comment by davpaez** [comment]
Hello Jackie! Thanks, I managed to get everything running :) I will add the steps I followed to get mesa working with conda. Also, I found a couple of bugs in one of the examples when using the visualization mode (in the browser).

Right now I'm finishing semester at uni, but I think next week I'll start helping out :)
Thank you guys.

David P

**Comment by jackiekazil** [comment]
That's awesome! Looking forward to it! Please reach out if you run into any
troubles that we might be able to help with!

**Comment by ReblochonMasque** [comment]
I have found the "Contributing" doc very helpful and quite complete.
Maybe this issue could be closed?

If we want to have a conda installer, a new issue can be opened.

**Comment by jackiekazil** [comment]
@ReblochonMasque ty for the feedback & closing. 
(if anyone thinks this shouldn't be closed, please pipe up OR create another ticket with the specific action that needs to be taken.)
