### ISSUE TITLE
Referencing Agent Properties from their ID obtained through "grid.get_cell_list_contents"

### ISSUE THREAD

**Issue by StueGrifn** [projectmesa/mesa#921]
Basically, I'm trying to create an agent, put it on a Grid, then find it on that grid based it's coordinates, and report back to me a variable of the agent. I have the agents created on the grid and the code (below) to get the contents of each cell. 

`class Cell(Agent):`
    `def __init__(self, unique_id, model):`
        `().__init__(unique_id, model)`
        `self.SquareNum= random (1,100)^ 2`

`class Lobule(Model):`
    `def __init__(self, width, height):`
        `self.width = width`
        `self.height = height`
       ` self.i = 0`
        `for x in range(width):`
          `  for y in range(height):`
                `a = Cell(self.i, self)`
              `  self.i += 1`
           `     self.schedule.add(a)`
          `      self.grid.place_agent(a, (x, y))`

 `def GetSquare(self):`
       ` SquareList= []`
        `for x in range(self.width): #Column`
         `   for y in range(self.height):`
             `   **print(self.grid.get_cell_list_contents((x,y)))**`
    `    print(SquareList)`

My problem is the object returned is "[<__main__.Cell object at 0x00000158AA565730>]", for example, and it's unique for each agent, which is great, except I can't for the life of me figure out how to get from this number-letter combination to accessing the variable 'self.SquareNum' again. 

Is what I'm asking for even possible? If so, how does one go about doing it? If not... any work arounds? Thanks!

**Comment by tpike3** [comment]
What is the line print(self.grid.get_cell_list_contents((x,y))) printing? Is it printing the cell contents?

**Comment by StueGrifn** [comment]
print(self.grid.get_cell_list_contents((x,y))) merely shows what the contents of the cell at position (x,y). I understand this code does not get me to the self.SquaredNum of "<_main_.Cell object at 0x00000158AA565730>"; my question is how I get from "<main.Cell object at 0x00000158AA565730>" to access the variables associated with said object, in this case "self.SquareNum".

Hope this clarifies.

**Comment by tpike3** [comment]
Yep, I just wanted to make sure there was a version or other problem. 
So if I am understanding correctly (without me running the code it is always iffy :)) the following should work:  
First get cell contents:  

In this case 
`list(main.Cell...)` or the function `self.grid.get_cell_list_contents((x,y))`
 should work, generically you can typically see what is in any python object with 
`<object>.__dict__`

In the cell contents list you should have an Agent object, to get any attribute of that agent object you just need to reference it in this case ......  
`<agent_object>.SquareNum`

Let me know if this works, if not can you shoot me the outputs you are getting

**Comment by StueGrifn** [comment]
I did some preliminary coding with this, and it seems to be working exactly as you said. The problem was I was referencing the whole list for the self.SquareNum variable, when I actually needed to reference the only member of the list first.

Thank you for your quick and accurate response! Closing issue.
