### ISSUE TITLE
I tried to run the very first ABM model in the tutorial and I get the error message: 'super' object has no attribute

### ISSUE THREAD

**Issue by Hildekyvik** [projectmesa/mesa#931]
**Describe the bug**

**Expected behavior**

**To Reproduce**

**Additional context**

**Comment by jackiekazil** [comment]
Hello! Glad to hear you are trying out Mesa. Without more details, we can not help trouble shoot the issue.  For now, I closing this issue. Please reopen with more details or post to the User listserv located here: https://groups.google.com/g/projectmesa
