### ISSUE TITLE
Visualization for ContinuousSpace

### ISSUE THREAD

**Issue by marensba** [projectmesa/mesa#932]
**What's the problem this feature will solve?**

I am currently working on a project using mesa. Great framework! The problem is that I use ContinuousSpace, and want to visualise it. Is this something you are working on?

**Comment by Corvince** [comment]
You can check out the [boid flockers example](https://github.com/projectmesa/mesa/tree/master/examples/boid_flockers). It includes a ContinousSpace visualization. Don't know why it never made it to the core visualizations.

**Comment by jackiekazil** [comment]
That is a good catch. I have no idea why it isn't in core as well!

**Comment by rht** [comment]
Duplicated of #753.
