### ISSUE TITLE
Travis-ci.org shutting down Dec 31st 2020

### ISSUE THREAD

**Issue by Corvince** [projectmesa/mesa#938]
I somehow missed that until today, but www.travis-ci.org will shut down at the end of the year. Not a very much big deal, since it will continue to operate under www.travis-ci.com, but we would need to create an account there and migrate the integration. This *should* be fairly easy ([here is the migration guide](https://docs.travis-ci.com/user/migrate/open-source-repository-migration)). However, we could also consider switching to [GitHub Actions](https://github.com/features/actions) for our CI/CD pipeline. 

What are some thoughts on this?

**Comment by jackiekazil** [comment]
Good catch! I pinged a few friends who are more into this than me. I will update when they get back to me. 
Another option is CircleCi.

**Comment by rht** [comment]
One vote for CircleCI -- it is used by Zulip (https://github.com/zulip/zulip/blob/master/.circleci/config.yml).

**Comment by jackiekazil** [comment]
I heard a lot of hype around Circle. So I did a bunch of research by polling some folks I respect and reading up.  It seems 2/1 that people lean on github actions versus other options (eg Travis or Circle) . Github actions seemed to have more weight than I expected. People leaning towards github actions if there is a change on the project for the following reason -- It is built in and if someone forks it the actions are also forked and CI/CD is run on the fork. 

Assuming that is true. I think that is a good reason as well as not having to deal with another interface. 

My vote is for taking this opportunity to move to github actions. (I am willing to take this on unless someone else is inspired.)

(Honestly I would love to move to gitlab, but I feel we are too established on Github... that is a conversation for another day.)

**Comment by jackiekazil** [comment]
@rht said Circle. 
I say github actions (or fix travis, but that makes me feel - meh.) 

@Corvince what are your final thoughts? 
@tpike3, @dmasad do either of you have thoughts on this?

**Comment by Corvince** [comment]
I would vote for GitHub Actions too. I have used it very rudimentary for mesa-viz and it was quite straight forward to set up (also my setup was very simplified, so I can't really judge that). CircleCI also seems a bit more restricted with only build environments for windows and unix, where GA also has macOS. And the "runs on forks" argument is really compelling - and it makes sense, since the configuration becomes part of the repo.

That said I don't have a qualified opinion on CircleCI. @rht do you know of some unique advantages?

**Comment by tpike3** [comment]
Although CircleCI is more developed, my vote is for GitHub Actions. It is developing fast and by being a part of the GitHub ecosystem already it will reduce obstacles to would be contributors. I think this benefit makes is the most suitable for Mesa and it goals.

**Comment by rht** [comment]
Just so that we can have an informed decision. You can use custom Docker images on CircleCI. You can ssh into a failed build to debug. I don't know about CircleCI vs GitHub Actions, but CircleCI is faster than Travis.

Another thing is I don't know what Microsoft will do next once they have taken hold of FOSS developments. Choosing CircleCI (or should I say GitLab) is like joining the resistance, like choosing Firefox over Chrome.

We should observe what other FOSS projects choose as well.

**Comment by jackiekazil** [comment]
With the merge of #966 I am going to close this ticket. i feel like the problem has been solved.

**Comment by rht** [comment]
I just noticed this: one key advantage of GA is that it supports Linux, macOS, and Windows. CircleCI only supports Linux, with a beta support for Windows.

**Comment by jackiekazil** [comment]
Interesting. Good catch!
