### ISSUE TITLE
Release next version of Mesa -- Nogales

### ISSUE THREAD

**Issue by jackiekazil** [projectmesa/mesa#949]
Release everything tagged as "Nogales" .... this still needs some clean up.

**Comment by jackiekazil** [comment]
@Corvince, @tpike3 -- was this the PR that we were waiting on and wanting to push a release shortly their afterwards? #917 ... meaning, can I go ahead and put together the release?

**Comment by Corvince** [comment]
Yes, this was the PR

**Comment by jackiekazil** [comment]
This is resolved by #957
