### ISSUE TITLE
how to understand self.random.choice

### ISSUE THREAD

**Issue by seeingwu** [projectmesa/mesa#950]
Hi, when I was reading the tutorial of Mesa, I am confused about this function.
![image](https://user-images.githubusercontent.com/52962497/98447477-01a08f80-211d-11eb-88e5-da7b092a55eb.png)

Does '' other_agent = self.random.choice(self.model.schedule.agents)'' means that 'self.random.choice()' wouldn't choose agent itself?

Best regards

**Comment by tpike3** [comment]
@seeingwu in this instance the other_agent could be same agent. In effect, if the agent randomly chooses itself it adds a unit and then loses that unit. 

You could prevents this by recursively checking for example...

```
def choice(self):
        other = self.random.choice(self.model.schedule.agents)
        if other.unique_id == self.unique_id: 
              self.choice()
        else: 
              return other

def step(self):
        if self.wealth == 0:
            return
        other_agent = self.choice()
        other_agent.wealth += 1
        self.wealth -= 1
```
