### ISSUE TITLE
Batch runner - TypeError: getattr(): attribute name must be string

### ISSUE THREAD

**Issue by alabrazi** [projectmesa/mesa#956]
**Describe the bug**

agent_reporters that is used in Model cause error when used with Batchrunner

https://ibb.co/4m0BqTS

**Expected behavior**

Batch runner run without error

**To Reproduce**

add "AgentStatus":lambda agent: "status" if type(agent) is Worker else "cc" to agent_reporters shown below.

# At the end of each model run, calculate the fraction of trees which are Burned Out
model_reporters={"SystemLatency":lambda m: HRB.computeSystemLatency(m),"utilization":lambda m: HRB.utilization(m), "time":lambda m:  m.current_datetime }

#only work with string properties 
agent_reporters={
        "AgentName":"agent_name",
    "AgentStatus":lambda agent: "status" if type(agent) is Worker else "cc",
       }

variable_params = {"scenario_sheet": [1], "remove_optional_EV":[True],"simulation_startdate":[datetime(2021, 10, 5, 5, 0, 0, 0)]}

batch_run = BatchRunner(HRB,
                        variable_params,
                        fixed_params,
                        iterations=1,
                        max_steps=20,
                        model_reporters=model_reporters, 
                        agent_reporters = agent_reporters)
                        
                        #        "Elevator_count": lambda m: m.schedule.get_type_count(Elevator),
        #agent_reporters={"AgentCapacity":lambda agent :  agent.capacity if type(agent) in [Elevator, WC, Break, Material] else "","AgentName":lambda agent: agent.agent_name, "AgentStatus":lambda agent: agent.status if type(agent) is Worker else "", "AgentIntention":lambda agent: agent.intention if type(agent) is Worker else "" })
                       

batch_run.run_all()
**Additional context**

**Comment by tpike3** [comment]
@alabrazi Two things to try. 1. I would install from github ```pip install -e git+https://github.com/projectmesa/mesa#egg=mesa``` as we have just updated batchrunner and are about to do a new Mesa release. 2. Particularly if you are on a Windows machine, lambda functions do not work well with Python's multiprocessing functions. I would recommend removing the lambda operators and that should resolve the issue.

**Comment by jackiekazil** [comment]
That release went out the door on 11/27. 
@alabrazi can you try again. if you have an issue, please comment on this ticket and reopen OR open a new ticket -- whichever you think is more appropriate to the issue based on the changes to batch runner.
