### ISSUE TITLE
Fix tutorial example code for batch_runner datacollector

### ISSUE THREAD

**Issue by koyafull** [projectmesa/mesa#959]
**Describe the bug**

[Tutorial](https://mesa.readthedocs.io/en/master/tutorials/intro_tutorial.html) provides following code snippet:
```
batch_run = BatchRunner(MoneyModel,
                        variable_params,
                        fixed_params,
                        iterations=5,
                        max_steps=100,
                        model_reporters={"Gini": compute_gini})

run_data = batch_run.get_model_vars_dataframe()
run_data.head()
plt.scatter(run_data.N, run_data.Gini)
```
which would return following error, complaining about `Gini` column content:
```
TypeError: float() argument must be a string or a number, not 'method'
```

**Expected behavior**

Provide run-ready code snippet.

**To Reproduce**

Follow the tutorial copy-pasting code snippets.

**Comment by jackiekazil** [comment]
Can you provide more details --- 
- What version of Mesa are you running? 
- How did you discover the tutorial? (Direct link somewhere or google search or some other way)

**Comment by tpike3** [comment]
@koyafull we you able to get the model working? If nothing hear, I will assume this issue has resolved.

**Comment by koyafull** [comment]
Yes I finally managed to have it working by correcting my mistakes. Sorry for disturbance!

**Comment by tpike3** [comment]
@koyafull Awesome, thank you! If you ever want to share your model we would be happy to link them in our examples page.
