### ISSUE TITLE
Help with Modelling

### ISSUE THREAD

**Issue by j-santoro** [projectmesa/mesa#961]
Hi there, 
I am trying to create a simulation project using your modelling software for my high school research class. I am having a hard time understanding how to use the software to create my own model, as I am new to computer science. I have tried creating the introductory sample model, but I do not understand all of the code and how to use it for my own model. Does anyone know what steps I can take to understand the code better, and learn to use the program for my own project?

**Comment by jackiekazil** [comment]
I would try to run some of the models in the examples folder here: 
https://github.com/projectmesa/mesa/tree/master/examples

You should post this question to the user group, which you can find here: 
https://groups.google.com/u/1/g/projectmesa

**Comment by jackiekazil** [comment]
Also... welcome! :-)

**Comment by j-santoro** [comment]
Thank you so much for the help!
