### ISSUE TITLE
Why am I getting this error? : --------------------------------------------------------------------------- AttributeError                            Traceback (most recent call last) <ipython-input-34-85f394baa6a9> in <module>       2 #batchrunner.FixedBatchRunner.get_collector_agents       3 #@@ ----> 4 data_collector_agents = batch_run.get_collector_agents()       5 #data_collector_agents = batch_run.FixedBatchRunner.get_collector_agents()       6 data_collector_agents[(N,2)] # 10 (<#number of agents>, <iteration#>).  AttributeError: 'BatchRunner' object has no attribute 'get_collector_agents'

### ISSUE THREAD

**Issue by achenie** [projectmesa/mesa#964]
Why am I getting this error:
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-34-85f394baa6a9> in <module>
      2 #batchrunner.FixedBatchRunner.get_collector_agents
      3 #@@
----> 4 data_collector_agents = batch_run.get_collector_agents()
      5 #data_collector_agents = batch_run.FixedBatchRunner.get_collector_agents()
      6 data_collector_agents[(N,2)] # 10 (<#number of agents>, <iteration#>).

AttributeError: 'BatchRunner' object has no attribute 'get_collector_agents'

Also This:

AttributeError                            Traceback (most recent call last)
<ipython-input-35-a1503d8dc526> in <module>
      1 #Get the Model DataCollection.
----> 2 data_collector_model = batch_run.get_collector_model()
      3 data_collector_model[(10,1)]

AttributeError: 'BatchRunner' object has no attribute 'get_collector_model'

**Comment by tpike3** [comment]
@archenie  Can you confirm what version of Mesa you are running?

**Comment by tpike3** [comment]
@achenie Were you able to resolve this issue?  I will assume it has been resolved if nothing heard.
