### ISSUE TITLE
GraphSpace like in Agent.jil

### ISSUE THREAD

**Issue by niedakh** [projectmesa/mesa#965]
**What's the problem this feature will solve?**
I am looking for a network based space for agent models.

**Describe the solution you'd like**
I'd love to be able to load up a networkx graph and use it as a space for agents moving on the network.

**Additional context**
https://juliadynamics.github.io/Agents.jl/stable/examples/sir/

**Comment by tpike3** [comment]
@niedakh Mesa has [NetworkGrid](https://github.com/projectmesa/mesa/blob/b08720cd65ffc76c4bf1690a8e7c3c20104a3eb7/mesa/space.py#L834) which uses NetworkX backend for that purpose. 

Here's an [example instantiation](https://github.com/metalcorebear/Mesa-SIR/tree/master/mesa_SIR)
