### ISSUE TITLE
Pending update to GA build file 

### ISSUE THREAD

**Issue by jackiekazil** [projectmesa/mesa#968]
Extending this.... https://github.com/projectmesa/mesa/pull/966 

- [x] https://github.com/projectmesa/mesa/pull/966#discussion_r550432657

**Comment by jackiekazil** [comment]
@Corvince -- can we also rename the file to "build" from "Python package"? 

That will carry over to the badge used in the readme. I was going to update, but it is not descriptive. 
This is what it would currently need to be updated to if name isn't changed: 
https://github.com/projectmesa/mesa/workflows/Python%20package/badge.svg

**Comment by rht** [comment]
I have another comment: flake8 seems to be run twice https://github.com/projectmesa/mesa/pull/966/files#diff-092659a9bd0068791326fb1d08f005532e5aeb983b999a7bd32c51deee0a71d5R27. Only one of them is necessary.

**Comment by rht** [comment]
It appears that it is possible to also run the tests on macOS and Windows: https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#github-hosted-runners.

**Comment by rht** [comment]
#970 adds Windows.

**Comment by jackiekazil** [comment]
Everything discussed in this ticket was covered by a PR.... leaving this ticket closed..... PRs will carry the respective conversation forward.
