### ISSUE TITLE
Rename 'master' branch to 'main'

### ISSUE THREAD

**Issue by rht** [projectmesa/mesa#969]
https://github.com/github/renaming

**Comment by Corvince** [comment]
TLDR: We should wait a little bit longer until there is a renaming tool available (scheduled for January 2021). Once it is available we should consider the renaming

**Comment by rht** [comment]
The wait is over: https://github.com/github/renaming/commit/040636ea50e945875c70cc964d586f645e9bd810.

**Comment by Corvince** [comment]
Great!

**Comment by jackiekazil** [comment]
I am onboard. I will bring it up during our dev meeting, which got bumped to this week to see if there are any concerns.

**Comment by jackiekazil** [comment]
This was discussed during the meeting and everyone is onboard. I am ready to change, but was wondering if we need to consider timing or announce it first or just the "main" people doing dev is good enough. 

PRs are updated automatically, but local branches will need to be updated. 

```
git branch -m master main
git fetch origin
git branch -u origin/main main
```

**Comment by dmasad** [comment]
Worth putting a note on top of the readme for a little while?

**Comment by jackiekazil** [comment]
master is now main. 
https://github.com/projectmesa/mesa/branches
