### ISSUE TITLE
vkEnumeratePhysicalDeviceGroupsKHR failed with ERROR_INITIALIZATION_FAILED

### ISSUE THREAD

**Issue by Stefan538871** [projectmesa/mesa#975]
**Describe the bug**
Currently I cant launch applications which require vulkan (e.g. dota 2 with vulkan renderer, dota underlords)

**Expected behavior**
Vulkan application can launch

**To Reproduce**
Just starting the machine because vulkan fails to initialize
https://pastebin.com/TFpvs05N

**Additional context**
OS: fedora 33
all packages are up to date
```
➜  workspace dnf info mesa-vulkan-drivers-20.2.6-1.fc33.x86_64 
Last metadata expiration check: 0:02:04 ago on So 10 Jan 2021 22:15:34 CET.
Installed Packages
Name         : mesa-vulkan-drivers
Version      : 20.2.6
Release      : 1.fc33
Architecture : x86_64
Size         : 14 M
Source       : mesa-20.2.6-1.fc33.src.rpm
Repository   : @System
From repo    : updates
Summary      : Mesa Vulkan drivers
URL          : http://www.mesa3d.org
License      : MIT
Description  : The drivers with support for the Vulkan API.
```

CPU: amd ryzen 3900x
GPU: amd Radeon 5700 xt

amdvlk seems to work just fine

thx in advance

**Comment by tpike3** [comment]
@Stefan538871 I do not think this is the library you are looking for. This is an agent based model library. I think you want Mesa 3D graphics on gitlab located [here](https://gitlab.freedesktop.org/mesa/mesa/blob/master/docs/relnotes/20.0.2.rst)
