### ISSUE TITLE
VisualizationModuleProblem

### ISSUE THREAD

**Issue by LeavesLi1015** [projectmesa/mesa#982]
When I use visiualization module to simulate COVID-19, there was a problem in visiualized grid. Every time I press start, it will run quickly and smoothly. But at step 9(more or less depending on number of agents), all the grids went out and disappear and simulation ended as well. 
![image](https://user-images.githubusercontent.com/76167689/106241182-70403700-61ba-11eb-91a8-362cb8b65fd7.png)

**Comment by LeavesLi1015** [comment]
![image](https://user-images.githubusercontent.com/76167689/106241257-906ff600-61ba-11eb-8171-eb7fe0436ae4.png)

**Comment by rht** [comment]
@LeavesLi1015 that's not enough information to debug/reproduce. Can you share a minimum code in a GitHub gist that reproduces the bug?

**Comment by LeavesLi1015** [comment]
This is the project:https://github.com/LeavesLi1015/test
Project is in master branch and a Readme.md is in main branch.

**Comment by rht** [comment]
I got this:
```
run.py 8 <module>
from model import COVID_model

model.py 13 <module>
from mesa_SIR import SIR

ModuleNotFoundError:
No module named 'mesa_SIR'
```

**Comment by rht** [comment]
Oh, nvm, the library is available on PyPI. Will download.

**Comment by LeavesLi1015** [comment]
The library was changed. I will upload a new library file for you

**Comment by LeavesLi1015** [comment]
new lib was uploaded in master branch, just overwrite venv/Lib/Mesa-SIR with it

**Comment by rht** [comment]
@LeavesLi1015 I ran your code verbatim. It has been more than 150 steps, and none of the dots has disappeared.

**Comment by rht** [comment]
I'm using the latest release of Mesa (0.8.8.1) on Python 3.8.6 on Linux.

**Comment by LeavesLi1015** [comment]
Are there any yellow or red dots? If all the dots are green, there might not be any problem.
Restart to make some yellow or red dots

**Comment by rht** [comment]
Ah, I see. Yes, I can reproduce your bug. Will investigate today.

**Comment by LeavesLi1015** [comment]
Thanks a lot!

**Comment by rht** [comment]
@LeavesLi1015 I found the bug. You forgot a final `else` clause after this line: https://github.com/LeavesLi1015/test/blob/d9eb86a28a78c63e2380128d69fe931e3e29df58/test2/Model_Vis.py#L18. I added 
```python
        else:
            portrayal["Color"] = "black"
```

and the invisible dots were then colored with black.

If this fixes your problem, remember to close the issue.

**Comment by LeavesLi1015** [comment]
It's fixed! Thanks a lot!
