### ISSUE TITLE
Enable GitHub Discussions

### ISSUE THREAD

**Issue by Corvince** [projectmesa/mesa#987]
**What's the problem this feature will solve?**
Mesas discussions currently should take place on the official mailing list. However, many things that should belong to the mailing list (e.q. usage questions) are posted on the issue tracker. Vice versa sometimes feature requests first appear on the mailing list.

**Describe the solution you'd like**

GitHub Discussions is now out of beta and available for every public repository. It's basically the same format as Issues, but for more general stuff. Issues/Discussions are movable to wherever they belong and its far easier to reference other issues and/or pull requests.

**Additional context**

https://docs.github.com/en/discussions
It's just a single checkbox in the repo settings to activate discussions

**Comment by rht** [comment]
Agreed. E.g. #988 is not an issue of Mesa itself, but rather a question on how to use Mesa.

**Comment by jackiekazil** [comment]
I will bring this up during the dev meeting this Thursday.

**Comment by Corvince** [comment]
Done! 🎉  
👉 https://github.com/projectmesa/mesa/discussions
