### ISSUE TITLE
Discuss: GA Chicken or Egg

### ISSUE THREAD

**Issue by jackiekazil** [projectmesa/mesa#990]
We have 2 PRs.... 
#972 GA: Add pypy3 
#970 GA: Run on Windows and macOS #970

Both are good additions, but one will probably break the other.  Which one takes priority. 

I am torn. 

What our our options? Which one comes first? 
Can we do an `if` statement in the code like this -- https://github.com/fabasoad/twilio-voice-call-action/actions/runs/440407309/workflow#L24

**Comment by rht** [comment]
I think the Windows and macOS one takes priority because it is closer to what the final form of what the .yml would look like. After #970 is merged I can update the PyPy one.

**Comment by Corvince** [comment]
I fully agree with @rht. We should merge the windows/macOS one as is and then update PyPy

**Comment by jackiekazil** [comment]
Sounds like we are in agreement.... let's merge #970 before we merge #972

**Comment by Corvince** [comment]
Closed after last dev meeting. #970  is merged, waiting for updates on #972
